### ISSUE TITLE
Option to display all plugins

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#100]
### Feature request

**Platform**
 website

**Describe the feature**

Option to display all plugins instead of just a maximum of 100.

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
As of the recent custom versions update, the plugin list was replaced with a new addons tab so this issue doesn't apply.
