### ISSUE TITLE
More Items Per Page settings for online server list

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#102]
### Feature request

**Platform**
 Website

**Describe the feature**

More items per page for the online Server List page.

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
The server list is now 1 page and will dynamically load more as you scroll down the page.
