### ISSUE TITLE
File Trees

### ISSUE THREAD

**Issue by Colbite** [Minehut/Meta#104]
### Feature request

**Platform**

Website (File Manager Editor)

**Describe the feature**

I believe there should be a easy and customizable file navigation system for people who creates large Skript files. Simply put, players should be able to create a "checkpoint" in files with a name. A UI would pop up at the side of the file manger showing all "checkpoint" buttons. Players can click on the "checkpoint" button to instantly be redirected to the "checkpointed" line.

For visuals here is the one similar to what im talking about found on Fandom https://gyazo.com/d9d702a0b9439e6b56986102221d0be8.

**How the feature is useful**

It's useful for Skripters like me who wants to stay organize and create large files. In my opinion, I found it hard to navigate around files and put a large line of hashtags showing what I'm searching for.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Can you show how you'd want that to look on the panel? Are creating files that big normal and best practice? Certainly isn't for most programming languages..

**Comment by jellz** [comment]
Some IDEs do have this feature IIRC

**Comment by ColbiteBlaze** [comment]
> Can you show how you'd want that to look on the panel? Are creating files that big normal and best practice? Certainly isn't for most programming languages..

I know but at some point you want to create one part of a feature but it's getting bigger. For instance what if you want to create a ability skript but there are multiple ability stuff?

**Comment by jellz** [comment]
In programming, you're generally supposed to split code into smaller files instead of having a small number of really large files

**Comment by BennyDoesStuff** [comment]
With the new file manager, you can now view a file tree of the directory on the left-hand side of the text editor. This isn't going to be possible inside of the files themselves, however.
