### ISSUE TITLE
Inconsistency in Refresh button on online server list

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#105]
### Feature request

**Platform**
 website

**Describe the feature**

Make this an icon rather than a button. The refresh is an icon for the file manager. But here it's a button.
![](https://cdn.discordapp.com/attachments/592130982451216402/725898034030051410/unknown.png)

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
The refresh button no longer exists on the server list. This issue isn't applicable anymore.
