### ISSUE TITLE
Ability to /find yourself

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#106]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java

**Describe the feature**

Ability to /find yourself. You can do this if you have finding enabled, but if it is enabled for friends or completely disabled you can't (also you can't friend yourself so you can't fix this like that).

**How the feature is useful**

To find out what server you are on

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Would probably qualify as a bug. Can reproduce.

**Comment by jellz** [comment]
Hey, please re-post this as a bug report. Thanks!
