### ISSUE TITLE
Allow direct download from the file manager

### ISSUE THREAD

**Issue by drtshock** [Minehut/Meta#11]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Users should be able to directly download any non blocked file or folder from their file manager. If they attempt to download a folder, zip up the folder, excluding any blocked extensions, and then download the zip.

**How the feature is useful**

Greatly improves ease of use of our custom file manager. Brings us closer to feature parity with normal hosts.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
Implemented in new file manager update.
