### ISSUE TITLE
Theme toggle on home page

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#114]
### Feature request

**Platform**
 website

**Describe the feature**

Might be just me but there isn't anywhere to toggle theme on home page
![](https://cdn.discordapp.com/attachments/592130982451216402/725904582915653693/unknown.png)

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Why is this needed on the home page?

**Comment by farwl** [comment]
Why did you guys make two different themes for the home page?

**Comment by farwl** [comment]
so it seems like maybe people should be able to witness your magical talents by being able to toggle theme on the home page ;o

**Comment by BennyDoesStuff** [comment]
Themes no longer exist so I'm going to close this issue.
