### ISSUE TITLE
Higher logs capacity

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#117]
### Feature request

**Platform**
 website

**Describe the feature**

higher logs capacity. this is pretty crucial to servers if you think about it. we're always told to check our logs but most of the time you have at max 1 log file that doesn't even contain the info you need..

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Pretty sure logs are automatically deleted when the server hibernates.

**Comment by drtshock** [comment]
Can you please give more info? When does this become a problem? How do you suggest we handle it? We save all your logs until you hibernate your server. Log files often take up gigabytes of storage, especially on servers that (ab)use skript and have things logging every tick.

**Comment by farwl** [comment]
It becomes a problem when people are told to **check logs** when griefed and whatnot. The current log(s) doesn't contain the information needed most of the time. Maybe don't delete them when hibernating? Or allow people to download the logs or save them to google drive.

**Comment by BennyDoesStuff** [comment]
You can now read through older log files.
