### ISSUE TITLE
Bring back /server command

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#119]
### Feature request

**Platform**
 in-game

**Describe the feature**

bring back the /server command. It allows you to directly join another minehut server without going to the lobby or through multiplayer server list.

**How the feature is useful**

See above.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Yes we will be bringing this back.

**Comment by BennyDoesStuff** [comment]
This no longer applies after the new server networks update.
