### ISSUE TITLE
Improve plugin panel

### ISSUE THREAD

**Issue by drtshock** [Minehut/Meta#12]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

* Support markdown, so links can be clickable and descriptions can be formatted
* Include a link / thumbnail for the tutorial video if that plugin has one
* Show when the plugin was last updated, and which version it's on
* Show any required dependencies, allow clicking to install them
* Allow sorting by popular, recently updated
* Add a button to report as outdated / broken. Automatically create a support ticket with their latest.log attached
* If a user searches for a plugin that isn't there, add a card at the bottom allowing them to suggest a plugin through a support ticket with a few clicks.

**How the feature is useful**

16% of users that haven't logged in for the last 30 days referenced issues with plugins as their main difficulty with Minehut. This greatly improves the user experience around using plugins on Minehut.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
The amount of skript, buycraft, and essentials tutorials... Would you put all of them or just one that seems most helpful?

**Comment by WallyTube** [comment]
You should also let the community have insight on new plugins. There are a few plugins out there that are duplicates of better plugins. Like minehut has just added the plugin 'Sentinel' that helps with NPC PvP, but there is a plugin called StrikePractice that is way less buggier and has if not the same, more features than Sentinel.

Also, what if you guys added a type of reactions field at the bottom of a plugin in the plugins list, that has a thumbs up, thumbs down, and red exclamation mark. You guys could track plugins and their "Hype" with the thumbs up and thumbs down to decide whether you should keep supporting it, and use the red exclamation mark to track which plugins have been reported broken or outdated to fix them.

**Comment by WallyTube** [comment]
It would also be nice if you could add tags to plugins, like NEW! or LATEST! or OUTDATED! kind of like github tags. This would help so much!

**Comment by kikimessy** [comment]
> If a user searches for a plugin that isn't there, add a card at the bottom allowing them to suggest a plugin through a support ticket with a few clicks.

Shouldn’t this be done through the forums, not a support ticket?

**Comment by Tringlle** [comment]
This isn't exactly useful anymore, the plugins tab is somewhat _ nonexistant_ :/

**Comment by tarna** [comment]
> This isn't exactly useful anymore, the plugins tab is somewhat _nonexistant_

Some of these suggestions could still apply for the new addons page.

**Comment by BennyDoesStuff** [comment]
This issue isn't relevant anymore.

**Comment by tarna** [comment]
> This issue isn't relevant anymore.

how is this not relevant anymore? These suggestions could still apply to the addons panel.

**Comment by BennyDoesStuff** [comment]
> > This issue isn't relevant anymore.
> 
> how is this not relevant anymore? These suggestions could still apply to the addons panel.

The majority of the suggestions provided in this issue do not apply anymore. New issues should be created for each separate suggestion that could still be implemented and has demand.
