### ISSUE TITLE
Remove /join cooldown when joining online server

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#120]
### Feature request

**Platform**
 in-game

**Describe the feature**

remove the cooldown on /join if you're joining an online server

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Is this a problem? How often do you run into this? Why not just remove the cooldown for ranked users?

**Comment by farwl** [comment]
It's a problem and I run into it fairly often. There shouldn't be a cooldown for joining servers that are already online. Removing the cooldown for ranked users would be nice too, in addition to the previous suggestion.

**Comment by BennyDoesStuff** [comment]
This doesn't appear to be an issue anymore, but if this does still exist, please comment here and I can reopen.
