### ISSUE TITLE
Minehut related show

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#123]
### Feature request

**Platform**
 Youtube / Discord

**Describe the feature**

Weekly minehut-related show. (Doesn't have to replace Taking Shape since apparently that's "popular") On the youtube channel.

**How the feature is useful**

Helps people discover Minehut and entertains current users.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Can you give an example of what might take place on said show? Like showcasing servers or something like that?

**Comment by drtshock** [comment]
Yeah we definitely want to do more, but would appreciate some more detail on the type of content :)

**Comment by farwl** [comment]
Anything like Good Grief or the previously Minehut Weekly.

**Comment by Sniped** [comment]
Going to close this issue as Minehut has a weekly show now.
