### ISSUE TITLE
File Manager improvements

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#127]
### Feature request

**Platform**
 website

**Describe the feature**

- numbered lines on text editor
- rename files
- download files

**How the feature is useful**

these are necessary features

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
Closed as invalid, not enough information and didn't use the issue template
