### ISSUE TITLE
Allow collapsing of code blocks in text editor

### ISSUE THREAD

**Issue by joshmusic** [Minehut/Meta#128]
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website
**Describe the feature**
I want to be able to close certain events in a file. such as .sk. Oh, and also numbers at the side to be how many lines there are.
Example:
![e](https://user-images.githubusercontent.com/69742441/90326203-7e273600-df53-11ea-9cc8-859bed8ba5c8.png)

**How the feature is useful**
1: Basically It'll be able to hide the giant chunk of code to THEN take up less space :p
2: It'll tell how many lines there are.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
So allowing you to collapse code blocks? What formats should this support?

**Comment by joshmusic** [comment]
> So allowing you to collapse code blocks? What formats should this support?

Like .java, .sk, and .js

**Comment by iGalaxyYT** [comment]
Since Skript isn't really a language, custom regex would probably have to be written to support this and imo isn't worth the effort.

**Comment by iGalaxyYT** [comment]
> > So allowing you to collapse code blocks? What formats should this support?
> 
> Like .java, .sk, and .js

.java and .js aren't supported file types for the File Manager.

**Comment by joshmusic** [comment]
> > > So allowing you to collapse code blocks? What formats should this support?
> > 
> > 
> > Like .java, .sk, and .js
> 
> .java and .js aren't supported file types for the File Manager.

oh..well im dumb then

**Comment by xSpiderMC** [comment]
This could be useful for colapsing config sections in yml, would be a lot easier to digest if you can look at certain parts at once.

**Comment by Vrganj** [comment]
Might as well use [Monaco](https://github.com/Microsoft/monaco-editor). Has it built in along with syntax highlighting.

**Comment by Double0negative** [comment]
Using Monaco would be interesting, but its support is not great (older browsers, no mobile support) and the overhead of using it for editing yml files is probably not worth it. Closing for now but I would like to revisit this in the future.
