### ISSUE TITLE
Get rid of the "chat enabled" message if you can't talk

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#131]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Ingame, both

**Describe the feature**
If you join a muted lobby, don't say "Chat enabled!" when you move.

**How the feature is useful**
It will be a nice qol feature, but also will clear up some confusion with people.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Double0negative** [comment]
This would probably just cause more confusion if the message isn't shown and the chat becomes enabled, and a bunch of extra cases to handle. While I can understand that its a little annoying, I don't think its worth changing right now.
