### ISSUE TITLE
Ingame commands, similar to Hypixel

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#134]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In-game

**Describe the feature**
Add /report, /appeal, /rules and perhaps /apply so users can access the links via the lobby.

**How the feature is useful**
It becomes easier for staff/active helpers to tell users to do something by just typing /(command) and going to the link

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
This seems like a no-brainer for minehut.

**Comment by LukasmanMHdude** [comment]
> This seems like a no-brainer for minehut.

why say "yes" in the comments but not upvote 😖

**Comment by BennyDoesStuff** [comment]
These commands are now implemented in the lobbies.
