### ISSUE TITLE
Optional silent punishment

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#139]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Ingame, java and bedrock

**Describe the feature**
Make silent punishments an option by adding -s (-silent) to the end of a punishment.

**How the feature is useful**
Can be used by staff to warn users in a way, often if you mute one person publicly other users will stop spamming.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Reassembly-Minehut** [comment]
I 100% agree with this, It can also stop people from arguing with staff that a player wasn't muted when they were

**Comment by BennyDoesStuff** [comment]
Punishments are no longer public so this isn't an issue anymore.
