### ISSUE TITLE
Dont allow illegal characters in world names

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#142]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website and ingame (servers)

**Describe the feature**
Stop allowing users to upload worlds with spaces and/or any illegal characters.

**How the feature is useful**
Worlds with spaces and/or illegal characters won't allow you to tp to them, this is probably one of the more common causes of users being unable to tp to their world.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
Was told this was fixed months ago, it still isn't fixed and we still have to tell people every day that spaces will break the world system

**Comment by BennyDoesStuff** [comment]
This is no longer an issue anymore as you can now rename files in the file manager and the old /upload command doesn't exist anymore.
