### ISSUE TITLE
Discount codes

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#143]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Add discount codes, these can be given to YouTubers as a kind of sponsor

**How the feature is useful**
More money for Minehut and more users get introduced to Minehut

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
Could also possibly be given to community teams and the staff team as well to reward them for their hard work and to encourage more applications?

**Comment by BennyDoesTheStuff** [comment]
> Could also possibly be given to community teams and the staff team as well to reward them for their hard work and to encourage more applications?

We already give out credits to the staff team occasionally, I feel like the best use case for this would be for things such as giving out to Youtubers or for holidays such as Christmas

**Comment by PundaChen** [comment]
> > Could also possibly be given to community teams and the staff team as well to reward them for their hard work and to encourage more applications?
> 
> We already give out credits to the staff team occasionally, I feel like the best use case for this would be for things such as giving out to Youtubers or for holidays such as Christmas

Black Friday is a great example for one of the holidays where this could be used ^^

**Comment by BennyDoesStuff** [comment]
Coupon codes now exist and have been given out on live streams and other places.
