### ISSUE TITLE
Show what default plan gets

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#149]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Show what the default plan gets next to the paid plans

**How the feature is useful**
Makes it more easier for users to decide whether they wanna get a plan or not, also lessens the question fo "what do I get with x plan"

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
This does exist, not too sure when this was added, however.
