### ISSUE TITLE
Automate booster passes with the bot

### ISSUE THREAD

**Issue by jellz** [Minehut/Meta#15]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord

**Describe the feature**

Add a **!boosterpass** Discord bot command with the usage:
- `!boosterpass info [user]` - shows user's given and received passes
- `!boosterpass give <user>` - give one of your booster passes to that user, provided they don't already have one assigned to them
- `!boosterpass revoke <user>` - take your booster pass away from that user

Maximum passes you can assign would stay the same

**How the feature is useful**

The Minehut Discord bot should automate assigning booster passes so senior staff don't need to spend time managing it and users can reassign their passes instantly.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
Could you then possibly find out if someone boosted the discord more than once? Allowing more than 2 passes?

**Comment by jellz** [comment]
Maybe. I haven't looked into that, but leaning towards no

**Comment by Sniped** [comment]
Would it be better to just limit nitro boosters from being given booster passes all together? Or just keep their booster passes for if they ever get stop boosting Minehut?

**Comment by jellz** [comment]
Nitro Boosters should be able to be given Booster Passes IMO

**Comment by Sniped** [comment]
Then in that case, should we limit the amount of booster passes a user can be given? Maybe they can only be given two just like nitro boosters can only give two?

**Comment by jellz** [comment]
I didn’t think about that. I don’t see a reason why it shouldn’t be unlimited or pseudo-infinite.

**Comment by Sniped** [comment]
The only thing I could see with them being unlimited is if people just give one person a lot of passes and end up spamming `!boosterpass info` with it. Other than that, there's no problems that I can think of. I don't believe the likelihood of a bunch of people giving one person a load of passes is very high, though it's just something to think of.

**Comment by jellz** [comment]
Just show the first 15 or so tags

**Comment by Sniped** [comment]
Yeah, that's good

**Comment by Sniped** [comment]
Addressed in PR [59](https://github.com/Minehut/MinehutBOT/pull/59) of the bot repo.
