### ISSUE TITLE
Better signin process for the forums

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#155]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website, forums

**Describe the feature**
Make the signing in process on the forums better (Here's how it currently works: Go to forums and sign in > get sent to minehut.com > log in > get sent to log in site from slg > get sent back to the MH log in page > get sent to panel > go back to the forums)

**How the feature is useful**
Saves so much time

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by liami101** [comment]
Ye I agree the signing in process takes way to long

**Comment by iGalaxyYT** [comment]
Would be nice if forums auth sessions were separate from panel auth sessions as well

**Comment by ZeroParticle** [comment]
We have some better options available for how we manage the forums logins now that we've moved to a new auth system. Definitely aware of how tedious and unintuitive the process is right now and we are planning to move the forums under the new system in the near future as well.

**Comment by BennyDoesStuff** [comment]
I'm not sure when this was changed, but it appears to be straightforward now for me (clicking login on the forums takes me directly to the login page, and redirects me back once I am logged in).

Solved
