### ISSUE TITLE
Ability to show more servers on online list

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#159]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Add an option to show more servers on the online server list.

**How the feature is useful**
Makes it easier to browse servers

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Which server list exactly? And how do you mean? Perhaps a quick 2m drawing or something to show us?

**Comment by PundaChen** [comment]
https://minehut.com/servers this list, the suggestion basically means adding a drop-down somewhere to show more servers on the list

**Comment by LukasmanMHdude** [comment]
Would be nice if there was 3 per row and the boxes are smaller overall, as well as it continues to load more instead of having pages.

**Comment by BennyDoesStuff** [comment]
This has been updated (at some point)! When you reach the bottom of the page, the website will automatically showcase more servers without the need to go to the next page.
