### ISSUE TITLE
Rule change for evading bans

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#162]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 
 

**Platform**
Ingame

**Describe the feature**
Allow users to evade bans for inappropriate names/skins

**How the feature is useful**
They're not really hurting anyone or evading a chat punishment so 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment]
Or they could change their name/skin and appeal. :shrug:

**Comment by PundaChen** [comment]
> Or they could change their name/skin and appeal. 🤷

They could, but then they have to wait a while for the appeal to be read, in the meantime the user should be able to play
Especially if their username was recently changed already, they would have to wait a month to change usernames again

**Comment by recalibrated** [comment]
They should wait then, it was a stupid choice to have an inappropriate skin / name and they got punished for it

**Comment by PundaChen** [comment]
> They should wait then, it was a stupid choice to have an inappropriate skin / name and they got punished for it

You're allowed to have an inappropriate skin/name on player servers, that's where a lot of the users come from, not their fault if they accidentally get kicked from a playerserver and then get spotted by a staff member. A bunch of servers allow users to evade inappropriate name/skin bans

**Comment by drtshock** [comment]
I agree I don't see a problem if someone "evades" a ban because of an inapp skin or username.
