### ISSUE TITLE
Server Backups

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#164]
### Feature request

**Platform**
 Website

**Describe the feature**

It would be nice if your server could have unlimited free backups. Automated of course. Other hosts give players unlimited backups for free using third party services like Google Drive. Since Minehut already uses some third party services, I think they should explore this and give players backups of their server.

**How the feature is useful**

This benefits all users and helps players recover lost/destroyed work.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
Honestly surprised this doesn't exist already 👀

**Comment by drtshock** [comment]
We started development on this earlier this week.

**Comment by LukasmanMHdude** [comment]
> Honestly surprised this doesn't exist already 👀

Because they removed it

**Comment by drtshock** [comment]
We never had it and never removed it. The "backups" that people might be referring to before was a result of the host we were on at the time, and was never anything we advertised or promised to users.

**Comment by LukasmanMHdude** [comment]
Yea that's true, ~~but you could have re-set up the infrastructure to support another host~~

**Comment by drtshock** [comment]
> but you could have re-set up the infrastructure to support another host
Which is a software solution on our end, which is what we're implementing now. The previous solution was just how AWS worked out of the box with versioning on s3 https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html.

**Comment by drtshock** [comment]
Initial implementation will be:

- All servers have a rolling backup every 1 hour
- All servers have 1 saved backup slot
- Each server plan has more saved backup slots
- You can purchase more backup slots for a monthly price


Looking to have this released by Thanksgiving.

**Comment by LukasmanMHdude** [comment]
> Initial implementation will be:
> 
> * All servers have a rolling backup every 1 hour

any way that we could set the amount of time for backups?
> * All servers have 1 saved backup slot

:+1:
> * Each server plan has more saved backup slots

👍 
> * You can purchase more backup slots for a monthly price

ok, makes sense. Would be nice for there to be a bit before the files are deleted if you forget/don't pay
> 
> Looking to have this released by Thanksgiving.

**Comment by Sniped** [comment]
> any way that we could set the amount of time for backups?

There could just be a button to manually trigger a server backup and then still have hourly rolling backups.

**Comment by iGalaxyYT** [comment]
When you say "saved backup slot", is that different from the rolling backups? I remember it being said somewhere that when backups would be implemented, you'd be able to save a backup so it doesn't get overwritten.

**Comment by drtshock** [comment]
Correct

**Comment by Sniped** [comment]
Closing this as backups are now released.
