### ISSUE TITLE
Ability to delete clubs or request deletion

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#165]
### Feature request

**Platform**
 Forums

**Describe the feature**

A way to delete a club or request deletion of a club. (For the time being maybe just make a form on the forums for deletion requests)

**How the feature is useful**

This is useful for people who don't want old clubs anymore.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
For now, you can DM a Senior Mod and we will probably delete it for you
