### ISSUE TITLE
More RAM for free servers

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#166]
### Feature request

**Platform**
 Website / in-game

**Describe the feature**

Make default plan 2gb ram and adjust following plans accordingly. 1.15 servers can barely run on on 1gb ram. Operating a 1.16 server on 1gb memory is really bad, even for a free service. This isn't too big of an ask so I think it should be considered.

**How the feature is useful**

This is useful because it will improve performance and allow players to do more on their server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesTheStuff** [comment]
We're a free service, we can't afford to just give free servers more ram. I don't see this happening, sorry.
