### ISSUE TITLE
Sorting options for friends list

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#167]
### Feature request

**Platform**
 in-game

**Describe the feature**

Sorting options for friends list

**How the feature is useful**

Helps organize your friends list. Simple QOL feature.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
How would you suggest it be sorted?

**Comment by Double0negative** [comment]
Closing due to lack of detail/response. Feel free to re-open with more detail.
