### ISSUE TITLE
Public Plugins page

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#168]
### Feature request

**Platform**
 Website

**Describe the feature**

A way to view supported plugins without actually registering. Maybe like minehut.com/plugins. Also give links to the plugin page, list the plugin version used on MH, etc.

**How the feature is useful**

This is useful for people who are interested in Minehut, have a question about a plugin, or would simply like to see what Minehut has to offer.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
or maybe just add a tab for plugin versions in the plugin list page in the panel

**Comment by BennyDoesTheStuff** [comment]
Please follow the correct format for suggestions, thanks.
