### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#17]
### Feature request

**Platform**
 Website

**Describe the feature**
 Currently you cannot Undo (CTRL + Z) tabs on the File Manager text editor. It would be nice if you could. Thanks.

**How the feature is useful**

People make mistakes often and if someone accidentally hits the tab key, they might need to undo it.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
Yeah. Overall, they should upgrade their text editor box. Things like triple clicking to highlight all the code, and tabs with 4 spaces settings should be added.

**Comment by drtshock** [comment]
Is this suggestion for tabs or for undoing on the file manager?

**Comment by farwl** [comment]
Just for undoing tabs. Everything else seems to work. Also adding on to my suggestion; It would be nice if you could SHIFT + TAB lines to remove a tab indent like in Visual Studio Code / Atom.

**Comment by BennyDoesStuff** [comment]
Works now as of the recent file manager update.
