### ISSUE TITLE
Numbered lines on text editor

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#170]
### Feature request

**Platform**
 Website

**Describe the feature**

Numbered lines on the text editor on the File Manager. Similar to text editors like Visual Studio Code or Atom.

**How the feature is useful**

This is useful especially for those who utilize Skript.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
or maybe just use a coding program, and copy the code over to the panel when updating?

**Comment by farwl** [comment]
Yeah thats what most people do but it doesn't mean the text editor shouldn't still be improved?

**Comment by recalibrated** [comment]
Not entirely necessary though?

**Comment by farwl** [comment]
If they don't want to improve the service then I guess it's not necessary.

**Comment by recalibrated** [comment]
not adding 1 thing is "not wanting to improve the service"?

**Comment by Vrganj** [comment]
> not adding 1 thing is "not wanting to improve the service"?

Yes.

Also, as I said before, they should just use the Monaco editor instead of trying to create their own that isn't and won't ever be half as good.

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update.
