### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#172]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Website, forums

**Describe the bug**
There's a spelling error on the media application form

**To reproduce**
1 - go to the forums
2 - go to the forms
3 - click the media app form

**Expected behaviour**
You see the question asking for your channel's primary language

**Device Information**

- Minecraft client (and version): 5zig 1.12.2
- Web browser (and version): chrome
- Operating system (and version): windows
- Minehut server name: Games

**Screenshots**

![image](https://user-images.githubusercontent.com/42002575/90337605-de65b880-dfe3-11ea-863c-7168d498173f.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by MiginsMC** [comment]
Could reproduce.
Web browser (and version): chrome
Operating system (and version): mac

**Comment by Shlba** [comment]
> * Minehut server name: Games

smh had to plug your minehut server

**Comment by PundaChen** [comment]
> > * Minehut server name: Games
> 
> smh had to plug your minehut server

idk man it wanted my server name

**Comment by Sniped** [comment]
Can reproduce this on the latest version of Opera GX, confirmed bug

**Comment by BennyDoesStuff** [comment]
This seems to have been fixed at some point.
