### ISSUE TITLE
Ability to rename files

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#174]
### Feature request

**Platform**
 website

**Describe the feature**

Ability to rename files/folders would be amazing. Just blacklist certain directories from being edited for security purposes.

**How the feature is useful**

Renaming files is supported on just about every other host. It's essential when working on your server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update.
