### ISSUE TITLE
Announce new icons in Discord

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#177]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Discord

**Describe the feature**
Announce the icon changes in the Discord as well

**How the feature is useful**
Easier for people to know when new icons arrive

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Preferrably also list the icons + show what they look like instead of just saying something like "A new icon set is available on Minehut.com!"

**Comment by jellz** [comment]
We’re going to start announcing available icon changes on Discord, thanks for the suggestion!
