### ISSUE TITLE
Starboard

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#179]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Discord

**Describe the feature**
Add a starboard. Make it similar to Google Blob's starboard, staff have to do the initial reaction and other users can react to it after (so inappropriate things dont get starred and lessens spam in the starboard channel)

**How the feature is useful**
Promotes activity for staff and users.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
+1 very cool

**Comment by Double0negative** [comment]
Can you add some more details about what this is? I'm not entirely sure what a starboard is.

**Comment by MiginsMC** [comment]
I believe it's when a user reacts to an image with a star, it sends a message somewhere, which includes the message. For example - 
![Screen Shot 2020-09-12 at 7 39 30 pm](https://user-images.githubusercontent.com/58871819/92992633-ae9cc880-f52f-11ea-807b-d35c39b69010.png)

**Comment by Double0negative** [comment]
Got it, so someone stars a post (on discord?) It sends it to a special channel that tracks how many stars it gets?

**Comment by PundaChen** [comment]
Yeah what mig said, it would be preferred if it's similar to what google blobs has, their starboard is pretty active, they only allow a staff member to star the message but after that everyone is able to star the message.

**Comment by xSpiderMC** [comment]
another thing could be that after a certain number of reactions it goes to a channel or somewhere for quick approval, letting the community start the entry and just needing staff to approve it for it to be displayed
