### ISSUE TITLE
Bold Formatting in Server MOTD

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#18]
### Feature request

**Platform**
 All

**Describe the feature**
 Currently you can't directly use the bold formatting code in your MOTD. (&l) It would be nice if it worked properly.

**How the feature is useful**

Bold formatting is commonly used.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
![image](https://user-images.githubusercontent.com/2638275/90325518-6fc82280-df31-11ea-8557-b703d3a9b55f.png)
Looks like you can.

**Comment by JackTMR** [comment]
Use **§** instead, worked for me.
