### ISSUE TITLE
Better Text Editor Boxes In Panel.

### ISSUE THREAD

**Issue by WallyTube** [Minehut/Meta#184]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
There are certain things that I can do in Notepad++ or VSC that I can't do in minehut's text editor box. The ability to triple click text to highlight all the text would be nice. We should also be able to do CTRL+S to automatically save text without needing to click a button.

**How the feature is useful**
I use VSC to make skripts, but It would be nice to edit text inside the panel instead of needing to copy over everything just to use VSC's features.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update.
