### ISSUE TITLE
Darker Dark Theme On Panel

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#186]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Make the current dark theme darker. 

**How the feature is useful**
Makes the panel look nicer

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
Yeah I have to agree. The current 'dark theme' is just an ugly gray palette. It's a tiny improvement that could make it look so much better.

**Comment by drtshock** [comment]
Done ;)
