### ISSUE TITLE
Cannot authorize for the API

### ISSUE THREAD

**Issue by Reassembly-Minehut** [Minehut/Meta#187]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website

**Describe the bug**

If you try to authorize in the API, it returns a 403 error.

**To reproduce**
Steps to reproduce the behaviour:
Try to authorize using the API

**Expected behaviour**

It should just let me do what I need to do

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): Chrome
- Operating system (and version): Windows 10
- Minehut server name: Rows

**Screenshots**

http://i.callumloustv.com/i/wvp18sru.png

**Additional context**

I'm using the "requests" library in python

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Vrganj** [comment]
This isn't a bug. Minehut doesn't use basic auth. It uses 2 headers, authorization & x-session-id.

**Comment by iGalaxyYT** [comment]
Can this get marked as invalid and closed? @jellz
