### ISSUE TITLE
use arc.io for profit

### ISSUE THREAD

**Issue by killergotrekt** [Minehut/Meta#188]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Both
**Describe the feature**

using https://arc.io/, minehut makes money off visitors on their website. From ARC:
`Arc is a peer-to-peer Content Delivery Network (CDN) that pays websites for contributing bandwidth.`

**How the feature is useful**

- It increases website performance.
- MInehut can make up to $40,000 per month (if 4 million people are on the site for 20+ minutes & everyone used desktop)
- It can give minehut users a passive way to earn credits by idling on a minehut specific webpage like (https://minehut.com/dashboard/earn-credits) such as every 20 minutes, give 5 credits?

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
Minehut can't really afford to be slower rn. :\

**Comment by farwl** [comment]
sounds cool, +1

**Comment by TrainerX** [comment]
> Minehut can't really afford to be slower rn. :\

I highly doubt this makes Minehut any slower. In fact, this might even accelerate the Minehut webpage. Arc.io uses computers running the web program to load pages, rather than having the normal web server which is further away to load the pages.
More people using arc = faster Minehut + faster other webpages

**Comment by killergotrekt** [comment]
Many other server *free* hosts use arc too (which i won't name). 
It's pretty easy to setup and they pay using paypal

**Comment by LukasmanMHdude** [comment]
There's literally no reason why mh shouldn't do this.

**Comment by Vrganj** [comment]
> There's literally no reason why mh shouldn't do this.

You want everyone using the website to share their bandwidth to earn a company a few hundred dollars?

**Comment by killergotrekt** [comment]
As I said.
`It gives minehut users a passive way to earn credits by idling on a minehut specific webpage like (https://minehut.com/dashboard/earn-credits) such as every 20 minutes, give 5 credits?`

I'm going to edit it and say `minehut users can give` not `It gives minehut a passive way to earn credits` it is too confusing

**Comment by robertwestbury** [comment]
I think this is a 10/10 idea yes, im sure the people of minehut would love to have their bandwidth stolen 👍 👍 👍 👍

**Comment by WallyTube** [comment]
> I highly doubt this makes Minehut any slower. In fact, this might even accelerate the Minehut webpage. Arc.io uses computers running the web program to load pages, rather than having the normal web server which is further away to load the pages.
> More people using arc = faster Minehut + faster other webpages

smh you really know nothing about networking do you? It doesn't matter how far away the services are. It matters if you have all of your bandwidth streaming into someone else stuff. That takes time.

**Comment by killergotrekt** [comment]
> I think this is a 10/10 idea yes, im sure the people of minehut would love to have their bandwidth stolen 👍 👍 👍 👍 

Ok.
1. When **You** use Arc, you are sharing your bandwidth with the service. 
2. Arc gives you an option to turn it off using the built in widget at anytime.

**Comment by WallyTube** [comment]
> > I think this is a 10/10 idea yes, im sure the people of minehut would love to have their bandwidth stolen 👍 👍 👍 👍
> 
> Ok.
> 
> 1. When **You** use Arc, you are sharing your bandwidth with the service.
> 2. Arc gives you an option to turn it off using the built in widget at anytime.

ok, so you're giving them authority to your bandwidth, and then turning off the service.....

**Comment by robertwestbury** [comment]
Imagine some kid going on data on his mums phone to run a command on his server while on data and it actually just uses all of the data 👍 👍 👍

**Comment by killergotrekt** [comment]
> > > I think this is a 10/10 idea yes, im sure the people of minehut would love to have their bandwidth stolen 👍 👍 👍 👍
> 
> > 
> 
> > Ok.
> 
> > 
> 
> > 1. When **You** use Arc, you are sharing your bandwidth with the service.
> 
> > 2. Arc gives you an option to turn it off using the built in widget at anytime.
> 
> 
> 
> ok, so you're giving them authority to your bandwidth, and then turning off the service.....

You choose to turn off the service by opting out of arc using the widget as I said

**Comment by killergotrekt** [comment]
> Imagine some kid going on data on his mums phone to run a command on his server while on data and it actually just uses all of the data 👍 👍 👍 

minehut can choose to disable using arc on mobile for this reason.

**Comment by robertwestbury** [comment]
or they just couldnt do it lol

**Comment by killergotrekt** [comment]
Plus, that bandwidth sharing should only be in effect while on a specific webpage like earning credits while idling.

**Comment by robertwestbury** [comment]
again or they just couldnt do it anyway

**Comment by killergotrekt** [comment]
> or they just couldnt do it lol
> again or they just couldnt do it

this is a suggestion, minehut can choose to add this or not.
no need to make it a full scale argument.
If you do not like this idea, you should’ve did a thumbs down on the first post

**Comment by robertwestbury** [comment]
did i ask

**Comment by Blocksnmore** [comment]
>  Feel free to discuss the idea in the comments.

**Comment by drtshock** [comment]
Interesting. I just sent this to our person that runs the ads on our site to see what they think. Not sure this is something we'd want to do, but definitely intriguing. I'll update with any more info I hear.

**Comment by gruns** [comment]
> minehut can choose to disable using arc on mobile for this reason.

Arc doesn't use any cellular bandwidth. If a user is on a cellular connection, Arc's widget doesn't share any bandwidth with the network (although it still connects to other, super-close browsers to download content p2p so the website continues to load as fast as possible).

Source: I build Arc. 😊

**Comment by killergotrekt** [comment]
> > minehut can choose to disable using arc on mobile for this reason.
> 
> Arc doesn't use any cellular bandwidth. If a user is on a cellular connection, Arc's widget doesn't share any bandwidth with the network (although it still connects to other, nearby browsers to download content p2p so the website loads as fast as possible).
> 
> Source: I build Arc. 😊

epic! thanks for clarifying for us :)

**Comment by drtshock** [comment]
Thanks for the suggestion but this isn't something we'll be doing at this time.

**Comment by BennyDoesTheStuff** [comment]
I know this is closed now but this is interesting for anyone wondering. I've been using arc.io on my website for the past month and I set it to do monthly payouts, and within the past month, it has made me $16.45. Setting up arc.io on my website was extremely easy and all it really required was adding a header to my website as well as a .js file.

My website stats (monthly):
- Around 2000 unique visitors
- 72k requests

I only set up arc.io on one of the pages on my website so not all visitors and requests made to the domain were set up to use arc.io. The specific website I set up arc.io on was [https://minehut.bennydoesstuff.me](https://minehut.bennydoesstuff.me).

Proof:
![ArcDashboard](https://i.imgur.com/JUZJwtg.png)
![Paypal](https://i.imgur.com/N07SJdR.png)

**Comment by oddmario** [comment]
> > minehut can choose to disable using arc on mobile for this reason.
> 
> Arc doesn't use any cellular bandwidth. If a user is on a cellular connection, Arc's widget doesn't share any bandwidth with the network (although it still connects to other, nearby browsers to download content p2p so the website loads as fast as possible).
> 
> Source: I build Arc. 😊

Hello @gruns 

I'm unsure if things started falling down recently but I've been an Arc user since it's very beginning and always was paid on time.

Went through a lot of revenue fluctuations and things like that. However, it's been like 15 days and I've received no payments at all since the July that ended just yesterday

Any updates on this?

**Comment by WallyTube** [comment]
You really shouldn't be necroposting on a closed thread for the sake of unrelated customer support.
