### ISSUE TITLE
Display hat layer on Minecraft player head in dashboard sidebar

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Meta#19]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Use https://minotar.net/helm/[username]/100.png instead of https://minotar.net/avatar/[username]/100 when fetching the head to display on the sidebar.

**How the feature is useful**

Using **/helm/[username]/** instead of **/avatar/[username]/** will display the hat layer on skins, and will appear most accurate to what the skin looks like ingame.
What it currently looks like, without the hat layer:
![Screenshot](https://cdn.discordapp.com/attachments/592130982451216402/743230117349949510/unknown.png)
What the user's face with the hat layer looks like:
![Screenshot 2](https://i.imgur.com/cxTlbZW.png)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Ah thanks for pointing out, didn't know.

**Comment by DaRealMinecraftexpert** [comment]
I'd love this as My Character looks Terrifying without its Hat Layer

**Comment by jellz** [comment]
It’s already implemented :)

**Comment by DaRealMinecraftexpert** [comment]
Ok, but it did make it creepy when it wasnt ;)
