### ISSUE TITLE
Auto-lock threads that haven't been active in over 60 days on the forums

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#192]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Auto-lock threads on the forums that haven't received any messages/poll votes after 60 days (negotiable time, don't vote based on this alone).

**How the feature is useful**

Minehut staff. It will stop necroposters!!

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by TrainerX** [comment]
I feel like it shouldn't be auto-locked, but rather lose the ability to be bumped.

**Comment by PundaChen** [comment]
There are multiple kinds of posts where users are allowed to respond after 60 days of creation
