### ISSUE TITLE
SkUniversal going red

### ISSUE THREAD

**Issue by Graphick2** [Minehut/Meta#197]
### Bug report

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
in-game: both

**Describe the bug**

This bug is an issue with 5 plugins together. those plugins are WorldEdit, WorldGuard, PlotSquared, Skript and SkUniversal

**To reproduce**
1. Add "skript, SkUniversal, WorldGuard, WorldEdit and PlotSquared" to your plugins
2. Restart Server
3. Join Server
4. type /pl
5. SkUniversal is red

**Expected behavior**
I expected that all 5 plugins would work speaking SkUniversal has multiple plugin hooks with one of them being PlotSquared

**Device Information**
- Minecraft client (and version): 1.16+

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by xSpiderMC** [comment]
Did you try checking your logs? This isn't a bug with minehut but an issue with a plugin

**Comment by BennyDoesTheStuff** [comment]
This is the wrong place, please post plugin bugs in the corresponding category on the forums.
