### ISSUE TITLE
What is this button?

### ISSUE THREAD

**Issue by WallyTube** [Minehut/Meta#198]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Website / Panel

**Describe the bug**
There is this weird logo next to the account settings + log out button, that takes me to this site [here](https://freestar.com/?utm_medium=stickyFooter)

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the panel
12. Look at the bottom.
7. See error

**Expected behaviour**
Don't Have A Button There?

**Device Information**
- Web browser: Microsoft Edge (Newer One)

**Screenshots**
![image](https://user-images.githubusercontent.com/69739715/90547584-5a314380-e151-11ea-951b-35c6a067566f.png)

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by PundaChen** [comment]
Can confirm, it doesn't look like a button however 
![image](https://user-images.githubusercontent.com/42002575/90551804-2cb8ba00-e192-11ea-8733-9923234a1600.png)
Using Google Chrome ^

**Comment by xSpiderMC** [comment]
It looks like an icon that links to a website, when you click on it, it directs you to a page that looks like minehut is using for analytics now?

**Comment by jellz** [comment]
The icon is a link to a service Minehut is using for an ad campaign. It's not a bug (the report was reasonable, though), and the icon should disappear in 10 days.
