### ISSUE TITLE
Bungee joining bug

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#199]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Java (bungeecord)
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1.Join a mh server
2. if it kicks you to the hub but theres no kick message etc it worked
3.look at chat
4.if you do try and rejoin with /join it says connected from another ip

**Expected behaviour**

this doesnt happen
**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 
Java 1.16
Browser: N/A
OS: Windows
Server: Azynpvp
**Screenshots**

https://blocksnmore.is-inside.me/PF2SAr7d.png
**Additional context**

This bug has been patched in paper's fork of bungee waterfall https://papermc.io/downloads if mh wants to update
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
Ok, I actually CAN'T play bc of this. 
https://discordapp.com/channels/546414872196415501/546422616609783818/747908828871262248

**Comment by BennyDoesStuff** [comment]
This doesn't seem to be an issue anymore, but we can reopen if it's still occuring.
