### ISSUE TITLE
Better Server Panel Idea

### ISSUE THREAD

**Issue by WallyTube** [Minehut/Meta#201]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website / Panel

**Describe the feature**
I came up with this cool server panel layout that is not only clean and looks nice, but convienient in many reasons, some being:
- No Annoying Sidenav For Farwl To Get Mad About
- No Ads At The Top Of The Page That Shifts The Whole Page Down 2 Seconds After Loading
- Cleaner Ad Placement (The ads right now are off centered)
- Nice looking Background + 70% Opacity Panels.
- Sidenav Now Located At The Top Of The Page. This looks way better.
- Better Looking Light/Dark Mode
- Option To Customize Background Image

Light Mode:
![image](https://user-images.githubusercontent.com/69739715/90565163-13047c00-e16c-11ea-9592-f71482be5da3.png)
Dark Mode:
![image](https://user-images.githubusercontent.com/69739715/90565207-257eb580-e16c-11ea-9fe1-c309d05b2acf.png)

**How the feature is useful**
I've seen a lot of panel complaints about thinks looking messy and out of place. This seems like a good solution to most of those features.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by hriaksnv5678** [comment]
something like this? 
![image](https://user-images.githubusercontent.com/39273217/90629237-f07b6d00-e216-11ea-9333-d5252c3c9a7c.png)

(this is me badly applying css to the panel, and the bottom ad didn't load for me so I couldn't add that but still)

**Comment by WallyTube** [comment]
> something like this?
> ![image](https://user-images.githubusercontent.com/39273217/90629237-f07b6d00-e216-11ea-9333-d5252c3c9a7c.png)
> 
> (this is me badly applying css to the panel, and the bottom ad didn't load for me so I couldn't add that but still)
> (yes its off-centered, if I was any good I would fix that)

yeah just without the bad color scheme.

**Comment by Double0negative** [comment]
We are continuously working on improving the layout and theme of the webpanel. Thank you for yall's input, it will be taking into account as we improve the panel.
