### ISSUE TITLE
Older Version Support Has Gone Bonkers Lately

### ISSUE THREAD

**Issue by WallyTube** [Minehut/Meta#204]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Java

**Describe the bug**
The Via Plugins are kicking people from their servers and not letting them join entirely. I don't know if it is just one bad plugin, but I had all 3 on my server and I couldn't join.

ProtocolSupport is having troubles rendering in entities. Sometimes item drops remain frozen on the ground and entities and players seem frozen but invisible in real time. It take a relog to fix this bug. This happens randomly, it isn't all the time. The best was to trigger it is large world changes, like switching worlds or using WorldEdit.

I'm pretty sure the via plugins are also affecting the lobbies, because whenever someone steps on a pressure plate, uses a door or lever, and other things, all the older version people get kicked from that lobby into a fallback one.

**Device Information**

- Minecraft client (and version): 1.8.9 Lunar
- Minehut server name: Hydrid (the server where via and protocol are not working)

**Screenshots**

Evidence of lobby bug [here](https://drive.google.com/file/d/1T1c12Rz8uPNdc8AQ5bjR7FzQq2RrAhV-/view?usp=sharing)

I haven't been able to get evidence for the ProtocolSupport bug. The via bug just disconnects me from the server to my minecraft server list.

If you can submit other bugs of 1.8 malfunctions, I'll add it to this post <3

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
This is because of the plugins being out of date, i posted the error log and i was told that viaback was out of date

**Comment by drtshock** [comment]
We updated to full 1.16.3 since this was posted and aren't using via on the proxy level. Please re open with further information if this is still an issue.
