### ISSUE TITLE
Support json.gz file uploads / downloads

### ISSUE THREAD

**Issue by officialRonSki** [Minehut/Meta#205]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
    => In Game, Java

**Describe the feature**
    => json.gz's is basically JSON, it's used by some plugins (Like LuckPerms), To Import and Export data.

**How the feature is useful**
    => The feature would benefit server owners by making it easier to dev a server on a localhost, and then just uploading everything onto minehut, For example, You could make your ranks / permissions locally and just upload it and import it onto luckperms.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
How do you use json.gz with LuckPerms?

**Comment by officialRonSki** [comment]
> How do you use json.gz with LuckPerms?

You do /lp import <filename> to import in ranks and /lp export <filename> to export ranks to use on other servers

**Comment by jellz** [comment]
Hey, please write your requested file extension here #5 thanks!
