### ISSUE TITLE
Quicker and easier punishment system for staff

### ISSUE THREAD

**Issue by Reassembly-Minehut** [Minehut/Meta#206]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Ingame

**Describe the feature**

Instead of mods having to check a users history and then punish someone based on that. Make a command (Say, /spam <user>) that checks the user's past punishments (for spam or all punishments, depending on how it goes) and then bans them for the correct time length

**How the feature is useful**

It would make it quicker for staff to mute people so they can help the community and punish more rule breakers

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Reassembly-Minehut** [comment]
Oh theres meant to be a "user" thing after /spam but it got removed for some reason

**Comment by jellz** [comment]
You can edit your post

**Comment by BennyDoesTheStuff** [comment]
I disagree with this, I know minecoder had a plan to eventually automate escalating punishments via a possible GUI (IIRC, don’t quote me) so I don’t think a system like this would be used. Staff could set the reason to anything so it wouldn’t be possible to check all punishments for a specific offense at the moment.
