### ISSUE TITLE
Move option selection at right side of screen

### ISSUE THREAD

**Issue by E4zily** [Minehut/Meta#207]
This menu is so annoying when you skripting or editing files, you always drag your mouse an it and opening something, move it on right side of screen?
![image](https://user-images.githubusercontent.com/59582293/90651111-55e65280-e245-11ea-8dd3-4087c2efc3cc.png)

**Comment by WallyTube** [comment]
or even better, move all the buttons to the tab above the panel #201

**Comment by xSpiderMC** [comment]
You should follow the feature request issue template
