### ISSUE TITLE
New botting rules suggestion

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#209]
**Platform**
All

**Describe the feature**
A new rule to combat lobby bots advertising player servers. This has been a very tough issue for everyone, as bots make it difficult for normal players to use the chat. The rule would be simple. Any server owner who has been **PROVEN** to have used or is using bots would be punished to a justifiable degree based on how they used the bots.

**How the feature is useful**
It would discourage users from boting the minehut lobby, as the potential punishment for boting the lobby would be far to great to risk. The current method of dealing with bots, is to ban them, but not attack the root of the problem- greedy player servers. I feel like this feature would help significantly reduce or even eliminate bot attacks on the lobby.

---------------------------------------------------------------------------------------------------------
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by xSpiderMC** [comment]
How can the staff team, or a player reporting this user/server verify that it is the owner of the server and not someone trying to get the owner banned or harrased by angry players?

**Comment by Shlba** [comment]
yea pretty much. I just feel like there isn't enough repercussions to the server owner when they bot the lobby. They aren't actively discouraged from boting as there aren't any real punishments for boting to the person instigating the bot attack

**Comment by LukasmanMHdude** [comment]
if you wanna send the owner like a slap on the hand, sure, but I don't really think that server owners should be targeted, because I know that this could get abused, and as a server owner, I commonly ask my staff members to "go advertise" and I don't know what there doing in the lobby.

(by slap on the hand just add a warning message to the dashboard)

**Comment by Shlba** [comment]
> if you wanna send the owner like a slap on the hand, sure, but I don't really think that server owners should be targeted, because I know that this could get abused, and as a server owner, I commonly ask my staff members to "go advertise" and I don't know what there doing in the lobby.
> 
> (by slap on the hand just add a warning message to the dashboard)

It would apply to bot attacks and not the everyday guy posting a advert every 5 minutes

**Comment by BennyDoesStuff** [comment]
A recent rule was added regarding the use of bots.
