### ISSUE TITLE
MH rollbacks

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#215]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information

**Platform**

**Describe the bug**
World progress disappears during restarts and stuff. This is probably an issue with world autosaving.

we're actually pretty lucky, as I've seen servers with HOURS of survival work gone to the Minehut void.

**To reproduce**
Steps to reproduce the behaviour:
1. Make a server
2. Spend a few hours building
3. AFK/wait/shut down your server

**Expected behavior**
Not undo your map.

**Device Information**

- Minecraft client (and version): 1.16
- Web browser (and version): Chrome Latest
- Operating system (and version): Windows 10 1909
- Minehut server name: azynpvp

**Screenshots**
before:
![image](https://user-images.githubusercontent.com/69743171/90924645-b7710300-e3a4-11ea-931f-78e9ada23792.png)

After:
![image](https://user-images.githubusercontent.com/69743171/90924681-c22b9800-e3a4-11ea-89b9-a7b569d8ed6e.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by MiginsMC** [comment]
This is a bug.
I've seen so many people come into #support heartbroken because their world has reset. I'm not sure why this happens or how to fix it, but this really needs to stop. Especially since /dl doesn't work-

**Comment by drtshock** [comment]
We're aware and actively working on this.

**Comment by drtshock** [comment]
Addressed in Monday night's update.

**Comment by deathsou** [comment]
Still not fixed...

**Comment by drtshock** [comment]
Can you please create a new ticket with details so we can dive in.

**Comment by deathsou** [comment]
I have, and was answered by someone who didn't really know what they were doing. Replied like 15 hours ago, no reply since.

**Comment by deathsou** [comment]
It's in the Minehut Forums (name: Death_Source, yoyojiiifb@gmail.com)

**Comment by LukasmanMHdude** [comment]
Would like to note that he calls github issues "tickets" as well, so maybe he meant a bug report???

**Comment by deathsou** [comment]
Well I already included all the info in the ticket... maybe just use that? Or be more clear about where you want users to get help

**Comment by Sniped** [comment]
@deathsou you can find where to get support for things such as this over [here](https://github.com/Minehut/Meta/blob/master/SUPPORT.md). In this case, I believe Trent is directing you to make a ticket over at the [support form](http://minehut.com/support/form).

**Comment by drtshock** [comment]
Support team can't really do anything about rollbacks. I was asking to create a new github ticket (since we initially resolved this one) with steps to reproduce the rollback so we can dig into it further.

**Comment by deathsou** [comment]
Ah ok, will do that
