### ISSUE TITLE
Mobile Panel Redesign

### ISSUE THREAD

**Issue by vishy-dev** [Minehut/Meta#216]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
I am suggesting a redo of the panel for mobile, as currently it isnt that great for mobile users.
I suggest something like this be introduced:
![](https://cdn.discordapp.com/attachments/718215158329114646/746498329638207558/7F71A58F-ABAF-451E-8E82-2859650B1EDD.jpeg)
![](https://cdn.discordapp.com/attachments/718215158329114646/746498701425377362/17032BE1-18C6-4B83-8BA0-922AA100C1F7.jpeg)
As well as a redesign of the server edit pages for mobile.

**How the feature is useful**
It lets people who want to manage their server on the go, check status or so from their phone to do so. As of right now, this is possible but it isnt very good to use.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Would probably be better to do a mobile app than redesign the website for mobile. Could be built using Vue Native, which compiles to React Native.

**Comment by vishy-dev** [comment]
hm but then paying $140 to release it to respective platform app stores + updating it is kinda annoying, itd be better to make the webpage just better, making a app could be a later project.

**Comment by vishy-dev** [comment]
Why is this still open lmao
