### ISSUE TITLE
Ip bans for moderators (or senior mods)

### ISSUE THREAD

**Issue by TrueReassembly** [Minehut/Meta#219]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 In game

**Describe the feature**

Allow moderators (Or senior mods) to IP ban bots and people who evade punishments.

**How the feature is useful**

It would let staff ban bots and people who evade to spam much quicker

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Reassembly-Minehut** [comment]
> > Then they appeal
> 
> I guess that works, its just inconvenient
> also the fact that most botters etc have a vpn kinda makes this obsolete since mh has no anti vpn (to my knowledge)

I mean more that staff can ban everyone on a certain IP address at once.

**Comment by jellz** [comment]
I don't think we should bend over backwards to support users who use accounts from MCLeaks etc. If they want a legitimate playing experience, they can use purchase their own or use a friend's Minecraft account.

**Comment by drtshock** [comment]
This is planned as part of a mod tools update coming in the future.

**Comment by Sniped** [comment]
The mod tools update has been released, making this issue done.
