### ISSUE TITLE
Add Hardware Banning

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#220]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Both

**Describe the feature**
Imagine IP banning, except this time it works. Hardware IP banning is basically banning the computer from connecting to your server instead of banning the connection. I think that it would be a good idea for minehut to add a hardware ban only manageable on the console. This could be done with a command, or with an actual UI that allows you to manage players. (while I would like to have this ingame for op, people may abuse it)

**How the feature is useful**
Makes it so people can actually get rid of annoying hackers that have a good vpn and an altenating account.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
![image](https://user-images.githubusercontent.com/44182379/90984999-d9a28680-e546-11ea-8b87-fb7343fae6b0.png)

**Comment by LukasmanMHdude** [comment]
done, thx

**Comment by Draem** [comment]
90% sure this is impossible

**Comment by LukasmanMHdude** [comment]
oh no far
