### ISSUE TITLE
Minecraft avatar off-center when sidebar is closed

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Meta#221]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website (Dashboard)

**Describe the bug**

The Minecraft player avatar is not centered on the sidebar when it is closed.

**To reproduce**
Steps to reproduce the behaviour:
1. Link a Minecraft account to your Minehut account
2. Observe the sidebar when closed

**Expected behaviour**

The Minecraft player avatar should have equal spacing on both sides.

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): Chrome 84
- Operating system (and version): Windows 10 Pro 2004
- Minehut server name: N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/22878174/90991046-0b254d00-e55b-11ea-98b9-b6071a2d51e4.png)

**Additional context**

N/A

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by PundaChen** [comment]
Can confirm 
![image](https://user-images.githubusercontent.com/42002575/92326393-06c85c00-f052-11ea-9ec7-bb2f02f52667.png)

**Comment by BennyDoesStuff** [comment]
This is no longer an issue as a new website design was released.
