### ISSUE TITLE
Disallow political content in chat

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#222]
**Platform**
all

**Describe the feature**
A rule that disallows discussions political in nature. 

**How the feature is useful**
Often times I have seen many people who discuss political things usually get to invested in their topics, usually spreading out and becoming too agressive in their messages, greatly ruining the vibe of the entire chat room until the user leaves. Having a rule like this would greatly reduce the spam in the text channels

---------------------------------------------------------------------------------------------------------
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
Yeah nothing good comes from discussing politics in chat so +1

**Comment by LukasmanMHdude** [comment]
Not 100% sure how this would be moderated, and some people may get falsely accused for this. Would be down for this on disc, but not ingame, so I'll not vote on this one.

**Comment by MiginsMC** [comment]
👎 
I like to receive contrasting opinions to my own, tbh and a lot of these can stem from political views/concepts. Although the Minehut lobby probably isn't the best place to discuss it, I don't think it should be disallowed entirely.

**Comment by Shlba** [comment]
> 👎
> I like to receive contrasting opinions to my own, tbh and a lot of these can stem from political views/concepts. Although the Minehut lobby probably isn't the best place to discuss it, I don't think it should be disallowed entirely.

There are better places to discuss political content than minehut lol. Minehut is a place for fun, not a place to listen to a guy rant about a very controversial topic.

**Comment by jellz** [comment]
Discussions about politics aren't the same as people ranting about very controversial topics

**Comment by MiginsMC** [comment]
> > 👎
> > I like to receive contrasting opinions to my own, tbh and a lot of these can stem from political views/concepts. Although the Minehut lobby probably isn't the best place to discuss it, I don't think it should be disallowed entirely.
> 
> There are better places to discuss political content than minehut lol. Minehut is a place for fun, not a place to listen to a guy rant about a very controversial topic.

Regardless, there isn't any reason why it shouldn't be discussed, tbh. Also I think staff members should just focus on actually punishing people for the current rules, having to monitor every minor conversation to see if it mentions even a slightly political phrase or view would be very difficult. 

Also if you mute or warn someone for saying something like 'BLM', the community is not going to like that moderator very much at all :eyes:

**Comment by BennyDoesTheStuff** [comment]
I'm against this, I'm fine with allowing political talks as long as it doesn't cause an argument or get too heated. It would also be difficult to need to moderate this and I don't see a good reason for disallowing it. Any topic could really lead to arguments and spam and I don't think we should disallow this just because it might.
