### ISSUE TITLE
Custom Panel Color Templates

### ISSUE THREAD

**Issue by jakepronger** [Minehut/Meta#223]
Custom Panel Color Templates that cost credits or some what from either market place or shop (wherever) its a great way to customise the panel color to peoples needs/wants and would look great!

**Comment by iGalaxyYT** [comment]
I don't think it should cost credits but it would be cool to customize the panel without having to use a userstyle.

**Comment by farwl** [comment]
where is your format 😲

**Comment by LukasmanMHdude** [comment]
^^^

**Comment by jellz** [comment]
Please follow the format for feature requests, you can use it [here](https://github.com/Minehut/Meta/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=).
