### ISSUE TITLE
Move plugin suggestions from forums to GitHub

### ISSUE THREAD

**Issue by TrueReassembly** [Minehut/Meta#227]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Move plugin requests from the forums to here

**How the feature is useful**

It makes it less confusing for players to suggest thing

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Agreed, this will help reduce duplicate plugin suggestions.

**Comment by LukasmanMHdude** [comment]
I assume you mean the plugin suggestions?

**Comment by iGalaxyYT** [comment]
> I assume you mean the plugin suggestions?

I think so, @Reassembly-Minehut said: "Move __plugin requests__ from the forums to here"

**Comment by LukasmanMHdude** [comment]
I would read the comments on #191

**Comment by MiginsMC** [comment]
I really like this idea. The only issue would be that there would probably be more people streaming in here not following the rules and the format. Which pretty much means an entire other platform for staff to moderate. 

Additionally, the whole idea of the Meta discord is that if you are involved in the community and have an understanding of the rules and how Minehut itself works, then you'll eventually stumble into the discord (more so before !meta existed). By encouraging users to come here on the forums, that's removing the whole point of the meta discord (excluding tests, ofc), imo. 

I'm also aware that tags featuring the meta invite (such as !suggest) exist, but there are a lot of people on the forums (especially compared to the discord) and I think this would cause a lot of people to just suggest ignorant ideas that will inevitably be shut down almost immediately, wasting staff members and our time. Contrarily, the influx of new members suggesting new ideas may present a different opinion or insight that may not have been available previously. 
I'll wait and see other opinions before I react.

**Comment by jellz** [comment]
@MiginsMC Is your reply about all feature requests or just plugin requests? Because the OP was about plugin requests 😂

**Comment by WallyTube** [comment]
yeah this would absolutely flood the github issues.

Alternatively, how about minehut makes a website where you can submit new plugins/update requests. If your request is new, you can post a new thread about it, and if it is duplicated, it will send you to the original post, where you can 'upvote' it. Threads with the most upvotes should gain the most attention from developers.

**Comment by KikoPT1234** [comment]
how about we just leave it as is

**Comment by LukasmanMHdude** [comment]
naaa, current ones aren't that great

**Comment by KikoPT1234** [comment]
ok, how about we make another github for plugin suggestions and put that one in the main discord, that way you don't have to worry about too many people joining the meta discord

**Comment by MiginsMC** [comment]
> @MiginsMC Is your reply about all feature requests or just plugin requests? Because the OP was about plugin requests 😂

It's relevant either way :)

**Comment by ItzOP** [comment]
I just think it's useful having everything in 1 place, so yeah I agree, moving them to github would be better.

**Comment by pop4959** [comment]
I like this idea, as I mentioned in #191. 😉 Would certainly be easier to organize plugin issues and requests that way.

**Comment by jellz** [comment]
I'll work on supporting plugin requests here.

**Comment by Double0negative** [comment]
dupe: #191
