### ISSUE TITLE
UL worlds breaking once server restarts.

### ISSUE THREAD

**Issue by WholeWheatGrape** [Minehut/Meta#228]
### Bug report

Sorry if I did something wrong.

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

In-game
Both

**Describe the bug**

If you upload a world using /ul and restart the server, once the server starts back up all the NPCs, Entities, etc will disappear and any skript that teleports you into that world won't work anymore.

**To reproduce**
Steps to reproduce the behaviour:
1. Go into your server and upload a world using /ul
2. Place around some Entities
3. Restart the server
4. Once you join back the Entities will be gone

**Expected behavior**

**Device Information**

- Minecraft client (and version): It doesn't matter but I was using Fabric 1.16.1 with some mods
- Web browser (and version): Brave Browser
- Operating system (and version): Windows 10 version 10.0.18362 64 bit 
- Minehut server name: PowerRPG

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by jellz** [comment]
> any skript that teleports you into that world won't work anymore.

But the world still exists, right?

**Comment by WallyTube** [comment]
This isn't a bug. You have to go into your panel settings and click on "Level type" and change it to the world you want to be spawned in. This also affects holograms, npcs, and skripts. Nothing like actually reading the panel will do for you.

![image](https://user-images.githubusercontent.com/69739715/91181107-25bc0b00-e6ae-11ea-9909-94dd72f33bf4.png)

**Comment by WallyTube** [comment]
Side note, when reporting and testing bugs in the future, don't use modded clients.

**Comment by WholeWheatGrape** [comment]
On Aug 25, 2020 9:39 AM, "WallyTube" <notifications@github.com> wrote:

Side note, when reporting and testing bugs in the future, don't use modded
clients.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minehut/Meta/issues/228#issuecomment-680031163>, or
unsubscribe

**Comment by WholeWheatGrape** [comment]
> This isn't a bug. You have to go into your panel settings and click on "Level type" and change it to the world you want to be spawned in. This also affects holograms, npcs, and skripts. Nothing like actually reading the panel will do for you.
> 
> ![image](https://user-images.githubusercontent.com/69739715/91181107-25bc0b00-e6ae-11ea-9909-94dd72f33bf4.png)

Huh? I don't really know what you mean.

**Comment by drtshock** [comment]
Does this happen if you do it on a local server as well? We're not doing anything unusual with world loading so it sounds like this is just Minecraft behavior.

**Comment by drtshock** [comment]
Feel free to re open if you can post further info on this.
