### ISSUE TITLE
New feature idea for ranks on MH

### ISSUE THREAD

**Issue by titustitus98** [Minehut/Meta#229]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta) 
- [x] This is not a bug report, support request or plugin request 
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue 
- [x] This issue does not contain any sensitive information 

**Platform**
 Website & In-game

**Describe the feature**
  why don't you make it so that instead of having people to pay large summs of credits and money for the server that if a player has a donator rank like vip or whatever that once every week or months they get like 100 credits or something and that they get a small reduction like 5% of server plan prices

**How the feature is useful**
 that way more people will want to buy ranks especially since they will have an actually use other than just being nice to look at and giving a few small perks in the lobbys.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
Sorry but lifetime donator ranks are never going to provide server hosting perks
