### ISSUE TITLE
Better Version Integration

### ISSUE THREAD

**Issue by WallyTube** [Minehut/Meta#23]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java

**Describe the feature**
Right now, Minehut uses the Via version plugins to allow older versions to join their servers and lobbies, but often times, these plugins break and are buggy as versions are upgraded. If Minehut made their own cross-version plugin or changed an existing plugin, they could have more control on what they do and don't want changed, as well as be able to automatically update the version plugin when updating minecraft versions and fix bugs faster than waiting for plugin developers to do it themselves.

It would also be nice to take advantage of the above ^^ and integrate versions into the server panel for users to have more control on player versions. This could be integrated as a checklist and you could enable/disable certain versions.

**How the feature is useful**
It would eleminate the current bugs we face with the Via plugins and ProtocolSupport and allow minehut to have more control over how their services should work with older versions.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
This would be an incredibly amount of work and I'm not sure worth the time we'd put into it. A plugin like viaversion / protocolsupport is very complex. There's a reason there are only 2 big ones that are maintained but really talented teams. I think the better path is to work to get on newer versions more quickly.

**Comment by farwl** [comment]
> I think the better path is to work to get on newer versions more quickly.

I strongly disagree. If anything you guys shouldn't be rushing into new versions without making sure everything is compatible and working as it should. There were a large number of bugs and glitches that the 1.16 update caused not to mention weeks of waiting for commonly used plugins. You could say it was the plugin author's fault but that'd be ignorant seeing as you guys don't allow anyone to change their server version or opt-out of the latest update. Some bugs that 1.16 caused still have not been fixed and it's a bit annoying. If you guys are focusing on updating to the newest version every time a new release comes out, better version integration/support is extremely necessary and quite vital. ProtocolSupport and the ViaVersion plugins just don't have the same effect as actually being on a 1.8 server. There are countless bugs. The most common one would probably be invisible players, this makes servers almost unplayable.

**Comment by drtshock** [comment]
I hear you. We just get around a 20%-30% bump every MC update when we're on the latest version within a few days. The solution isn't to delay updating, it's to allow users to not have to update by supporting multiple versions I think.

**Comment by WallyTube** [comment]
farwl has an amazing point. Yes, a version merger would be challenging, but switching the version of the server entirely could be nice. The only problem with this is the large majority of players using 1.16 would have to switch over to 1.8
