### ISSUE TITLE
Weird thing from adverts.

### ISSUE THREAD

**Issue by ItzOP** [Minehut/Meta#230]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

**Describe the bug**

You can see a weird symbol over the settings button when ads are enabled. (Does not show if you have no ads)
**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://minehut.com/dashboard/home'
2. Click on 'N/A'
3. Scroll down to 'N/A'
4. See error (Weird symbol over settings icon)

**Expected behaviour**

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): Chrome 84.0.4147.135
- Operating system (and version): Windows 10
- Minehut server name: N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/70059430/91225160-09a28300-e71b-11ea-8838-bac10271e57b.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
Pretty sure the devs already know about this, but if your having issues consider using an adblocker.

**Comment by ItzOP** [comment]
> Pretty sure the devs already know about this, but if your having issues consider using an adblocker.

Already do use an adblocker, just wanted to make sure they were aware. Thanks

**Comment by ZeroParticle** [comment]
We are aware of this and it will be fixed soon.
