### ISSUE TITLE
Unable to log into forums

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#231]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Website, forums

**Describe the bug**
I'm unable to log into the forums despite already being logged into the forums. When clicking sign in on the forums it sends me to minehut.com and where I can't do much since I'm already logged into the panel.

**To reproduce**
Steps to reproduce the behaviour:
1. Make sure you're logged into the panel
2. Go to the forums
3. Have the random chance to not be logged in for some odd reason
4. Try logging in.

**Expected behaviour**
You get sent to the sign in page on the panel, you're already logged into the forums or you get sent to the panel and then have to go back to the forums

**Device Information** 
Mobile Android, Brave browser.

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by killergotrekt** [comment]
Unproducable. 
iOS 12.4.8
Safari

**Comment by iGalaxyYT** [comment]
I've experienced this bug before on Chrome 84 / Windows 10 Pro 2004, but I'm unable to reproduce it reliably.

**Comment by drtshock** [comment]
Please post more info if you're able to reproduce and re open the ticket.
