### ISSUE TITLE
Take some functionality out of !server

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#234]
**Platform**
discord

**Describe the feature**
Make it so we can't see all these stats with the !server command. You can steal rss packs, plugins, world settings, and much more info. 

**How the feature is useful**
Makes is so people can't as easily steal stuff from ur server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
Yeah, most servers use skript to block people from seeing their plugins so it would be nice not to let the boss see it.
But then again, if you rely on plugins, like Citizen CMD or other plugins that can be coded with skript EASILY, anyone has the right to judge you ;)

**Comment by Shlba** [comment]
> **Platform**
> discord
> 
> **Describe the feature**
> Make it so we can't see all these stats with the !server command. You can steal rss packs, plugins, world settings, and much more info.
> 
> **How the feature is useful**
> Makes is so people can't as easily steal stuff from ur server.
> 
> **Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

No. It provides you with a list of plugins, nothing more. You still need to know how to actually use the plugins. Plugins such as skript will require a lot of skill to use, making just knowing what plugins they have virtually useless

**Comment by Shlba** [comment]
Besides I believe that you can still use the API to view the plugins that a server has, so it would pretty much be useless

**Comment by jellz** [comment]
There is no reason to make the information in the server command private.
