### ISSUE TITLE
Get rid of bedrock support

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#235]
### Feature request

**Platform**
ingame

**Describe the feature**
you read the title. get rid of it. 28 players at the most its ever had. Just a mess of bugs for devs to waste time on.

**How the feature is useful**
Drop it so they aren't spending dev monies on it.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
From my point of view, bedrock incorporation took a lot of time to make, and it isn't worth removing since it isn't hurting anyone.

**Comment by MiginsMC** [comment]
I don't believe Bedrock is that expensive (if it costs money at all). 
The devs don't even work on it anyway, it's run through a plugin external to Minehut.

**Comment by iGalaxyYT** [comment]
Bedrock support shouldn't be removed as it doesn't cause any harm. It's an extra thing that improves Minehut's accessibility.

---

> The devs don't even work on it anyway, it's run through a plugin external to Minehut.

The plugin you mentioned is https://geysermc.org

**Comment by theminecoder** [comment]
Bedrock support won't be going away anytime soon. Given it based off geyser as stated before its not much hassle for us to maintain. The current thing that is blocking faster update is also affecting bungee rollouts in general so removing bedrock support won't fix it.
