### ISSUE TITLE
Issue uploading worlds through websites

### ISSUE THREAD

**Issue by Coballium** [Minehut/Meta#236]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
In-game, Java

**Describe the bug**
 When trying to upload worlds through services such as gofile.io or mediafire, an error message saying `Upload error! Invalid files.` will pop up. However, this will not happen if file.io is used.

**To reproduce**
Steps to reproduce the behaviour:
1. Generate a world (I generated it through PaperMC)
2. Add the `world` folder to a .zip document
3. Upload the .zip document to any service other than file.io (I tested it with **mediafire**, **gofile.io** and **google drive**)
4. Enter any server you have OP on
5. Introduce the command /upload world `name you want to give that world` `link to the file you uploaded in step 3`
6. See error message pop up

**Expected behaviour**
 The world should upload normally after a couple of seconds, and then inform you that the file was successfuly uploaded

**Device Information**

- Minecraft client (and version): Minecraft Java, 1.16.2
- Web browser (and version): Microsoft Edge
- Operating system (and version): Microsoft Windows 10 Home, version 10.0.18362
- Minehut server name: Nagland.minehut.gg & GamerCom.minehut.gg

**Screenshots**

**Additional context**
 Tested with both custom WorldPainter maps and vanilla maps generated through PaperMC

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by iGalaxyYT** [comment]
Are you using a direct download link with each service? If the link doesn't return the file directly, it'll throw an error

**Comment by Coballium** [comment]
> Are you using a direct download link with each service? If the link doesn't return the file directly, it'll throw an error

I think so, i'm using the download link given
![image](https://user-images.githubusercontent.com/70524278/91736720-67691c00-ebae-11ea-84fc-d38ea25047eb.png)

**Comment by LukasmanMHdude** [comment]
I would try with file.io if you don't hit the cap, it seems stabler, and if that doesn't work use dropbox and make sure to set dl=1

**Comment by Coballium** [comment]
> I would try with file.io if you don't hit the cap, it seems stabler, and if that doesn't work use dropbox and make sure to set dl=1

didn't even consider dropbox lol, tried it with dl=1 and seems to be working. thanks a lot!
