### ISSUE TITLE
File moving

### ISSUE THREAD

**Issue by quick007** [Minehut/Meta#237]
### Feature request

**Platform**
Web (core)

**Describe the feature**
add a "clipboard" of sorts that allows us to move files around on the dashboard, and between servers. (Clipboard would appear whenever you clicked and held on a file, or when you clicked a little icon on the top right corner [looking for more ideas on how to do the clipboard icon tho])

**How the feature is useful**
People can move scripts, worlds, schemes, plugin files, and more cross-server, and within its self. This would make it easier for people to create a new server (i.e. if they wanna use the same via version or advanced ban config)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Shlba** [comment]
would be incredibly useful

**Comment by drtshock** [comment]
Between servers might not be feasible but we can probably do it within a single server.

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update.
