### ISSUE TITLE
Ban/Kick Screen

### ISSUE THREAD

**Issue by BlakeH2208** [Minehut/Meta#238]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
 Java

**Describe the feature**

Make it to where if you are banned/kicked, it doesn't go to the minehut lobby instead of the traditional failed to connect screen

**How the feature is useful**

To help bigger servers seem more professional and to help people understand why they can't join better

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
This may not be possible, and even if it is, most I just don't think that this is rly necessary.

**Comment by BlakeH2208** [comment]
It would make people know why they were banned and also make it more clear that they are banned

**Comment by Blocksnmore** [comment]
It already kicks them to the lobby and very clearly says in chat you are banned or whatever the message is. I don't see a point in this. Also if someone tries to /server ie and they get kicked off the entire minehut server that would be inconvenient, that's why i think they don't do that

**Comment by iGalaxyYT** [comment]
Should be possible using ServerKickEvent. Just straight up kick them from the network with the same reason if the ServerKickEvent state is CONNECTED (i.e. being kicked after already being connected to the server, not while connecting to the server)

**Comment by BlakeH2208** [comment]
> Should be possible using ServerKickEvent. Just straight up kick them from the network with the same reason if the ServerKickEvent state is CONNECTED (i.e. being kicked after already being connected to the server, not while connecting to the server)

Is that a plugin? If not how do I use it?

**Comment by LukasmanMHdude** [comment]
> > Should be possible using ServerKickEvent. Just straight up kick them from the network with the same reason if the ServerKickEvent state is CONNECTED (i.e. being kicked after already being connected to the server, not while connecting to the server)
> 
> Is that a plugin? If not how do I use it?

:pesnsivewiggle:

**Comment by LukasmanMHdude** [comment]
(you don't)

**Comment by BlakeH2208** [comment]
Then what is it lol

**Comment by Blocksnmore** [comment]
Its part of the bungeecord api, someone would have to write a plugin for that, so theres no way currently to do it

**Comment by BlakeH2208** [comment]
Ok, sounds right. I might do it actually

**Comment by BlakeH2208** [comment]
This issue is now closed

**Comment by WallyTube** [comment]
1. This is a duplicate of #49 

2. Trent has already said:
> We hear from a lot of users that they actually learned about Minehut when the server they were playing on shut down. I'm not sure we'd want to do this, as this would just be disconnecting users from our network when we can avoid it.

**Comment by jellz** [comment]
Yep, it looks like a duplicate of #49. Thanks for pointing it out

**Comment by WallyTube** [comment]
> I might do it actually

oh and 3. Even if you did make a plugin for bungee, I don't think the admins want small servers messing with thier bungee stuff

**Comment by BlakeH2208** [comment]
Add on to issue #244

**Comment by Blocksnmore** [comment]
This issue is already closed why add onto it
