### ISSUE TITLE
Custom Lobby & Server Connectivity

### ISSUE THREAD

**Issue by BlakeH2208** [Minehut/Meta#239]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
 Both

**Describe the feature**

The ability to add a custom lobby to the server and the ability to connect to a seperate minehut server from it

**How the feature is useful**

To make servers more professional and to join a network of mh servers from one custom place

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
This has already been discussed on the discord and github (i think, ill post thing if i find it) and will not likely happen

**Comment by LukasmanMHdude** [comment]
server separate from minehut? no. -1. Also, pretty sure there's already been talk about bungee linking.

**Comment by BlakeH2208** [comment]
I just hope it's possible soon

**Comment by BlakeH2208** [comment]
Aside from this, what happened to /server from in game? Here is a minehut video based on this https://www.youtube.com/watch?v=htg8hVsVsUs

**Comment by Shlba** [comment]
> Aside from this, what happened to /server from in game? Here is a minehut video based on this https://www.youtube.com/watch?v=htg8hVsVsUs

This was easily accomplished when /server was still a feature. Just wait until /server is re-enabled.

**Comment by Blocksnmore** [comment]
> This has already been discussed on the MH Meta discord and will not likely happen

(this is about linking multiple servers)
I doubt they will consider it again considering they said it won't likely happen. They want to prioritise stuff like custom icons first

**Comment by BlakeH2208** [comment]
Ok. I will just assume it won't work. This issue is now closed

**Comment by WallyTube** [comment]
They removed /server for bug. Some of this includes the fact that servers were binding /server onto npcs to make server networks. The only good reason to make a network is to have less lag, and more player slots. If you want a network, learn some java and make your own server network.

**Comment by xSpiderMC** [comment]
It's been mentioned that /server will come back at some point (I believe), so making a network by making players do /server <servername> could be possible in the future.
