### ISSUE TITLE
Player Visibility

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#24]
### Feature request

**Platform**
 Java / Bedrock

**Describe the feature**

Allow users to toggle player visibility in the lobby. Hypixel has a feature like this in lobbies. You simply toggle with a hot bar item and players can either be seen/heard or they can't.

**How the feature is useful**

This is useful for taking screenshots of the lobby, improving FPS / performance, reducing lag, etc.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
This is really easy to do with skript, so I'm not sure how much harder it could be with java. You should also have a feature that still shows staff members and media members

**Comment by drtshock** [comment]
Yep it's pretty easy to do. We can do this in our next lobby update (not sure when).
