### ISSUE TITLE
Minehut Needs To Fix Their Advertising Problems.

### ISSUE THREAD

**Issue by WallyTube** [Minehut/Meta#240]
**Platform**
Java

**Describe the feature**
Minehut has some serious chat problems in the lobbies with advertisement flood and spam. If Minehut could find a way to make a separate in game "chat channel" just for advertisements, and would warn people for using the main chat for ads, that would solve so many problems. You could then allow people to enable/disable seeing the ad channel.

**How the feature is useful**
It could allow people in the minehut lobbies to have an actual conversation, rather than getting flooded by the nons trying to promote an all new kitpvp server which is the same as the last hundred of them made. It could add more organization to the lobbies and fix a lot of unhappiness with the in game chat rules.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
If you had an ad channel, everyone would turn it off, defeating the purpose of ads. If you don't want to see them, there's already an option to turn off chat in minecraft.

**Comment by WallyTube** [comment]
+ Alternatively, you could leave the toggle advertisement filter just for people with ranks, and not only would that help minehut, but it would also keep a decent amount of people seeing the advertisements.

**Comment by WallyTube** [comment]
> If you don't want to see them, there's already an option to turn off chat in minecraft.
yes, but what you don't get is people still try to have conversations in that channel. Imagine you were in the general chat on the minehut discord, and you were having a nice conversation with someone else, and then 200 nons came and flooded general chat with their server advertisements. How would you feel about that?

**Comment by LukasmanMHdude** [comment]
That's different, ingame chat channels are a bit different than on discord.

**Comment by LukasmanMHdude** [comment]
And just having ranked people able to sign up for it is pretty dumb ngl.

**Comment by WallyTube** [comment]
> That's different, ingame chat channels are a bit different than on discord.

It really isnt.

> And just having ranked people able to sign up for it is pretty dumb ngl.

It's really not. If you think otherwise, explain it. Don't just hate on a suggestion just because you don't like it.

**Comment by LukasmanMHdude** [comment]
Don't dislike a suggestion because I don't like it... huh?

**Comment by PundaChen** [comment]
"Minehut has some serious chat problems in the lobbies with advertisement flood and spam." this just seems like an issue with the staff team then?

**Comment by LukasmanMHdude** [comment]
Better idea: #242

**Comment by xSpiderMC** [comment]
#242 As lukas mentioned, our staff coverage has seemed to change with the less staff members. If we had more staff online to deal with spam it could be better, or stricter anti-spam preventions.
