### ISSUE TITLE
Recommended Plugins

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#243]
### Feature request

**Platform**
Website

**Describe the feature**
When you search up plugins to help your server, there's usually 5 or 6 of them. Let's try searching up something simple: Permissions. I'm faced with multiple sub-par plugins that most people wouldn't use. Most people just install a random one if they don't know what there doing and can't receive support on how to use it, the plugin could be broken due to lack of updates, or just featureless. Recommended plugins would give people a head upon which plugins to choose.

Not 100% sure on the design of this, but maybe a gold symbol to the left of the name would work, or maybe just bolding the plugin. 

Note to the devs: If you add this, please PLEASE do this with the community. A "minehut knows whats best for us" approach will ruin this idea. 

**How the feature is useful**
New players or just someone looking to install some different plugins for there server now have a way to tell wich ones are a good fit and will have compatibility.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Double0negative** [comment]
Adding "favorite" while on the surface seems like a good idea, it will be viewed as "favoritism" or promoting certain plugins. It is not our job to decide which plugin you choose, every option we provide is equal and the user should research the plugin to decide what is the best option for them.

**Comment by LukasmanMHdude** [comment]
> Adding "favorite" while on the surface seems like a good idea, it will be viewed as "favoritism" or promoting certain plugins. It is not our job to decide which plugin you choose, every option we provide is equal and the user should research the plugin to decide what is the best option for them.

The goal of this is not to make favoritism but go by facts such as which one is the most commonly updated, or which is the most solid. As I pointed out above, people look up "permissions" and probably randomly select one. With recommended plugins, luckperms and pex would have a check so they can do reach on those 2 to find out which is better. (this is an example)
