### ISSUE TITLE
Who wants this plugin

### ISSUE THREAD

**Issue by BlakeH2208** [Minehut/Meta#244]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
 Java

**Describe the feature**
 A bungee cord plugin that essentially disables the lobby making the minehut server ban, kick, etc on a general screen

**How the feature is useful**
 it makes the server more professional

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**This would be a plugin I make on my own time and I'm wondering if anyone else wants it?**

**Comment by LukasmanMHdude** [comment]
Ima have to vote no cheif.

**Comment by LukasmanMHdude** [comment]
Minehut gets players from that anyways, which equals revenue, so I'm not about to stop that flow lol

**Comment by BlakeH2208** [comment]
This would not effect the lobby lol. It would stop connections from going to lobby once failed. /hub still works

**Comment by Blocksnmore** [comment]
Ima have to downvote too, just dont see a point in it. The system they have right now works perfectly fine

**Comment by Shlba** [comment]
didn't someone make a similar suggestion to this? and wasn't that suggestion denied?

~~Is this the new Shlba?~~

**Comment by Blocksnmore** [comment]
Yup, it was made by the same person and they closed it, not sure why they made a new issue instead of reopening

**Comment by LukasmanMHdude** [comment]
He made that similar suggestion lol.

**Comment by BlakeH2208** [comment]
This is totally different than the other thing. This is asking about if y'all want the plugin. The other was asking about if I could do it and if so what was it

**Comment by Blocksnmore** [comment]
Plugin requests are done on the forums, and tmk they dont do bungee requests, they have to be coded by mh staff

**Comment by LukasmanMHdude** [comment]
which was like bassiclly said this was dumb

**Comment by LukasmanMHdude** [comment]
If you would like to suggest plugins, head over to forum.minehut.com

**Comment by BlakeH2208** [comment]
Lol this isn't a plugin request. It's my plugin I haven't made yet

**Comment by LukasmanMHdude** [comment]
Then please don't

**Comment by Shlba** [comment]
ngl this guy is pretty determined and persistent

**Comment by BlakeH2208** [comment]
Lol thx. Imma just close this as it's clear nobody wants it

**Comment by WallyTube** [comment]
bro what is up with you? This is like the third issue you have made requesting to remove some aspect of mine hut from your server. Almost as if you are trying to take advantage of its features, but don't want its watermark. This is Minehut. The top servers only get around 50ish people. That's not enough to need a bungeecord network, or too unprofessional to ban someone.

**Comment by WallyTube** [comment]
> Lol this isn't a plugin request. It's my plugin I haven't made yet

Also, Minehut very RARELY allows members to make their own plugins and upload it to minehut, It would have to get approved for no backdoors, no game-breaking bugs, and no inconvienient code.

**Comment by Blocksnmore** [comment]
especially for a bungee plugin. Tmk the only plugin thats public on mh bungee is geyser and its been modified
they wont be using any public plugins to do that lol

**Comment by LukasmanMHdude** [comment]
To be fair, I think bungee linking for servers is a decent idea, even if its just a /server command that only works on "connected" servers. And my gets money for it, cause big servers like sythes network or genes may like something like that instead of making a "minehut bungee sever" (teleport player to {hub2} in world hubs)

**Comment by Shlba** [comment]
> To be fair, I think bungee linking for servers is a decent idea, even if its just a /server command that only works on "connected" servers. And my gets money for it, cause big servers like sythes network or genes may like something like that instead of making a "minehut bungee sever" (teleport player to {hub2} in world hubs)

the suggestion was about kicking you from minehut lol and not /server, even as /server **is** a rather useful command.

**Comment by LukasmanMHdude** [comment]
responding to chikenator lmao
![image](https://user-images.githubusercontent.com/69743171/92005349-3e54a280-ecf8-11ea-8a51-be297c419c88.png)

**Comment by WallyTube** [comment]
I would like to see a server surpass 100 players before we need a bungee cord network for servers. Minehut has yet to get a server with more than 90 people on at once

**Comment by LukasmanMHdude** [comment]
A minehut server with 90 players would be unplayable, BUT if the community wanted to organize an event, it would work :). Combined, server networks have over 150 players on their multiple servers, so this would just be a way of continuing the trend
