### ISSUE TITLE
 Question: What have the devs done within the past week?

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#247]
### Question

**Question**

Would like to know what the devs have been up to, as a progress update.

**Comment by PundaChen** [comment]
Recently they haven't actually done much since they're focusing on the constant crashes and the more recent sponsor from some random soccer club, besides plugins that's really the only noticable thing they've done lately

**Comment by Double0negative** [comment]
Please use this to track feedback and request. Questions can be answered on this discord.
