### ISSUE TITLE
 Question: Why is there a question tag

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#248]
### Question

**Question**
@Double0negative Why would you say in #247 that were not allowed to ask questions here when there is literally a button to ask a question? If you don't want questions here then don't add a button to ask a question.
![image](https://user-images.githubusercontent.com/69743171/92310733-ff2b8900-ef65-11ea-826f-a5717aa33202.png)

**Comment by Double0negative** [comment]
That button is for asking questions about Minehut Meta, not for creating low-quality tickets about "what are the devs doing." That is out-of-scope for this forum. I understand your frustration if you feel stuff you care about is not getting worked on, but I can assure you we are working hard (even over weekends!) If you are curious what some of us are working on, im sure the devs would be more than happy to talk about it on discord, but there's no reason to track that here.

**Comment by LukasmanMHdude** [comment]
The point of the question is to figure out what are the dev's doing to improve Minehut, which to my knowledge is the point on the meta discord/GitHub. If essentially asking what the devs are doing, the point of which is to see what's been going on internally and if our suggestions are being added/implemented is an "illegitimate question," then please give an example of a question that we can ask. If essentially asking if our suggestions are being implemented and how fast and whatnot is not related to minehut meta, then what standards does a question have to meet? 

Tbh you could have said something like "This question was already answered on discord" or copy-pasted the response Trent gave that would have been fine.
