### ISSUE TITLE
Bedrock Players cannot Break Blocks in Survival

### ISSUE THREAD

**Issue by Zoriot** [Minehut/Meta#249]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Bedrock 

**Describe the bug**

There is no way to break Block`s in Survival if you join in it. If you change your mode to Creative and than to Survival it works fine. Get no error in Console!

**To reproduce**
Steps to reproduce the behaviour:
1. Start your Server
2. Gamemode:Survival
3. Join via Bedrock
4. Run away bc of spawn protection
5. See that you cannot break blocks

**Expected behaviour**

I excepted that i can normaly break the block.

**Device Information**

- Minecraft client (and version): Minecraft Win 10 4641649 (newest)
- Web browser (and version): Firefox 80.0.1
- Operating system (and version): Windows 10 Pro 2004
- Minehut server name: RevoNet

**Screenshots**

https://imgur.com/a/0ut1Ruj

**Additional context**

Geyser self fixed this Problem already

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by AdxmGG** [comment]
I've heard that switching game modes can fix this, try this at least for a temporary fix.

**Comment by WallyTube** [comment]
Minehut uses an external plugin for Bedrock support. I'm 80% sure there isn't much Minehut itself can do about it since java users don't have this problem.

**Comment by LukasmanMHdude** [comment]
As they said Gyser already fixed this problem, so this I more of a request to update that

**Comment by DoctorMacc** [comment]
We just confirmed this bug on Geyser's end - we don't have much information but it's likely something to do with gamemode switching.

**Comment by drtshock** [comment]
They just made a PR that addresses this <3 https://github.com/GeyserMC/Geyser/pull/1348

We'll work on testing and merging soon. Thanks everyone for the detailed report!

**Comment by DoctorMacc** [comment]
That PR has been merged into Geyser.

**Comment by drtshock** [comment]
Then we will be testing and hopefully deploying soon on our end <3

**Comment by drtshock** [comment]
Fix was deployed last night.
