### ISSUE TITLE
Display an embed of the GitHub issue when including a GitHub issue ID in your message

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Meta#25]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord (Meta)

**Describe the feature**

Display an embed of the GitHub issue when including a GitHub issue ID in your message.
The issue ID, title, and an excerpt from the issue description should be included.
Example:
```
CoolUser: Have you seen this issue? #1234
MH Meta:
┍━━━━━━━━━━━━━┑
╿#1234 - Blah.╿
╿Excerpt...   ╿
┕━━━━━━━━━━━━━┙
```

**How the feature is useful**

It will make linking GitHub issues easier when discussing them in the Minehut Meta Discord server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
@jellz please :)
