### ISSUE TITLE
1.8 Players continually kicked in lobbies

### ISSUE THREAD

**Issue by JapaneseSquid** [Minehut/Meta#250]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 
Java
**Describe the bug**

1.8 Users in the lobby are continually reconnected to different lobbies after a period of 15-20 seconds, with an internal exception citing ViaVersion displayed in the chat
**To reproduce**
Steps to reproduce the behaviour:
1. Connect to the server using any 1.8.9 client (Vanilla, Lunar, BLC tested)
2. Stay on the lobby, being idle or active does not matter although players have reported that interacting with some blocks (pressure plates, boats) caused a kick- cannot reproduce that aspect, however other players in the lobby interacting with blocks/entities could be related
3. Get kicked, and immediately reconnected to a lobby (could be same or different lobby)
4. Internal exception is displayed in chat

**Expected behaviour**

1.8.9 Users not being continually tossed in the lobby leading to dozens of reconnects
**Device Information**

- Minecraft client (and version): Vanilla, Lunar Client, Badlion Client 1.8.9
- Web browser (and version): N/A
- Operating system (and version): Windows 10
- Minehut server name: N/A

**Screenshots**

https://i.imgur.com/Zc6RwRi.png
**Additional context**

Issue has persisted since August 
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
This has already been fixed with the via plugins, the lobbies are yet to update them (for some reason) so until someone updates all the via plugins on the lobby this will happen

**Comment by LukasmanMHdude** [comment]
play 1.16 🤔

**Comment by WallyTube** [comment]
> play 1.16 🤔

yeah this is a very lousy solution for a big problem. Probably every pvp server relies on older version support to work.

**Comment by Double0negative** [comment]
Can anyone confirm that this issue has been fixed after we updated?
