### ISSUE TITLE
Disallow political servers

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#251]
### Feature request

**Platform**
both?

**Describe the feature**
Don't allow people to make a server like this:
![image](https://user-images.githubusercontent.com/69743171/92525179-399c5c80-f1d8-11ea-99ca-3dd8c57c8a0d.png)

**How the feature is useful**
Less political chat, and helps the community

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
I don't see an issue with "politically-focused" servers as long as they're not promoting harmful or hateful content. For example, the server in the screenshot is promoting hate speech, which shouldn't be allowed.

**Comment by LukasmanMHdude** [comment]
> I don't see an issue with "politically-focused" servers as long as they're not promoting harmful or hateful content. For example, the server in the screenshot is promoting hate speech, which shouldn't be allowed.

Yea, that defo makes sense.

**Comment by Double0negative** [comment]
We don't have any rules against political servers. However as iGalaxy pointed out above, the server in the example could be violating other TOS. Please report it so our staff can review it and act accordingly. Thanks!

**Comment by LukasmanMHdude** [comment]
Ok, thanks. Any idea on where I can report this?

**Comment by jellz** [comment]
You can report a server [here](https://forums.minehut.com/topic/21720-information/)

**Comment by LukasmanMHdude** [comment]
Thanks!
