### ISSUE TITLE
!plugin command

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#252]
There should be a discord command that gets info on a plugin via the api

**Comment by Blocksnmore** [comment]
:clap: Follow :clap: the :clap: template

**Comment by LukasmanMHdude** [comment]
Hey, do you mine creating a new suggestion and copy pasting the template here?

**Comment by MrScopes** [comment]
> Hey, do you mine creating a new suggestion and copy pasting the template here?

why

**Comment by LukasmanMHdude** [comment]
Your suggestion is more likley to get implemented that way, and it helps is know more about it

**Comment by Double0negative** [comment]
Its important that the template is followed so we have all the info we need, and its presented in an easy-to-read way. I will close this but feel free to open a new ticket that followed the template

**Comment by MrScopes** [comment]
> Its important that the template is followed so we have all the info we need, and its presented in an easy-to-read way. I will close this but feel free to open a new ticket that followed the template

you have all the info you need based on the issue

**Comment by LukasmanMHdude** [comment]
### Feature request


**Platform**
discord


**Describe the feature**
add a !plugin command that gets info on a plugin via the api


**How the feature is useful**
Helps people learn more info on the plugin


---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
@Double0negative if you wanna go ahead a reopen this and delete all the stuff above my comment, that would be nice

**Comment by Sniped** [comment]
why not just open a new issue with that template?

**Comment by LukasmanMHdude** [comment]
> why not just open a new issue with that template?
> 
> edit: seems like scopes already did

/shrug
