### ISSUE TITLE
Fix/remake the Server Plans

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#253]
**Describe the feature**
-
Minehuts top plan costs 45%, and the 6bg one costs 18 dollars*. These prices are WAY too high. I can get a **$19** plan from other server hosts with version switching, live console, 24/7 hosting, 12 gigs of ram, backups, pterodactyl panel, and more for the price of a Minehut 6gb plan. This plan also comes with a good CPU that doesn't host **50** on one machine. (acc to Trent there’s overhead, but from what I see ingame that's not the case: https://discordapp.com/channels/546414872196415501/546422616609783818/751499629081919578) (Note that I found a 25-gigabyte plan a month that gives discounts for paying monthly and whatnot, but it didn't have all the features I was looking for in a good Minecraft server, but its performance/features were still better than Minehut's anyways)

**Making Monies**
Now Minehut, like any company, cares about making money and people may ask “how does lowering the price of server plans get Minehut more money?" Well, many servers that are already established in the community try to branch out to other server hosts because of what I said above. Now, the discussion can go both ways on how successful this is, BUT the fact that many big servers actively attempt to do it isn't great for business. Another big way to lose potential customers if they aren't already part of the Minehut server making community, the majority of users that have played Minehut a bit and know that they have server plans will go out and check other hosts first before spending money on a server and go there due to the lack of features and whatnot. (also https://discordapp.com/channels/546414872196415501/546422616609783818/750149338822475817)

**Hanging by a Thread**
Now, Minehut's current marketing strategy, while not great, isn't the worst either. Because they're a “**free server host**” (lol try and make an SMP on the free plan) they can hook a lot of people on that ideology. Most people then realize they need to buy a server plan to even have a decent experience (get more plugins, be able to build large farms without the server TPS dying, and so on), but as there's no way to download server files easily and world downloading is a pain in the butt
(until the new system comes out, which looking at Minehuts' track record will take another 5 months or so).

There is one more thing that Minehut has that almost no other server host has, **a community**. Whether it be in the skript channel at midnight, the meta discord, or the amazing lobby discussions that have "<!> minehut.com <!> free server host <!>" between every line, the community is here for us. While a lot of people may hate those ads as well as the #servers channel on discord, the constant stream of players from ads and the lobby board and the "join random server” button and the discord is one of the **huge** reasons why servers are on Minehut when they become big.

But back to the “roasting” now. Those two reasons (and maybe one or two more that | can't think of} are the main reasons why
people even use Minehut. The fact that Minehuts' “better than other hosts" context can be summed up to **lobby ads and a good hook to bring in new players**, is kinda sad ngl. 

I know that this is gonna be controversial, so please hit the 👍  if you agree with the idea of changing the perks/prices of server plans, and hit the ❤️ if you like what I said above.

**New Prices**
-
The current prices aren't that great, and with the way minehut makes you pay for the credits, they cost even more than advertised. The server space is how much space the server gets per computer out of 100. I think that this could be called smth else if implemented, but would be a welcomed change. You'll also notice that the prices now seem more “random.” While I do like the 24, 48, and so on, I tried to give people more bang for there buck as the plans go up. (besides weekly and daily) | also considered adding plugin limits but ehhhhh.

- Minehut Daily:
> 49 credits a day (49 daily)
> Gigs of ram: 2
> Server space: 3 (to encourage weekly)
> Max players: 20

- Minehut Weekly:
> 245 credits a week (35 daily)
> Gigs of ram: 2
> Server space: 5 
> Max players: 20

- Minehut 20:
> 690 credits a month (23 daily) (big jump to encourage this over my weekly. Note that even though the plan costs less, people with this are more likely to stop 
> Gigs of ram: 2
> Server space: 5
> Max players: 20

- Minehut 35:
> 1,470 credits a month (49 daily)
> Gigs of ram: 4
> Server space: 7
> Max players: 35

- Minehut 75:
> 2,940 credits a month (98 daily)
> Gigs of ram: 6
> Server space: 10
> Max players: 75

- Minehut 75 Plus/enhanced/server/idk: **
> credits a day (124 daily) (new flagship plan)
> Gigs of ram: 8
> Server space: 20
> Max players: 76
> World backups***

- Minehut Unlimited Plus/enhanced/server/idk: **
> 5,940 credits a month (198 daily)
> Gigs of ram: 12
> Server space: 36
> Max players: Infinite (within what Minecraft can handle) default is set to 500. (no reason to cap it, never seen 500 players on a server in general with ultra good hardware)
> World backups***

Please don't judge this based on these prices, these are ideas and I'd love for people to modify them/come up with new ideas in the comments. I'll keep an eye on this post and update prices to what the community believes in the comments.

**How this feature is useful**
Helps bring more players to minehut and fixes a lot of pricing issues. I included a lot of this info in the main body "paragraphs." 

*estimated price
**need to choose/come up with a name for this
***Maybe a 2-day backup world thing (it would take a backup daily, and delete the older ones, so there would be 2 saves of all the worlds that you could revert to. This is temp until minehut actually adds backups. Would like to hear ideas in the comments on this :eyes:

---
I know that this is gonna be controversial, so please hit the 👍  if you agree with the idea of changing the perks/prices of server plans, and hit the ❤️ if you like what I said above.

**Comment by ItzOP** [comment]
I think prices are good rn, you can vote and get mh20 for free.
And the rest of the plans are reasonably priced. Especially with publicity you get from Minehut.

**Comment by WallyTube** [comment]
What op said^^ The only problem with the servers right now is the fact it is kinda hard to get a new server started. Featured servers should help with this, but once again, you could get a $17 server from other people but you would need an audience to play it.

**Comment by LukasmanMHdude** [comment]
True, but they gotta give bigger servers more. They also are doing a pricing revision right now so I thought i'd give my 2 cents on that.

**Comment by Double0negative** [comment]
Thanks for the detailed post! We are currently in the process of reviewing server plans, including prices and provided features. Unfortunately I can't provide any more details than that at this time.
