### ISSUE TITLE
!plugin command

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#254]
**Platform**
 discord

 **Describe the feature**
 add a !plugin command that gets info on a plugin via the api
 
 **How the feature is useful**
 Helps people learn more info on the plugin

**Comment by WallyTube** [comment]
And they still somehow failed to format it correctly

**Comment by MrScopes** [comment]
> And they still somehow failed to format it correctly

I copied what someone pasted in my replies, why are you upset?

**Comment by LukasmanMHdude** [comment]
wally you don't need the checklist if you've done it once (from what I've seen)

**Comment by jellz** [comment]
> wally you don't need the checklist if you've done it once (from what I've seen)
> 
> Edit: its his first post, should probs include it

You are expected to include the checklist in every issue

**Comment by LukasmanMHdude** [comment]
uh oh

**Comment by jellz** [comment]
This feature was actually already on my to-do list, it was one of the first things I thought of when I first took over the bot. Would be nice to see it implemented.

**Comment by MiginsMC** [comment]
I'm not super sure what information you want in it, apart from the description and link that is already on the plugin page, I'm not sure why they would want or need to look for information via the discord.

**Comment by mygizli04** [comment]
I think it could definetly be done, i did something like this for my own bot:
![image](https://user-images.githubusercontent.com/42012824/98049380-ff061780-1e48-11eb-81e1-01366a5459f2.png)
Obviously the minehut bot wouldn't be able to show installed/plugin id/etc. but i think that's definetly something someone should work on. ( My javascript isn't good enough to implement a searching algorithm + i couldn't find a library so my bot only works with exact names )

**Comment by jellz** [comment]
This issue should be closed as the plugin command has already been added
