### ISSUE TITLE
New Management

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#255]
### Feature request

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**

 Universal

**Describe the feature**

I strongly believe Minehut should find new management. In recent months a lot of really good staff members have resigned. Most of them have claimed it was due to management issues within Minehut. After the wave of resignations concluded for a brief time, another individual was kicked off the team unfairly more recently. It is evident and clear that the current management is not what is best for Minehut. This needs to be said. The staff team got severely depleted under the current management and many people resigned. Quite a few of these staff members have been with Minehut for a very long time and have done a great amount of good work for the Minehut network. For people like this to be unfairly demoted or forced to resign because of error in management, is unjust and requires immediate correction.

**How the feature is useful**

Minehut needs new management gravely. This will improve everyone's experience.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Thanks for the suggestion. If you have anything specific you want to report about the team, feel free to do so. Otherwise, we have full confidence in our management team to lead us in the future.
