### ISSUE TITLE
Forums rank stuff

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#257]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Forums

**Describe the feature**
Get rid of the following ranks/use them properly:
Logged in or Member, both are technically the same thing
Media team, doesn't get used, guessing this is for the staff in the media team?
Recruitment team, same reason as above
Reports and appeals team, same reason as above
Support or support team, only one is really needed but I'm guessing support team should be for the staff within said team?
![image](https://user-images.githubusercontent.com/42002575/92691884-9ff1be00-f343-11ea-9e04-92ea9f2bae2c.png)

**How the feature is useful**
Just makes the rank list look neat

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
> Media team, doesn't get used, guessing this is for the staff in the media team?
> Recruitment team, same reason as above
> Reports and appeals team, same reason as above
> Support or support team, only one is really needed but I'm guessing support team should be for the staff within said team?

Yeah, Media, Recruitment and Reports & Appeals are for staff permissions to view those submissions - Support is for normal community Support members, and Support Team is for Senior Support members (who have access to Support apps).

**Comment by theminecoder** [comment]
Unfortunately the forums software we use doesn't give us a ton of room when handling permission so we have to add multiple roles to handle it. We are unable to hide these roles in filter lists/other places due to limitations in the software.
