### ISSUE TITLE
Change MC Server List banner for Minehut

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#26]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 Minecraft Server List Website (Voting website)

**Describe the bug**

The banner for Minehut on the voting website claims **Free 24/7** which is incorrect as the 24/7 plan is $40+/mo

**To reproduce**
Steps to reproduce the behaviour:
1. Go to https://minecraftservers.org/vote/443456

**Expected behaviour**

The banner should say Free Minecraft Servers or something other than Free 24/7.

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): Chrome Latest
- Operating system (and version): N/A
- Minehut server name: N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/44182379/90324830-aad25200-df41-11ea-9b92-52f318ac38e8.png)

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by iGalaxyYT** [comment]
Was able to reproduce this bug using Google Chrome 84 and Windows 10 Pro 2004.

**Comment by recalibrated** [comment]
I don't think this is a bug.

**Comment by Blocksnmore** [comment]
Technically the ad isnt wrong since the servers are free for 24/7 (making them) i think this is just being interpreted the wrong way

**Comment by WallyTube** [comment]
I don't think Minehut shuts free servers down anymore since they migrated hosts... I could be wrong though.

**Comment by Blocksnmore** [comment]
Why would minehut spend resources keeping your server online? Lol, they shut down the server and when you /join etc it un compresses the files and starts the server

**Comment by drtshock** [comment]
This isn't a bug. It's also not false, you can have a free 24/7 server if you're online. We don't limit uptime.
