### ISSUE TITLE
ReImplement Minehut Navbar Promotion

### ISSUE THREAD

**Issue by 3Q6Dev** [Minehut/Meta#263]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform** Website

**Describe the feature** On the old panel, Minehut used to have a promotion on the navbar, would say something like "Go subscribe to our Youtube channel" or "Vote for 25 credits!" (Minehut actually still checks the navbar promotion, but doesn't use if, you can check if you check your browser network), It would be good for promoting if it was added back

**How the feature is useful**It benefits Minehut, and some users may not know that... Minehut has a TikTok for example, if minehut promoted it, some users may find it interesting and continue watching,

The API for the navbar still exists at https://api.minehut.com/website/navbar/promotion, but currently returns blank for the text and link value.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
This was added today. Feel free to close (:
