### ISSUE TITLE
Soccercity bugs

### ISSUE THREAD

**Issue by Baron-Sengir** [Minehut/Meta#264]
### Bug report

**Checklist**
- [Y] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [Y] I am NOT reporting a security vulnerability
- [Y] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [Y] This issue does not contain any sensitive information

**Platform**
 In-game, Java

**Describe the bug**
 There is a second lobby that you sometimes join that doesn't get new people often.  Randomly if you queue for the 2v2 ranked scheduled match, you'll join another queue that only sometimes gets people.  Quitting and queueing again gets you the same lobby.  You basically have to party with a non-glitched person and queue again to get out of it.  This is really annoying because it's hard enough to get a game already without a second and glitched lobby flitering away players.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'soccercity'
2. Click on '2v2 ranked/scheduled match'
3. Get someone else to join queue as well
4. If you're not in the same lobby, one of you is glitched.  This won't always happen, but if you keep playing games it will happen.

**Expected behaviour**
  When two people queue, they should get in a lobby together to fill up and start games as quick as possible.  Since there aren't a lot of people playing this, it's hard to get a game already.

**Device Information**

- Minecraft client (and version): 1.16.2 java
- Operating system (and version): Windows 10 (don't see how it's relevant).
- Minehut server name: soccercity

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**
I've done it several times and have friends who have as well.  Skittleyy and Gill784, specifically.

**Comment by LukasmanMHdude** [comment]
Please close this issue and add all bugs to #258

**Comment by LukasmanMHdude** [comment]
(and to `[x]`)

**Comment by LukasmanMHdude** [comment]
Please make sure to close this. Thanks!
