### ISSUE TITLE
Ability to change default Unknown Command message

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#266]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website / In-game

**Describe the feature**

I think it would be neat if we could change the default *Unknown Command.* message. This is a setting located in paper.yml. Until we're able to edit that file (if we ever will be) I think it would be cool to have a setting for it in Server Settings where player slots and others are located.

**How the feature is useful**

This allows people to customize a common message on their server, giving them more freedom over their server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Double0negative** [comment]
paper.yml editing should be available very soon
