### ISSUE TITLE
Non global punishments.

### ISSUE THREAD

**Issue by cxtch** [Minehut/Meta#267]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Ingame: Java & bedrock edition.

**Describe the feature**
Limit the scope of punishments made by staff of MineHut to MineHut lobbies. This is already done in cases of mutes. But it would also be useful in situations where a player might be banned for an inappropriate username. If the reason that there's a rule against inappropriate usernames is to keep MineHut lobbies PG, then they shouldn't also be banned from server's hosted by MineHut as well, as perhaps those servers have different sets of rules. 

Doing this would really promote the idea that when you host a server on MineHut, it's an autonomous server that can handle punishments on their own accord.

**How the feature is useful**
If you spend enough time online, your online alias can become almost a second name (at least for me it is). Not requiring users to change something about their profile (whether it be a username or a skin) to join server X because it breaks a rule on server Y saves users the hassle of having to change their username if they only play a few servers on MineHut and talked once or twice in the lobby chat. Thank you for taking the time to read this.

**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by RichieNy** [comment]
This is not going to happen. If a player was banned for DDoS Threats or Death Threats, why only ban them from the lobbies? Do you want those players to continue to make threats and actions? Doesn't seem like the best idea.

**Comment by Shlba** [comment]
the base appeal of minehut is mainly the playerservers. It would not be a punishment if you were only blocked from accessing the lobbies. Global punishments remain the best, as they can effectively punish a user, possibly making them regret their actions.

**Comment by Blocksnmore** [comment]
I feel the punishment system should vary for punishments ie ddos threats are network wide, while cheating is only for the lobbies

**Comment by ItzOP** [comment]
> This is not going to happen. If a player was banned for DDoS Threats or Death Threats, why only ban them from the lobbies? Do you want those players to continue to make threats and actions? Doesn't seem like the best idea.

Yeah, I agree with Richie, there are punishments that relate to player servers like griefing and banning them in the lobby would be an ineffective punishment.

**Comment by Sniped** [comment]
Yeah this will likely never happen, a global punishment needs to be set in place for things such as a blacklist on Minehut. When you grief on a Minehut server, do you believe that punishing the user by banning them from only the lobby is helpful? This is just one instance of how this could introduce negative effects to Minehut moderation. There are many more, some of which have been stated in this issue as well.

**Comment by Sniped** [comment]
Closing this as **wontfix**
