### ISSUE TITLE
Nicknames replace inappropriate usernames in the lobby.

### ISSUE THREAD

**Issue by cxtch** [Minehut/Meta#268]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Both, ingame.
**Describe the feature**
If someone has a username that is deemed as inappropriate, or not PG, staff can give them a nickname that is non-offensive in order to avoid needing to ban a player from the network. These usernames can be marked with a tilda ~ or any other non alpha-numeric character to prevent username overlap. If the player so chooses, they can submit an appeal and say they have changed their username in order to be de-nicked in the lobbies.

**How the feature is useful**
Prevents users from having to appeal a ban and lets players with inappropriate usernames play and chat in lobbies without MineHut needing to worry about not being PG.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Shlba** [comment]
Changing the nickname doesn't actually solve the problem with users having a inappropriate nickname. Also this raises a few concerns:

-How will users /msg a nicked player? Will they use their real ign?(Hard to find out due to the nickname)
-Would this even punish users for using an inappropriate username?

**Comment by cxtch** [comment]
> How will users /msg a nicked player?
Often times, if you /msg a nicked player in essentials, it redirects to the player that has that nickname. So that would be fine.
>would this even punish users for using an inappropriate username?
If they don't wanna be referred to as "user1937491" or "DUNCE#182" or "nickname#13829" then yes. But it's also their own account, and other players' servers shouldn't be the responsibility of Staff when it comes to a username. Doesn't matter if they feel punished or not.

**Comment by MiginsMC** [comment]
I disagree with this suggestion. I think having the change the tab, chat, /msg, friends list, friends add, /find, punish commands, etc would just be unnecessary effort. And would you change it on player servers? If so that would be a lot of effort implementing that.

**Comment by ahoulton** [comment]
I also have to disagree but for a different reason, what the point of having an inappropriate username in the first place? See no point of why this should be added, they should learn that having that name is not allowed and appeal like everyone else.

**Comment by drtshock** [comment]
I appreciate the suggestion but I don't think we'll be going out of our way for people that have inappropriate names.
