### ISSUE TITLE
Permission nodes for minehut commands like /worlds

### ISSUE THREAD

**Issue by quick007** [Minehut/Meta#269]
### Feature request

**Platform**
ingame

**Describe the feature**
Add permission nodes for the minehut commands, so that staff can have access to it without opping them.

**How the feature is useful**
Helps owners

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
This is actually a great suggestion, not sure why they don't already!

**Comment by BennyDoesStuff** [comment]
This is no longer an issue as the player servers plugin was removed.
