### ISSUE TITLE
minehut bot blank space bypass patch (JAVASCRIPT)

### ISSUE THREAD

**Issue by moom0o** [Minehut/Meta#270]
unban me and i will give u the fix in javascript

**Comment by MiginsMC** [comment]
Yo, follow the format, my dude, it's there for a reason.

**Comment by RichieNy** [comment]
Not following format, appeal on the forums. 
Forums.minehut.com

**Comment by moom0o** [comment]
appealing doesnt work 🤣 it will be denied

**Comment by Shlba** [comment]
Moo, you did that to yourself, just remember that lol

**Comment by moom0o** [comment]
did what

**Comment by moom0o** [comment]
all i did was swear and they banned me because it was a "minor punishment" and when i appealed before that they said if i do anything minor they would perm ban me again. I didnt even say the full word i censored it with a *

**Comment by moom0o** [comment]
https://read-my-man.ga/3vw4YQQJzL.png
