### ISSUE TITLE
Feature Request:Install Dates

### ISSUE THREAD

**Issue by DaRealMinecraftexpert** [Minehut/Meta#271]
Platform: Website
Feature: On the Plugin section, alongside the plugin, I can see what Date a Plugin was installed the first time to my server.
Usefulness: It can help with finding and Reporting issues and Bugs with Plugins

**Comment by DaRealMinecraftexpert** [comment]
And I'm new to writing issues like this, this is the first time I ever used Github to write anything

**Comment by PundaChen** [comment]
If you click new issue and then click feature request I'm pretty sure the format should already be there, follow that fully instead of making it shorter ^^

**Comment by RichieNy** [comment]
LINK To Suggest/Report: https://github.com/Minehut/Meta/issues/new/choose

**Comment by DaRealMinecraftexpert** [comment]
Ok, let me try again.
