### ISSUE TITLE
Use normal forum topics instead of forms for Staff Applications

### ISSUE THREAD

**Issue by jellz** [Minehut/Meta#273]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website (Forum)

**Describe the feature**
For Staff Applications (and Support Applications), go back to using standard forum topics instead of the form system.

**How the feature is useful**
Allows for personalisation and formatting in applications. With the current form system, the form is just plain text boxes. With normal forum topics, you can make your application look like your own. You can make it memorable and be creative with it. You can also use basic formatting (bold, italics, underline) which are often helpful when constructing an application, which you cannot use on the current form system.

The current form system is severely limiting what applicants can do in their application, by removing the ability to use basic text formatting, colours, pictures/art, links, headers, and lists; all of which can be useful in an application, either to improve readability or to enhance the application's aesthetic.

The form system is also awkward because of the resizable text boxes, the default sizes and resizing isn't ideal for the answer lengths in some cases.

The _only_ "pro" of using forms is to enforce the application format, but applicants should be able to add to their application and deviate from the standard application format. To quote Hypixel's Application Guide, "_you are free to add your own questions and spin on it if you wish. It is your application and you are free to be as creative with it as you like._" And it's not difficult to simply deny the applications that don't follow the format at all.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
Staff applications are no longer a thing.
