### ISSUE TITLE
Minehut Credit Donation Feature

### ISSUE THREAD

**Issue by LinkBlock123** [Minehut/Meta#274]
So, sorry that I don't understand the template. But let me keep it simple. We really need donation / gifting credit feature where using their Minecraft username, they can give their credit to other users. I think this will function for Buycraft too. Please add this feature I REALLY want it please. 

Minecraft Username - LinkBlock

**Comment by Sniped** [comment]
Hey there!

In order to submit issues on Meta, you must follow the [template](https://github.com/Minehut/Meta/issues/new/choose) that is provided to you. This helps us keep a general format in place for suggestions and to keep these issues more organized.

**Comment by Shlba** [comment]
@LinkBlock123 I'll give an actual reason.

    Minehut will never support credit transfers, this is because you could easily transfer credits gained from voting from one account to another, making voting practically too over powered. In addition, suggestions similar to this one have all been discussed in the past, all ending with similar results, with a "no" usually.
