### ISSUE TITLE
Hub bugs

### ISSUE THREAD

**Issue by eksynn** [Minehut/Meta#276]
### Bug report

**Checklist**
- [ x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x ] I am NOT reporting a security vulnerability
- [ x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x ] This issue does not contain any sensitive information

**Platform**

java

**Describe the bug**

most doors in the hub are always at weird positions when i log in.
it's also really easy to "reset" them. (or to manually break then)

**To reproduce**
Steps to reproduce the behaviour:
1. go to any house or building within the hub that has doors for chairs
2. look at the chairs
3. to reset (or break) them, double-click the door very quickly. it should snap back to its broken (or unbroken) position, and then stay how you want it

**Expected behaviour**

i expected players to be entirely unable to interact with these doors and trapdoors, but instead, it's very easy to do so, whether it's to grief, or to fix.

**Device Information**

- Minecraft client (and version): 1.16.3
- Web browser (and version): not applicable
- Operating system (and version): winX (don't know the version. 1903 or something)
- Minehut server name: the main hub

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by eksynn** [comment]
not really a security issue, but doors that are meant to keep players from accessing the houses are also able to be opened like this. if this isn't an issue, then nevermind lol

**Comment by Double0negative** [comment]
This is actually related to another separate issue I'm working on right now, expect this to be fixed soon

**Comment by Double0negative** [comment]
Change is live. Fixes staff not being able to build properly, also fixes people opening stuff. However this prevents some interaction with the map (Easter eggs and stuff) so I might re-add some of this in a non-bugged fashion. Let me know if you experience any issues with this.
