### ISSUE TITLE
Better anti-bot

### ISSUE THREAD

**Issue by ReportCardsMC** [Minehut/Meta#277]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord

**Describe the feature**

Within the Minehut bot, create a better anti-bot. Recently MH has had a lot of DM advertisement bots, to better circumvent this, you can track the amount of joins in recent times, check if they have similar account creation dates, and automatically ban all of them, give them a link of where to appeal if needed.

**How the feature is useful**

This is helpful because bots are being abused to message a ton of people on the Minehut Discord their server, this could be harmful as it can push players away from our Discord, or strongly annoy our community.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
Addressed in PR [59](https://github.com/Minehut/MinehutBOT/pull/59) of the bot repo.

**Comment by Double0negative** [comment]
PR: https://github.com/Minehut/MinehutBOT/pull/59
