### ISSUE TITLE
Grammatical error on spigot.yml/paper.yml warning

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Meta#280]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website (Dev)

**Describe the bug**

There is a grammatical error in the notice popup (warning symbol) when editing spigot.yml, paper.yml, etc.

**To reproduce**
Steps to reproduce the behaviour:
1. Edit spigot.yml or paper.yml on the dev site (https://dev.minehut.com)
2. Click the warning symbol
3. Observe grammatical error

**Expected behaviour**

There should not be a grammatical error.
"spigot.yml will overwrites these settings" -> "spigot.yml will overwrite these settings"

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): Chrome 85.0.4183.121
- Operating system (and version): Windows 10 Pro ver. 2004 (build 19041.508)
- Minehut server name: N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/22878174/93843716-a93a2f00-fc4f-11ea-8418-0c3b9f2cc35b.png)

**Additional context**

N/A

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by killergotrekt** [comment]
Can reproduce

**Comment by ZeroParticle** [comment]
Appreciate the feedback, but I think it's best if we only create issues for released features or desired features here. While the dev site is accessible, features there are generally incomplete so it's not worthwhile to make issues about problems on dev. We will generally resolve them on our own before release.
