### ISSUE TITLE
SoccerCity: Leaderboards Out of Action

### ISSUE THREAD

**Issue by skittleyy** [Minehut/Meta#281]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Java Minecraft, In-Game.

**Describe the bug**
Soccer City Leaderboards have ceased to update. While Ranked Modes seem to update their temporary leaderboards, the fixed permanent stats have not updated in over a week.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'Soccer City'
2. Play a Game. (Friendly, or Ranked)
3. Come back to Lobby.
4. See error (no update on the Leaderboard)

**Expected behaviour**
I expected to see my stats increase, in terms of wins and goals. 

**Device Information**
- Minecraft client (and version): Minecraft Java: 1.16.2
- Web Browser: Chrome
- Operating System: Windows 10
- Minehut Server Name: Soccer City

**Additional context**
I'm currently second on the wins leaderboard overall but there is no update after I win a game and I do not get closer to first place. What I assume may be the bug is that the leaderboard has frozen after it was online for a week, which is the time period that the leaderboard uses to log scores. It is now a new week (in fact if im not mistaken we may be close to Week 3 of the Event) but no scores have updated since 13th/14th September.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Double0negative** [comment]
An update went out earlier this week that updated the scoreboards for this week. Thanks for reporting, this should be resolved at this time.
