### ISSUE TITLE
Cannot check box when deleting files

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#282]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website

**Describe the bug**

When I try to delete files by selecting them, I cannot click to box to select/de-select them.

**To reproduce**
Steps to reproduce the behaviour:
1. Press the 'delete files' button
2. Click on the checkbox
3. See error

**Expected behaviour**

I would be able to select and de-select the file by clicking the box.

**Device Information**

- Web browser (and version): Chrome
- Operating system (and version): MacOS

**Screenshots**

https://streamable.com/2d822v

**Additional context**

It works when I click the name, but not the box.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by AdxmGG** [comment]
Can reproduce. Windows 10, Chrome

**Comment by PundaChen** [comment]
Can confirm, chrome + windows

**Comment by RealResistance** [comment]
Can reproduce, Windows 10 + chrome
