### ISSUE TITLE
Buy Credits For Different Users / MOTD Extension / Server Icon Change / Server Domain Change 

### ISSUE THREAD

**Issue by LinkBlock123** [Minehut/Meta#283]
So..for last few days, I have been searching for server hosting sites, but they all had issues. But for Minehut, there are some, which can be updated and make the hosting much much better.

1. Buying Credits For A DIfferent Users
So for example, when you are buying a credit, they ask foe Mojang Username, and you can type someone else to donate credits. This can be used in donations, easier process and more. I think this feature will be used a lot!

2. Server MOTD Extension
For now, the MOTD can be maximium 64 characters. But I think we can make if longer using a server plan:
MH 20 -> 80 Characters Max
MH 35 -> 100 Characters Max
MH 75 -> 120 Characters Max
MH Unlimited -> 150 Characters Max

Or buy characters with credits -> 100 credits per 15 character extension / VIP rank gets 20 characters extra or so!

3. Server Icon Change
I think other than just a Minehut logo, if we can change the sever icon to whatever we want, it would be great. Or maybe only for VIP rank or higher / MH 20 or higher. Please make this, this shows the unique of the server!!

4. Server Domain Change
This one might not be super important, but for people like perfectionist or just want to make the domain better or cooler, they might want to erase minehut.gg ; instead maybe like .co or .com or .net might be better. And this isn't about saying that "minehut.gg" is weird and bad but I just want to say it would be better! 

**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
Make multiple issues for this please, thanks (makes it easier to vote for specific things)

**Comment by Shlba** [comment]
> Buying Credits For A DIfferent Users
So for example, when you are buying a credit, they ask foe Mojang Username, and you can type someone else to donate credits. This can be used in donations, easier process and more. I think this feature will be used a lot!

- Allows for people to purchase credits then refund them without punishment. 

> Server MOTD Extension
For now, the MOTD can be maximium 64 characters. But I think we can make if longer using a server plan:
MH 20 -> 80 Characters Max
MH 35 -> 100 Characters Max
MH 75 -> 120 Characters Max
MH Unlimited -> 150 Characters Max

- I think that this is unneeded, as a **MOTD** should really only be simple. Having 64 characters is already way more than enough for most servers.

> Server Icon Change
I think other than just a Minehut logo, if we can change the sever icon to whatever we want, it would be great. Or maybe only for VIP rank or higher / MH 20 or higher. Please make this, this shows the unique of the server!!

- Can't wait for people to start using **NSFW** images in their server icons. 

> Server Domain Change
This one might not be super important, but for people like perfectionist or just want to make the domain better or cooler, they might want to erase minehut.gg ; instead maybe like .co or .com or .net might be better. And this isn't about saying that "minehut.gg" is weird and bad but I just want to say it would be better!

- You can **ALREADY** do this...  [Video](youtube.com/watch?v=seFJb-Uhz2c)

**Comment by Shlba** [comment]
* Video link:

youtube.com/watch?v=seFJb-Uhz2c

**Comment by DaRealMinecraftexpert** [comment]
I have had so many Incidents when I ran out of MOTD space for what I wanna Write

**Comment by drtshock** [comment]
Hey can you please make one ticket per feature request?
