### ISSUE TITLE
.json files get rejected when the first character in the name is either ., #, or %

### ISSUE THREAD

**Issue by RealResistance** [Minehut/Meta#284]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 Website

**Describe the bug**
 When attempting to upload a .json file with the characters . (dot), # (hashtag), or % (percent) at the beginning of the file name the file gets automatically rejected and is not accepted.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to minehut -> dashboard -> edit server -> file manager
2. Click on upload file
3. Scroll down through the file list after a few seconds

**Expected behaviour**
 File gets accepted and is added to the file list a few seconds later

**Device Information**

- Minecraft client (and version): Java edition (1.16.3)
- Web browser (and version): Google Chrome (84)
- Operating system (and version): 64-bit operating system, x64 based processor, windows 10 home, version 1903
- Minehut server name: StuffTesti.minehut.gg

**Screenshots**
 https://gyazo.com/8264acd4e5e009a8aeef8306d233861c

**Additional context**
 Prevents some datapack files from being uploaded sometimes causing the datapack to not function as intended.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by kimheffy** [comment]
Is there a particular reason why the filenames starts with ., #, % from the first place?

**Comment by PundaChen** [comment]
#epicgamerfile.json sounds like a pretty cool name for a file

**Comment by kimheffy** [comment]
it do be sounding awesome... but how about just epicgamerfile.json? lol

**Comment by RealResistance** [comment]
> Is there a particular reason why the filenames starts with ., #, % from the first place?

For some reason some datapack creators use those characters at the beginning, possibly because they're on a mac whilst developing their datapack.

**Comment by TeamMH** [comment]
Trying to create a file starting with "." will result in a file being created else where, that isn't in the current directory (Tried this myself, was unable to find where the file was being created.)
As for % and #, that's definitely an issue. 

![2020-10-05-113346_1920x1080_scrot](https://user-images.githubusercontent.com/71158208/95106834-a84cd700-06fe-11eb-9754-73944031a001.png)

**Comment by youngmasterseth** [comment]
I mean why would you have a file starting with "." though lol seems disorganized...

**Comment by Double0negative** [comment]
files that start with . is actually a pretty common thing, especially in linux environments. It signifies the file should be hidden

**Comment by kimheffy** [comment]
> Trying to create a file starting with "." will result in a file being created else where, that isn't in the current directory (Tried this myself, was unable to find where the file was being created.)
> As for % and #, that's definitely an issue.
> 
> ![2020-10-05-113346_1920x1080_scrot](https://user-images.githubusercontent.com/71158208/95106834-a84cd700-06fe-11eb-9754-73944031a001.png)
> 
> (Nothing returning from "ls" means there are no files in the directory)

If you do `ls -la` in your terminal, you should be able to see the hidden file.

**Comment by jellz** [comment]
(Pssst, for a more succinct output, omit the `l` and just use `ls -a`)

**Comment by TeamMH** [comment]
> files that start with . is actually a pretty common thing, especially in linux environments. It signifies the file should be hidden

oops, i actually forgot about that :sweat_smile:

**Comment by kimheffy** [comment]
Closing this issue because changes are up :)
