### ISSUE TITLE
Denying "illegal" characters in worlds

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#285]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website and ingame

**Describe the feature**
Stop allowing users to upload worlds when its name has a space or any illegal characters in it, you could instead replace spaces with dashes.

**How the feature is useful**
Spaces and illegal characters break worlds making users unable to teleport to it or download it, it's a huge issue that still hasn't been fixed and could help so many people.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesTheStuff** [comment]
yea totally agree, either this or fix not being able to teleport to worlds with spaces or characters using the /world and /worlds commands and not being able to download worlds.

**Comment by kimheffy** [comment]
Changes are up, closing this issue :)

**Comment by PundaChen** [comment]
This bug still exists, still see people every day with this issue
