### ISSUE TITLE
Hide this server

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#286]
### Feature request

**Checklist**
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

A button/setting in the panel where you can hide your server from the server list and the random join
**How the feature is useful**

Some servers are whitelisted etc. This could prevent people being sent to whitelisted servers
This is somewhat of an extension of #226 but that was closed
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by TeamMH** [comment]
This already exists, and can be found on the first page of the web panel. View attached image. 
![Uploading Screenshot_20200928-235447_Chrome.jpg…]()

**Comment by Blocksnmore** [comment]
Only issue ive seen is that random send sometimes connects to servers with visibility off

**Comment by LukasmanMHdude** [comment]
Yes but no, ppl can still use the "random server" button to join it. (also why tf is that so high res)

**Comment by PundaChen** [comment]
The visibility server does NOT whitelist it, it only takes it off the server list, you should instead whitelist it AND put it on invisible if you want it to be invis and not joinable by users

**Comment by LukasmanMHdude** [comment]
I have servers that I want anyone to be able to join with the IP, I just don't want my users being able to "random server" in

**Comment by Double0negative** [comment]
The server panel does have an option to hide your server from the server list and random join button (as shown above). However, The sever can still be joined via direct join (/join servername) (doesn't auto-enable whitelist). These are inherently different options, some people don't want to show up on Minehut, but still want people to be able to join.

**Comment by LukasmanMHdude** [comment]
wait does not let people join with join random server anymore?
