### ISSUE TITLE
World download problem

### ISSUE THREAD

**Issue by BlueTree242** [Minehut/Meta#288]
Hello, when i try to download my world, it says "Failed to upload files" Please tell me what to do

**Comment by PundaChen** [comment]
This isn't the right place to ask for help, please go to the Minehut discord and ask in #support 
Can close this issue now ^^

**Comment by BlueTree242** [comment]
I dont need help, it is a bug that i am reporting

**Comment by BlueTree242** [comment]
But i need it to br fixed fast

**Comment by BlueTree242** [comment]
> This isn't the right place to ask for help, please go to the Minehut discord and ask in #support
> Can close this issue now ^^

**Comment by PundaChen** [comment]
Please follow the bug report format then :/

**Comment by BlueTree242** [comment]
> Please follow the bug report format then :/

Ok, please fix the bug as fast as possible

**Comment by Blocksnmore** [comment]
You still haven’t followed the bug report format 🤦
