### ISSUE TITLE
libdisguises says i need to purchase to use player commands

### ISSUE THREAD

**Issue by Clickmeharder** [Minehut/Meta#291]
![liberror](https://user-images.githubusercontent.com/69931387/94988433-5c493900-052a-11eb-9b15-329425c9264b.png)

**Comment by LukasmanMHdude** [comment]
Hi, please make sure to follow the format, close this and open a big report

**Comment by Blocksnmore** [comment]
Also this isnt a bug, your just missing the needed permissions to use /disguise
