### ISSUE TITLE
Add uploading datapacks in /ul

### ISSUE THREAD

**Issue by quick007** [Minehut/Meta#292]
### Feature request

**Platform**
Ingame, both

**Describe the feature**
Currently, uploading data packs is a massive pain in the ass, if you've ever tried to do anything with them in this current state its an incredibly hard and time-consuming "folderception" (as Michael calls it) process, which you can view here: https://www.youtube.com/watch?reload=9&v=y_lqGGIrDwI (this btw, is one of the longest tutorials ever made to do something that would usually take 5 seconds anywhere else).

Add datapacks into the UL command, please 🥺 (or maybe allow the file extension .zip in certain places in the file manager if that's easier to do)

**How the feature is useful**
Lets people use sites like vanilla tweaks and returns easy functionality to the file manager (imagine of rss pack's had to be added this way lmao). 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by youngmasterseth** [comment]
Dang, now thats the spirit! I mean it would also be nice to have then able to just upload folders in the file manager. I mean I get why that would be ify, cause they have to check if the contents of said folder have no no stuff in them, but I mean, it would be nice to have for this same reason.

**Comment by LukasmanMHdude** [comment]
> Dang, now thats the spirit! I mean it would also be nice to have then able to just upload folders in the file manager. I mean I get why that would be ify, cause they have to check if the contents of said folder have no no stuff in them, but I mean, it would be nice to have for this same reason.

I actually added that to my issue as well, but I don't see them whitelisting that anytime soon

**Comment by youngmasterseth** [comment]
Yeah and that's understandable... it would be nice tho 😀

**Comment by drtshock** [comment]
How would that format need to work? Something like `/ul datapack <worldname> <linktodatapack>` ?

**Comment by mygizli04** [comment]
Datapacks only work if they're in the same world as the one in server.properties. So `/ul datapack <linktodatapack> [worldname]` makes more sense making worldname optional ( defaulting to current world in the dashboard ) but still keeping it in case the player wants to change worlds soon or something. A warning that the datapack will not work unless you change the world in the dashboard would also be nice in order to not confuse people

**Comment by BennyDoesStuff** [comment]
The upload command no longer exists anymore so this issue doesn't apply.
