### ISSUE TITLE
Added functionality to server unlisting

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#293]
**Platform**
In-game/control panel 

**Describe the feature**
Removing the ability for a server to be joined via the random server button if it was unlisted.

**How the feature is useful**
It would help people by offering them an additional method of securing their servers.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
This is basically like #286 (which the devs closed), excited to see what double does with this one

**Comment by MiginsMC** [comment]
I was under the impression that this already happens 🤷

**Comment by drtshock** [comment]
I think a better scope of this ticket could be:
- Random join ignores whitelisted servers
- Show if a server is whitelisted in its description in the server list when you hover over its icon

**Comment by MrTibo1** [comment]
> I think a better scope of this ticket could be:
> 
> * Random join ignores whitelisted servers
> * Show if a server is whitelisted in its description in the server list when you hover over its icon

or just automatically unlist servers when they're whitelisted. it's annoying to press random join and 9/10 times you get a whitelisted server

**Comment by BennyDoesStuff** [comment]
This has been implemented (at some point)!
