### ISSUE TITLE
Server phases between online and offline

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#296]
### Bug report

**Platform**
Wesite

**Describe the bug**
The server goes from 
![image](https://user-images.githubusercontent.com/69743171/95353109-c38f2200-0877-11eb-8cb0-f9f14de74c3b.png)
to
![image](https://user-images.githubusercontent.com/69743171/95353154-ce49b700-0877-11eb-94f3-59097bd70599.png)

**To reproduce**

Sit on the website and wait,

**Expected behaviour**

**Device Information**
Chrome lastest (85)

**Screenshots**
above

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by PundaChen** [comment]
Is it possible that a user is using /join (server) in the lobby?

**Comment by LukasmanMHdude** [comment]
No, it flickers between the two on occasion. I would also like to note that the server was very laggy at the time, not sure if that made an impact

**Comment by drtshock** [comment]
Anyone able to reproduce or also seeing this? Can you list out the status order that you see?

**Comment by LukasmanMHdude** [comment]
Haven't seen this recently, I'll reopen if I see it again (comment on this as well if anyone else see's it)
