### ISSUE TITLE
Cross-server join CMD

### ISSUE THREAD

**Issue by DaRealMinecraftexpert** [Minehut/Meta#297]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
I am suggesting an In-game Feature for both platforms.

**Describe the feature**
I believe this was once a thing and if it was, it was most likely Removed. I have wanted to have it so players on my Main server can go to my Secondary one on command. I guess you could say, I want to bring in a Cross server Join Command, so a player on one server can use the same function as if in the Lobby.

**How the feature is useful**
I feel that anyone whom uses Multiple servers can utilize this feature for using their Second Server Slot, or others beyond.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
This used to be a command, `/server`, and im not actually sure why it was removed. I feel like this would be beneficial.

**Comment by PundaChen** [comment]
Tdlr bring back /server aka #119

**Comment by DaRealMinecraftexpert** [comment]
I tried searching, and it didn't show me nothing

**Comment by Double0negative** [comment]
It was removed as a security issue because people could force other users to join servers they didn't want to join (even if they weren't on the same server). I do think its useful, and could potentially be re-added in some form, but just giving some context of why it was removed

**Comment by drtshock** [comment]
Duplicate of https://github.com/Minehut/Meta/issues/119 which we confirmed will be brought back. See Double0's above comment for context on why it was removed initially.
