### ISSUE TITLE
disable the chat

### ISSUE THREAD

**Issue by killergotrekt** [Minehut/Meta#301]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game so both
**Describe the feature**

Stop the people from talking.
**How the feature is useful**

- No more pesky moderators
- No more advertisements
- No more arguments
- No more punishments needed to hand out
- No more political breakouts
- No more work on anti-spam, anti-bot required
- No more moderators (disband them)
- Relief on moderators
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesTheStuff** [comment]
Serious suggestions only, please.

**Comment by LukasmanMHdude** [comment]
I personally like this suggestion, would help with the spambots as well

**Comment by Blocksnmore** [comment]
I feel this should be more of a toggle ie /togglechat and not just have it disabled outright
