### ISSUE TITLE
Verification as forum post

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#305]
### Feature request

**Platform**
website

**Describe the feature**
Have a forum post where people can respond to get the verified role instead of DM'ing a Sr. Mod for it.

**How the feature is useful**
Takes effort of Sr. Mods bc someone can just check it once a week/daily

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
could work as a temporary fix but seems tacky as a long term solution

**Comment by LukasmanMHdude** [comment]
yea, not supposed to be long term, just until they fix it. It just doesn't feel like the new verification is coming any time soon :/

**Comment by drtshock** [comment]
We won't be doing verification until we can properly implement it on our main website. All verified role permissions have been opened up to everyone now.
