### ISSUE TITLE
Discord: !google <keywords>

### ISSUE THREAD

**Issue by crewly** [Minehut/Meta#306]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Discord

**Describe the feature**
 Instead of telling people to google for themselves, you can redirect them to a google search with specified keywords by typing: "!google player teleport skript not working"

**How the feature is useful**
 It's for support members and other helpers trying to help users with extra resources on google.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
http://www.googleguide.com/linking.html
this seems like a useful guide for anyone looking to create this

**Comment by theminecoder** [comment]
I feel this is just going to lead to spam once people find the command, so I am going to deny this.
