### ISSUE TITLE
Allow normal users to nick again

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#307]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Discord

**Describe the feature**
Give all users the ability to nick again.

**How the feature is useful**
There's no longer a verifying system so users constantly have to ask srmods just for the ability to nick, this should also lessen the issue of users breaking the nickname rule (Need alphanumeric characters in name) 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Double0negative** [comment]
Closing as done. All users can nick again.
