### ISSUE TITLE
Aikar's startup parameters

### ISSUE THREAD

**Issue by Woeben** [Minehut/Meta#311]
### Feature request

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] This is not a bug report, support request or plugin request
- [x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x ] This issue does not contain any sensitive information 

**Platform**

 In-game, Java

**Describe the feature**

The usage of Aikar's startup parameters:  https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**How the feature is useful**

Helps with lag spikes on paper servers.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Hey we're running some slightly different flags but yes we're aware of aikar's flags, and will review the ones we use again.

**Comment by BennyDoesStuff** [comment]
It does look like Minehut is using Aikar's startup parameters (or something similar) as it shows that in my timings report.

![image](https://user-images.githubusercontent.com/16548272/130268626-cc4c9a92-0cdb-40a6-826e-138dffcb1f25.png)
