### ISSUE TITLE
Separate roles for changelog and announcements

### ISSUE THREAD

**Issue by wiidotmom** [Minehut/Meta#313]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord

**Describe the feature**

The changelog and announcement channels should mention separate roles when updates are posted. Currently, they both use `@Changelog`. Announcements occasionally use `@here` for maintenance notices, that can stay the way it is.

Example from announcements:
![image](https://user-images.githubusercontent.com/22878174/95915034-6e617d80-0d5b-11eb-9814-4aee02f70b6e.png)
Example from changelog:
![image](https://user-images.githubusercontent.com/22878174/95915058-78837c00-0d5b-11eb-9689-dc18a1a0c9bd.png)

**How the feature is useful**

For people who really only care about larger updates that add new features rather than staff and plugin updates, this prevents us from getting unnecessary mentions.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Anyone else have thoughts on this? Perhaps we have a separate plugins role instead?

**Comment by LukasmanMHdude** [comment]
Maybe @announcements, @changelog, and @plugins

**Comment by xmuel** [comment]
I'm not a fan of having what would be 5 reaction roles because that would just fill up the role list of users. I'm a fan of how its currently set up as the 3 roles that we currently have. Changelog can be used for anything which relates to changes in Minehut which is why I think it's a good idea to keep it as it is.
