### ISSUE TITLE
Discord autoreact

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#318]
### Feature request

**Platform**
Meta discord

**Describe the feature**
Autoreact to all the messages in \#fiter-request and \#meta-feedback (and make a command to set it up maybe?)

**How the feature is useful**
Instead of staff or people having to react, Minehut Bot could do it and it would save time from staff and make the channels get no reaction spam.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
Per the guild configuration features that the Minehut bot has, I'll be making a pull request for this on the Minehut bot's repo today that will allow channels to be configured to auto react with an array of specific emojis.

**Comment by Sniped** [comment]
Implemented in pull request [65](https://github.com/Minehut/MinehutBOT/pull/65)
