### ISSUE TITLE
Panel Overhaul

### ISSUE THREAD

**Issue by quick007** [Minehut/Meta#320]
### Feature request

**Platform**
Web (core)

**Describe the feature**

### Introduction

Currently, the panel is slow, badly color-themed, and needs a complete overhaul from the ground up. There are many errors and things that just make sense to have in a panel missing from it, and the features that are there either work or are janky to use. I'm not suggesting specific designs because I don't want this suggestion to be judged based on my horrible graphic design, so I'll point out things wrong with the panel and give ways to fix it. (let people who can actually graphic design do there job)

I think a panel update right now would be amazing. With a ton of planned features that are coming to the panel, this gives minehut a chance to 

### Themes

Currently, we have a dark and light theme. They both don't look that great and could is improved. I think we should also add AMOLED to that collection of themes. Also, the colors need to be redone. I don't have an exact color scheme right now, but trying to add more blue into the colors could look good imo.

### General look at feel

One of the things that really bugs me about the panel right now is this page: 
![image](https://user-images.githubusercontent.com/69743171/96359552-fb446800-10c8-11eb-8230-34a979d121e6.png)
I personally dislike it for a few reasons:
* Sidenav is ugly 
  * Packed with too many items
  * Has unnecessary lines on it that just feel weird
  * Overall design could use some colors and better icons
  * No customization 
* Server list needs a remake
  * Instead of wasting area with stats we don't need (why does "last online" need to be on the front page. It feels like someone just needed an icon so used that instead of something intuitive.
  * Main card design should be redone
  * 

#### Don't judge this suggestion based on what features it has, I just tried to layout something. Just like /ad, I would love feedback and ideas, and I will edit the suggestion to add everything :)

**How the feature is useful**

Changes the panel and makes minehut a better place for everyone. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**
# Still working on updating this

**Comment by farwl** [comment]
The panel is really slow, and poorly designed. It needs a complete overhaul and new theme(s). Personally I really liked Luuke's old panel theme and I think that it would look superb if Minehut re-implemented it. Hope to see some changes (:

**Comment by LukasmanMHdude** [comment]
> The panel is really slow, and poorly designed. It needs a complete overhaul and new theme(s). Personally I really liked Luuke's old panel theme and I think that it would look superb if Minehut re-implemented it. Hope to see some changes (:

Not sure if we really would want to implement a theme like that, I think trying to match other websites with the modern design would be a better idea. Implementing the site first on dev.minehut.com, then changing it on a case by case basis would be preferable imo. I also changed "need improvements" to "complete overhaul" to make it clearer, that's what I meant lol.

**Comment by drtshock** [comment]
Any specific things you don't like or that you preferred on the old panel, or another panel?

**Comment by Sniped** [comment]
What exactly needs overhauling in the panel? So far, it seems like there's just a need for new themes in the panel. In my opinion, this issue should be dedicated to theme suggestions and should be titled as such.

**Comment by LukasmanMHdude** [comment]
> Any specific things you don't like or that you preferred on the old panel or another panel?

Well, a lot of the features I stated above were baked into the core website experience on other hosts, for example, sub-users I think would benefit from having a new panel because things can be added with that in mind. I never actually used the old pnel, just saw some not the best screenshots for it so I'm not trying to bring that back.

**Comment by LukasmanMHdude** [comment]
> What exactly needs overhauling in the panel? So far, it seems like there's just a need for new themes in the panel. In my opinion, this issue should be dedicated to theme suggestions and should be titled as such.

Themes may not be the right way to say it, more like actually redoing the panel design, especially the settings, file manager, server selector, and side nav. Color schemes are just an important way to tie everything together, not the main focus of this issue.

**Comment by Double0negative** [comment]
Can you give some detail? It just sounds like you are just saying "I don't like it" but nothing actual substantial about it that could be better. What are your pain points? What could be improved to improve your experience? please give us more detail and we can look into those issues. We aren't going to re-make the entire panel because you don't like something with the server selector, but if you tell us what you don't like about the server selector we can look into make improvements to it.

**Comment by LukasmanMHdude** [comment]
> Can you give some detail? It just sounds like you are just saying "I don't like it" but nothing actual substantial about it that could be better. What are your pain points? What could be improved to improve your experience? please give us more detail and we can look into those issues. We aren't going to re-make the entire panel because you don't like something with the server selector, but if you tell us what you don't like about the server selector we can look into make improvements to it.

Thanks for pointing that out. I'll update my suggestion later today/tomorrow to be more in-depth with what I feel should be changed

**Comment by BennyDoesStuff** [comment]
A new website design was released so this issue doesn't apply anymore.
