### ISSUE TITLE
Bossbar updates when Minehut is having issues.

### ISSUE THREAD

**Issue by ahoulton** [Minehut/Meta#321]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
In-game (Bedrock and Java)

**Describe the feature**
When Minehut is having issues and admins are looking into issues, the bossbar for all lobbies should be updated to something like "We are currently looking into issues, please join our Discord for updates.".

**How the feature is useful**
This could help since staff won't have to keep saying that Minehut is having issues and players can just look at the bossbar and see that the network is having issues and that developers are looking into said issues.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
^ Maybe also saying it in chat as well, and when people try to connect to servers sending "You may experience problems on minehut due to an outage" or smth like that

**Comment by DaRealMinecraftexpert** [comment]
Don't they Close Lobbies on Outages?

**Comment by LukasmanMHdude** [comment]
> Don't they Close Lobbies on Outages?

Just an example msg, they could use that during server updates at whatnot with some tweaks, and as well when servers are having issues starting but they still want to keep lobbies open.

**Comment by theminecoder** [comment]
Gonna be honest, I would rather we spend time on actually fixing the problems rather then updating a bossbar. However I think this concept might be useful as a maintenance reminder

**Comment by ahoulton** [comment]
Could be a Moderator+ command or something, my original idea for this, devs/admins would work on fixing the issue and Moderator+ could do something like "/lockdown" which would then update it.

**Comment by AdxmGG** [comment]
it could just base it off the api and see if theres alot of servers up or not

**Comment by Sniped** [comment]
Maybe this could be integrated with a status page (#91) and simply be "If you're experiencing issues, check out status.minehut.com" or something like that.

**Comment by drtshock** [comment]
So yes potentially. What I'm looking to do is make this configurable via an admin panel, that way if we're having issues, I can go and manually update it easily. Otherwise, we'll be able to update this more frequently. Right now it requires a code change and deploy.

**Comment by drtshock** [comment]
^^ We're going to be working on that part soon.
