### ISSUE TITLE
Create a list of basically everything minehut needs to do (maybe in the projects tab?)

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#323]
### Feature request

**Platform**
Github/Trello (depending on where they choose to implement it)

**Describe the feature**
Hava list of everything minehut has planned, big and small. I see announcements about rollbacks, and stuff like https://github.com/Minehut/Meta/issues/305#issuecomment-709463648, but there's no clear list of smaller ticket items that Minehut wants to add in the future. I think that it would be beneficial for minehut to create a list of all this stuff to help bring clarity to the process. 
As I said earlier, a Trello board or GitHub projects (as people are already here anyway) would help us see more of the smaller tasks that are happening. I think this is important so people can go to that page and see an up-to-date list of everything.

**How the feature is useful**
This would help with people not having to sort through old closed issues that mention future features (like the example I provided before) and a smaller, more concise version of the planned list. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
I believe the admins were looking into using GitHub Projects for this. I personally believe that the integration with GitHub projects and issues is outstanding. With everything in one place, you're able to simply add an issue to a project board and it will automatically retain its labels and other details for you to view. 

GitHub's default automation seems quite bare from what I can tell. Their default automation pertains to only the board and what happens to the issue once it's placed on the board. For example, if you put an issue onto a project board and the project board isn't configured to know where to initially place the issue, it will put it into something called a "Triage" where you can place the issue. However, if you have it configured, it will place it into the configured column.

While the default automation may seem bare, GitHub offers an extensive API that can be taken advantage of with available resources on the GitHub Marketplace. With [GitHub Project Automation+](https://github.com/marketplace/actions/github-project-automation), we can take advantage of GitHub workflows to further increase our automation of the project board. With this, we would be able to add workflow configuration to automatically place an issue on the project board if we give it the label of "Planned", and if we give it the label of "Done", we can have it moved to the "Done" category. 

This is just my rough idea of what we could do with GitHub Projects. If anyone else has anything to add, feel free to do so here.

**Comment by Sniped** [comment]
This has been implemented, all game and web (core) issues that are planned will now end up on the project board. Trent will be updating the board for when these are in progress, in testing, and done.
