### ISSUE TITLE
A form of compensation for the recent rollbacks issue

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#327]
**Platform**
Web panel, in-game

**Describe the feature**
Some sort of compensation for the recent rollbacks. 

**How the feature is useful**

The recently fixed bug affected a lot of people's daily lives on their own servers. Some lost entire days worth of progress. For those users, it has made many users frustrated and disappointed, others it has made angry and fuming. I believe that a credit compensation of any amount(around 100-500 per server) would help minehut users "cool down". I take this moment to thank the devs who worked hard on a solution to this bug.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
I understand, but unfortunately it's difficult for us to track down who was impacted, how badly, and would be very expensive to compensate everyone with credits. Rather, we're doing our best to improve the quality of the service without increasing the cost.

**Comment by farwl** [comment]
Should do double credits for voting this weekend 😎

**Comment by LukasmanMHdude** [comment]
> Should do double credits for voting this weekend 😎

100% this is a good idea

**Comment by drtshock** [comment]
We are already on top of the voting site <3

**Comment by AdxmGG** [comment]
> We are already on top of the voting site <3

So? You may as well compensate players, **while also** confirming and keeping your place as number one on the list.

**Comment by LukasmanMHdude** [comment]
add more voting sites then

**Comment by LukasmanMHdude** [comment]
a

> We are already on top of the voting site <3

sureeee
![image](https://user-images.githubusercontent.com/69743171/96614807-5e92ed80-12b5-11eb-823d-341377a8fa79.png)

**Comment by Shlba** [comment]
> I understand, but unfortunately it's difficult for us to track down who was impacted, how badly, and would be very expensive to compensate everyone with credits. Rather, we're doing our best to improve the quality of the service without increasing the cost.

ah understood. That is very reasonable.

**Comment by farwl** [comment]
People have suggested more credits per vote / more voting sites before. If they allowed us to vote on more sites, it would be for a smaller amount of credits. Getting Minehut high up on one voting site is more beneficial than voting on multiple, and it's less of a hassle to get credits if you're voting for 25 once per day as apposed to voting for say 5 credits 4 times a day.

**Comment by farwl** [comment]
I just think it would be cool if they did double credits for voting this weekend. They did this once or twice before.
