### ISSUE TITLE
Multiple Panel Instances

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#33]
### Feature request

**Platform**
 Website (Panel)

**Describe the feature**

You used to be able to have multiple instances of the panel open, so you could be logged into more than one panel account at once. It was removed for no reason.

**How the feature is useful**

This feature helps vastly decrease the risk of getting a server name sniped.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Would probably be better just to be able to log into multiple accounts at the same time, and switch between accounts from the same page without having to login.

**Comment by drtshock** [comment]
Can you show me an example of another site that does this well?

**Comment by farwl** [comment]
> Can you show me an example of another site that does this well?

Can't think of any atm. Minehut could be the first ;)

**Comment by CoreyShupe** [comment]
This seems to work. Please re-open if it doesn't.

I seem to be able to open multiple tabs of minehut with both panel instances working properly.
