### ISSUE TITLE
Github Connections

### ISSUE THREAD

**Issue by MrEnxo** [Minehut/Meta#330]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Link a file system to a github. like having the minehut servers files on github so you can just push to github and reload server in game. Obviously this would be if we have full control over files in minehut but that will come in a later date for sure.

**How the feature is useful**
you can choose your own text editor for making stuff. Unless minehut makes a better text editor which would just waste time they could just like their filesystems to githubs and have players get full access over files.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
I believe it would be a better solution to just allow SFTP connections to a server and transfer files using a client such as FileZilla.

**Comment by Blocksnmore** [comment]
> I believe it would be a better solution to just allow SFTP connections to a server and transfer files using a client such as FileZilla.

Honestly i believe little to no people would have a FTP client and most servers i see have a backup/development repo on github so that would make sense.

**Comment by ahoulton** [comment]
Not many people have Github (just seeing how much stuff get upvoted around here), so I think SFTP would be the best option since admins/devs can limit what people can and cannot edit/open, with Github, this might be inpossible.

**Comment by Sniped** [comment]
> Honestly i believe little to no people would have a FTP client and most servers i see have a backup/development repo on github so that would make sense.

Hosting all of your files on GitHub and linking the two just doesn't make sense to me. Why make commits to GitHub to, for instance, add a world to your server, when you can just drag and drop it onto an SFTP client just like any file in a file manager and have it upload within two-three minutes depending on your internet connection? 

> so I think SFTP would be the best option since admins/devs can limit what people can and cannot edit/open, with Github, this might be inpossible.

It wouldn't be impossible I believe, however the way I imagine it would work would be quite weird and impractical. If some user were to upload an illegal plugin (or just any plugin at the moment), it would still be on the GitHub however not on the actual server. Which could be quite confusing and seems like unneeded work to make GitHub and the Minehut file manager synergetic in that regard.

**Comment by MrEnxo** [comment]
facts

**Comment by LukasmanMHdude** [comment]
Ya know, it's nice seeing someone take criticism \:)
