### ISSUE TITLE
Change Media Requirements

### ISSUE THREAD

**Issue by 83y** [Minehut/Meta#331]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Java

**Describe the feature**
 Up the consistent view count for your YouTube video and lower the subscriber requirement.

**How the feature is useful**
 Here are some reasons why:

- Most people got their subscribers from other games / servers
- Most of the people who have YouTube rank currently make trash content / click baiting content which gives the server a bad image / reputation (no offense intended)
- Quality over quantity is always better and gives the server a better image, as of right now the minimum views is 350, I think this should be upped to 1k  if their amount of subs is 3000, normally YouTube channels that are of a high quality get more views than they do subs. If not it shows its either a bad channel or dying one.
- 3k is a lot for Minehut youtubers, I think this should be lowered to 1k as there are no channels who have grown their subs purely off Minehut that have more than 3k subs (not that I know of).

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
> Most people got their subscribers from other games / servers

Ok? Many big people like Ssundee (yes, ik he's cringe) grew off of other games but now play something different. I don't see why this is an issue/how that would fix it.
>Most of the people who have YouTube rank currently make trash content / click baiting content which gives the server a bad image / reputation (no offense intended)

How do you determine "trash content" lmao
> Quality over quantity is always better and gives the server a better image, as of right now the minimum views is 350, I think this should be upped to 1k if their amount of subs is 3000, normally YouTube channels that are of a high quality get more views than they do subs. If not it shows its either a bad channel or dying one.

minehut = quantity > quality
> 3k is a lot for Minehut youtubers, I think this should be lowered to 1k as there are no channels who have grown their subs purely off Minehut that have more than 3k subs (not that I know of).

Idk I don't think it needs to be lowered, its fine to get subs from other sources

**Comment by drtshock** [comment]
No need to flame people because you don't like their content.
