### ISSUE TITLE
Ability to mute lobby messages during botting.

### ISSUE THREAD

**Issue by ItzOP** [Minehut/Meta#333]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Both

**Describe the feature**
The ability for Minehut staff to disable the /message command like they can disable chat in the lobbies.

**How the feature is useful**
During botting circumstances, as soon as a lobby is muted. Bots quickly turn to dm botting quite quickly.
If the staff had the ability to temp mute/disable messaging then it'd be helpful to stop this.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
+1 i feel that the botting is getting out of hand, they need to do something like this until they sort out the bots

**Comment by AlwaysVape** [comment]
+1 These bots need to be controlled.

**Comment by Tastq** [comment]
+1 People decide to bot whenever they dislike a server and it can be really damaging to creators who work day and night to try and make their server the best it can be and then it's destroyed by one individual who simply doesn't like them or their server.

**Comment by SwiftyWeb** [comment]
+1 I agree, these bots really need to controlled. They are out of hand

**Comment by Sniped** [comment]
The question I have with this is whether or not this should make it so it blocks messaging network-wide or if it should just stop players from being messaged specifically on the lobby. I do believe that this would be a great moderation tool either way to stop bots quickly.

**Comment by Sniped** [comment]
Also, please use reactions instead of just saying "+1" in the comments, it's a much better way of measuring upvotes for a suggestion.

**Comment by KingofUndead** [comment]
My questions are what's stopping players from disabling private messaging themself and how likely are bots going to msg players? its not that i don't like the idea or trying to sound mean its just that minehut already gives the players a way to prevent people from messaging them

**Comment by Blocksnmore** [comment]
> My questions are what's stopping players from disabling private messaging themself and how likely are bots going to msg players? its not that i don't like the idea or trying to sound mean its just that minehut already gives the players a way to prevent people from messaging them

A surprising amount of users don't know how to turn off private messages, also this would only affect lobby messages since thats where the bots are

**Comment by ItzOP** [comment]
> My questions are what's stopping players from disabling private messaging themself and how likely are bots going to msg players? its not that i don't like the idea or trying to sound mean its just that minehut already gives the players a way to prevent people from messaging them

It's more of a moderation tool, for example, someone could be sending IP grabber links with bots. Some people may not realise and click the links. So in that case it could be used as a safety tool to protect people from it.
And if people don't want to see the bots, they could just turn dm's off after being messaged by one, but then they've still gotten bot messages in the first place. If the staff can turn messages off, it will mean that a large majority of people won't have to see the bot messages in the first place.

**Comment by ahoulton** [comment]
I want this to be added to MH as a shocking amount of users don't know how to turn off dms and incase of ip grabbers in bot attacks.

**Comment by drtshock** [comment]
The dm's only impact a couple hundred out of thousands of users online. We're working on a better solution to prevent botting that won't be annoying for people using the service normally.

**Comment by BennyDoesStuff** [comment]
This does not appear to be an issue anymore.
