### ISSUE TITLE
Recent (last) servers list

### ISSUE THREAD

**Issue by Sploric** [Minehut/Meta#337]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Game: Both

**Describe the feature**

A command / gui item, that displays the last few servers you visited, like the names of the server and if they are online or not.

**How the feature is useful**

Benefits players who randomly join a server and forget the name later on. Useful because you can check the last handful of servers you joined. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by xmuel** [comment]
I think a /history command would also be very nice, it could just display the past ~5 servers that the user has been on. If this was to be in the form of a GUI, it could potentially be shown in the Account Menu GUI on lobby which I think could be nice.

**Comment by LukasmanMHdude** [comment]
> I think a /history command would also be very nice, it could just display the past ~5 servers that the user has been on. If this was to be in the form of a GUI, it could potentially be shown in the Account Menu GUI on lobby which I think could be nice.

why do people say "this is a good idea" but not upvote it 😕

**Comment by drtshock** [comment]
Definitely something we want to do. Can someone propose a cool way to do this? What I was thinking:

Part of your player profile GUI in the lobby
- List of recent sessions (including lobbies?) showing:
  - Name of server (at the time)
  - Time joined
  - Minutes played
  - Click the icon to join the server again
  - Should we show current server info here? Like player count and if it's online.
- List of servers ordered by most time spent on them for you
  - Name of server
  - First join
  - Most recent join
  - Total times you've joined it
  - Total time you've played on it

**Comment by killergotrekt** [comment]
- Lobbies shouldn't be included
- Server Info:
• Should add `Server's MOTD`
- Should be sorted from (left to right), the latest server that is played, up to a certain amount of recent slots per rank:
• Non - 3 slots
• VIP - 5 slots
• Pro - 8 slots
• Legend - 12 slots
• Patron - 20 slots

**Comment by drtshock** [comment]
Interesting, I wasn't thinking it would be a rank perk. I was thinking to just show all the data to everyone since we're storing it :) but not a bad idea!

**Comment by AdxmGG** [comment]
Personally I dont think lobbies should be included. Mostly because your lobby can change so often (joining a whitelisted / full server) and what lobby your on doesn't really matter as the chats all connected.

Secondly, I dont think it should be a rank thing. It's just a handy feature for all users and you shouldn't have to pay extra to see what server you were previously on. Just think a default user wants to see what server they were on a few sessions ago, but can't because it's too far back for default rank, **boom** lost a player because they can't find their favourite server.

**Comment by DaRealMinecraftexpert** [comment]
More things locked behind Purchased Ranks makes me feel like They take away MH's Purpose of being free. But that's just me.

**Comment by killergotrekt** [comment]
> Secondly, I dont think it should be a rank thing. It's just a handy feature for all users and you shouldn't have to pay extra to see what server you were previously on. Just think a default user wants to see what server they were on a few sessions ago, but can't because it's too far back for default rank, boom lost a player because they can't find their favourite server.

I disagree. This gives another reason to buy a cosmetic rank and you are still getting free slots, could've made this like a donator only feature such as lobby glow too. Plus 3 servers are already a lot to give.

**Comment by not-3than** [comment]
Honestly I think a GUI system is a bit overkill, maybe just make a /rejoin command if a player accidentally gets disconnected from a server and can't find the name of it. (Instead of them having to go to their logs folder)

**Comment by Shigbeard** [comment]
@not-3than 

> 
> 
> Honestly I think a GUI system is a bit overkill, maybe just make a /rejoin command if a player accidentally gets disconnected from a server and can't find the name of it. (Instead of them having to go to their logs folder)

I disagree, I've had several scenarios where I've been playing on a server I've either joined from random or from some advert that happened several hours ago, only to hop off for the night, go to bed, and wake up the next morning wondering "what was that server I was playing on?".

I largely agree with @drtshock's idea:

> 
> 
>     * List of recent sessions (including lobbies?) showing:
>       
>       * Name of server (at the time)
>       * Time joined
>       * Minutes played
>       * Click the icon to join the server again
>       * Should we show current server info here? Like player count and if it's online.
> 
>     * List of servers ordered by most time spent on them for you
>       
>       * Name of server
>       * First join
>       * Most recent join
>       * Total times you've joined it
>       * Total time you've played on it

... but I think that the in-game GUI should be limited to at most 5 recent servers, simply to prevent information overload for newer or less experienced players. In any case, there should be no need to review servers older than this, but if there is, the GUI could be paginated much like the regular server list is. A web-based GUI could be created that would show a complete set of servers you've played on, as well as your most frequently played servers, authenticated via the pre-existing workflow for Minehut accounts.

**Comment by BennyDoesStuff** [comment]
This has been implemented! Resolved.
