### ISSUE TITLE
Confirmation for Mass Delete files

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#34]
### Feature request

**Platform**
 Website (File Manager)

**Describe the feature**

Make a confirm modal when you click Delete selected files. Currently, you click it and it deletes with no confirmation.

**How the feature is useful**

This is useful because some people accidentally delete files.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Should we do this for all file deletions? Any other confirmations we need?

**Comment by jellz** [comment]
It doesn't hurt to have confirmation modals for potentially destructive actions

**Comment by farwl** [comment]
^

**Comment by BennyDoesStuff** [comment]
Implemented in the recent file manager update.
