### ISSUE TITLE
Captcha passes without moving

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#343]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Java

**Describe the bug**

On join, the captcha message is sent and then almost instantly the 'you may talk now' message it sent, without moving.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to any lobby
2. See bug

**Expected behaviour**

The captcha wouldn't pass until I move or type in the code.

**Device Information**

- Minecraft client (and version): 1.16.4 optifine

**Screenshots**

![Screen Shot 2020-10-30 at 8 33 18 pm](https://user-images.githubusercontent.com/58871819/97695038-27abab80-1aef-11eb-82aa-1bac9ef5a809.png)
Sorry about the limited evidence, had a few friends test and they could all reproduce.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by PundaChen** [comment]
Can confirm on 1.16.3 and 1.12.2

**Comment by jellz** [comment]
Can reproduce on MC 1.16.3

**Comment by Sniped** [comment]
Can reproduce on MC 1.16.3, confirmed bug

**Comment by MiginsMC** [comment]
Closing this as the captcha has been updated and this bug is no longer present.
