### ISSUE TITLE
Players getting kicked and bugging the game.

### ISSUE THREAD

**Issue by deathsou** [Minehut/Meta#345]
- [yep ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ yep] I am NOT reporting a security vulnerability
- [ kinda] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ yep] This issue does not contain any sensitive information

**Platform**
java

**Describe the bug**
I have players on a server (currently MHUltimate, eddyevents 😉 ) getting kicked without a kick message, and then when attempting to log back on, cannot. Meanwhile, in game, it says that they are still on, and we can /tp to them, even though their actualy player isn't on the server. This is very new and may be associated with mhultimate. Who knows?

**To reproduce**
Steps to reproduce the behaviour:
1. Not really a common issue

**Expected behaviour**
What

**Device Information**
-doesn't matter

**Screenshots**
https://www.dropbox.com/s/aocuol75sb3acka/Screen%20Shot%202020-10-31%20at%2012.52.14%20AM.png?dl=0
https://www.dropbox.com/s/tjjlfeeenzn2j4w/2020-10-30_23.43.06.png?dl=0

**Additional context**
:( 

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Sniped** [comment]
Could you try to find the origin of this bug and post detailed steps on how to reproduce? This way, other players can try to reproduce your bug and verify that they get the same results. Additionally, expected behavior is what you expect to happen when you do something, such as player's not showing as online when they disconnect. 

For now, I'm going to close this as `invalid`, please edit your issue to show the steps for reproducing this bug as well as an expected outcome or recreate this issue.

**Comment by deathsou** [comment]
> Could you try to find the origin of this bug and post detailed steps on how to reproduce? This way, other players can try to reproduce your bug and verify that they get the same results. Additionally, expected behavior is what you expect to happen when you do something, such as player's not showing as online when they disconnect.
> 
> For now, I'm going to close this as `invalid`, please edit your issue to show the steps for reproducing this bug as well as an expected outcome or recreate this issue.

There's no way I know of to reproduce it. I've been working on this server for weeks now, nothing of this kind, and as I said it's most likely due to the MHUltimate.. or something. If you wanna test it out yourself, go ahead, but I'm not sure you'll get the same results.  Also, when i do /tp (player), i teleport to their last location, but there's no one there. When i /find them, either they left minehut a while back or are on a different server/Lobby now. They will show up as being on the server, without really being on.

**Comment by LukasmanMHdude** [comment]
also they can't patch it if they don't know the cause of it
