### ISSUE TITLE
Homepage infinitely loads 

### ISSUE THREAD

**Issue by Recal** [Minehut/Meta#346]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Web

**Describe the bug**

Going to / results in the page infinitely loading due to a SyntaxError in **js/app.74e8167a.js**

**To reproduce**
Steps to reproduce the behaviour:

1. Hard refresh or clear cookies + page data and go to the homepage.
2. Observe how the page infinitely loads.

**Expected behaviour**

Page properly loads and renders the homepage.

**Device Information**

- Web browser (and version): Brave Version 1.16.68

**Additional context**

### This behavior doesn't happen if you already have the page cached.
If the page doesn't exist going to minehut.com/[whatever] redirects to the homepage and properly renders.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
Cannot reproduce, windows chrome

**Comment by Recal** [comment]
This was fixed I guess
