### ISSUE TITLE
Modify Server Icon

### ISSUE THREAD

**Issue by Desfile** [Minehut/Meta#35]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website and Java game

**Describe the feature**

Allow server owners (or people with access to server panel) to change the server icon which displays in the Minecraft server list.

**How the feature is useful**

This feature will benefit the server as a whole as it may attract more players, improve advertisement, etc.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
I think this would fall under a website feature request, not ingame.

**Comment by Desfile** [comment]
Apologies.

**Comment by drtshock** [comment]
Would fall as both web / in game. We've actually done some research on this and know that we can implement. Requires us further modifying bungee to support per server icons dynamically.

**Comment by BennyDoesStuff** [comment]
Released
