### ISSUE TITLE
Book and quill (internal Exception Java.lang.array index out of bound exception

### ISSUE THREAD

**Issue by Voidlesss** [Minehut/Meta#351]
### Bug report

**Checklist**
- [ X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ X] I am NOT reporting a security vulnerability
- [ X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ X] This issue does not contain any sensitive information
This happened in java

**Platform**

**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Sniped** [comment]
Could you add how to reproduce this error and what expected behavior you find out of it? People can't replicate the error you're getting otherwise.

(Marking as invalid for now, will test again once OP has given detailed steps on how to reproduce)

**Comment by LukasmanMHdude** [comment]
I have no idea how to reproduce this, someone pls close this issue

**Comment by CoreyShupe** [comment]
@Sniped can this be closed.

**Comment by Sniped** [comment]
Yeah, it seems like the author isn't going to update the ticket.
