### ISSUE TITLE
Toggleable /ad messages

### ISSUE THREAD

**Issue by ManagePasswords** [Minehut/Meta#353]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java, Bedrock

**Describe the feature**
Add "Ad Messages" to the setting, this will let players toggle if they can see messages from /ad or not

**How the feature is useful**
This feature would clean their chats. This would be very useful if a youtuber/twitch streamer is recording/streaming or something, and want to hide advertisement messages.

**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
What's the use of /ad if you can toggle it...

**Comment by LukasmanMHdude** [comment]
Yea, the whole point of /ad was to reduce spam, just allowing people to turn off ads would be dumb imo. Maybe yt and above could toggle it if you really wanted to.

**Comment by mygizli04** [comment]
I'd love this but if this happened no one would use /ad and we'd be back to square 1. The entire point of /ad is to make ads more visible while reducing spam.

**Comment by ahoulton** [comment]
Because some owners are so hungry for players, we might go back to square 1 as they will simply do everything for players even if it means breaking the rules, I'm not supporting this for everyone but might be useful for YouTubers.

**Comment by MiginsMC** [comment]
Maybe this could be a donor perk?

**Comment by Blocksnmore** [comment]
> Maybe this could be a donor perk?

Still feel that this would put people to square 1. What's the point of /ad if you can disable them

**Comment by MiginsMC** [comment]
> > Maybe this could be a donor perk?
> 
> Still feel that this would put people to square 1. What's the point of /ad if you can disable them

People 1. Won't know about the setting unless they actually care and 2. If it's a donor perk for PRO or above, not many people would even disable it

**Comment by mekb-turtle** [comment]
People (maybe like me) might just get a client side filter to remove ads so idk, it might be useful.

**Comment by ManagePasswords** [comment]
Yeah, toggleable ads should be only for [PRO] or higher so many people wouldn't disable it.

**Comment by LukasmanMHdude** [comment]
If ur gonna get a client-side filter then you deserve to have ads off lol

**Comment by ManagePasswords** [comment]
Since the new system has a prefix for every ad, all players can easily filter them so there should be an option to hide the messages.

**Comment by Sniped** [comment]
I believe server owners should get the most exposure for their server from the lobby. In fact, one of Minehut's main selling points is the large community and the amount of people that roll through the lobby. Why should we be lowering the amount of exposure for a server?

**Comment by Chilkins04** [comment]
Touching on what everyone said, /ad already decreases a great portion of spam. I can see why people would rather not have it but like others said it's important for servers to get proper exposure as that's what Minehut is best at providing.

**Comment by drtshock** [comment]
Thanks for the suggestion. Like others have said, we're trying to push people to use /ad while not being too harsh on filters in the normal chat. If we did this, we'd have even more issues of players advertising in normal chat as well as decreasing the visibility servers get by advertising in the lobby, which is a main selling point of Minehut.

If you have further thoughts on how to get around those challenges, feel free to comment / re open the ticket :)

**Comment by LukasmanMHdude** [comment]
> If you have further thoughts on how to get around those challenges, feel free to comment / re open the ticket :)

If you close the issue pretty sure we can't reopen it if that's what your implying
