### ISSUE TITLE
Warning points to prevent botting

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#354]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Server so both
**Describe the feature**

Botting is a very common issue happening on minehut right now. To prevent this I suggest a warning points system. If a server is caught botting they will receive a warning point. If the server gets x amount of points (I think 3 would be good) they get their server suspended for x time (I feel a week would be good) the suspension would prevent playing and starting up the server
**How the feature is useful**

This would majorly reduce the amount of botting. Because server owners won’t try and risk botting for more players since it they are caught they get suspended.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
What exactly are you referring to when you say botting? Botting the lobbies using /ad or botting the server itself? How, in any of these cases, would staff be able to pin the botting on the server? 

We already verbally warn players before suspending their server, they don't need to have three warnings as they already know that it's wrong the first time.

**Comment by Blocksnmore** [comment]
This would be more for stuff like /ad as has been seen in the recent bot storms. I feel this approach would be good because the servers always use disposable alts from websites like TheAltening so warning them doesn’t do much. If the server got punished instead of the bots it would likely prevent botting since owners are worried of getting warning points. About the pinning down of servers, it could be done via looking at all the ads being sent out by mass sets of accounts and also messages with stuff like &k which is mainly used for spam

**Comment by Sniped** [comment]
Sure they can have similar advertisements, however how would we know that the server owner or people affiliated with the server are even responsible for these bot attacks?

**Comment by LukasmanMHdude** [comment]
Yea there are times when people bot servers for them

**Comment by Shlba** [comment]
I think a better way to solve botting for /ad would be just to restrict /ad to people who have accounts linked to a console panel

**Comment by LukasmanMHdude** [comment]
> I think a better way to solve botting for /ad would be just to restrict /ad to people who have accounts linked to a console panel

I think people didn't want to do that because not many people have a panel acc

**Comment by ahoulton** [comment]
Another way to avoid this is to simply add a cooldown for each server aslong side the player cooldown.

**Comment by Shlba** [comment]
> > I think a better way to solve botting for /ad would be just to restrict /ad to people who have accounts linked to a console panel
> 
> I think people didn't want to do that because not many people have a panel acc

Minehut has around 3 million servers hosted, most people would have an account. Additionally all it takes is around 5 minutes and you’ll have a console panel already set up. It would be a very effective way of stopping bots from using /ad

**Comment by MiginsMC** [comment]
Having your account linked could also be something only required for default users since ranked users are almost always real people (not bots)

**Comment by drtshock** [comment]
We are doing other things that will prevent botting more successfully that are easier to implement.
