### ISSUE TITLE
Wait a bit of time before updating to the next Minecraft version.

### ISSUE THREAD

**Issue by aroze123** [Minehut/Meta#356]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In-game,

**Describe the feature**
Wait a bit of time before updating to the next Minecraft version.

**How the feature is useful**
Most popular plugins and third party clients take just a hours to a few days to update. It would be really helpful if Minehut waited at least a week or so to update rather than just pushing it out like as soon as possible, not like they did with the 1.16.4 update. It would break/partly break way less servers and would provide us a much better experience.

**Comment by LukasmanMHdude** [comment]
smh they always do this and break like half of there shit. Is soccercity broken btw?

**Comment by AdxmGG** [comment]
+1, honestly don't know why they updated so soon, they should have known better from past failures.

**Comment by TrueReassembly** [comment]
+1 Can agree to this

**Comment by LukasmanMHdude** [comment]
I thought minehut was going somewhere then they updated to 1.16.3 with proxy first then waiting for plugins... maybe just do that?

**Comment by killergotrekt** [comment]
Yep. This helps stability on minehut by allowing server owners to prepare for this

**Comment by drtshock** [comment]
We often see issues with lag / rubberbanding whenever we support the latest version via a protocol hack like viaversion, and most of our users are attempting to connect on the latest version. In this case, I think waiting another day would've made this a lot smoother, but we had other updates we needed to get out that night as well.

**Comment by LukasmanMHdude** [comment]
why not just do the thing where it updates when you restart your server? You should test these Minecraft pl's as well
