### ISSUE TITLE
Level Name

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#36]
### Feature request

**Platform**
 Website (Panel)

**Describe the feature**

Also allow us to set level name to worlds with _ and . because I have a world with the name containing 1.0.2, and It's not like I can rename it

**How the feature is useful**

This benefits all players.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Can you show this not working? This sounds like a bug, not a feature request.

**Comment by farwl** [comment]
You can't set your level name to a world name containing _ and/or .

I'm suggesting that you're allowed to do that.

**Comment by BennyDoesStuff** [comment]
No longer an issue as of the recent file manager update.
