### ISSUE TITLE
Auto generate SAH-1 hashes when people add a rss pack to there file manager

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#360]
### Feature request

**Platform**
Web(core)

**Describe the feature**
Automatically generate the hash for a RSS pack. 

**How the feature is useful**
helps new server owners who don't know what it is

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
I like this idea but i feel its unnecessary. The Sha1 hash doesn't need to be filled for the resource pack to work.

**Comment by ManagePasswords** [comment]
This is very unnecessary, as Blocksnmore said. The SHA-1 hash only needs to be filled if you want the resource packs to be updated without changing its name.

**Comment by LukasmanMHdude** [comment]
Yea thats true, closing
