### ISSUE TITLE
Properly record videos

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#363]
### Feature request

**Checklist**
- [yeah] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [yes] This is not a bug report, support request or plugin request
- [yea] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [yes] This issue does not contain any sensitive information 

**Platform**
 youtube channel

**Describe the feature**
 don't record tutorials during the live streams

**How the feature is useful**
 the tutorials made during these streams get 0 editing and are extremely rushed, I'm gonna be harsh here but they're horrible and would personally not watch them if I were in need of help. All errors made during these tutorials stay in the tutorial and is just extremely messy to watch.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
Im pretty sure most / all of the tutorials before they started doing the streams were properly recorded, so im not sure why they switched to this uncoordinated and unprofessional format of recording. **+1**

**Comment by LukasmanMHdude** [comment]
yea this is preatty trash lol: https://www.youtube.com/watch?v=QqkBFJxwieM

**Comment by drtshock** [comment]
We made some updates for last week based on your feedback, thanks for posting this.
