### ISSUE TITLE
prohibit misleading terms in /ad

### ISSUE THREAD

**Issue by killergotrekt** [Minehut/Meta#364]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java, Hub
**Describe the feature**

rule change: content in /ad must be related to the server (eg, "JOIN xxx FOR FREE GOODIES PAYOUTS" is acceptable but "JOIN xxx FOR ESCAPE SERVER biden sucks trump 2020" is not) 
**How the feature is useful**
minehut is a "kid friendly community" so keep it that way and enforce and check advertisements better since kids are "too young" to be in politics and parents might be concerned that their children is exposed to 'bad influence' <br>
---<br>
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
(noting that a filter like this was part of the of suggestion but never implemented), that's a +1 from me

**Comment by drtshock** [comment]
This is tough to do and isn't just a problem with ad, but also with chat in general.
