### ISSUE TITLE
Click msg to respond

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#365]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java

**Describe the feature**

When you are sent a message you should be able to click the msg (anywhere - username, rank, msg) and it will enter `/msg (msg author's name) ` (including space at end) in the users chat box.

**How the feature is useful**

Very useful for users when they're being messaged by multiple people at the same time or just for convienience.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
#349

**Comment by MiginsMC** [comment]
> Dupe of #349

#349 is about clicking users names generally in chat, this is to do with clicking messages sent to the user. This would happen on player servers and lobby.

**Comment by Sniped** [comment]
Why not have that on #349 then instead of creating a separate suggestion for it?

**Comment by LukasmanMHdude** [comment]
> Why not have that on #349 then instead of creating a separate suggestion for it?

that one is broader while this one stifles the use, IDK why you would want this one over that one

**Comment by MiginsMC** [comment]
Sorta forgot that, sorry. Will close this
