### ISSUE TITLE
Plugin Requirements RED

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#369]
**Checklist**
- [-] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [-] This is not a bug report, support request or plugin request
- [-] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [-] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
If a plugin requires something, the requirement should be highlighted red in the description

**How the feature is useful**
Incase someone just skims the description, they'll see the requirement

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
This suggestion belongs on https://github.com/Minehut/Meta/issues/12 since it has to do with improving the plugin panel. Dependencies were just suggested to be shown and then one click to install them, any suggestions should take place there for how to improve it.

Closed as dupe
