### ISSUE TITLE
Sidenav Shop Dropdown

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#37]
### Feature request

**Platform**
 Website

**Describe the feature**

Make this not a dropdown. Just make it take you to /shop/credits by default and then you can navigate from there. It's quite simple. It's just annoying and looks bad as the dropdown.
![](https://cdn.discordapp.com/attachments/592130982451216402/710632072640725102/unknown.png)

**How the feature is useful**

This is useful because it removes unnecessary navigation.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
or just make a hub for the shop sub-sites and then turn the dropdown button into a normal button, and then get rid of the other buttons

**Comment by drtshock** [comment]
How should we handle the dropdown for market? What would the nav on the new shop page look like?

**Comment by farwl** [comment]
The way the market pages were setup/made you can't really do anything with the market dropdown. You wouldn't have to change anything on the shop page or make a new one. Simply remove the dropdown content from the Shop link on the sidenav and let it take you to the shop page. On the shop page there are already navigation links there for things like Icons, Credits, etc.

**Comment by BennyDoesStuff** [comment]
This issue isn't applicable anymore as of the recent design update.
