### ISSUE TITLE
Captcha bug

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#371]
**Platform**
Lobby

**Describe the bug**
When entering the captcha wrong once the second captcha isn't in full caps

**To reproduce**
1- go to lobby
2- type the captcha incorrectly
3- see issue

**Expected behaviour**
captcha is in full caps the second time

**Device Information**

Java Minecraft 1.16.4

**Screenshots**
https://i.imgur.com/4OjJjJc.png

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by drtshock** [comment]
Interesting, thank you. We're working on a new captcha system to roll out asap so it's unlikely patch this.

Does it prevent you from solving it?

**Comment by PundaChen** [comment]
I can still solve it, just looks a bit odd

**Comment by drtshock** [comment]
Closing since we rolled out a new captcha system.
