### ISSUE TITLE
Server Commands override Bungee commands

### ISSUE THREAD

**Issue by mekb-turtle** [Minehut/Meta#373]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Java 1.8.9

**Describe the bug**

You cannot use commands that are on the server but have bungeecord too
**To reproduce**
Steps to reproduce the behaviour: (example with msg)
1. Join a server with /msg
2. Type /msg
3. You will use the server's /msg not minehut's /msg

**Expected behaviour**

It will use the command on the bungee instead of the server

**Device Information**

- Minecraft client (and version): Java 1.8.9 Forge - Patcher, Labymod
- Web browser (and version): Irrelevant
- Operating system (and version): Windows 8.1 64 bit
- Minehut server name: mekb

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by untitledgeese** [comment]
I was unable to reproduce this on 1.16.4
![image](https://user-images.githubusercontent.com/62254220/100114178-c3061700-2e36-11eb-860e-cf3c87bd979f.png)
Normal minehut message from /msg
"noob" from /skript:msg

**Comment by mekb-turtle** [comment]
Hmm. This happens for me on 1.8.9

**Comment by untitledgeese** [comment]
> Hmm. This happens for me on 1.8.9 and not 1.16.3 or 1.16.4

i'll check it out tmr

**Comment by BennyDoesStuff** [comment]
Cannot reproduce
