### ISSUE TITLE
Blocking /join <server> (Read more)

### ISSUE THREAD

**Issue by ReportCardsMC** [Minehut/Meta#374]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-Game (Both)

**Describe the feature**

Before starting on the feature, I know this has been talked about already and people have said that it'd be a bad idea due to people helping others, but this idea might help out with a ton of ads in chat.

This feature is a way of blocking some server advertisements with `/join <server>` or `<server>.minehut.gg`... What could happen is the filter can detect when a message contains `/join or x.minehut.gg`, and after receiving that message it can check the API for the server stated so in the case of `/join <server>` it'll just check the word after /join, and in the case of `x.minehut.gg` it'll check the name of the server from the subdomain. And with the API check it can just check if the server is online, as some helpers will use `/join server`, and usually that server wouldn't be started anyway. 

**How the feature is useful**

This is useful because it will help with spammers (Most people that just advertise anyway spam), it will help with people bypassing the cool-down, and so on.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
maybe we could have an ingame tag system instead, so a player would type `!join` and it will send a message as themselves to join the server. you would also write a name at the end as well (we could use tags for other stuff besides this)

**Comment by Sniped** [comment]
I'm not exactly sure where you're coming at with this idea, do you just mean outright blocking a message such as `Do /join <server> for coolness points` or `Join amazingserver.minehut.gg for free beans`? If so, couldn't that simply just be done with CommunitySift? Why would fetching the API come into play here?

> maybe we could have an ingame tag system instead, so a player would type !join and it will send a message as themselves to join the server. you would also write a name at the end as well (we could use tags for other stuff besides this)

What is *the* server, is it their server? How would Minehut know who owns what server if that's the case? Why not just use /ad instead of just typing `!join myserver`?

**Comment by ReportCardsMC** [comment]
> I'm not exactly sure where you're coming at with this idea, do you just mean outright blocking a message such as Do /join <server> for coolness points or Join amazingserver.minehut.gg for free beans? If so, couldn't that simply just be done with CommunitySift? Why would fetching the API come into play here?
To verify the server is a valid one and someone isn't trying to help some eg:
Helping someone: `To join your server do /join server`
Advertising: `<!> /join server <!> Free Money OWO`

**Comment by LukasmanMHdude** [comment]
> I'm not exactly sure where you're coming at with this idea, do you just mean outright blocking a message such as `Do /join <server> for coolness points` or `Join amazingserver.minehut.gg for free beans`? If so, couldn't that simply just be done with CommunitySift? Why would fetching the API come into play here?
> 
> > maybe we could have an ingame tag system instead, so a player would type !join and it will send a message as themselves to join the server. you would also write a name at the end as well (we could use tags for other stuff besides this)
> 
> What is _the_ server, is it their server? How would Minehut know who owns what server if that's the case? Why not just use /ad instead of just typing `!join myserver`?

`!join` would be the thing, no server in the command. It would be like on discord where you can use `!bedrock` and it says how to connect. it would just be tags but ingame

---

we aren't trying to use /ad, this is meant to help people learn how to join their server

**Comment by Sniped** [comment]
> we aren't trying to use /ad, this is meant to help people learn how to join their server

Ah okay, I understand the idea now, at first I thought this was to block things from the /ad command. Though, how often would a tag system like this be used, and how practical would a tag system like this be in-game? I think something like including holograms giving a player commonly asked questions and the answers to them would be more effective. Looking at tracc on Minehut Staff and querying "how to join server" yields 9,000 results of players asking how to join their server. We could look into most commonly asked questions such as these and answer them with these holograms and then direct them to look at the official FAQ page if their question isn't answered.

How effective might checking the API be to block a message with `/join <server name>` in it though? What if the player's server has already been started and they're trying to figure out how to join it? Would the message be blocked at that point as a false positive? What if someone does start up the server with the name `server` in it? It would be quite tedious if that did happen and then helpers couldn't direct people to their server with `/join server`.

**Comment by ReportCardsMC** [comment]
> helpers couldn't direct people to their server with /join server.

Helpers could be exempt from the advertisement filter, and most put `/join <server>` to help someone anyways

**Comment by Sniped** [comment]
> Helpers could be exempt from the advertisement filter

This makes it so only staff members can tell people how to join their server guaranteed, what if a player wanted to answer the question but used `/join server` instead of `/join <server>`? There's various formats people can tell people how to join their server, and while they would be allowed. 

Someone could also just say `Please join x, it's about to come out of hibernation!` or something along those lines where they don't have to have their server online and still bypass this. I do believe that this would get rid quite a lot of the spam that currently goes on in the Minehut lobbies, however it would also have some false positives and false negatives.

**Comment by ReportCardsMC** [comment]
The filter would be more of a "hard" filter, it's okay if some people bypass it but if someone were to trigger the filter it could tell you how to use /ad, and if you bypass it and a staff online, you just get hit with a mute.

And some helping can be done but with the whole `/join server` argument, it's unlikely it's always gonna be up, or maybe since that server is unlikely to be used we could just make that server and `servername` exempt from the filter

**Comment by CoolProgrammerX** [comment]
I agree with this, a lot. How about exempting keywords such as server, <server>, and similar? Apart from that, just like you said, checking with the API weather or not a server actually exists or is online, and then blocking it if exists. This sounds quite interesting and easy to make, however new problems might take birth during the making of this. Good luck!
