### ISSUE TITLE
/ad request

### ISSUE THREAD

**Issue by Videocard2** [Minehut/Meta#379]
Hello, Minehut

I have a suggestion about the /ad

There`s been issues people that does not know about the /ad and just keep spamming without doing /ad I`ve know a idea for these people If we just join minehut and u look at the chat it says use /ad to advertise a server if that is possible to do for making it easier for people not forgetting about the /ad new feature so people only use /ad and would be great for staff not saying everytime use /ad please

Greatings from: Videocard

**Comment by LukasmanMHdude** [comment]
lmao learn how to use ' instead of \`
also, ppl have tried to get /ad blocked also, pls follow the format.

**Comment by Sniped** [comment]
> lmao learn how to use ' instead of \`
> 
> also, ppl have tried to get /ad blocked also, pls follow the format.

Your title should also give a better description of what your suggestion includes rather than just "/ad request". In the future, please be nicer to people on this forum Lukas, as that criticism could've been delivered in a nicer way.
