### ISSUE TITLE
Stop supporting bedrock

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#380]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
bedrock

**Describe the feature**
stop supporting bedrock

**How the feature is useful**
bedrock on Minehut is extremely bugged, it doesn't work 99% of the time and barely gets any players because of this. Wait until everything actually works and then look into supporting bedrock again, the use of bedrock shouldn't be recommended to players at this point

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
People frequently request support for bedrock, a system that is buggy and doesn't work frequently. To be blunt this is wasting their time and the time of the users who try to help them with bedrock edition. As much as I love the idea of cross-play, it should not exist unless it is stable and working, which it isn't at the moment.

**Comment by drtshock** [comment]
What are some of the big issues with it? We aren't always on the latest version because it's tied to our bungee instances and we don't always want to boot our 10k java players to update for our 50 bedrock players. We'll get those separated soon.

Otherwise I'd be curious to hear what major challenges you see to see if we can tackle them rather than giving up.

**Comment by LukasmanMHdude** [comment]
Problem: No one uses it and its down have the time.

**Comment by MiginsMC** [comment]
I don't think no one using it is much of a problem, it's really the fact that it is almost always outdated (somehow :eyes:), I believe Trent has stated before that it require a little amount of hardware to run

**Comment by tarna** [comment]
For me, Bedrock works sometimes and doesn't others. One time I tried joining and it worked fine but I came back a few hours later and it kept saying could not connect to world. Sometimes it even pings the server but still doesn't connect. I've also seen other people with similar issues.

**Comment by LukasmanMHdude** [comment]
> I don't think no one using it is much of a problem, I believe Trent has stated before that it requires a little amount of hardware to run. The problem is really the fact that it is almost always outdated (I realise it's hard to update as stated above, but it was outdated for weeks when 1.16.40 (bedrock version) came out. Correct me if I'm wrong, but I don't think it has even updated yet, even though geyser has updated (not sure how long ago though)).

if it really had little to no hardware/time then we wouldn't be talking about this

**Comment by jellz** [comment]
> > I don't think no one using it is much of a problem, I believe Trent has stated before that it requires a little amount of hardware to run. The problem is really the fact that it is almost always outdated (I realise it's hard to update as stated above, but it was outdated for weeks when 1.16.40 (bedrock version) came out. Correct me if I'm wrong, but I don't think it has even updated yet, even though geyser has updated (not sure how long ago though)).
> 
> if it really had little to no hardware/time then we wouldn't be talking about this

We’re talking about officially providing support for Bedrock – the hardware cost of hosting the Geyser proxy is negligible. It’s also interesting to note that Bedrock support is not advertised at all on Minehut’s website, which suggests MH’s only partial confidence in the quality of cross play, because it would certainly be a good selling point if it worked well.

**Comment by Blocksnmore** [comment]
Mh could offer a seperate bungee server for bedrock edition, that would likely have the best of both worlds. I haven’t seen a bedrock player on ever since a few days after it being released. If there was a seperate bedrock exclusive network there might be more intrest

**Comment by jellz** [comment]
That would only bring less incentive for Bedrock players to join. It’s easier to convince someone to join a network with several thousand players than a network with <100, regardless of which platforms they’re using.

**Comment by Shlba** [comment]
> That would only bring less incentive for Bedrock players to join. It’s easier to convince someone to join a network with several thousand players than a network with <100, regardless of which platforms they’re using.

Currently as of writing this, there is a total of **12** people on minehut who are using the bedrock edition of minecraft, out of a **TOTAL** of **8771** players. Bedrock players are a very small minority of minehut, and more focus should be put towards the **8759** java edition users. Allowing cross-play via Geyser is merely a accessory in my eyes, and seeing how the recent issues with bedrock edition have only caused issues that have to be dealt with, further support for bedrock edition is comparable to flushing resources down the drain.

**Comment by jellz** [comment]
> > That would only bring less incentive for Bedrock players to join. It’s easier to convince someone to join a network with several thousand players than a network with <100, regardless of which platforms they’re using.
> 
> Currently as of writing this, there is a total of **12** people on minehut who are using the bedrock edition of minecraft, out of a **TOTAL** of **8771** players. Bedrock players are a very small minority of minehut, and more focus should be put towards the **8759** java edition users. Allowing cross-play via Geyser is merely a accessory in my eyes, and seeing how the recent issues with bedrock edition have only caused issues that have to be dealt with, further support for bedrock edition is comparable to flushing resources down the drain.

I’m not sure how that’s relevant to my comment that you quoted.

**Comment by Shlba** [comment]
> I’m not sure how that’s relevant to my comment that you quoted.

There isn't much incentive to join using a bedrock edition client which is shown by the low number of actual people playing minehut on bedrock edition

**Comment by jellz** [comment]
> > I’m not sure how that’s relevant to my comment that you quoted.
> 
> There isn't much incentive to join using a bedrock edition client which is shown by the low number of actual people playing minehut on bedrock edition

Yeah, but do you think there would be more incentive if Bedrock players were separated from Java? And it was a separate network?

**Comment by PlainApple** [comment]
> For me, Bedrock works sometimes and doesn't others. One time I tried joining and it worked fine but I came back a few hours later and it kept saying could not connect to world. Sometimes it even pings the server but still doesn't connect. I've also seen other people with similar issues.

I have also tried connecting to Minehut on Bedrock various times, but majority of the time there is a connection issue. Obviously, yes, there have been occasions where it has worked, but it has been quite laggy, but that just might be my internet playing up. Apologies if this was unhelpful at the least.

**Comment by AdxmGG** [comment]
I just think they need to update with new versions of Geyser more frequently *(as Geyser themselves are constantly pushing new updates for bug fixes)*, and also make sure that it works 100% of the time. Then they can advertise as supporting Bedrock clients more as Daniel said. I don't believe the solution is just removing bedrock support.

**Comment by MiginsMC** [comment]
> I just think they need to update with new versions of Geyser more frequently _(as Geyser themselves are constantly pushing new updates for bug fixes)_, and also make sure that it works 100% of the time. Then they can advertise as supporting Bedrock clients more as Daniel said. I don't believe the solution is just removing bedrock support.

I do agree, but I think until Minehut can get a hold on what they're doing with bedrock, it should be temporarily removed (i.e wait until they are 'separated' as Trent said). When they're able to update geyser quickly and with ease, bedrock support may come back and hopefully, the bedrock player count will increase as well as geyser's reliability. 

I'm not sure how long doing what I've stated above will take so it might not necessarily need to be removed, but I think something needs to happen.

**Comment by PlainApple** [comment]
> > I just think they need to update with new versions of Geyser more frequently _(as Geyser themselves are constantly pushing new updates for bug fixes)_, and also make sure that it works 100% of the time. Then they can advertise as supporting Bedrock clients more as Daniel said. I don't believe the solution is just removing bedrock support.
> 
> I do agree, but I think until Minehut can get a hold on what they're doing with bedrock, it should be temporarily removed (i.e wait until they are 'separated' as Trent said). When they're able to update geyser quickly and with ease, bedrock support may come back and hopefully, the bedrock player count will increase as well as geyser's reliability.
> 
> I'm not sure how long doing what I've stated above will take so it might not necessarily need to be removed, but I think something needs to happen.

I do agree with the fact that bedrock support shouldn’t be eliminated completely, but I also agree with the fact that Minehut should get a better idea of how they’ll deal with constant updates to Geyser and stuff like that. When the issue has been dealt with, I think that Bedrock would be a great addition to Minehut, as it obviously allows friends to play together regardless of the platform they use. Although, as stated by MiginsMC, Bedrock usage may be more popular due to the system actually working.

**Comment by DaRealMinecraftexpert** [comment]
I kind of like having a Bedrock Alt on my Server to help with Certain Moderation things.

**Comment by ahoulton** [comment]
If you know what you are doing, you can self-host a [Geyster](https://geysermc.org/) proxy allowing you to login to any Java server with a Java account.

On another note, the Bedrock community of Minehut is very small and the Bedrock proxy for Minehut does not get updated as much as it should, as I'm writing this, the Bedrock proxy only has 12 players online out of the around 10k Java players that Minehut gets during peak times, if Bedrock was updated and maintained, maybe more people would use it.

**Comment by muelr** [comment]
I quite like being able to connect through Bedrock especially as a staff member. There have been multiple times when I wasn't at my laptop and could easily go in on my phone, when Bedrock is working, and mute the person causing trouble then leave again. Even if it doesn't work at times, there's no harm having it be an option, at least from my POV.

**Comment by Blocksnmore** [comment]
I personally see both sides of this but i feel until geyser on minehut is at a stable and working point bedrock should be removed

**Comment by jellz** [comment]
> Even if it doesn't work at times, there's no harm having it be an option, at least from my POV.

There is harm in being expected to provide support for it. It’s very unreliable.

**Comment by drtshock** [comment]
Closing since we are not going to stop supporting bedrock.
