### ISSUE TITLE
mh unlimited for free pog?

### ISSUE THREAD

**Issue by aroze123** [Minehut/Meta#382]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Both

**Describe the bug**
My server is stuck on one more player than actually online. So if there's 0 players, it would still show as one being online and the server would just stay up forever.

If I log on, it would show 2 total players in the server list and 2 on the panel, only me in tab though. /playerlist would show me twice. When nobody is on, it would show as one player on the server list and panel, can't tell about in-game.

Will reply to any staff who would like more info. Alternatively, you could dm me, Aroze#0001. 

**To reproduce**
I have no idea. It just happened and I recently realised. I tried doing everything I thought it might be, didn't work.
Staff told me to write a bug report here anyways though so, 

**Expected behaviour**
Show the correct player count and not give me a 24/7 server for free.

**Device Information**

- Minecraft client (and version): Any,
- Web browser (and version): n/a
- Operating system (and version): Doesn't matter,
- Minehut server name: Oitq

**Screenshots**
![image](https://user-images.githubusercontent.com/68871455/99153750-8f8ef400-26a2-11eb-816d-020da198f5d3.png)
![image](https://user-images.githubusercontent.com/68871455/99153755-96b60200-26a2-11eb-8815-ca7541ac5369.png)
![image](https://user-images.githubusercontent.com/68871455/99153759-a3d2f100-26a2-11eb-8011-a7d3ade30f7f.png)
![image](https://user-images.githubusercontent.com/68871455/99153775-ac2b2c00-26a2-11eb-953b-7117ee229476.png)

After logging off:
![image](https://user-images.githubusercontent.com/68871455/99153804-bb11de80-26a2-11eb-9e2c-1105a227e75f.png)
![image](https://user-images.githubusercontent.com/68871455/99153810-c5cc7380-26a2-11eb-83f8-d86b4659b784.png)
![image](https://user-images.githubusercontent.com/68871455/99153818-cd8c1800-26a2-11eb-9ba9-efe815b0f516.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
bro, this is the wrong place. https://getmhunlimitedfree.pog

**Comment by LukasmanMHdude** [comment]
I'm also assuming that this is probably a skript glitch, do you have vanish scripts or smth that parse people as offline? (I think its skript probs in general

**Comment by aroze123** [comment]
> I'm also assuming that this is probably a skript glitch, do you have vanish scripts or smth that parse people as offline? (I think its skript probs in general

Nope, the closest thing I have is a skript that kicks you on join for a nicer looking whitelist thing. Already tried experimenting with that and it's not the issue as far as I could see,

**Comment by LukasmanMHdude** [comment]
Can anyone reproduce this?

**Comment by aroze123** [comment]
Seems to be fixed now so closing,

**Comment by LukasmanMHdude** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by aroze123** [comment]
:(((((
