### ISSUE TITLE
Convert log files into a pastebin post on the discord.

### ISSUE THREAD

**Issue by AdxmGG** [Minehut/Meta#384]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
DISCORD

**Describe the feature**

I often see people send in their logs as a `message.txt` file when using #support, and this is just a hassle for everybody especially when the user helping is on mobile as they have to download the file, and figure out a way to view it. 

My suggestion is that the Minehut Bot detects when a log file is sent and automatically creates a pastebin post and sends it to the channel. Pastebin itself has an easy to use and well documented API so it shouldn't be too hard to make.

This would be implemented in the #support channel, however could work in #skript & #code.

The GeyserMC discord has this feature and I've seen first hand just how helpful it can be. 
![Screenshot_20201115-193938_Discord](https://user-images.githubusercontent.com/40618525/99195082-7443e780-277b-11eb-90e6-be6ec2dee26b.jpg)

**How the feature is useful**

#### This is super handy for anybody trying to help another player by viewing their logs easily and effortlessly.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
Maybe we could have a configuration option so it only converts in specific channels. This way, message.txt attachments in channels other than support don't get converted since we can assume that they aren't support related.

**Comment by LukasmanMHdude** [comment]
I could see this maybe being a command

**Comment by Sniped** [comment]
> I could see this maybe being a command

I thought about that possibility, however I think it would be an inconvenience to users as if they wanted to attach it in a message, they couldn't do so as they would have to execute the command.

**Comment by AdxmGG** [comment]
> Maybe we could have a configuration option so it only converts in specific channels. This way, message.txt attachments in channels other than support don't get converted since we can assume that they aren't support related.

Yeah, I meant it only be in #support, sorry for the confusion.

**Comment by LukasmanMHdude** [comment]
would be nice in #skript and #code as well

**Comment by AdxmGG** [comment]
> would be nice in #skript and #code as well

added, feel free to upvote now smh

**Comment by AdxmGG** [comment]
Woah! Awesome.
