### ISSUE TITLE
World generation bug

### ISSUE THREAD

**Issue by JackTMR** [Minehut/Meta#386]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Website

**Describe the bug**
Basically, the bug causes the server to refuse to start and continously crashes into the 'offline' state.
I think the bug might be a Spigot bug, but I'm not sure, AND you can reproduce it whilst trying to generate a world on singleplayer but I put it here anyways just in case.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the Minehut website
2. Go to the 'Settings' panel
3. Set 'Level Type' to 'Flat'
4. Set 'Generator Settings' to a valid generator setting
5. Restart the server
6. See error (server refuses to go online, logs show [this](https://pastebin.com/UzPxTAPD))

**Expected behaviour**
Server starts and the world generator creates the world

**Device Information**
- Minecraft client (and version): Fabric 1.16.4
- Web browser (and version): Microsoft Edge (Chromium) 86.0.622.69
- Operating system (and version): Windows 10 2020H2
- Minehut server name: N/A
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by ahoulton** [comment]
Nah, I dont think it's a world issue, it's a JSON issue.

**Comment by AdxmGG** [comment]
Try this;
> JSON Read Error
This error is normally caused by a corrupted json file. Do the following

1️⃣ Delete `ops.json`, `whitelist.json`, `banned-ips.json`, `usercache.json` and `banned-players.json`. Make sure to **delete the whole file** and not just the content of them.
2️⃣ Restart your server.
3️⃣ You may need to re-op, re-whitelist, or re-ban users.

**Comment by iGalaxyYT** [comment]
> Try this;
> 
> > JSON Read Error
> > This error is normally caused by a corrupted json file. Do the following
> 
> 1️⃣ Delete `ops.json`, `whitelist.json`, `banned-ips.json`, `usercache.json` and `banned-players.json`. Make sure to **delete the whole file** and not just the content of them.
> 2️⃣ Restart your server.
> 3️⃣ You may need to re-op, re-whitelist, or re-ban users.

This isn't related to the issue at all. It's an issue with the superflat generator settings, and it's not something that Minehut can fix. Here's the bug on [Jira](https://bugs.mojang.com/browse/MC-135383?jql=labels%20%3D%20generator-settings)

**Comment by AdxmGG** [comment]
> > Try this;
> > > JSON Read Error
> > > This error is normally caused by a corrupted json file. Do the following
> > 
> > 
> > 1️⃣ Delete `ops.json`, `whitelist.json`, `banned-ips.json`, `usercache.json` and `banned-players.json`. Make sure to **delete the whole file** and not just the content of them.
> > 2️⃣ Restart your server.
> > 3️⃣ You may need to re-op, re-whitelist, or re-ban users.
> 
> This isn't related to the issue at all. It's an issue with the superflat generator settings, and it's not something that Minehut can fix. Here's the bug on [Jira](https://bugs.mojang.com/browse/MC-135383?jql=labels%20%3D%20generator-settings)

my bad L

**Comment by Sniped** [comment]
Since the bug seems to originate from Minecraft itself, I'm going to close this as **wontfix**
