### ISSUE TITLE
Minehut video skipping

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#387]
### Bug report

**Checklist**
- [Oui] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [tak] I am NOT reporting a security vulnerability
- [si] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [yes] This issue does not contain any sensitive information

**Platform**
Website

**Describe the bug**
You can skip the video on the mh dashboard (current on dev)

**To reproduce**
Go to the mh advertisement and skip ahead

**Expected behaviour**
It either doesn't skip ahead or won't give the credits

**Screenshots**
https://blocksnmore.is-inside.me/wgFnkNPw.gif

**Additional context**
Nope

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by mekb-turtle** [comment]
Can confirm on Google Chrome Version 87.0.4280.66 (Official Build) (64-bit) - Windows 8.1 64x bit

**Comment by drtshock** [comment]
This was fixed for the promotion.
