### ISSUE TITLE
Use the Vanity Discord URL

### ISSUE THREAD

**Issue by TrueReassembly** [Minehut/Meta#390]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In game

**Describe the feature**

Use the vanity discord URL for the join message
![image](https://user-images.githubusercontent.com/62158683/99905882-a0a3ba80-2ccb-11eb-91b1-3cf74dbb410d.png)

**How the feature is useful**

It makes the server look more professional and would make it uniform with the rest of the links
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by mekb-turtle** [comment]
:+1: Same for the link in the /discord command

**Comment by mekb-turtle** [comment]
And the `https://` is just for the Discord and not the youtube or twitter
