### ISSUE TITLE
Change /msg and /staffchat

### ISSUE THREAD

**Issue by not-3than** [Minehut/Meta#391]
**Platform**

Java

**Describe the feature**

I'm suggesting that Minehut change the /msg and /staffchat commands to something like /mhmsg or /mhstaffchat so that servers can use their own /msg and /staffchat systems, and not have to find a way around it. When trying to set up my /staffchat at first, I was extremely confused when it said I didn't have permission, and it took me quite a while to figure out it was Minehut that was messing with it. This also applies to the many aliases for /msg.

**How the feature is useful**

It will benefit all server owners and admins, so they can implement their own messaging system and staffchat system more easily.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
This just makes it inconvenient for people who want to message others on the network to do so. It also makes it inconvenient for staff members to have to type in `/mhstaffchat`. You should be able to use something like `/sc`, why aren't you able to use that?

**Comment by Blocksnmore** [comment]
I don't see a reason in not using minehut's /msg and also I belive the staffchat is /s since that returns "no permission" while /staffchat works (if you have it being used by a plugin or skript)

**Comment by not-3than** [comment]
I do use /sc, but when mods can't use /staffchat then come to me and complain about it, it gets just a bit more annoying. I'm fine with them only changing the staffchat, because minehut's messaging system comes in handy, but it would be nice if basic commands weren't overruled by minehut.

**Comment by mekb-turtle** [comment]
I say we keep /msg as is. Maybe keep staffchat but only use Minehut's staff chat if the player using the command has permission (e.g is a helper or mod)

**Comment by RichieNy** [comment]
I believe that we should keep both commands (`/msg` and `/s`) because it makes the staff's job a lot easier if we need to communicate with each other in different player servers.

**Comment by Blocksnmore** [comment]
> I believe that we should keep both commands (`/msg` and `/s`) because it makes the staff's job a lot easier if we need to communicate with each other in different player servers.

Those arent really the issue, OP was complaining about /staffchat being blocked as some of his staff try to use it

**Comment by not-3than** [comment]
I mainly would like /staffchat changed, but /msg and /s can remain.

**Comment by MiginsMC** [comment]
I can see how `/staffchat` can be intrusive on player servers. I feel like most staff use `/s` anyways so if `/staffchat` was removed I reckon we could live with it.

**Comment by not-3than** [comment]
Most staff do use `/s`, so it would be nice if they could just remove `/staffchat`.

**Comment by mekb-turtle** [comment]
I'm used to /s (on another non mh server) so it'd be cool to remove /s or just make it go through if you aren't staff

**Comment by BennyDoesStuff** [comment]
/s or /staffchat is now a command that only exists for Minehut staff members. Meaning if you are not a staff member, you will be able to create your own staff chat command and use it normally.
