### ISSUE TITLE
discord rules

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#392]
### Feature request

**Checklist**
- [ya] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [yup] This is not a bug report, support request or plugin request
- [ mhm] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [yes] This issue does not contain any sensitive information 

**Platform**
discord & maybe forums

**Describe the feature**
Get rid of or add the rule "- English only in chat, please." to the forum rules/official rules

**How the feature is useful**
99% of the players aren't aware that this rule exists, I'm sure a lot of staff don't either because I've never seen it be enforced by anyone, it's not on the official rules either. So either get rid of the rule (which imo is kinda a dumb rule with a community of people all over the world) or add it to the official rules and tell staff to actively enforce said rule

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
Its actually allowed to use other languages acc to the staff when I made the suggestion to whitelist English only characters.

**Comment by PundaChen** [comment]
> Its actually allowed to use other languages acc to the staff when I made the suggestion to whitelist English only characters.

The discord rules state otherwise

**Comment by Sniped** [comment]
I can't find this rule on the rules channel on Discord nor can I find it on the official Minehut rules page. Can you point me to where it is in case I've missed somewhere?

**Comment by PundaChen** [comment]
Seems like they got rid of the rule, will close.
