### ISSUE TITLE
Logging into forums redirects to dashboard

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#393]
### Bug report

**Checklist**
- [let this = true;] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [Boolean this = true;] I am NOT reporting a security vulnerability
- [set this to true] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [this = true] This issue does not contain any sensitive information

**Platform**

Website
**Describe the bug**

MH login to forums redirects to dashboard
**To reproduce**
Steps to reproduce the behaviour:
Make sure you are logged out of the forums. Press log in. Log into your account. You will be redirected to the dashboard instead of the forums

**Expected behaviour**

Redirect to forums
**Device Information**
- Web browser (and version): Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Operating system (and version): Windows 10

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by PundaChen** [comment]
#155

**Comment by Blocksnmore** [comment]
Oop my bad.
