### ISSUE TITLE
Web interface update?

### ISSUE THREAD

**Issue by CoolProgrammerX** [Minehut/Meta#395]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

• A better online file editor with syntax highlighting for files which can be edited. Few of these are: YAML, JSON, Skript (custom syntax highlighting, which can be made by taking examples from extensions for Skript VS-Code), etc.
• Having quick shortcut keys to edit and modify stuff in a file. This can be, pressing CMD+S or Ctrl+S to quickly save the file.
• Tabs being calculated into space automatically (e.g. 1 tab = 4 spaces)
• CMD/Ctrl+F and CMD/Ctrl+R to find-replace things in a file, auto indentation. 
• Font best suit for code editor, where each character has equal width.
• Pretty much basic stuff provided by a simple code editor.

Oh forgot to say, you should try Pterodactyl's web-editor interface! (Pterodactyl is a hosting solution, like Multicraft but free and better in many ways)

**How the feature is useful**

• Would save a lot of time while editing files, instead of having a plain editor where someone would have to use 2/4/6 spaces every single time while editing a skript.
• Eye appealing interface, which motivates and provides comfort while editing/making skripts/files.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by honkling** [comment]
Panel also isn't very mobile friendly. Would be nice if it could be updated to include support for mobile too, and the fact that it's so slow performance wise is also a bit of an issue.

**Comment by CoolProgrammerX** [comment]
> Panel also isn't very mobile friendly. Would be nice if it could be updated to include support for mobile too, and the fact that it's so slow performance wise is also a bit of an issue.
> 
> EDIT: I think there should be a setting to disable turning tabs into 4 spaces automatically. Many people like myself hate using spaces and much prefer tabs.

True, for some browsers, tabs are automatically converted to spaces, and in some browsers, they remain as "tabs" which is quite irritating.
I'd love if they would make a code editor like Pterodactyl panel, simple, clean and easy to use, with no problems.

**Comment by BennyDoesStuff** [comment]
Implemented in the recent file manager update.
