### ISSUE TITLE
Server crashed; went offline; and had a rollback.

### ISSUE THREAD

**Issue by deathsou** [Minehut/Meta#396]
**Checklist**
- [ yes] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ yes] I am NOT reporting a security vulnerability
- [ yes] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ yes] This issue does not contain any sensitive information

**Platform**
In-game; Java

**Describe the bug**
A server I manage/develop, Void15, had about 5-6 people on, and then they were all kicked, with a message saying that the server had gone down. There was no reason why this happened, no one was making a lag machine, the tps was at 20, and there was **no** crash report. Since we can't read old logs (thank you minehut!) I can't really see why it crashed, because the "latest log" file was not reachable until i force hibernated, repaired files and restarted the server. And: surprise surprise: 30 minute rollback. Super fun! 👍  Also: server was marked as "online" and having 5 people on, long after it crashed.
Just to clarify: this issue was very common when all the rollbacks were happening on MH servers. It hasn't happened ever since the issue was "fixed". Maybe it's related to the recent changes?
**To reproduce**
Steps to reproduce the behaviour:
1. Go on Void15 console
2. Do nothing for 12-24 hours
3. Hopefully you'll see a rollback
4. Sleep because you don't get enough sleep
5. No i'm serious
6. Insomnia is a serious problem man 

**Expected behaviour**
End of the world

**Device Information**
- Minecraft client (and version): Sigma V-1.3 + Future clie- nah im jk i use 1.16.4 vanilla, i'm a good boy
- Web browser (and version): why does that matter- uhhh i use chrome ._.
- Operating system (and version): >_< u reaaaaally don't need to know this
- Minehut server name: Void15

**Screenshots**
I didn't take any screenshots ;-;

**Additional context**
Recent updates among minehut may have done stuff

**EDIT:**
We just had a 2nd crash + rollback. Will be transitioning to an external host until the issue is fixed; possibly permanently if the issue remains unfixed.
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes

**Comment by ahoulton** [comment]
I think that this is a Vanilla issue, meaning Minehut might not be able to fix this, can I ask what time this happened (with timezone)?

**Comment by deathsou** [comment]
> The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes. The crashes aren’t normal though.

I disagree. Normal crashes bring the server back 2-3 minutes (usually), and the server clearly goes offline. However in this case it remains "online" until going into hibernation. This is a Minehut issue.

**Comment by deathsou** [comment]
> I think that this is a Vanilla issue, meaning Minehut might not be able to fix this, can I ask what time this happened (with timezone)?

This happened today at 10:00 am and 10:21 am EST respectively.

**Comment by ahoulton** [comment]
> > The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes. The crashes aren’t normal though.
> 
> I disagree. Normal crashes bring the server back 2-3 minutes (usually), and the server clearly goes offline. However in this case it remains "online" until going into hibernation. This is a Minehut issue.

However, by default, the server **will** rollback, I don't see this as a Minehut issue until more evidence/cases are bought up.

**Comment by deathsou** [comment]
> > > The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes. The crashes aren’t normal though.
> > 
> > 
> > I disagree. Normal crashes bring the server back 2-3 minutes (usually), and the server clearly goes offline. However in this case it remains "online" until going into hibernation. This is a Minehut issue.
> 
> However, by default, the server **will** rollback, I don't see this as a Minehut issue until more evidence/cases are bought up.

I believe this is still a server using Minehut hosting, unless I'm mistaken. Why do you think the issue be ignored by admins/devs if 'not enough cases' have showed up? Exceptions happen; and I think that after the considerable amount of money put into server plans, we are entitled to a decent customer support and people who actually care about ongoing issues.
-Death Source

**Comment by ahoulton** [comment]
> 
> 
> > > > The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes. The crashes aren’t normal though.
> > > 
> > > 
> > > I disagree. Normal crashes bring the server back 2-3 minutes (usually), and the server clearly goes offline. However in this case it remains "online" until going into hibernation. This is a Minehut issue.
> > 
> > 
> > However, by default, the server **will** rollback, I don't see this as a Minehut issue until more evidence/cases are bought up.
> 
> I believe this is still a server using Minehut hosting, unless I'm mistaken. Why do you think the issue be ignored by admins/devs if 'not enough cases' have showed up? Exceptions happen; and I think that after the considerable amount of money put into server plans, we are entitled to a decent customer support and people who actually care about ongoing issues.
> -Death Source

That's not what I'm saying at all, the issue is this is not just a Minehut issue, it's happened with any server that crashes, however, some changes to the saving system was made **awhile** ago, but I don't think that this is the core problem here, I could think of many other things that might be broken, but I don't want to.

**Comment by deathsou** [comment]
> > > > > The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes. The crashes aren’t normal though.
> > > > 
> > > > 
> > > > I disagree. Normal crashes bring the server back 2-3 minutes (usually), and the server clearly goes offline. However in this case it remains "online" until going into hibernation. This is a Minehut issue.
> > > 
> > > 
> > > However, by default, the server **will** rollback, I don't see this as a Minehut issue until more evidence/cases are bought up.
> > 
> > 
> > I believe this is still a server using Minehut hosting, unless I'm mistaken. Why do you think the issue be ignored by admins/devs if 'not enough cases' have showed up? Exceptions happen; and I think that after the considerable amount of money put into server plans, we are entitled to a decent customer support and people who actually care about ongoing issues.
> > -Death Source
> 
> That's not what I'm saying at all, the issue is this is not just a Minehut issue, it's happened with any server that crashes, however, some changes to the saving system was made **awhile** ago, but I don't think that this is the core problem here, I could think of many other things that might be broken, but I don't want to.

Either way, it's a bug that can't be ignored and has made the server completely unplayable, crashing every 15 minutes or so. The reason it crashes; Minehut. We changed absolutely nothing in the past few days. also it crashes even when zero players are on...

**Comment by Blocksnmore** [comment]
> > > > > > The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes. The crashes aren’t normal though.
> > > > > 
> > > > > 
> > > > > I disagree. Normal crashes bring the server back 2-3 minutes (usually), and the server clearly goes offline. However in this case it remains "online" until going into hibernation. This is a Minehut issue.
> > > > 
> > > > 
> > > > However, by default, the server **will** rollback, I don't see this as a Minehut issue until more evidence/cases are bought up.
> > > 
> > > 
> > > I believe this is still a server using Minehut hosting, unless I'm mistaken. Why do you think the issue be ignored by admins/devs if 'not enough cases' have showed up? Exceptions happen; and I think that after the considerable amount of money put into server plans, we are entitled to a decent customer support and people who actually care about ongoing issues.
> > > -Death Source
> > 
> > 
> > That's not what I'm saying at all, the issue is this is not just a Minehut issue, it's happened with any server that crashes, however, some changes to the saving system was made **awhile** ago, but I don't think that this is the core problem here, I could think of many other things that might be broken, but I don't want to.
> 
> Either way, it's a bug that can't be ignored and has made the server completely unplayable, crashing every 15 minutes or so. The reason it crashes; Minehut. We changed absolutely nothing in the past few days. also it crashes even when zero players are on...

If it happens when nobody is on its likely a script that eats up all the ram. Try running the server with no scripts

**Comment by deathsou** [comment]
> > > > > > > The rollbacks arent anything that mh can fix. If a minecraft server crashes its restored to its last saved state. Which is typically around 5 ish minutes. The crashes aren’t normal though.
> > > > > > 
> > > > > > 
> > > > > > I disagree. Normal crashes bring the server back 2-3 minutes (usually), and the server clearly goes offline. However in this case it remains "online" until going into hibernation. This is a Minehut issue.
> > > > > 
> > > > > 
> > > > > However, by default, the server **will** rollback, I don't see this as a Minehut issue until more evidence/cases are bought up.
> > > > 
> > > > 
> > > > I believe this is still a server using Minehut hosting, unless I'm mistaken. Why do you think the issue be ignored by admins/devs if 'not enough cases' have showed up? Exceptions happen; and I think that after the considerable amount of money put into server plans, we are entitled to a decent customer support and people who actually care about ongoing issues.
> > > > -Death Source
> > > 
> > > 
> > > That's not what I'm saying at all, the issue is this is not just a Minehut issue, it's happened with any server that crashes, however, some changes to the saving system was made **awhile** ago, but I don't think that this is the core problem here, I could think of many other things that might be broken, but I don't want to.
> > 
> > 
> > Either way, it's a bug that can't be ignored and has made the server completely unplayable, crashing every 15 minutes or so. The reason it crashes; Minehut. We changed absolutely nothing in the past few days. also it crashes even when zero players are on...
> 
> If it happens when nobody is on its likely a script that eats up all the ram. Try running the server with no scripts

As I said, I haven't added or removed anything in the past days. Also, a script corrupting files, and stopping us from starting?? Maybe it's a plugin...

**Comment by Sniped** [comment]
> Go on Void15 console

People aren't able to log into your console and then observe changes this way. How will people be able to reproduce this issue that you're getting?

**Comment by deathsou** [comment]
> > Go on Void15 console
> 
> People aren't able to log into your console and then observe changes this way. How will people be able to reproduce this issue that you're getting?

It was sarcasm. I know there's no way to really reproduce it, since most people (including me on my other servers) aren't getting this issue. That's why i did the bug report, trying to find out how it happened and how to fix it. o_O

**Comment by Sniped** [comment]
Since there's no way to reproduce this bug it seems, I'm going to close this issue as invalid. Please edit with detailed steps to reproduce if you find the source of it and the best way to reproduce it and reply to this.

**Comment by deathsou** [comment]
> Since there's no way to reproduce this bug it seems, I'm going to close this issue as invalid. Please edit with detailed steps to reproduce if you find the source of it and the best way to reproduce it and reply to this.

So I can't submit bug reports??? Isn't that the whole point of "bug reports"?? Show issues that you don't know the reasoning to? I have submitted a support ticket (still unanswered!), and due to that, I request an admin or some qualified person on my case. I personally don't care what you think about me when reading this, I'm trying to get this issue fixed, and there are well over 30 hours of time spent into scripts on this server.

**Comment by DaRealMinecraftexpert** [comment]
You need to say what you did to cause the Error. That's what Reproducing the Bug means

**Comment by Sniped** [comment]
> So I can't submit bug reports??? Isn't that the whole point of "bug reports"?? Show issues that you don't know the reasoning to?

I'm not discouraging you from submitting bug reports, but the question is where to even start looking at a rollback issue in the first place. You're telling people to just go to your console and magically expect some sort of result when people can't even access your console in the first place and hope to expect a rollback. I understand that you don't know the cause of it, however if this is an exception in this specific server (which even you say doesn't occur on your other servers) then I believe it can be investigated further as a support ticket, as if it is a plugin or script on your server that's causing this, then it's not a bug on Minehut's end.

**Comment by LukasmanMHdude** [comment]
> So I can't submit bug reports??? Isn't that the whole point of "bug reports"??
 
lmao

**Comment by NanaMan04** [comment]
I’m having the same issue my server randomly crashes and rerolls. I’ve tried everything I can think of. Resetting main world and repairing files.

**Comment by deathsou** [comment]
I just want to say this is some of the worst customer support ever. We lost an entire server which had an MH75 server, it was completely wiped after one of the rollbacks, and the backup made a 2 weeks ago just loads endlessly without actually being able to restore the server. I'm not asking you, as a moderator, helper, or whatever, to do anything, but instead an admin or dev to at least try to restore the server. As you can see i'm not the only one.

**Comment by Baezor1** [comment]
> I just want to say this is some of the worst customer support ever. We lost an entire server which had an MH75 server, it was completely wiped after one of the rollbacks, and the backup made a 2 weeks ago just loads endlessly without actually being able to restore the server. I'm not asking you, as a moderator, helper, or whatever, to do anything, but instead an admin or dev to at least try to restore the server. As you can see i'm not the only one.

I personally think that the issues you're having are your fault. Most servers obviously don't crash and rollback like yours. Blaming Minehut for issues with your specific server is kind of dumb. I would recommend looking into the issue yourself. Try to fix the issue. If you identify a problem with Minehut, make a valid bug report on the issue that people can test and try to fix.

**Comment by deathsou** [comment]
> > I just want to say this is some of the worst customer support ever. We lost an entire server which had an MH75 server, it was completely wiped after one of the rollbacks, and the backup made a 2 weeks ago just loads endlessly without actually being able to restore the server. I'm not asking you, as a moderator, helper, or whatever, to do anything, but instead an admin or dev to at least try to restore the server. As you can see i'm not the only one.
> 
> I personally think that the issues you're having are your fault. Most servers obviously don't crash and rollback like yours. Blaming Minehut for issues with your specific server is kind of dumb. I would recommend looking into the issue yourself. Try to fix the issue. If you identify a problem with Minehut, make a valid bug report on the issue that people can test and try to fix.

I've talked to over 6 people (which I can name! and there are more than that) who have the same issues, some on servers just as large as mine. After the server was wiped the issue stopped. Once again, I stress the fact that the **server was wiped**. Devs, do something.
