### ISSUE TITLE
account losing info ingame

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#398]
### Bug report

**Checklist**
- [ye] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ya] I am NOT reporting a security vulnerability
- [yup] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [oui] This issue does not contain any sensitive information

**Platform**
ingame

**Describe the bug**
All the information of my account disappeared, friend list, favourite list and rank completely cleared. (with this, my account also shows up twice on everyone's friends list)

**To reproduce**
Idk man, theres no steps, all I know is this is the second time it's happened

**Expected behaviour**

**Device Information**
Minecraft java 1.16.4
 
**Screenshots**
https://i.imgur.com/PBiCNVL.png

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by PundaChen** [comment]
Gonna bump this and ask for a response, it's been a week and my account is still wiped, would be nice to know that devs are at least trying to figure out the issue

**Comment by AdxmGG** [comment]
?

**Comment by PundaChen** [comment]
It just got fixed

**Comment by drtshock** [comment]
In the future, please use https://minehut.com/support to report individual account issues.

Separately, this has been fixed as Panda noted.
