### ISSUE TITLE
mAkE WbeSitE gooD

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#399]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**
web

**Describe the feature**
read title

**How the feature is useful**
cause website is bad

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
why close that's sexist

**Comment by LukasmanMHdude** [comment]
![image](https://user-images.githubusercontent.com/69743171/100292645-e794e880-2f35-11eb-8861-7892b5d26f04.png)
