### ISSUE TITLE
Invisible search bar text while using dark mode on forums

### ISSUE THREAD

**Issue by residal** [Minehut/Meta#40]
### Bug report

**Checklist**
- 

- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 
Website

**Describe the bug**
 
While using dark mode on the forums, text entered in the search bar is not visible unless you hold left click on the text and highlight it.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the [forums](https://forums.minehut.com) and activate dark mode.
2. Navigate to the search bar in the top right.
3. Type anything within the search bar.
4. Highlight it using left click to see that the text is still there, but is just invisible unless highlighted.

**Expected behaviour**
 
Text should be automatically visible.

**Device Information**

Minecraft client (and version): N/A
Web browser (and version): Chrome Latest
Operating system (and version): N/A
Minehut server name: N/A

**Screenshots**

[Click](https://gyazo.com/fda19fa63ff9ecc7851e649bdc5078e1)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by jellz** [comment]
Can reproduce on Brave, confirmed bug

**Comment by recalibrated** [comment]
Can reproduce on Brave.

**Comment by drtshock** [comment]
Is this only on dark mode? Does it happen on light mode too? Or perhaps just an issue with our custom theme.

**Comment by jellz** [comment]
@drtshock Only on the custom dark theme

**Comment by BennyDoesStuff** [comment]
No longer an issue on the current dark theme.
