### ISSUE TITLE
/testfilter command

### ISSUE THREAD

**Issue by mekb-turtle** [Minehut/Meta#400]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

yes

**Describe the feature**

Add a command where people can test the filter to see if a message is blocked or not without it getting sent to chat on the dev server.
I know the dev server has features that will eventually get added to minehut or just for testing and not as a thing we'll use all the time. Maybe we could instead make a webpage to test if it's blocked or not. :shrug: 

**How the feature is useful**

Helps people in #filter-requests in the meta discord server know if phrases have been blocked or not without it getting sent to chat and them getting muted

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by RichieNy** [comment]
I wouldn't see a need for this becoming a command but, a possible discord channel/website with the filter/sift would be a cool idea to test the filter and risk being punished for breaking a rule.

**Comment by BennyDoesTheStuff** [comment]
I'm personally against this, allowing people to test the filter without getting punished will only make it easier for malicious users to be able to find loopholes in our filter and be able to take advantage of it.

**Comment by theminecoder** [comment]
This isn't something we are likely to expose on its own. Why not just jump into the dev server lobby and start chatting?

**Comment by mekb-turtle** [comment]
> This isn't something we are likely to expose on its own. Why not just jump into the dev server lobby and start chatting?

ahh, that'd be helpful
i completely forgot the dev server had a chat filter
