### ISSUE TITLE
Minehut commands requries OP

### ISSUE THREAD

**Issue by mekb-turtle** [Minehut/Meta#401]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

player servers

**Describe the feature**

minehut commands such as /dl /ul /world normally require op, i'm saying we make it so people can use permission plugins to control whether people can use this. i'm saying we use permission nodes like `minehut.world` `minehut.upload` `minehut.download`. ofcourse having op will still work (if the player doesn't have a permission plugin)

**How the feature is useful**

It's a pain having to op yourself, type the command, deop yourself if you don't want to be opped all the time

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
yeah seems good, not sure why this isn't already a thing.

**Comment by jellz** [comment]
Duplicate of #269

**Comment by mekb-turtle** [comment]
> Duplicate of #269

thanks, didn't see that
