### ISSUE TITLE
Releasing old lobbies

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#403]
**Platform**
Discord, in-game

**Describe the feature**
Release old lobby worlds that aren’t used anymore to the public 

**How the feature is useful**
Allows players to explore the lobbies and find out what they may have missed out on 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Shlba** [comment]
I~ mobile is weird, my apologies

**Comment by Sniped** [comment]
Do you propose that this should be done via discord?

**Comment by Shlba** [comment]
> Do you propose that this should be done via discord?

It can be, if there isn’t a better option. Personally I think a Dropbox link would be more than sufficient

**Comment by PundaChen** [comment]
> Do you propose that this should be done via discord?

Mh market

**Comment by drtshock** [comment]
Yeah we can do this on the market.

**Comment by honkling** [comment]
This would be epic.

**Comment by BennyDoesStuff** [comment]
Duplicate of #290
