### ISSUE TITLE
Permission to use geyser offhand 

### ISSUE THREAD

**Issue by ChampionAnt** [Minehut/Meta#404]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

**How the feature is useful**

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by a-cpu-a** [comment]
.. you forgot to check the boxes?

**Comment by PundaChen** [comment]
> .. you forgot to check the boxes?

He forgot to fill in anything on the format lol
