### ISSUE TITLE
Make Reset All button properly reset the server

### ISSUE THREAD

**Issue by honkling** [Minehut/Meta#407]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Instead of making the `Reset All` button only delete plugins, make it completely reset the server. Delete worlds, plugins, plugin configs, everything.

**How the feature is useful**
Often when resetting a server to transform it into something else, users have to manually delete plugin configurations, worlds, and lingering folders/files. Deleting everything in the server's root (except for the jar?) solves this problem, and makes for a much easier server reset.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by not-3than** [comment]
I personally think they should remove the reset button until they add multi-user support, because sharing a made up password and a spam email with someone is fine, but them having access to completely reset everything with just the push of a button is a bit extreme.
I feel it should be added after multi-users has been added, and at that point it can be implemented to serve its proper function.

**Comment by honkling** [comment]
> I personally think they should remove the reset button until they add multi-user support, because sharing a made up password and a spam email with someone is fine, but them having access to completely reset everything with just the push of a button is a bit extreme.
> I feel it should be added after multi-users has been added, and at that point it can be implemented to serve its proper function.

It's a bad practice to share an account anyways, and if you're sharing with people that are willing to reset your server without hesitation, you shouldn't be sharing your account with them in the first place, but I do suppose how they user couldn't have seen it coming if they were somebody they trusted prior.

**Comment by BennyDoesStuff** [comment]
This doesn't seem to be the current behavior but can reopen if you're still experiencing this issue.
