### ISSUE TITLE
Change the /discord tooltip to 50k instead of 10

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#410]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Server (Java/Bedrock)

**Describe the feature**

Change the tooltip for the /discord command to be 'Join over 50,000 users.'
![image](https://user-images.githubusercontent.com/58871819/101241635-9f4ea500-3743-11eb-9056-974defcfe495.png)

**How the feature is useful**

Isn't super useful, I guess it makes the discord look more appealing to join 🤷 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
I'm sure there's an API or some way to check how many users are in a guild, from there it could automatically update and then just round down to the nearest ten thousand.

**Comment by MiginsMC** [comment]
> I'm sure there's an API or some way to check how many users are in a guild, from there it could automatically update and then just round down to the nearest ten thousand.

Not sure how necessary it would be to have it use an API, you only really need to update this every like 20k users, which can be done manually tbh, but that's not a bad idea.

**Comment by LukasmanMHdude** [comment]
or just add a 0 and futureproof

**Comment by Sniped** [comment]
> or just add a 0 and futureproof

Instead of that why not just a `+` to indicate that there are more than x amount of members in the discord?

**Comment by LukasmanMHdude** [comment]
it already says "**over** 10,000 users" so

**Comment by BennyDoesStuff** [comment]
No longer an issue anymore as the /discord command was revamped.
