### ISSUE TITLE
More ways to earn credits.

### ISSUE THREAD

**Issue by xenitrogen** [Minehut/Meta#411]
**Platform**
Panel

**Describe the feature**
Recently we've seen "Click here to earn 50 minehut credits (enough for a server upgrade)" and I was just thinking about this - Potentially in the server panel there could be an advertisements section where minehut can present their own videos or advertisers videos & each video you watch you gain 10 - 20 credits.

**How the feature is useful**
This could help fund minehut (kinda) businesses could purchase adspace on the webpage & is a pretty good way of earning credits (for people who cant afford to purchase credits)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by boop-the-dog** [comment]
boop

**Comment by LukasmanMHdude** [comment]
Lukas

**Comment by LukasmanMHdude** [comment]
> Potentially in the server panel there could be an advertisements section where minehut can present their own videos or advertisers videos & each video you watch you gain 10 - 20 credits.

oh no its a crappy mobile game in a nuteshell

**Comment by honkling** [comment]
Voting and event awards seem fine, I don't really think we need more ways to get free credits.

**Comment by drtshock** [comment]
Definitely something we want to do, just need to find people to pay enough money for us to be able to justify giving out credits in exchange for watching the ad.

**Comment by BlurTehEpic** [comment]
n
