### ISSUE TITLE
let us download files as binary

### ISSUE THREAD

**Issue by mekb-turtle** [Minehut/Meta#413]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

dashboard / file manager

**Describe the feature**

let us download files as a binary file, maybe a button next to the file or maybe change the select files to delete, to select files and let us pick, delete selected files, download selected files, etc

**How the feature is useful**

we can download files such as .log.gz without needing to copy and paste and risk having it get messed up with null bytes, crlfs etc

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by ManagePasswords** [comment]
this would require checking for disallowed files so they cant be obtained in the binary which is hard to implement and would be buggy sometimes?

**Comment by mekb-turtle** [comment]
> this would require checking for disallowed files so they cant be obtained in the binary which is hard to implement and would be buggy sometimes?

check if most of bytes are ascii (32-255) and treat it as text
else treat it is binary

**Comment by BennyDoesStuff** [comment]
Downloading files is implemented as of the recent file manager update.
