### ISSUE TITLE
tab complete /msg

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#414]
### Feature request

**Checklist**
- I have read and agree to the README (found on https://github.com/Minehut/Meta)
- This is not a bug report, support request or plugin request
- I have searched the Issue Tracker to make sure this is not a duplicate issue
- This issue does not contain any sensitive information 

**Platform**
Ingame

**Describe the feature**
/msg should tab complete to the users on the current server

**How the feature is useful**
so we don't have to type someone's entire name out

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
it does, *sometimes*. Would be nice to have some consistency tho
