### ISSUE TITLE
Server Upvote

### ISSUE THREAD

**Issue by DaRealMinecraftexpert** [Minehut/Meta#418]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Either Ingame (Both) or on the Website.
**Describe the feature**

I can't remember if I asked about this before, but I have been wondering about if they were to add a Upvote or Downvote Server system. Upvotes could Push the server up on the Server list Ingame, or on the Website Server List. Another thing that may work, is Upvoting using a Star Rating System, Maybe Upvoting Ingame this way would show a Menu with 5 Nether Stars, which could be clicked on to set a Ranking. As well as the more regular way on the Website. (It could notify the Owner of the server in some way, but I feel like it might Annoy the owner if the Server is really popular. ) To start the Upvote ingame, Minehut could use a command like /upvote, /uv, or something related to that on the server they want to Upvote or Rate.
**How the feature is useful**

It could help Server Owners who want to have the ability to be higher up on the List for more players. It could also help players who want to find the More Popular or Recommended servers.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
This suggestion is very similar to https://github.com/Minehut/Meta/issues/352 in the way of bumping servers and voting for them, please comment additions to that issue there.
