### ISSUE TITLE
minehut credit timer feature idea

### ISSUE THREAD

**Issue by angrybird121** [Minehut/Meta#421]
add a "credit timer" for the monthly credit plan, that shows you how long until you need to pay again.
it would help a lot - ANGRY_BIRD121

**Comment by Blocksnmore** [comment]
👏 Follow 👏 the 👏 format

**Comment by angrybird121** [comment]
format? im new to github xd

**Comment by Blocksnmore** [comment]
Theres an issue template that shows up when you create the issue, fill it out instead of deleting it

**Comment by Sniped** [comment]
As @Blocksnmore said, please use the correct issue format when submitting an issue rather than creating your own. In this case, you can find the feature request template [here](https://github.com/Minehut/Meta/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=).
