### ISSUE TITLE
Bold colour code will not make motd bold in Minehut lobby 

### ISSUE THREAD

**Issue by TheRoyalAce** [Minehut/Meta#429]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Website and in Game

**Describe the bug**
When applying the &l colour code for example &d&l(word) it will not make the motd of the server bold. It will only show the bold colour code in the multilayer tab in Minecraft java but in the minehut lobby it will not show any of the bold text

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'minehut.com/dashboard/home'
2. Scroll down to 'edit motd in server panel'
3. Click 'click the motd text box to edit the message'
4. Type 'any colour and the bold colour code for example (&d&l)'
5. Click 'Click save button'
6. Go to 'Minecraft and look at the server in the Minehut lobby'
7. See error 

**Expected behaviour**
I expected a bold motd of my server in the Minehut lobby.

**Device Information**

- Minecraft client (and version): Java version 1.16.4 (latest release) 
- Web browser (and version): google chrome
- Operating system (and version): windows 64 bit
- Minehut server name: GalaxyGN (ip: GalaxyGN.minehut.gg)

**Screenshots**
![Minehut lobby MOTD](https://user-images.githubusercontent.com/71574286/101994208-a79c6800-3c8e-11eb-938d-aaca464ad359.png)
![Minehut motd](https://user-images.githubusercontent.com/71574286/101994211-ad924900-3c8e-11eb-9911-44efe39b4b26.PNG)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by CoreyShupe** [comment]
What about in a server list? I think we cut out formatting within MOTDs in game for specific reasons such as people putting a ton of formatting crap inside of MOTDs which make it a lot harder on the eyes. We could consider allowing specific color codes.

**Comment by MiginsMC** [comment]
I have suspected for some time that bold only works for servers with a plan, although I've been told this isn't true, I'm yet to see any evidence of this.

**Comment by CoreyShupe** [comment]
> 
> 
> I have suspected for some time that bold only works for servers with a plan, although I've been told this isn't true, I'm yet to see any evidence of this.

Do we have any evidence of the alternate where a specific server plan allows bold coloring? It's hard to prove a negative. I'd like to see cases where some server plans do have access and some don't. I could dig into the codebase but I don't think we do anything special like that.

**Comment by MiginsMC** [comment]
I've taken a quick look across the in-game server list and I haven't seen a single server with a 10 player limit use bold or any other format except for colours. It seems that servers with a 20 player limit or higher (with a server plan) are able to use format codes (&l, &n, &m, &o, &k).

![image](https://user-images.githubusercontent.com/58871819/102006898-4c42a680-3d70-11eb-9aca-24b5030ea3d6.png)

**Comment by TheRoyalAce** [comment]
Ok Thank you. I was planning on buying a server plan anyway,
