### ISSUE TITLE
Allow Moderators to Download Logs on ANY Server.

### ISSUE THREAD

**Issue by RichieNy** [Minehut/Meta#432]
### Feature Request -- Moderators DL Logs

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In-Game - Java/Bedrock

**Describe the feature**
Give moderators the permission to be able to download logs on any server without having to be operator. 

**How the feature is useful**
This feature can assist moderators in reports for server griefing and helping users with bugs.
I believe that this is possible because /dl is a minehut command. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
This could potentially pose privacy issues which I don't necessarily see us giving to moderators. I would love to hear from others like Trent on this issue. This could be something we give to managers but I don't see us giving this to moderators. Also, yes it's a minehut command but not a proxy command which makes it sort of different.

**Comment by not-3than** [comment]
I honestly don't think this is a good idea. It is a violation of privacy that I think users of Minehut services are entitled to.

**Comment by MiginsMC** [comment]
I can understand the privacy implications, but I think that there is sometimes a need for this (botting servers for example). However, I think this would be better in the hands of managers or even admins (if it isn't already possible) and even then there should be strict guidelines on how and when the data could be used. Also just a side note, you shouldn't be putting private information on a Minecraft server that you wouldn't want moderators seeing.

**Comment by ahoulton** [comment]
> 
> 
> I can understand the privacy implications, but I think that there is sometimes a need for this (botting servers for example). However, I think this would be better in the hands of managers or even admins (if it isn't already possible) and even then there should be strict guidelines on how and when the data could be used. Also just a side note, you shouldn't be putting private information on a Minecraft server that you wouldn't want moderators seeing.

Due to data protection laws, I would keep this administrators only, maybe allow moderators to request server logs with a valid reason and say in the TOS that _"Minehut moderators may request your server logs from administrators if they think that you or your server is breaking our rules."_

**Comment by Double0negative** [comment]
Unfortunately, as stated above, we cannot allow moderators to view or download server logs due to privacy concerns.
