### ISSUE TITLE
Make server logs read-only

### ISSUE THREAD

**Issue by jellz** [Minehut/Meta#433]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

The files in the `logs/` directory should not be editable by any means

**How the feature is useful**

Read-only logs would mean moderators can trust dl.minehut.com links (since they can only be created through the `/dl` command) and consider them a reliable and honest source of server logs (so they can be used as evidence as part of a griefing report, for example).

Currently, server logs can be modified and therefore are not considered valid evidence.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BlakeH2208** [comment]
This would serve no purpose as if your server was griefed or anything, nobody would try to hide it

**Comment by MiginsMC** [comment]
> This would serve no purpose as if your server was griefed or anything, nobody would try to hide it

What do you mean? Griefing is really difficult to punish people for since you cannot use any evidence taken from a player server, including their logs. The whole point of this feature is that server logs can be used as griefing evidence if they are read-only.

**Comment by DaRealMinecraftexpert** [comment]
Are we implying that TNT ignition is logged?

**Comment by Sniped** [comment]
> Are we implying that TNT ignition is logged?

That's not being implied at all, in fact, nothing's being implied really. However, moderators often download logs from people's servers to see if someone has executed commands that would indicate server griefing, such as `//sphere tnt 100` or something like this (I'm not sure of WorldEdit's syntax, so I'm not sure if that's right or not).

**Comment by DaRealMinecraftexpert** [comment]
Sometimes, Griefers don't use WorldEdit, and just spam down a ton of TNT Manually.

**Comment by Sniped** [comment]
> Sometimes, Griefers don't use WorldEdit, and just spam down a ton of TNT Manually.

The suggestion is that logs be read only to make them more credible in cases where they are considered valid. In the case of a griefer just spamming TNT manually and igniting it, logs wouldn't be acceptable either way, rather another form of evidence would be needed.

**Comment by BennyDoesStuff** [comment]
The /download command doesn't exist anymore so this issue does not apply.
