### ISSUE TITLE
CoolDown issue ( Feature )

### ISSUE THREAD

**Issue by TwieYT** [Minehut/Meta#434]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request, or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Java, Bedrock

**Describe the feature**
 I suggest that you on the MineHut Staff team make it easier to advertise their servers, So I suggest having a shorter cooldown on the /ad command because the way it is today is more longer I'm not saying it's not waitable but it takes some time and the people here on The MineHut pretty surely agrees with my suggestion here on Mine-hut, I suggest make it 1-3 Minutes as the cooldown here with the /ad command! Thanks ;)

**How the feature is useful**
 Because people want to get many players in short terms such as advertising for 10minutes and you get 30 players that are how I expect it to be, This feature benefits all the players that want to advertise here on Minehut!

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
If you want a shorter cooldown get a rank. One of the main reasons the cooldown is somewhat big is cause of bots

**Comment by ahoulton** [comment]
> 
> 
> If you want a shorter cooldown get a rank. One of the main reasons the cooldown is somewhat big is cause of bots

This is why /ad was added, **bots**, how are we meant to keep cooldown short while keeping bots in the picture.

**Comment by ballxishot** [comment]
It is already bad enough when mods have to keep saying use /ad but if we put your suggestion they will need to mute people and say "Stop Spamming".

**Comment by Duziest** [comment]
Feel free to buy a donator rank. It’s one of those perks to have shorter cool downs. 

In addition, it would be spammy, and harder to moderate if they gave defaults 1-3 minute cool downs. 

Keep in mind, an average of 500 users are always in the Minehut lobbies. Approximately 30-40 of them are there to advertise. The eight minute cool down ensures that they don’t spam and abuse /ad as a whole.

Have a good day!

**Comment by Double0negative** [comment]
Cooldown can be reduced by purchasing a rank. Current limitations are in place to reduce spam.
