### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by ballxishot** [Minehut/Meta#435]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Discord
**Describe the bug**

DISCORD BOT IS DOWN
**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'the discord server'
2. Click on the discord bot
3. See the bot is down

**Expected behaviour**

People will now be able to swear because there is no filter
**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by ballxishot** [comment]
This is very urgent people can abuse this by saying slurs and swear words. I've tested it and then deleted the messages.

**Comment by Sniped** [comment]
The bot is online again
