### ISSUE TITLE
/ignore doesn't work

### ISSUE THREAD

**Issue by BlakeH2208** [Minehut/Meta#436]
### Bug report

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

**Platform**
 Ingame both

**Describe the bug**
 When using /ignore on someone is still allows them to message you and you can still see it

**To reproduce**
Steps to reproduce the behaviour:
1. Use '/ignore player'
2. Have that player message you
3. See error

**Expected behaviour**
 It should not allow them to message you or send them a message saying "An error has occurred" to the player who the other player has ignored

**Device Information**

- Minecraft client (and version): 1.16.4 Java
- Web browser (and version): 
- Operating system (and version): Windows 10 64 bit
- Minehut server name: N/A

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by jellz** [comment]
You need to relog for the changes to take effect

**Comment by BlakeH2208** [comment]
Oh, ok thanks. Whats supposed to happen when the player who was ignored sends you a message?

**Comment by jellz** [comment]
I believe it looks like it went through on their end but the message is lost before it gets to you

**Comment by LukasmanMHdude** [comment]
can @Sniped lock this pls?
