### ISSUE TITLE
Default report option to be In-game

### ISSUE THREAD

**Issue by mekb-turtle** [Minehut/Meta#437]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

forums - https://forums.minehut.com/application/form/1-player-reports/

**Describe the feature**

The report type (Platform this occured on) should be In-game and not Discord by default 

**How the feature is useful**

Most reports I make (and probably in general) are in-game and not on the Discord or forums

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
it takes 2 seconds to change it, so I'm indifferent to this

**Comment by BennyDoesStuff** [comment]
Updated

**Comment by LukasmanMHdude** [comment]
> Updated

add done label?
