### ISSUE TITLE
Fake Buttons

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#44]
### Feature request

**Platform**
 Website

**Describe the feature**

Make it so hovering over values here doesn't change the background because it appears as a button.
![](https://cdn.discordapp.com/attachments/592130982451216402/710642773052883064/unknown.png)

**How the feature is useful**

This is useful because it doesn't mislead people.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment]
I think it's fairly obvious you aren't meant to click on them? If you click it and it doesn't do anything it's not a button.

**Comment by CoreyShupe** [comment]
Seems like a UI/UX nitpick. What do people think about removing the hover effect? Seems like a very small nitpick to worry about honestly.

**Comment by BennyDoesStuff** [comment]
Doesn't apply anymore, outdated issue
