### ISSUE TITLE
Lockdown Command for the bot

### ISSUE THREAD

**Issue by DaRealMinecraftexpert** [Minehut/Meta#440]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord
**Describe the feature**

The Minehut bot Desparately needs a Lockdown Command, especially during Outages
**How the feature is useful**

Help Admins not have to go through each channel individually to lock it because of someone spamming "My Server isn't starting" During an outage.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
I believe that this could be useful, however I don't believe that a lockdown command should lock every channel. Instead, I think we should configure a list of commonly locked channels during outages and be able to use a flag to lock those configured channels. I also think that there could be an optional arg to list additional channels to lock.

**Comment by DaRealMinecraftexpert** [comment]
Yeah, It doesn't have to be all, I only say all because when one channel gets locked, odds are they will go to an unlocked one to do it again.

**Comment by honkling** [comment]
Could just lock all channels (by default?) and then staff members could unlock channels manually.

**Comment by DaRealMinecraftexpert** [comment]
> Could just lock all channels (by default?) and then staff members could unlock channels manually.

Are you saying something about a Verification to Speak sort of thing?

**Comment by honkling** [comment]
> Are you saying something about a Verification to Speak sort of thing?

Well no, I was thinking:

!lockdown command is called
All channels are locked
#general should stay unlocked, staff have to unlock manually

Not like verification to speak, that's probably for another issue.

**Comment by MiginsMC** [comment]
By unlock manually, do you mean with an additional !unlock bot command?

**Comment by Sniped** [comment]
I believe that there could be the option to unlock the channels manually, but also have them locked for a set amount of time. This could be done by a flag. To unlock, there could just be a `!unlock` command that would be done within the channel to unlock it.

**Comment by honkling** [comment]
> By unlock manually, do you mean with an additional !unlock bot command?

I originally meant by just going into Channel Settings and allowing everybody to speak again but `!unlock` seems like a better and more reliable idea.

**Comment by MiginsMC** [comment]
> I believe that there could be the option to unlock the channels manually, but also have them locked for a set amount of time. This could be done by a flag. To unlock, there could just be a `!unlock` command that would be done within the channel to unlock it.

I think the command should have an argument for the channel (unlike !clean and !cooldown) or it could automatically delete (like clean) because I think it looks a bit unprofessional to have a mod use a cmd, the command could also have a reason argument which sends an embed or smth to every channel (depending on how its set up).

**Comment by DaRealMinecraftexpert** [comment]
Another Reason that I suggested this (I should probably edit the Main thing with this) is that I have seen a lot of servers have a bot with an Anti-Raid Function, while Minehut doesn't seem to have one at all.
