### ISSUE TITLE
AD message format

### ISSUE THREAD

**Issue by mekb-turtle** [Minehut/Meta#441]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

ingame

**Describe the feature**

change the AD format to look nicer
currently it looks like ![image](https://user-images.githubusercontent.com/48314599/102702463-2f99f780-42b7-11eb-83eb-502f901eee74.png) where there's no space between the `[AD]` and `[RANK] username`
what would look better is the colon is white not the rank color and there's a space between `[AD]` and the `[RANK] username` 
![image](https://user-images.githubusercontent.com/48314599/102702500-80a9eb80-42b7-11eb-9b9b-939f625265d6.png)

**How the feature is useful**

looks nicer

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
I think it's just a bug to be honest.

**Comment by MiginsMC** [comment]
Also the colour of the colon is the colour of the rank, which doesnt stick to the colour in chat.

**Comment by BennyDoesStuff** [comment]
This seems to have been fixed at some point.
