### ISSUE TITLE
Toggling Advertisements

### ISSUE THREAD

**Issue by Columner** [Minehut/Meta#442]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In-game

**Describe the feature**
Basically an option in the player head to maybe toggle advertisements.

**How the feature is useful**
Chat looks really spammy with the /ad update and I think that with this sort of option players can have genuine conversations without needing to use a 3rd party program with all the messy spam.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
Think this was already suggested before, in case anyone wants to pull that up
This completely makes the ad feature useless, they're not adding this

**Comment by AdxmGG** [comment]
no lol

**Comment by Columner** [comment]
I don't know about you I just thought that it's just so much harder to talk to other people in the lobby than it was before.

**Comment by PundaChen** [comment]
> I don't know about you I just thought that it's just so much harder to talk to other people in the lobby than it was before.

Did you see the lobby before? The like 30 people just spam advertising their server? That wasn't fun, this is better

**Comment by AdxmGG** [comment]
> > I don't know about you I just thought that it's just so much harder to talk to other people in the lobby than it was before.
> 
> Did you see the lobby before? The like 30 people just spam advertising their server? That wasn't fun, this is better

Not sure if you've noticed Emily, thats still happening! The rule isn't being informed.

**Comment by PundaChen** [comment]
#353 this feature was denied and close, please close this issue
