### ISSUE TITLE
Re-enable editing of spigot.yml

### ISSUE THREAD

**Issue by killergotrekt** [Minehut/Meta#444]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Panel

**Describe the feature**

Allow us to edit spigot.yml *with* restrictions again
**How the feature is useful**

pretty sure this was disabled, please reenable it. got some stuff in there that i wanna edit.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by honkling** [comment]
people used spigot.yml to obtain custom plugins and set their player count to like 10,000. we probably won't be enabling it for a while

**Comment by LukasmanMHdude** [comment]
we?

**Comment by honkling** [comment]
> we?

er- they. i often say we even if im not a part of it, that's my bad

**Comment by killergotrekt** [comment]
> people used spigot.yml to obtain custom plugins and set their player count to like 10,000. we probably won't be enabling it for a while

That is why this exists:
![Capture](https://user-images.githubusercontent.com/36091645/103245084-10d9d780-492d-11eb-9705-4fc47c553494.PNG)
If Paper.yml can be edited with overwrites, this shouldn't be a problem with spigot.yml

**Comment by drtshock** [comment]
Yes we will bring this back when we can.

**Comment by honkling** [comment]
> > people used spigot.yml to obtain custom plugins and set their player count to like 10,000. we probably won't be enabling it for a while
> 
> That is why this exists:
> ![Capture](https://user-images.githubusercontent.com/36091645/103245084-10d9d780-492d-11eb-9705-4fc47c553494.PNG)
> If Paper.yml can be edited with overwrites, this shouldn't be a problem with spigot.yml

This was also in place for spigot.yml, and people got past it, that's why it was disabled.

**Comment by AyhamAl-Ali** [comment]
Any updates on this?

**Comment by killergotrekt** [comment]
Ask Trent on the Meta Discord.

**Comment by quick007YT** [comment]
nice
