### ISSUE TITLE
Addon wrong placement.

### ISSUE THREAD

**Issue by DevRKJha** [Minehut/Meta#446]
There is a plugin called BentoBox on MH plugin list. It has few addons that need to be installed inside /plugin/bentobox/addon/bentoaddon.jar. But, Mh installs the addon jar in /plugin folder. And it is not working. What can I do?

**Comment by Blocksnmore** [comment]
👏 follow 👏 the :clap: format

**Comment by DaRealMinecraftexpert** [comment]
https://github.com/Minehut/Meta/issues/new/choose

Close?
