### ISSUE TITLE
Lobby Moderation + Discord Chat Log

### ISSUE THREAD

**Issue by Duziest** [Minehut/Meta#447]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java + Discord

**Describe the feature**

Minehut always had a problem with moderation. There was either one moderator or none in the lobbies. Sometimes the moderator doesn’t even have moderation permissions (helper), however, this could easily be changed. What if Minehut allowed Minehut lobbies to connect to a discord chat log in the Minehut staff discord. Lobby moderators do not need to worry about fly hackers, but they need to worry about chat spammers and such. If we were to report this stuff to the moderators on discord, they could easily mute those cheesy spammers on their phones without even logging onto the network. It could change the way Minehut’s lobby is moderated in an entirely new and better form. This could mean a better chat environment for users. 

**How the feature is useful**

Makes moderators lives easier and more efficient. If I were to report a chat spammer to a random moderator on discord, the chances of them not being on the network is high. If they did need to log onto the network, by the time they do, they would forgot about the user. Even worse is that they may redirect us to some other moderator who may not even be on the network either. If they didn’t need to log onto the network to mute chat due to bots, mute users due to spam and external advertising, and ban bots, then Minehut’s chat could be very clean and well moderated for almost 24/7. People wouldn’t even know if there was a moderator moderating, which could also save a lot of hassle.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
There is already a discord chat log on the Minehut staff discord. However, this is done from a user account, maybe it would be better if it was created within the network and a bot could allow for punishing users on discord as well as in-game?

**Comment by Blocksnmore** [comment]
This does technically go with #415 since it talks about discord integration with stuff like report

**Comment by Sniped** [comment]
> This does technically go with #415 since it talks about discord integration with stuff like report

He's not suggesting a formal command to report like #415 is, rather, he was just saying that moderators could be notified on discord and be able to punish them from discord.

**Comment by Duziest** [comment]
> > This does technically go with #415 since it talks about discord integration with stuff like report
> 
> He's not suggesting a formal command to report like #415 is, rather, he was just saying that moderators could be notified on discord and be able to punish them from discord.

I’m more suggesting that punishments should easily be done on discord. Notifying them could be on discord, which is where most punishments are.

**Comment by Duziest** [comment]
Woops! My bad!

**Comment by MiginsMC** [comment]
The issue could be, how would you know if the staff member is on discord? Sometimes other staff might ask the moderator why they punished for that reason or length. Or maybe someone for whatever reason has said 'dont punish __', the discord moderator would be oblivious to this. i think this would have to be set up in a way that the moderator can also use and see the staff in game chat as well as a way to discern whether someone is in the lobby or on discord.

**Comment by BennyDoesStuff** [comment]
Not an issue anymore.
