### ISSUE TITLE
Missing Parkour NPC in Lobby

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#451]
### Bug report

**Platform**
ingame

**Describe the bug**
Missing NPC?

**To reproduce**
play game
Steps to reproduce the behaviour:

**Expected behaviour**
have NPC or some way to get rank

**Device Information**

- Minecraft client (and version): 1.16.2 (or whatever the lastest is)
- Web browser (and version): not needed
- Operating system (and version): again, not needed
- Minehut server name: in a lobby

**Screenshots**
![image](https://user-images.githubusercontent.com/69743171/103191297-4af19d80-4889-11eb-8fb1-039fdff6c0e2.png)
![image](https://user-images.githubusercontent.com/69743171/103191299-4cbb6100-4889-11eb-9002-8b9a7fc8d6c3.png)

If applicable, add screenshots, short videos/GIFs to help explain your problem 
You can leave this blank -->

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Sniped** [comment]
> play game
I'm unsure what you mean by just "playing the game", do you mean do the parkour? I just flew through the parkour and there were no signs of an NPC nor this placeholder here, rather once you completed the parkour it told you that you had the rank rather than it just being claimed by an NPC.
