### ISSUE TITLE
Ability to modify spigot.yml indirectly in Settings menu

### ISSUE THREAD

**Issue by honkling** [Minehut/Meta#452]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Allow users to modify spigot.yml in the Settings menu, just like we can with server.properties.

**How the feature is useful**
It allows people to modify spigot.yml to change stuff like whitelist message and whatnot, while still keeping people away from the nodes that provide security vulnerabilities.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by killergotrekt** [comment]
This will bloat the settings menu with things that a basic minehut user will never (will maybe) use. Letting advanced users who want more customizations should tackle into the file system and modify themselves. (#444)

**Comment by drtshock** [comment]
We'll bring this back when we're able to the way it was.
