### ISSUE TITLE
[Severe] MineHut Plugins not working properly

### ISSUE THREAD

**Issue by KhrysAK47** [Minehut/Meta#455]
### Bug report

**Checklist**
- [YES] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [YES] I am NOT reporting a security vulnerability
- [YES] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [YES] This issue does not contain any sensitive information

**Platform**

**Describe the bug**
To be short some of the most interesting plugins don't work on MineHut, as a example, Murder Mystery that is on MineHut plugins, it has a required dependency, which does not work because of the server being in 1.16.4 as base, it clearly states on the spigot page of the plugin that the dependency has a specific versions that it works on. Second issue is worse, plugins such as Annihilation or uSkywars require you to upload the clean world in the actual plugin ''arenas'' folder so it can reset a arena properly, but you can't do that - in other words because of this you cannot reset / clear worlds after a game which makes it all unplayable, I reported this issue via support over a month ago but it was given no relevance. I also purchased a lot of credits just to make the game modes above which didn't work at the end because of the issues above and I feel scammed. So yeah, thanks MineHut, showcasing real professionalism there, thank god you are no longer required to purchase the plugins, otherwise it would be a fiasco to purchase plugins that don't work at all. 

**To reproduce**
Steps to reproduce the behaviour:
1. For the murder mystery, just try installing the plugin and the dependency through minehut
2. Restart and see error

1. For the uSkywars, Annihilation and others that require you to upload a clean copy of the arena, well you simply can't upload worlds directly to folders located in the plugins folder, so yeah. No detailed guide here. 

**Expected behaviour**
The plugin to work properly, what a dumb question

**Device Information**

- Minecraft client (and version): The default one minehut provides
- Web browser (and version): Not relevant here
- Operating system (and version): The default one minehut provides
- Minehut server name: Not relevant here since it happens on any server you put the plugins on

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by KhrysAK47** [comment]
I also put expected behavior but it doesn't display above, basically the plugin to work properly lol

**Comment by Sniped** [comment]
Issues involving plugins don't belong here, rather, they belong on the forums. Once the [forums](https://forums.minehut.com) come back up, please make your issue there.

**Comment by AdxmGG** [comment]
@Sniped, its not that the plugin is outdated. The plugin cannot be used because you need to drag the main world folder there *(or smth like that)*, which is impossible on Minehut.

**Comment by KhrysAK47** [comment]
@Sniped @AdxmGG Hella useless ''collaborator'' right here, this is ridiculous, I reported the same issues over a month ago on the forums and nothing was done about it, then I asked in the discord where should I report or address this since I was nothing was done, I was told to do it through here, and now you say I need to report it once again on the forums when it wasn't taken into consideration previously? I already wasted enough time to trying to get this shit fixed and MineHut just doesn't care. Totally disappointed.

**Comment by LukasmanMHdude** [comment]
> Hella useless ''collaborator'' right here, 

that just means they worked on making the github

**Comment by Sniped** [comment]
> @Sniped, its not that the plugin is outdated. The plugin cannot be used because you need to drag the main world folder there _(or smth like that)_, which is impossible on Minehut.

I understand that, but nonetheless these sorts of issues belong on the forums, that's where they're checked.

> @Sniped @AdxmGG Hella useless ''collaborator'' right here, this is ridiculous, I reported the same issues over a month ago on the forums and nothing was done about it, then I asked in the discord where should I report or address this since I was nothing was done, I was told to do it through here, and now you say I need to report it once again on the forums when it wasn't taken into consideration previously? I already wasted enough time to trying to get this shit fixed and MineHut just doesn't care. Totally disappointed.

 If nothing was done about it on the forums, then I recommend posting a thread on it on the forums category again once they're up again. Super League staff are out on break until January 4th, so there might be a bit of a delay before then, however after that plugin requests will be looked at. I'm not sure who directed you here, however it very clearly states on the [`README`](https://github.com/Minehut/Meta/blob/master/README.md) that all issues related to plugins go on the forums category and are not taken up here.
