### ISSUE TITLE
Filter in boosters

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#457]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
discord

**Describe the feature**
make the filter work in booster channels for slurs

**How the feature is useful**
slurs aren't allowed in boosters so might as well block them so people don't get the chance to use em in there

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
maybe a watered-down version of it? ik ppl like talking in boosters cause you can curse so

**Comment by LukasmanMHdude** [comment]
or just have a punishment where you lose ur booster rank/pass if you do say a slur

**Comment by PundaChen** [comment]
These people still need to be punished for what they say, atm people can just say the n word in boosters (they get muted eventually) while we could just make it so slurs are blocked, losing a pass compared to the long mute theyre supposed to get is kinda dumb

**Comment by jellz** [comment]
Currently the bot’s filter rules consider slurs and other swear words to be in the same filter category of Swearing, so a new filter rule type would need to be created for the slurs and slurs would need to be switched over to that category.

**Comment by AdxmGG** [comment]
Is it really worth this massive change just to block the n word? Maybe staff could do their job a little more and watch it!

**Comment by Sniped** [comment]
> Is it really worth this massive change just to block the n word? Maybe staff could do their job a little more and watch it!

It would be rather nice for both the users of the channel and moderators if it was automatically censored. Staff do their job, however they can't be constantly watching a channel. It would block not only the N word but other words as well with the change.

**Comment by AdxmGG** [comment]
The channel allows swearing, I see why the Nword would be blocked but what other words would need blocked?

**Comment by Sniped** [comment]
> The channel allows swearing, I see why the Nword would be blocked but what other words would need blocked?

I would imagine other slurs that target specific groups of people such as the F word and different variations of the N word that may be used to bypass it.

**Comment by PundaChen** [comment]
> The channel allows swearing, I see why the Nword would be blocked but what other words would need blocked?

D-slur (d*ke), f-slur (f*g), n-slur (not gonna name that one), r-slur (ret*rd) and I'm sure there's a few other slurs that could be added to this list, these would also included bypasses for these words
