### ISSUE TITLE
Minehut YouTube banner

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#46]
### Bug report

**Platform**
 Minehut YouTube

**Describe the bug**

On the Minehut YouTube, the banner says create your server at https://superleague.com/minehut

But that link throws an error on the SLG site.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.youtube.com/minehut

**Expected behaviour**

The banner should display a functional link, or the link should be fixed.

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): Chrome Latest
- Operating system (and version):  N/A
- Minehut server name: N/A

**Screenshots**
![](https://cdn.discordapp.com/attachments/592130982451216402/710643315732774972/unknown.png)

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by drtshock** [comment]
Ah forgot about that. Will get a new one made, thanks.

**Comment by Sniped** [comment]
Closing this as the Minehut YouTube banner has been changed
