### ISSUE TITLE
Fix. The. Lag.

### ISSUE THREAD

**Issue by killergotrekt** [Minehut/Meta#460]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Both
**Describe the bug**

Lag on minehut servers, usually get 1 bar and you get lagged back
(Not my end since I have fast internet)

**To reproduce**
Steps to reproduce the behaviour:
1. Join minehut
2. Join any server
3. Try moving around. Almost impossible without teleportation

**Expected behaviour**

A smooth gameplay without hiccups.

**Device Information**

- Minecraft client (and version): MC 1.14.4
- Web browser (and version): N/A
- Operating system (and version): Windows 10
- Minehut server name: All of the servers

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by drtshock** [comment]
Yes working on it.

**Comment by LukasmanMHdude** [comment]
> Yes working on it.

if your working on it, then add the planned label, don't close the issue

**Comment by ksu-tech** [comment]
frick u

**Comment by drtshock** [comment]
Seems to be better now :) Please let us know when you notice more lag, what kind of lag you're seeing, how often you see it, and the servers you see it on.

**Comment by ksu-tech** [comment]
BRUH CENSORSHIP HAHA CHINA MOMENT

**Comment by killergotrekt** [comment]
Starting to lag again ![lag](https://i.imgur.com/THpUyLe.png)
some proxies are better than others, but you can tell significant amount, ping spikes

**Comment by LukasmanMHdude** [comment]
yea the lag is back, losing proxy connections as well.
