### ISSUE TITLE
Hub chat moderation

### ISSUE THREAD

**Issue by SiEvans222** [Minehut/Meta#461]
### Feature request

**Checklist**
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x ] This issue does not contain any sensitive information 

**Platform**
 In-Game

**Describe the feature**

In-Game chat is very frustrating with the amount of people spamming servers without doing /ad, I know this issue is currently being worked on. Why not use a auto punishment system to better filter the chat, I know this can be very troublesome to setup and implement because of false positives, and you don't wanting people getting punished for something that they didn't do. We all know that chat from 10k people cant be monitored by people [staff]. The man power it would take to keep the chat monitored is astronomical. But I feel like a auto punishment system should be implemented because its ridiculous honestly. You have people including me paying for ranks on the hub just so they can do /ad faster and yet everyone else is flooding the chat because they don't use /ad like they're told to do. But I digress, I would assume there is already some form of chat filter being worked on as I am typing this. But I figured I would come suggest that this be set up in the hub. Unless you have multiple people doing /ad for your server its pointless to even try to get people to join your server. Its very annoying, because there is only two ways to advertise your server discord and in the hub, Most ad services cant advertise minehut servers because of the unique ip address. I.e. .25555, But without minehut they wont allow the ip to be used in their config. So unless you are manually advertising your server on a 3rd party website or paying someone to do so its almost impossible to get players to join your server, As soon as you post your add woosh gone. Why not make separate chats so people can advertise only and one for chat. that would clear the chat flooding and people can actually chat with each other like back in the old days of minehut. Id be more than happy to moderate chat and try to keep the flooding down but that's irrelevant because you cant mute 1000 people that are spamming chat. Both the ideas I listed have flaws like people having to switch what chat they are on to talk or look for servers. I feel like that would have a negative effect on /ad aswell. The best option seems like to do the auto punishment system I mentioned earlier. Per say, three warnings = hour mute. every occurrence there after be an extra hour mute, so first occurrence after three warning 1 hour mute, second occurrence 2 hour etc. etc. I've bought ranks to advertise faster and yet its still pointless to do so during peak hours.
**How the feature is useful**

everyone in the hub. makes the hub experience more enjoyable.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
Gonna be honest I read this like three times and I still don't understand everything in it. Your suggestions are automatic mutes, something about server IPs and separate chats? Please correct me if I'm wrong, wanna make sure I got everything right before commenting on the suggestions themselves

**Comment by AdxmGG** [comment]
Maybe staff should jusf do their job idk about you

**Comment by SiEvans222** [comment]
The auto mute was a suggestion. I was stating reasons why the chat needs to be fixed. you cant use minehuts server ips in ad service websites

**Comment by PundaChen** [comment]
This place is for suggestions, not for stating something needs to be fixed (unless it's a bug ofc) 
I recommend you make a new issue for some of the stuff mentioned in here and actually turn them into suggestions

**Comment by Sniped** [comment]
On top of what @PundaChen said, these ideas can be put into separate issues where they can be elaborated on differently, such as the idea of separating lobby chats and an automatic punishment system. I'd like you to do this instead of creating one massive issue about lobby chat moderation.
