### ISSUE TITLE
Remove panel file extension limitations

### ISSUE THREAD

**Issue by honkling** [Minehut/Meta#463]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Allow users to modify and upload any file of any type (Excluding types like .properties, .jar, .sh, etc.)

**How the feature is useful**
The limitations are simply unnecessary, it only causes frustration and allows users to do less with their servers. This would also remove the need for people to suggest new extensions to be whitelisted.

This also solves (slight) issues that were suggested to be fixed in Meta, for example, not being able to remove the top file in plugins/Skript/scripts (suggested by @farwl)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by killergotrekt** [comment]
So instead of a whitelist of extensions, a blacklist of extensions instead?

**Comment by honkling** [comment]
> So instead of a whitelist of extensions, a blacklist of extensions instead?

Yeah

**Comment by BennyDoesStuff** [comment]
The file extensions limit was removed as of the recent file manager update.
