### ISSUE TITLE
Welcome Message Issue

### ISSUE THREAD

**Issue by AdxmGG** [Minehut/Meta#465]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

I believe both but at least Java.
**Describe the bug**

The `!` should go back to the white colour after saying the username in green.
![68747470733a2f2f692e6962622e636f2f533552316747502f6c6f6262792d6a6f696e2d6d6573736167652d7570646174652e706e67](https://user-images.githubusercontent.com/40618525/103877889-96981880-50cd-11eb-9a46-f2689efe93ab.png)
*(stolen screenshot <3)*
**To reproduce**
Steps to reproduce the behaviour:
1. Login.
2. View Chat.

**Expected behaviour**

Revert back to white.

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): N/A
- Operating system (and version): N/A
- Minehut server name: N/A

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by MiginsMC** [comment]
Can reproduce, Optifine 1.16.4.

**Comment by not-3than** [comment]
Hey, that's my screenshot!
(Can reproduce on any client)

**Comment by BennyDoesStuff** [comment]
fixed lol
