### ISSUE TITLE
Server Crash Bug

### ISSUE THREAD

**Issue by CoverageCraft** [Minehut/Meta#467]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

In-game on Java, and bedrock.

**Describe the bug**

A server crash bug that includes Dispensers, Flint and Steel and Obsidian. I heard it has been patched in the latest version of paper. (This happens on all servers)

**To reproduce**
Steps to reproduce the behaviour:
![image](https://user-images.githubusercontent.com/67969086/104028603-5b3b3e00-51e2-11eb-89e7-cb4bc629945d.png)
This is the design. (with a Flint and Steel inside the Dispenser)
![image](https://user-images.githubusercontent.com/67969086/104028800-98073500-51e2-11eb-8ad0-46a918d50c1a.png)

Flip the lever and it crashes the server.

**Expected behaviour**

The server wouldn't crash performing this.

**Device Information**

- Minecraft client (and version): Fabric Mod Loader 1.16.4 
- Web browser (and version): Brave Browser Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
- Operating system (and version): Windows 10 Version 20H2
- Minehut server name: CoverageYT

**Screenshots**

![image](https://user-images.githubusercontent.com/67969086/104029155-1368e680-51e3-11eb-95b4-8d24c2289f68.png)
![image](https://user-images.githubusercontent.com/67969086/104029192-1ebc1200-51e3-11eb-9cbc-1b1ea04f6e8a.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
ig they can update paper next downtime? imo that's kinda an edge use case scenario so.

**Comment by MrTibo1** [comment]
> ### Bug report
> **Checklist**
> 
> * [x]  I have read and agree to the README (found on https://github.com/Minehut/Meta)
> * [x]  I am NOT reporting a security vulnerability
> * [x]  I have searched the Issue Tracker to make sure this is not a duplicate issue
> * [x]  This issue does not contain any sensitive information
> 
> **Platform**
> 
> In-game on Java, and bedrock.
> 
> **Describe the bug**
> 
> A server crash bug that includes Dispensers, Flint and Steel and Obsidian. I heard it has been patched in the latest version of paper. (This happens on all servers)
> 
> **To reproduce**
> Steps to reproduce the behaviour:
> ![image](https://user-images.githubusercontent.com/67969086/104028603-5b3b3e00-51e2-11eb-89e7-cb4bc629945d.png)
> This is the design. (with a Flint and Steel inside the Dispenser)
> ![image](https://user-images.githubusercontent.com/67969086/104028800-98073500-51e2-11eb-8ad0-46a918d50c1a.png)
> 
> Flip the lever and it crashes the server.
> 
> **Expected behaviour**
> 
> It crashes the server.
> 
> **Device Information**
> 
> * Minecraft client (and version): Fabric Mod Loader 1.16.4
> * Web browser (and version): Brave Browser Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
> * Operating system (and version): Windows 10 Version 20H2
> * Minehut server name: CoverageYT
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/67969086/104029155-1368e680-51e3-11eb-95b4-8d24c2289f68.png)
> ![image](https://user-images.githubusercontent.com/67969086/104029192-1ebc1200-51e3-11eb-9cbc-1b1ea04f6e8a.png)
> 
> **Additional context**
> 
> **Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

"Expected behavior" would be the server *not* crashing lol

**Comment by LukasmanMHdude** [comment]
@MrTibo1 can you please only quote the part your referring to? creates a lot of unnecessary scrolliung

**Comment by Sniped** [comment]
A patch was released on Minehut, restarting your server will pull up the patched server version.
