### ISSUE TITLE
Reset tablist header/footer when switching servers

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Meta#47]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game (Java)

**Describe the feature**

Reset the player's tablist header & footer when switching servers.

**How the feature is useful**

This will prevent a tablist header/footer from carrying over to another server where it does not belong.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
When you say switching servers, do you mean between player servers or going back to the hub?

**Comment by CoreyShupe** [comment]
Need more information on the bug this actually is causing. Seems like a per-server implementation can be done to manage this. This also seems like a client issue with the proxy, I'll mention it to the proxy devs and see what they think about it.

**Comment by DebitCardz** [comment]
> Need more information on the bug this actually is causing. Seems like a per-server implementation can be done to manage this. This also seems like a client issue with the proxy, I'll mention it to the proxy devs and see what they think about it.

In Minecraft whenever you switch between servers in the proxy it doesn't reset the Header/Footer unless in the server you connect to it specifically does so.

Example being I connect to a playerserver and it's header is 'Test' then I do /server otherserver and it doesn't set your Header/Footer when you join, the Header in your tablist will still be 'Test'.

**Comment by tarna** [comment]
> > Need more information on the bug this actually is causing. Seems like a per-server implementation can be done to manage this. This also seems like a client issue with the proxy, I'll mention it to the proxy devs and see what they think about it.
> 
> In Minecraft whenever you switch between servers in the proxy it doesn't reset the Header/Footer unless in the server you connect to it specifically does so.
> 
> Example being I connect to a playerserver and it's header is 'Test' then I do /server otherserver and it doesn't set your Header/Footer when you join, the Header in your tablist will still be 'Test'.

Isn't /server disabled on player servers?

**Comment by CoreyShupe** [comment]
Seems like this might be a job on the proxy's end.

**Comment by DebitCardz** [comment]
@tarna, no idea I was just trying to give a basic example to understand.

**Comment by DebitCardz** [comment]
> Seems like this might be a job on the proxy's end.

I don't know if the proxy can actually handle sending Header/Footer packets, if it can't just reset the Header/Footer when players connect to the lobby.

**Comment by CoreyShupe** [comment]
> if the proxy can actually handle sending Header/Footer packets

it most certainly can

**Comment by CoreyShupe** [comment]
https://www.spigotmc.org/resources/bungeetablistplus.313/ example of this being done on the proxy layer

**Comment by BennyDoesStuff** [comment]
I'm going to close this issue for now. The lobby resets your tablist whenever you join it and going through the lobby is currently the only way to switch servers.
