### ISSUE TITLE
Allow us to connect github with minehut file manager

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#471]
### Feature request

**Platform**
website 

**Describe the feature**
Basssilly let us make a repo of the files on minehut, and we can edit them on github. You would be able to target an existing repo to add a folder of the files you to be able to modify, or create a new repo. You can't select anything and only certain types of files can be created. (i.e. .sk only allowed in scripts folder)

**How the feature is useful**
This would be amazing for example I can skript in vsc (or your chosen code editor), then apply the changes to minehut. Also not to be mean, but githubs file management is miles ahead of minehuts, and much easier to use. I save all my server files on github anyway, so in my situation, it would just be such a huge QoL feature. Also, almost everyone experienced with skript to some degree use a secondary code editor, so being able to easily save then push with git desktop would simplify many peoples workflow.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
#330 suggests this, however it was closed by the author. On that issue, I said that hosting your files via GitHub is quite impractical and would be a hassle to make it so that it was synergistic between the Minehut file manager and GitHub. It would be more practical to allow SFTP connections and manage your files that way via clients such as FileZilla.

**Comment by LukasmanMHdude** [comment]
> SFTP

wasn't this said to not be allowed?

**Comment by Sniped** [comment]
> wasn't this said to not be allowed?

GitHub would really be the same as SFTP, you would be able to upload anything you wanted, except that SFTP is a lot more convenient in my opinion.

**Comment by LukasmanMHdude** [comment]
> > wasn't this said to not be allowed?
> 
> GitHub would really be the same as SFTP, you would be able to upload anything you wanted, except that SFTP is a lot more convenient in my opinion.

they would obvi only allow you to upload things in certain areas with much restrictions (i.e. the skripts foldar)

**Comment by Sniped** [comment]
> they would obvi only allow you to upload things in certain areas with much restrictions (i.e. the skripts foldar)

I think it would be cool if you'd be able to select certain directories to be "ported" over to a GitHub repo and once you commit to those files they sync with Minehut's file manager. Anything uploaded that could be deemed malicious can be detected and removed on GitHub via a commit.

**Comment by LukasmanMHdude** [comment]
> I think it would be cool if you'd be able to select certain directories to be "ported" over to a GitHub repo and once you commit to those files they sync with Minehut's file manager. Anything uploaded that could be deemed malicious can be detected and removed on GitHub via a commit.

That was my intention lol, lemme update the suggestion

**Comment by honkling** [comment]
> > SFTP
> 
> wasn't this said to not be allowed?

During a Trent AMA, minecoder actually stated he was working on an SFTP client(?) for Minehut, where you could use SFTP but it'd still have the common file limitations as the panel.

**Comment by LukasmanMHdude** [comment]
> During a Trent AMA, minecoder actually stated he was working on an SFTP client(?) for Minehut, where you could use SFTP but it'd still have the common file limitations as the panel.

soon:tm:

**Comment by Double0negative** [comment]
Sorry, but isn't really viable. If anything we would have a sftp option, but thats not on the roadmap any time soon.
