### ISSUE TITLE
Transaction IDs

### ISSUE THREAD

**Issue by muelr** [Minehut/Meta#473]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website.

**Describe the feature**

When any purchases are made using credits, when the receipt is sent to the email of that account, include a transaction ID. This transaction ID could be easily used by Support to track any purchases made by users to ensure they're authentic and not someone trying to scam Support. 

This would include donator ranks.

**How the feature is useful**

QOL update for Support as well as ensuring authentic purchases if they don't receive what they purchase.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by not-3than** [comment]
This is in use by almost all other companies who sell things digitally, it's time Minehut adds it.

**Comment by BennyDoesStuff** [comment]
> This transaction ID could be easily used by Support to track any purchases made by users to ensure they're authentic and not someone trying to scam Support.
The support team can easily lookup an email and find a list of all the purchases made through that email or whether a rank was actually bought for an account.
