### ISSUE TITLE
No more /ad warnings

### ISSUE THREAD

**Issue by MrTibo1** [Minehut/Meta#474]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

both

**Describe the feature**

Immediately mute the people not using /ad to advertise. The amount of people not using /ad is through the roof and then you get this
![image](https://user-images.githubusercontent.com/28931191/104131919-092d2080-537a-11eb-99b3-b005eed781f1.png)
It is made very clear to use /ad when advertising the moment you join the lobby so when not following these instructions you should simply be muted. also mute for longer than like 3 hours or something because people will just keep doing it. I suggest that a mute for not using /ad is 4 days at least.

**How the feature is useful**

Calm down the spam in chat, it's actually terrible at times.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
I'm surprised mh still gives warnings since its been over a month of ad being out so people had plenty of time to transition yet people still dont use it.

**Comment by killergotrekt** [comment]
imagine if all the nons knew that helpers can't moderate... it would most likely be a moderation nightmare, 🙃

**Comment by MiginsMC** [comment]
i definitely think that we shouldnt warn anymore, but 4 days seems excessive. I think our current mute time works.
