### ISSUE TITLE
/ul world limit bypass

### ISSUE THREAD

**Issue by modderongithub** [Minehut/Meta#475]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website & In-Game (java)

**Describe the feature**
A way to be able to bypass the upload limit for worlds if you have a non-free server plan.

**How the feature is useful**
It would allow people to add worlds that are over 500mb, like the 1:2000-scale Earth map I'm trying to upload to my server. (Just under 1gb.)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
I actually kind of like this idea. Adds more incentive to purchase a plan.

**Comment by modderongithub** [comment]
> I actually kind of like this idea. Adds more incentive to purchase a plan.

"Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments."

**Comment by AdxmGG** [comment]
> > I actually kind of like this idea. Adds more incentive to purchase a plan.
> 
> "Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments."

I know how the github works 😉

**Comment by modderongithub** [comment]
> > > I actually kind of like this idea. Adds more incentive to purchase a plan.
> > 
> > 
> > "Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments."
> 
> I know how the github works 😉

But you didn't add the reaction...

**Comment by modderongithub** [comment]
Note: If any Minehut administrators think this could be abused, just up it to 2gb instead. It'll allow for most worlds and if anyone wanted to slow the server hosting down they'd already have been botting accounts so they'd just continue.

**Comment by BennyDoesStuff** [comment]
The /upload command doesn't exist anymore so this issue doesn't apply.
