### ISSUE TITLE
/ad Cooldown bug

### ISSUE THREAD

**Issue by not-3than** [Minehut/Meta#479]
### Bug report

**Checklist**
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] I am NOT reporting a security vulnerability
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x ] This issue does not contain any sensitive information

**Platform**

In game, Lobby

**Describe the bug**

When your cooldown is at 0 seconds, it says "Something went wrong, please try again"

**To reproduce**
Steps to reproduce the behaviour:
1. Join the lobby
2. Use /ad to advertise
3. Keep using it when your cooldown is around 0-10 seconds, and wait until the "Something went wrong, please try again" message shows after the cooldown is less than 1 second

**Expected behaviour**

You should be able to just advertise after the 1 second, but it blocks it and has some kind of error.

**Device Information**

- Minecraft client (and version): Optifine 1.16.4
- Web browser (and version): N/A
- Operating system (and version): Windows 10 Home 1909
- Minehut server name: Lobby

**Screenshots**

![ad bug](https://i.ibb.co/F6ZBMsZ/ad-bug.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
stop advertising

**Comment by Sunni05** [comment]
Reproducible

**Comment by TrueReassembly** [comment]
It might be related to there still being more than 0 seconds, but less than 1 second remaining

**Comment by MiginsMC** [comment]
Can reproduce on Lunar Client 1.16.5.

**Comment by quick007YT** [comment]
seems to be an issue with the way people code java cooldowns as I've experienced smth similar on other servers

**Comment by CoreyShupe** [comment]
> 
> 
> seems to be an issue with the way people code java cooldowns as I've experienced smth similar on other servers

not coded in java

Another note, seems like it isn't actually causing issues so it probably either won't be fixed or will be put at the bottom of the backlog.

**Comment by quick007YT** [comment]
minehut uses skript :flushed:

**Comment by drtshock** [comment]
Doesn't seem like an issue if we're just off by less than a second.
