### ISSUE TITLE
Sidenav Improvements

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#48]
### Feature request

**Platform**
 Website

**Describe the feature**

- Add some padding to the right of the Sidenav, or to the left of the page content.
- Make the sidenav setting remember if you had it collapsed or expanded. Every time you reload a page it changes back and can be very annoying.

**How the feature is useful**

This is a quality of life update and there is no reason not to add it.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
With the recent website design overhaul, this issue no longer applies.
