### ISSUE TITLE
Allow us to change the default level of op

### ISSUE THREAD

**Issue by AwesomeGamer333** [Minehut/Meta#481]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

For Java but could work for bedrock too
**Describe the feature**

Add a way to change the default op level without doing /op
Currently the only way to do so is to change ops.json, but in order to do that u have to op them first with /op, which gives them level 4 op but I want them to have level 3 op.
**How the feature is useful**

It benefits me and others who want to give someone a lower level of op without having to change ops.json
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**
Here is what each level of op does for reference 
Level 1 Ops can bypass spawn protection. No commands are assigned for this level.
Level 2 Ops can use all commands, except /ban, /deop, /whitelist, /kick, /op, /stop, /save, /save-all and /save-off and /save-on, and can edit command blocks. (Single player cheating)
Level 3 Ops can use /ban, /deop, /whitelist, /kick, and /op . (Multiplayer management)
Level 4 Ops can use /stop, /save, /save-all . (Server management)
4 is the highest OP level. Any level op also has the lower levels' permissions

**Comment by AdxmGG** [comment]
I never knew operator had different levels... woah.

**Comment by AwesomeGamer333** [comment]
> I never knew operator had different levels... woah.

Yup, that’s why you can’t kick of ban in lan singleplayer worlds

**Comment by LukasmanMHdude** [comment]
> I never knew operator had different levels... woah.

use any other host instead of minehut and its usually built right into the panel

**Comment by AwesomeGamer333** [comment]
> > I never knew operator had different levels... woah.
> 
> use any other host instead of minehut and its usually built right into the panel

But minehut gives you more players

**Comment by BennyDoesStuff** [comment]
Could be quite useful for free-op servers.

**Comment by BennyDoesStuff** [comment]
You can now directly edit the server.properties file to edit this property.
