### ISSUE TITLE
Credit Conversion Pricing

### ISSUE THREAD

**Issue by Echological** [Minehut/Meta#482]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

I believe that the ratio of purchasing credits, as in the ratio of USD to Credits on Minehut is unbalanced. Not just the cost to purchase ranks, that deserves its own meta issue, but more of just how you buy them.

----- 800c for $5 [monthly] -----
800 = $5.00
800/5 = $1
160 = $1

----- 800c for $6 -----
800 = $6
800/6 = $1
133.33-- = $1

----- 1800c for $10 [monthly] -----
1800 = $10
1800/10 = $1
180 = $1

----- 1800c for $12 -----
1800 = $12
1800/12 = $1
150 = $1

----- 4650c for $25 [monthly] -----
4650 = $25
4650/25 = $1
186 = $1

----- 4650c for $30 -----
4650 = $30
4650/30 = $1
155 = $1

----- 9400c for $50 [monthly] -----
9400 = $50
9400/50 = $1
188 = $1

----- 9400c for $60 -----
9400 = $60
9400/60 = $1
156.666667 = $1

The conversion ratio of credits to USD (used in this case) should be altered to better understand the number of credits you are getting for your money. I am suggesting that the ratio should be altered to give a more direct ratio of credits : money rather than a seemingly random ratio that does not make a lot of sense when trying to figure out how many credits you will get compared to other deals.

**How the feature is useful**

The feature is beneficial to the Minehut Community, especially those who purchase credits constantly. This suggestion produces a conversion that makes sense and is logical to use because of its reason and sense behind it. Helping to balance the conversion so that it makes sense to buy the package you wish to buy so that the money you spend actually relates to the number of credits you are getting in the game. This helps drastically when trying to consider what package to buy, this, in turn, makes it easier for the people purchasing the packages.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by ballxishot** [comment]
Connecting to this, take fortnite for example. 
![image](https://user-images.githubusercontent.com/75959235/104688099-6b4fa200-573b-11eb-835c-06f194cb2ca4.png) it has a clean ratio which is 1000 for $10.00.

**Comment by mekb-turtle** [comment]
> Connecting to this, take fortnite for example.
> ![image](https://user-images.githubusercontent.com/75959235/104688099-6b4fa200-573b-11eb-835c-06f194cb2ca4.png)
> it has a clean ratio which is 1000 for $10.00.

also hypixel's gold for rank gifting etc, that adds up evenly and the same as buying it from the store

**Comment by farwl** [comment]
Agreed, especially the higher up plans have drastic price changes and there is no real balance or fixed conversion rate between credits and actual currency.

**Comment by quick007YT** [comment]
> fixed conversion rate between credits and actual currency.

would love to see what credits to money for market would look like

**Comment by Echological** [comment]
doesnt look like this has gone anywhere, will close
