### ISSUE TITLE
Remove minehut messages from servers 

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#483]
### Feature request

**Platform**
Ingame

**Describe the feature**
Don't show this message on playerservers, I know you guys want stream people but common, playerservers shouldn't really be getting minehut's spam in it. (at least make this toggleable for paid if you have to, although I would prefer all servers not having to deal with it)

![image](https://user-images.githubusercontent.com/69743171/104780463-b2d32f80-5735-11eb-939d-944b16697f8e.png)

**How the feature is useful**
People don't have to see minehuts spam in chat

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
Honestly, I think serverwide messages should only be used for restarts/actually important stuff, not for stuff like this

**Comment by xenitrogen** [comment]
To be completely honest, I don't really mind it. Some could find it annoying which I completely understand. But sometimes im on my server and I don't know mh is streaming.

**Comment by ahoulton** [comment]
> 
> 
> To be completely honest, I don't really mind it. Some could find it annoying which I completely understand. But sometimes im on my server and I don't know mh is streaming.

Maybe allow users to toggle non-important announcements which will need a change in the backend to allow for this.

**Comment by LukasmanMHdude** [comment]
yea toggle could work as well

**Comment by MiginsMC** [comment]
Something in /settings, maybe /setting receive-announcements or smth

**Comment by Double0negative** [comment]
The ability to send targeted messages (lobby, paid/unpaid servers) instead of only network wide is getting deployed tomorrow morning.

**Comment by LukasmanMHdude** [comment]
> The ability to send targeted messages (lobby, paid/unpaid servers) instead of only network wide is getting deployed tomorrow morning.

It was deployed, is it being used? (on mh20 btw) 
![image](https://user-images.githubusercontent.com/69743171/107089283-3ae7aa80-67b3-11eb-9cdf-1da38d5194cb.png)

**Comment by quick007** [comment]
Would love for thi to be reopened, as pointed out in #591, people can still see these messages.
