### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by ObeyBeastJj23** [Minehut/Meta#485]
### Feature request

**Checklist**
- [Y] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [Y] This is not a bug report, support request or plugin request
- [Y] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [Y] This issue does not contain any sensitive information 

**Platform**

Minehut as a whole

**Describe the feature**

Bring back Minecraft EULA enforcement. It used to be in the [Minehut TOS](https://minehut.com/terms-of-service) that you must follow the EULA while using the service. The TOS was updated at some point rather recently and removed the entry regarding the EULA, which I don't personally thing is right. It could be due to Minehut's lobbies themselves having very slightly EULA breaking content, or just the lack of care for enforcing it, but I still think you should enforce it, as it's such a simple thing to do.

**How the feature is useful**

Will clean up the player servers as a whole, stopping their being so many scammy servers around, or discontinue scams.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
Minehut does not have to enforce the EULA, that is Mojang's job, feel free to report a server to Mojang for breaking the EULA.

**Comment by StealthyAssassin69** [comment]
Hell yea minehut can break the rules ez money boys :default_dance:

**Comment by not-3than** [comment]
Minehut p2w in the lobbies tho

**Comment by killergotrekt** [comment]
not minehut's job and should not be minehut's job

**Comment by BennyDoesStuff** [comment]
Mojang enforces their EULA, not us. If you find a server breaking the EULA, report it to them and they'll handle it accordingly.
