### ISSUE TITLE
Disable CORS for oauth2

### ISSUE THREAD

**Issue by honkling** [Minehut/Meta#486]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Disable CORS to allow programmers to login to Minehut programmatically. Currently, we have the janky method of having to go into the panel and grab the auth token/session-id from Local Storage, and then it's only temporary. It'd be much more convenient to be able to login right from the get-go, without needing to copy and paste fields or sign in with headless browsers.

**How the feature is useful**
This benefits programmers and makes it very convenient for us to interact with the Minehut API.
Though it's undecided if the API was meant for public use, I still believe it's a great move and I find no reason not to :) It's only one setting, and takes like 2-3 minutes to setup on the admin's side.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by KikoPT1234** [comment]
It isn't a hard thing to do, either. They should stop delaying this. With all these maintenances, surely they can do this with no problem?

**Comment by Double0negative** [comment]
The Minehut API is not intended to be public. We currently have no intention in opening it up for public use.

**Comment by KikoPT1234** [comment]
What kind of security/privacy concerns? I'm pretty sure you can make an OAuth2 system like GitHub or Twitch and still be secure. Just because your API isn't publicly supported, it is still _public_, and as long as it is so, you should make it more organized and accessible, not only for the public's sake, but for _your_ sake as well, since it could vastly increase your developers' productivity.
