### ISSUE TITLE
Toggle-able /join

### ISSUE THREAD

**Issue by chrlew082** [Minehut/Meta#487]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Web
**Describe the feature**

There should be a Dropdown setting on the control panel for something to toggle /join startup, so like a few of the options could be, “always”, “hibernation”, or “offline”?

**How the feature is useful**

This benefits everyone, this could be used for maintenance instead of whitelist, just so we don’t get the “You are not whitelisted on this server” message, or other things.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by IWolfZ** [comment]
This has already been requested in #7 and is already in projects
