### ISSUE TITLE
Can't delete backups

### ISSUE THREAD

**Issue by Georgak** [Minehut/Meta#488]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta) 
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website
**Describe the bug**

I want to free up backup slots. I have 4 in total (MH35 Plan). When I press delete backup button nothing happens even if i reload page or switch device.
**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'minehut.com/dashboard'
2. Click on 'Backups'
3. Scroll down to 'Saved backups and delete one'

**Expected behaviour**

I expected to have 1 free backup slot and 3 full
**Device Information**

- Minecraft client (and version): Minecraft Java Edition 1.16.5 optifne G5
- Web browser (and version): Chrome stable latest
- Operating system (and version): Windows 10 Pro 20H2
- Minehut server name: Perisco

**Screenshots**

https://user-images.githubusercontent.com/65731193/105349529-836b6980-5bf2-11eb-872d-dea813f05df8.mp4

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
> I want to free up backup slots.

Lol no.

> I have 4 in total (MH35 Plan). When I press delete backup button nothing happens even if i reload page or switch device.

Known bug (I hope) so just go ahead and hit "replace backup" for now

**Comment by not-3than** [comment]
Can reproduce, Google Chrome latest version.

**Comment by honkling** [comment]
Definitely not a client side issue

![image](https://user-images.githubusercontent.com/62254220/105406371-f45e5180-5bf1-11eb-8059-945f19f8b885.png)

**Comment by Sniped** [comment]
This bug has been reported as fixed, tested on Brave and it worked so closing as done
