### ISSUE TITLE
Share Console Options

### ISSUE THREAD

**Issue by Phill310** [Minehut/Meta#490]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
(This suggestion is similar to #471)
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Add a share server thing like Aternos did. It allows you to share your console with options to limit their power. You could share it with other people and let them edit files without being able to delete the server for example. You could also make it so that you only share 1 server. That way if you have multiple servers on one account, you don't have to give people the power to edit all of the servers, just the one you want.

**How the feature is useful**
I think this helps server owners and their developers. Right now the only way to let someone edit files in your server is to give them your whole minehut account. That makes server owners very hesitant in allowing their devs to access the files. But if they were able to control what the devs could edit it would make it a lot easier.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
#13

**Comment by Blocksnmore** [comment]
Dupe of #13

**Comment by Phill310** [comment]
oops, didnt look that far back
