### ISSUE TITLE
/team list crash

### ISSUE THREAD

**Issue by DaRealMinecraftexpert** [Minehut/Meta#491]
### Bug report

**Checklist**
- [Yes] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [Yes] I am NOT reporting a security vulnerability
- [Yes] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [Yes] This issue does not contain any sensitive information

**Platform**

It affects the server, so I assume it'd be both Ingame
**Describe the bug**

Whenever I run the Command /team list it takes the Server down (See Attached Video)
**To reproduce**
Steps to reproduce the behaviour:
1. Go to your Server Ingame
2. Run the Command /team list in the chat
3. See error

**Expected behaviour**

It would Instead of Crashing, List my registered teams.
**Device Information**

- Minecraft client (and version): 1.16.5 Optifine
- Web browser (and version): Google Chrome Version 87.0.4280.141
- Operating system (and version): Windows 10
- Minehut server name: CityCal

**Screenshots**

https://user-images.githubusercontent.com/55472940/105642757-8a87b700-5e40-11eb-9acf-3597f1f64b95.mp4

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
OF 1.16.4, cannot reproduce

**Comment by ahoulton** [comment]
I would suggest trying this on a blank server if that server didn't crash you have too many teams or the teams are not registering. However, if that server did crash, it's a valid bug report.

**Comment by DaRealMinecraftexpert** [comment]
I wonder how 2 teams would be too many

**Comment by Double0negative** [comment]
This sounds like a minecraft or plugin issue, unrelated to minehut itself

**Comment by LukasmanMHdude** [comment]
You have quite a lot of plugins, try disableing them all and see if the issue persists (it'll take the files): 
⋆ Buycraft (Tebex)
⋆ ChatReaction
⋆ SuperVanish
⋆ Skript Addon: TuSKe
⋆ Citizens
⋆ Multiverse
⋆ Player Report
⋆ Title Welcome Message
⋆ AdvancedBan
⋆ PlayerParticles
⋆ VoidGenerator
⋆ Skript Addon: Skellett
⋆ Citizens CMD
⋆ GSit
⋆ Multiverse Sign Portals
⋆ EpicGenders
⋆ WorldEdit
⋆ ChatFeelings
⋆ ScreamingBedWars
⋆ NoteBlockAPI
⋆ Multiverse Portals
⋆ MythicMobs
⋆ CCTV
⋆ Skript Addon: SkBee
⋆ Holograms
⋆ Carz
⋆ Skript Addon: FunkySk
⋆ EasterEggs
⋆ Vault
⋆ Skript
⋆ OpenInv
⋆ Marriage Master
⋆ ClearLag
⋆ Parties
⋆ CustomCrafting
⋆ Permissions Ex
⋆ Core Protect
⋆ ShopKeepers
⋆ Per World Inventory
⋆ Skript Addon: Misk
⋆ HeadsPlus
⋆ JukeBox

**Comment by BennyDoesStuff** [comment]
This is not an issue with Minehut itself, please look for support in other places such as our Discord server or forums.
