### ISSUE TITLE
server jar

### ISSUE THREAD

**Issue by JustDoom** [Minehut/Meta#492]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
in-game servers

**Describe the feature**
I think there should be an option to use either tuinity or purpur server jars instead of paper because they help with performance.

**How the feature is useful**
Helps with performance

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
uh lol

**Comment by killergotrekt** [comment]
oh nonoonononono paper is excellent

**Comment by LukasmanMHdude** [comment]
> oh nonoonononono paper is excellent

assuming this is a joke right?

**Comment by MrTibo1** [comment]
Paper is fine. I'd rather see version selection, 1.12 and below also helps performance

**Comment by LukasmanMHdude** [comment]
> Paper is fine. I'd rather see version selection, 1.12 and below also helps performance

tunity + 1.12 😳

**Comment by Blocksnmore** [comment]
lmao they only checked 2 boxes

**Comment by killergotrekt** [comment]
> > oh nonoonononono paper is excellent
> 
> 
> 
> assuming this is a joke right?

no, paper's performance is pretty good

**Comment by LukasmanMHdude** [comment]
> > > oh nonoonononono paper is excellent
> > 
> > 
> > assuming this is a joke right?
> 
> no, paper's performance is pretty good

those are even faster forks of paper

**Comment by JustDoom** [comment]
> lmao they only checked 2 boxes
Thought  I did them all lol

**Comment by Double0negative** [comment]
Options, or customization may come in the future.
