### ISSUE TITLE
Don't change the Discord icon in June

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#494]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord

**Describe the feature**

Don't change the Discord icon to a rainbow one in June (Pride Month)

**How the feature is useful**

Firstly, I have nothing against LGBTQ people. This is a very controversial topic and if you don't agree then simply react with thumbs down. Last year, Minehut changed the Discord icon to a rainbow one for Pride month. I and many others feel this was unnecessary and it was quite clear that it caused quite a community uproar for the few weeks while it lasted. Many people were punished for even asking why it was changed. Big companies do this for "good PR". It doesn't do anything for Minehut except for cause problems. There was also multiple cases where certain users were teasing straight people in the Discord simply because they believed they could. Discrimination goes both ways. Changing the icon to a rainbow one during Pride month simply incited dramatic behavior and it really felt forced on us by Minehut. It goes against most religious beliefs and it is just rude to put that in our faces. Again, I have nothing wrong with LGBTQ people. I have a few friends that are LGBTQ. LGBTQ people deserve to be represented. Changing the Minehut discord icon does not do this. It only has negative effects as seen during last year's Pride month. Also on the note of good PR, there are exponentially more people who believe in religions that do not believe in LGBTQ, than there are LGBTQ people on Minehut. Please think carefully in the coming months about what the discord icon will be during the month of June. This post is not meant to be rude or attack anyone or any group. This is simply what's best.

For anyone wondering;

I made this 5 months in advance because it usually takes a few months for these posts to be read.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
![image](https://user-images.githubusercontent.com/44182379/105932484-e73ec980-601a-11eb-9bde-a0042c1a371e.png)

**Comment by farwl** [comment]
![image](https://user-images.githubusercontent.com/44182379/105934145-9da3ae00-601d-11eb-81e5-c11e297a0daa.png)

**Comment by AdxmGG** [comment]
Ah nice to see its just a public relations decision, as in they don't do it because they want to.
