### ISSUE TITLE
Update allowed file extensions

### ISSUE THREAD

**Issue by drtshock** [Minehut/Meta#5]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Minehut whitelists which file extensions can be edited on the dashboard. That list needs to be updated to include:
config.yml.broken.<anynumber>

**How the feature is useful**

Allows users more access to customize their server where they would be able to do so on any other normal host.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Also needed:
.gif and .lang
(From #116 - was closed as duplicate)

**Comment by officialRonSki** [comment]
Need:
   => json.gz file extension

Why:
   => Allows you to make ranks / permissions on localhost and exporting it to import on your minehut server. (Luck Perms)

**Comment by iGalaxyYT** [comment]
.template (from #212)
> Make it so we can add .template files onto Minehut so we can have custom roads for PlotSquared

**Comment by iGalaxyYT** [comment]
.jpg and .jpeg (from #225)
> This could be useful for server owners who use skript and want to use image on map features and don't understand how to convert a jpg to a png, and it'll be easier to use as we won't have to go through extra steps

**Comment by BennyDoesTheStuff** [comment]
I know plugins like CoreProtect uses the extension .db which might be helpful if someone ever wants to delete its database and storage file. IIRC (I might be incorrect), but there are also a few other plugins that use the .language extension as well.

**Comment by WallyTube** [comment]
it would be nice to change some stuff in the spigot config, like unknow command messages, kick messages and other convenient tools.

**Comment by LukasmanMHdude** [comment]
.zip please

**Comment by pop4959** [comment]
.schem

Sponge schematic format used by WorldEdit and other plugins in 1.13+
<https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-2.md#specification>

**Comment by Blocksnmore** [comment]
Add the ability to upload midi files so .mid

**Comment by mekb-turtle** [comment]
.mca so we can modify world region files

**Comment by LukasmanMHdude** [comment]
pls allow the .users extention

**Comment by CaptainGolem** [comment]
For people to use the plugin model engine, for the textures to work users need to be able to upload .bbmodel files. If this could be added quickly, that would be highly appreciated.

**Comment by drtshock** [comment]
Closing in favor of custom plugins, which will allow us to unlock the entire file manager.

**Comment by boyonmilk** [comment]
.bbmodel for model enginge

**Comment by lj-pixel** [comment]
> .bbmodel for model enginge

They will be releasing the unlocked file manager in the close future, so we will get access to everything, including .bbmodels :)
