### ISSUE TITLE
Changing server version

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#50]
### Feature request

**Platform**
 Website

**Describe the feature**

Allow users to change their server's version. Maybe plugin version too?

**How the feature is useful**

This is useful for using old/outdated plugins, version compatibility, proper 1.8 pvp, etc.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment]
Duplicate/Extension of #20
