### ISSUE TITLE
Add Applications to Forums Clubs

### ISSUE THREAD

**Issue by not-3than** [Minehut/Meta#500]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Forums (Website)

**Describe the feature**

Add an option for clubs to be able to make applications within their club pages.

**How the feature is useful**

It benefits users currently using the Minehut club system as a website for their server, and it benefits Minehut because it can lead to more players using their forums.

**Also: Happy 500th Issue 🥳**

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
i mean g forms exist, not sure how pausable/how this would look compared to other options.

also btw pls use an actual forums site for any1 on meta, for example here's my servers (its free!) https://azyn-net.nhforums.net/

**Comment by BennyDoesStuff** [comment]
This isn't possible currently, and won't be as we aren't the ones that code the forums. Sorry
