### ISSUE TITLE
Switch to reputable payment provider

### ISSUE THREAD

**Issue by killergotrekt** [Minehut/Meta#501]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Panel - Credit Payments
**Describe the feature**

Switch to a more *reputable* payment system, such as **paysafewall**, **stripe**, etc
**How the feature is useful**

Webmoney & Xsolla is a Russian owned payment system. Many users, including me, do not trust Russian/Chinese systems because they are prone to mass data surveillance. Webmoney is not generally favored by consumer reviewers, stating that their "poor ui" has caused them to suddenly lose money in their accounts, and they have less-than-average support agents. Their support agents "do not care" or generally "take too long to respond", and many people believe that this was to wait as long as possible, and gets away with your money. Take a look at a review:

> The problem with Webmoney lies in that SMS system, however. I found it to be extremely unreliable. Every time I would need to make an exchange I'd place money into my Webmoney account and then it would fail to send me the SMS message. This would always require a support ticket which is where the problems start to kick in. Support is extremely slow, with 12+ hour response times seeming commonplace. The issue was always a gateway issue. They'd need to switch my gateway to something new and then it would work every time. This often took 2-3 days of exchanges before it got to that point. That always led me to wonder why they couldn't permanently change my gateway or at least keep the information on file so the next ticket someone would know how to fix it? This was an inconvenience but payments always went through and I dealt with it. I have eight previous tickets in Webmoney, one for every time I deposited.

>Recently this all took a turn for the worse. I put in my largest deposit ever. And they ran away with my money. Unlike the previous tickets, this time they almost immediately dismissed me, trying to tell me that my cell phone is bad. Now this is where things get sketchy. Over the couple years I had been using Webmoney I was on my third phone. And all three had this same issue. I kept hounding them though and asking them to just go back to my old tickets and see what the gateway switch was, the answer should all be there. I then received two SMS messages directly from them, which all but confirms that my phone is working. But when I'd try to make the payments they would fail. But they continued to insist the problem was on my end.

>So first a little extra information on my phone. I use the largest provider available in my country (AIS). I phoned AIS, checked all my phone settings, and tested SMS from multiple international locations including Russia, and also using Yahoo Mails SMS verification. And in each case I received the SMS messages perfectly. When AIS investigated the matter they were able to get transmissions from Russia perfectly but said they had no record of anything from Webmoney. Sound suspicious? At the suggestion of the Webmoney people I tried two other phones, my wife's and my sister in law's. And it didn't work with either other phone.

> After about a week of this exchange I had enough. All I wanted was to take my back out of the account. I could accept that maybe they were trying to deliver the messages, but I wasn't receiving them. It was to switch to Neteller, who is the other option for me. So I made a simple request to tech support, how do I get my money out of my account when the verification to withdrawal also goes through SMS? They would not respond. I have asked this question repeatedly for the last week and I get no response at all. The only responses I have gotten to that question are, "We just sent you an SMS did you receive it?" and of course I didn't. Then after I kept stressing to please answer the question they haven't responded in four days. I can provide them with full documentation, they know I am who I am already though from the past I don't think there's any debate there.

> Unable to get any answer from their tech support I turned to trying ot contact them through other channels. All I would get in return is that I need to wait for them to respond to my ticket and they would give me no further information. Considering Webmoney is completely stone walling me I think it's safe to say that they have run away with my money, which would be a pretty hefty sum in Russia. And due to the nature of business in Russia, there is really no legal avenue I can pursue that would get it back.
Source: [Here](https://webmoneyfacts.weebly.com/blog/webmoney-answers-to-noone)

Oh, you need a *reliable* reviews site? Okay, here's some reviews from [trustpliot](https://www.trustpilot.com/review/www.wmtransfer.com).

(Yes, webmoney is owned by Xsolla)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Web money was a specific gate way enabled on xsolla before they enabled all other gateways on our account. We accept credit cards directly, bank wires, and gift cards. Currently we accept 274 forms of payment.

**Comment by killergotrekt** [comment]
> Web money was a specific gate way enabled on xsolla before they enabled all other gateways on our account. We accept credit cards directly, bank wires, and gift cards. Currently we accept 274 forms of payment.

if webmoney is a gateway, you should consider closing it then

**Comment by honkling** [comment]
But you don't have to pay using Webmoney? You can use other payment methods just as fine

**Comment by not-3than** [comment]
I don't think reviews of WebMoney can justify Super League changing payment providers, seeing as Xsolla is used by tons of big gaming corporations such as Epic Games, Steam, Twitch, and even Roblox.

**Comment by LukasmanMHdude** [comment]
![image](https://tenor.com/view/minehut-minecraft-bad-host-gif-18610513)
yea, its not as if they have good reviews either

**Comment by BennyDoesStuff** [comment]
Minehut now supports PayPal once agaib

**Comment by DaRealMinecraftexpert** [comment]
Why are people complaining MH is too popular? There's Many Servers and Hosts that are more Popular, and not many complain about that

**Comment by LukasmanMHdude** [comment]
> Why are people complaining MH is too popular? There's Many Servers and Hosts that are more Popular, and not many complain about that

on those hosts, there isn't a weekly red alert of something breaking

**Comment by BennyDoesStuff** [comment]
You can directly buy credits using the credit/debit option or by simply choosing PayPal at checkout.
