### ISSUE TITLE
Clubs Webhook

### ISSUE THREAD

**Issue by Sunni05** [Minehut/Meta#504]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord
**Describe the feature**

Allow us to make webhooks in the club, so if we have a club and a discord but we post events on the club for example, it would send a message into discord, similar to namelessmc webhooks, if this makes sense.
**How the feature is useful**

It is useful to those who have a club and a discord, you can announce things on the club and it announces into discord too!
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
Don't know how much control they have over the forums, so probably impossible to implement

**Comment by Blocksnmore** [comment]
Yeah, I don't think invision has support for that

**Comment by BennyDoesStuff** [comment]
It doesn't seem like this would be possible.
