### ISSUE TITLE
Server Type Chooser

### ISSUE THREAD

**Issue by CookieGuy123** [Minehut/Meta#507]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Add an option to choose between Spigot, Paper, Bukkit, Purpur, Tuinity, etc. It would be good and we could have our personal preference.

**How the feature is useful**
It is useful because then we can choose which server type we want (to reduce lag maybe.) It is also on other server hosting websites.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
This has been implemented somewhat recently with the ability to choose between Spigot and Paper. More version types will be added later.
