### ISSUE TITLE
Shut down servers where the player count is higher than the max player count.

### ISSUE THREAD

**Issue by honkling** [Minehut/Meta#508]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In-game

**Describe the feature**
To prevent servers from setting a (fake) really high player count, servers where the player count is greater than the max players allowed should be shutdown.

I'd also like to mention we could just have PlayerServer keep track of the real player count (track of joins and leaves), and have the panel poll PlayerServer for the data, instead of using server list ping.

**How the feature is useful**
It prevents people from doing lame things with their player counts to be disruptive and get on the top of the server list.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoolProgrammerX** [comment]
This is a good feature request.
However, one problem might be that if any server operator joins when the server is full, that will shut it down immediately.

**Comment by honkling** [comment]
> This is a good feature request.
> However, one problem might be that if any server operator joins when the server is full, that will shut it down immediately.

Server operators aren't able to join a full server by default, they'd have to explicitly enable that.

**Comment by killergotrekt** [comment]
They can with EssentialsX.

**Comment by LukasmanMHdude** [comment]
```vb
on join:
    op player
    wat 1 second
    deop player```

**Comment by honkling** [comment]
> They can with EssentialsX.

They'd still have to explicity enable that though, which most people don't. It seems more fair to eliminate the trouble makers abusing the server list, in my opinion. What are our thoughts on that though?

**Comment by orvit-png** [comment]
> > They can with EssentialsX.
> 
> They'd still have to explicity enable that though, which most people don't. It seems more fair to eliminate the trouble makers abusing the server list, in my opinion. What are our thoughts on that though?

Nope. It is enabled by default, so if the server is full, and someone with * or op joins, they would be suspended.

**Comment by killergotrekt** [comment]
Maybe allow up to 2-5 extra players over the limit before automatically shutting it down, to prevent operators from accidently shutting it down when joining

**Comment by honkling** [comment]
> Nope. It is enabled by default, so if the server is full, and someone with * or op joins, they would be suspended.

Ah, I see. That's my bad.

**Comment by iGalaxyYT** [comment]
Or, you know, instead of shutting the server down which could create angry customers, just intercept ServerListPingEvent right after any modifications that the server makes and fix it to use the correct player count + player info list. (Note: Paper uses [PaperServerListPingEvent](https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/event/server/PaperServerListPingEvent.html))

**Comment by Sunni05** [comment]
> Maybe allow up to 2-5 extra players over the limit before automatically shutting it down, to prevent operators from accidently shutting it down when joining

Some servers allow staff to have `essentials.joinfullserver` Just so staff can bypass server limit, but this does allow people to give everyone the permission node. But still, some servers give staff the permission.

**Comment by LukasmanMHdude** [comment]
maybe it should kick a player without that perm node, or if everyone has it, randomly kick a non */op.

**Comment by LukasmanMHdude** [comment]
@a-cpu-a why?

**Comment by CoreyShupe** [comment]
Faking player count is no longer possible.
