### ISSUE TITLE
Display ranks globally

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#51]
### Feature request

**Platform**
 All

**Describe the feature**

Display ranks / roles on all platforms. Ex. Show donor ranks on forums and discord.

**How the feature is useful**

This is useful because its another cosmetic perk for donors.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
Agree with it on forums, not with discord

**Comment by BennyDoesTheStuff** [comment]
I disagree with showing them on the Discord server.

**Comment by LukasmanMHdude** [comment]
> I disagree with showing them on the Discord server.

Once minehut fixes verifying users thru the panel/forums, I can see this being possible. If its easy to do with the mh bot, then I actually think this could be a cool idea, cause at the moment 😏
![image](https://user-images.githubusercontent.com/69743171/99316831-e0752880-2819-11eb-8c68-0d4b3a55eb75.png)

**Comment by DaRealMinecraftexpert** [comment]
Couldn't someone Easy Impersonate a Rank they don't have if it were on Discord with Nicknaming themselves?

**Comment by Blocksnmore** [comment]
I feel that to avoid that it could give a role instead of a nickname

**Comment by DaRealMinecraftexpert** [comment]
Roles Seem more Reasonable, and less Inpersonable.

**Comment by LukasmanMHdude** [comment]
Yea, that's what I'm sayting. ATM people add that t thair name so I just added Patreon to mine cause I can.

**Comment by CoreyShupe** [comment]
Seems like ranks in discord is available. Unsure if forums will work the same way. I'll reopen this once forums are a priority and we've done work on our forums.
