### ISSUE TITLE
Remove a feature from starboard.

### ISSUE THREAD

**Issue by Frostingly** [Minehut/Meta#510]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Discord

**Describe the feature**
 Remove the ability for people to unreact to a starboard message or atleast make the starboard message permenant unless a staff member removes it.

**How the feature is useful**
 Because it messes with the author's head and is simply annoying knowing there is a few people who just want to mess with you and your starboard message.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
What’s the point of a starboard if a post goes under the starred amount? We cannot control whether or not a user removes their reaction and it’s more confusing to have a starred message stay despite it being under the star count of 10.

**Comment by ahoulton** [comment]
> What’s the point of a starboard if a post goes under the starred amount? We cannot control whether or not a user removes their reaction and it’s more confusing to have a starred message stay despite it being under the star count of 10. 

Gonna have to agree with @Sniped here for the same reasons, that's not what a starboard is meant for.

**Comment by BennyDoesStuff** [comment]
Agreeing with what was said above, closing this.
