### ISSUE TITLE
Find command

### ISSUE THREAD

**Issue by ShadowSword21** [Minehut/Meta#515]
So I have been try to do /find command on minehut and it's not working at all here is the screenshot, please fix the command as well. (in the screenshot you see player not found but this guy really is on minehut just the command doesn't work at all)
https://i.imgur.com/5PZhReY.png

**Comment by Sniped** [comment]
Hey, thanks for creating this bug report, however you need to follow the format as shown [here](https://github.com/Minehut/Meta/issues/new?assignees=&labels=bug&template=bug_report.md&title=).
