### ISSUE TITLE
/restart doesn't restart the server, it just stops it

### ISSUE THREAD

**Issue by Prorickey** [Minehut/Meta#519]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

In game

**Describe the bug**

When you do /restart in console or in game, it just stops the server and doesn't actually stop it and start it again.

**To reproduce**
Steps to reproduce the behaviour:
1. Execute the command /restart in console or in game
2. Wait for server to completely stop
3. See it doesn't start and just says "Offline" as it's status

**Expected behaviour**

I would expect for /restart to stop a server, then start it again without any input from the user. This means all I would have to do is type /restart, wait and join the game again.
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
This isn’t really a bug with minehut. Mc stops the server when you run /restart and you need to manually reboot it

**Comment by Prorickey** [comment]
Oh my bad then
