### ISSUE TITLE
Tab auto-complete names of currently online friends when doing /find

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Meta#52]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game (Java, 1.13+ only)

**Describe the feature**

Tab auto-complete names of currently online friends when doing /find.

**Example:**
1. User types /find into chat window
2. User presses tab
3. List of online friends pops up above the chat window, allowing the user to tab through them to find who they are looking for.

**How the feature is useful**

This will allow us to easily run the /find command when we only need to find online friends.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
This is something which is pretty much impossible or otherwise not viable since we have multiple proxies and "online" players are hard to verify. Tab completion is handled in such a way where this is hard to scale well at all when having more than 1 friend.
