### ISSUE TITLE
Allow donors to do /ad when chat is muted.

### ISSUE THREAD

**Issue by Oiiink** [Minehut/Meta#520]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Java and Bedrock

**Describe the feature**

Allow people who buy ranks to do /ad whenever chat is muted. They can do /ad when the chat is muted and it's only for VIP+.

**How the feature is useful**

Since most of the time the people who didn't do anything gets punished whenever someone bots the server and can't advertise their server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
A ton of bots are now buying ranks to bot so it would be easily bypassed. When chat is muted you cant advertise for a reason

**Comment by awaffle1** [comment]
> A ton of bots are now buying ranks to bot so it would be easily bypassed. When chat is muted you cant advertise for a reason

Yes, but this feature would still be good. It's another perk for donators that Minehut could profit off of and if people are buying ranks for their bots, Minehut makes money, the botters lose money, and eventually the botters won't be able to buy more ranks for their bots and are stopped in their tracks. It also makes finding and muting/banning bots much easier for staff because ranked chat doesn't blend into regular chat like defaults chatting.

All in all I think this would be a great feature. Full support.

**Comment by LukasmanMHdude** [comment]
> Minehut makes money, the botters lose money, and eventually the botters won't be able to buy more ranks for their bots and are stopped in their tracks. 

Not rly a reason, trying to stop botters with a paywall is just dumb

> It also makes finding and muting/banning bots much easier for staff because ranked chat doesn't blend into regular chat like defaults chatting.

:wut:... It's rly not that hard to figure out whose botting when they're sending 50 messages a minute... Also, mods can look at chat logs on discord which makes it easier to find botters anyways. Using /ad as a way to find botters is dumber then just not having it in the first place.

> Yes, but this feature would still be good.

Also cute how you agree with him then come up with lackluster exuses to defend the issue

My turn:

Who was their on /ad day one? &k&0 bots EVERYWHERE! It seems the botters have enough money/time to be able to still bot even with a paywall and 8min cooldowns.

**Comment by mygizli04** [comment]
Might as well give them a bypass for chat mutes then. Chat being muted so regularly that this issue even exists is already ridiculous and this issue just wants mute bypass+

**Comment by BennyDoesStuff** [comment]
Not happening, sorry.
