### ISSUE TITLE
Stretch server name character limits

### ISSUE THREAD

**Issue by honkling** [Minehut/Meta#522]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Stretch the 4-10 character limit on server names to 3-12 (or higher). 

**How the feature is useful**
Allows players to pick more server names, as there are a lot of epic names out there that remain inaccessible because of the restrictive character limit currently out there. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
maybe we could go up to 15?

**Comment by honkling** [comment]
> maybe we could go up to 15?

the more characters the merrier really. maybe im just wanting to stick to multiples of 3 but 3-16 seems pretty clean

**Comment by killergotrekt** [comment]
2-16 i'll suggest that

**Comment by EarthAgar** [comment]
I think 12 would be a reasonable increase but the higher the limit the more creative our names can be. I've had many name ideas that just don't fit and it sucks because most names are taken and never used.

**Comment by not-3than** [comment]
I'd enjoy a limit of 3-12 so players won't have to type out /join thisserverisepic, because if your server name can contain that many words, that's too high of a character limit. A server name should be 1-2 words, not an entire sentence.

**Comment by tskopen** [comment]
I think it should be 15 I have a Minecraft server and I'm thinking of moving it to minehut and restarting here but my name won't fit by ONE LETTER ):

**Comment by honkling** [comment]
Why would this be closed if it were only temporary? It just seems like a huge slap to the face. Here's what you want, but only for a little bit.
