### ISSUE TITLE
People are allowed to make a server, never play on it, and keep that servers name indefinitely

### ISSUE THREAD

**Issue by ismoothytv** [Minehut/Meta#527]
### Feature request

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] This is not a bug report, support request or plugin request
- [x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x ] This issue does not contain any sensitive information 

**Platform**

Both
**Describe the feature**

minehut names are just running out, soon most servers will be forced to be named numbers/something nonsensical

my suggestion is that every month on the minehut panel you have to click something that makes sure you didnt just leave the server sitting, and if your time expires the person will have to pick a new server name if they come back to that server
**How the feature is useful**

it will allow people to use the server names that are otherwise taken by bot owned servers/servers that have been abandoned (which take up the majority of server names)
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by lolBoi9696** [comment]
or they could just extend the character limit?

**Comment by awaffle1** [comment]
> or they could just extend the character limit?

That wouldn't do anything about older names, just create more clutter. That is not a long-term solution

**Comment by LukasmanMHdude** [comment]
dupe of #189

**Comment by awaffle1** [comment]
> dupe of #189

Ooooo, yeah

**Comment by ismoothytv** [comment]
> dupe of #189

didnt see that

**Comment by LukasmanMHdude** [comment]
pls close the isse then

**Comment by ismoothytv** [comment]
how

**Comment by LukasmanMHdude** [comment]
:clown: like that
