### ISSUE TITLE
Allow server owners to view private messages sent between players in their servers

### ISSUE THREAD

**Issue by awaffle1** [Minehut/Meta#529]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In-game; java, bedrock

**Describe the feature**
When players in a server are exchanging messages (Messages sent to players not currently in the server are exempt), it would be a great feature for server owners to be able to view the messages sent between players in their server. It would help out a lot for moderation as there's no defined rule that I've seen that server owners deal with direct messages or Minehut staff deal with direct messages. This would clear up a lot of things and make server moderation more efficient.

Criteria for players who are able to view direct messages:
> Three options can be defined:
> > 1. All server operators can view direct messages sent via Minehut's direct messaging service (I'm not sure if Minehut is able to track players with operator status on a player server, however.)
> > 2. The account linked to the Minehut account that the server's dashboard is on (only toggleable if the Minehut account the server is connected to has an account linked)
> > 3. A list of players are able to view the direct messages (Either defined through a list in the panel or a cmd in-game)

Criteria for direct messages that are able to be viewed:
> 1. The direct message must be sent from someone in the server to someone else currently in the server.
> 2. Direct messages originating or being delivered to a player outside of the server are not shown to the players who are able to view the direct messages.

The program could possibly be opt-in at first, but after a while, it could become an opt-out program where server owners could disable the direct message viewing system if they want to.

**How the feature is useful**
Like stated before, this would help server owners moderate their servers better than what is just in public chat. This could also take a burden off of Minehut staff... if they are even moderating what's sent in direct messages on player servers.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
I feel the main reason why this doesn’t work is for privacy, you don’t know what a random person is gonna do with what you said in dms. Server owners not being able to see it gives players some privacy.

**Comment by awaffle1** [comment]
> I feel the main reason why this doesn’t work is for privacy, you don’t know what a random person is gonna do with what you said in dms. Server owners not being able to see it gives players some privacy.

Server owners being able to see direct messages in-game is common practice to help with moderation. The only other solution I see is to completely eliminate Minehut messages and only use messaging services in servers.

**Comment by Sunni05** [comment]
Let’s look at this in a different way, what if server owners could only see messages from players in their server to players in their server..?

**Comment by Sunni05** [comment]
Or just scrap the /msg command and let server owners make the command. Maybe replace it with /mmsg?

**Comment by awaffle1** [comment]
> Let’s look at this in a different way, what if server owners could only see messages from players in their server to players in their server..?

That's what I was trying to say- guess I made it a little too confusing lol

**Comment by awaffle1** [comment]
> Or just scrap the /msg command and let server owners make the command. Maybe replace it with /mmsg?

I also mentioned something of that nature at the end of the OP as a last-ditch effort if nothing else works for Minehut

**Comment by ahoulton** [comment]
This is a big data protection/privacy lawsuit just waiting to happen, this is why we don't allow this kind of thing to happen. No matter what, if something got shared in DMs and server owners shared it. It could spark uproar within the Minehut community. /msg is a well-known command to be managed by Minehut and any other command had a message function in it, then the user knows it could be logged to someone who wants to uses that information for dangerous/illegal reasons. And since /msg is known to not be shared with servers owners, people share information that they may not want the server owner or the staff to see. I'm sorry but I going to **downvote** this unless more useful information is shared by OP that makes sense with data protection/privacy laws.
