### ISSUE TITLE
Kick AFK players

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#53]
### Feature request

**Platform**
 In-game

**Describe the feature**

Kick AFK players in the lobby (30m timeout or so) or maybe just move them to a private AFK lobby or limbo of some sort until they move or type again (teleport them back to main lobby).

**How the feature is useful**

Gets real laggy when you're spawning in a cluster of 30 people.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Not going to kick, but we could move to an idle lobby.

**Comment by farwl** [comment]
Yeah an idle lobby sort of like something Hypixel has (limbo) would be nice.

**Comment by not-3than** [comment]
Moving to an idle lobby would be VERY nice. Lots of servers have people AFKing, which is taking up server resources that can be used for active players. Lots of servers like Gen servers have "80%" (according to a donator on FastGens) of their people afk, boosting their player count unnecessarily.

**Comment by LukasmanMHdude** [comment]
> Moving to an idle lobby would be VERY nice. Lots of servers have people AFKing, which is taking up server resources that can be used for active players. Lots of servers like Gen servers have "80%" (according to a donator on FastGens) of their people afk, boosting their player count unnecessarily.

this is for lobby...

**Comment by not-3than** [comment]
> this is for lobby...

my bad, it should be for in player-servers too, I didn't want to make another issue for it

**Comment by CoreyShupe** [comment]
This seems like a non-issue now that players are hidden by default if they haven't moved from spawn.
