### ISSUE TITLE
Custom Plugin Upload

### ISSUE THREAD

**Issue by Sunni05** [Minehut/Meta#532]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Web
**Describe the feature**

I’m honestly surprised there isn’t a issue already for this, but it’s a good idea for those people who bought premium plugins or just don’t want to wait hours for their plugin to get added from their request. I have bought litebans, but I can’t use it 😭 i want to use it because it’s best, but still.
**How the feature is useful**

It’s useful to those people who don’t want to wait hours for their plugin request to get  _ANSWERED_, there’s not even a guarentee it will get added. This might repel users.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Please Note**: _I could not find a issue for this, that does not mean there isn’t one. Please let me know if there is so I can remove this._

**Comment by Centrect** [comment]
I mean, it's a great idea, but don't expect it to be added any time soon. There's a lot of work that needs to be done to ensure the security of plugins etc.

**Comment by Sunni05** [comment]
Yes, I am aware.

**Comment by Blocksnmore** [comment]
Dupe of #5 the main reason mh doesn't want to add it atm is because of security concerns but it's deffo planned

**Comment by Sunni05** [comment]
Wait, but #5 is update the file extensions?

**Comment by MrTibo1** [comment]
They talked about this on the Discord [here](https://discord.com/channels/546414872196415501/546422616609783818/811707099485962280)

**Comment by Blocksnmore** [comment]
> Wait, but #5 is update the file extensions?

Correct, jar files would be filtered so thats why it's dupe of #5. I would look at that Tibo posted as it semi clarifies it

**Comment by Sniped** [comment]
#445 was closed for the same reason, so closing for dupe of #5 as @Blocksnmore said

**Comment by Sunni05** [comment]
> Correct, jar files would be filtered so thats why it's dupe of #5. I would look at that Tibo posted as it semi clarifies it

I’m going to leave this open due to the fact that this one is a more specific request, that one is more general.

**Comment by Sunni05** [comment]
Or not
