### ISSUE TITLE
Server Not Loading on the Website 

### ISSUE THREAD

**Issue by PrincessSmile** [Minehut/Meta#537]
### Bug report

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] I am NOT reporting a security vulnerability
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x ] This issue does not contain any sensitive information

**Platform**

**Describe the bug**
 The bug is that on the Minehut website (https://minehut.com/dashboard/home) me and a friend's third server won't load, instead it just shows where the server should be and a loading bar, which is quite annoying considering how we want to make adjustments to the server.

**To reproduce**
Steps to reproduce the behaviour:
I'm unsure how other's recreate this error but me and the friend running the server can recreate it by heading to the website, the third server just straight up won't load. So the steps is just how I recreate it
1. Go to 'https://minehut.com/dashboard/home' (logged into the problem account)
2. Click on 'Dashboard'
3. Scroll down to the third server slot
4. See error (infinity loading)

**Expected behaviour**
I expect the third server slot to show the server that is owned there.

**Device Information**

- Minecraft client (and version): Java edition (1.16.5)
- Web browser (and version): Google Chrome (88.0.4324.182 (Official Build) (64-bit))
- Operating system (and version): Windows 10 Home (ver. 1909)
- Minehut server name: Mithics.minehut.gg

**Screenshots**

![loading](https://user-images.githubusercontent.com/78091350/108740673-ead34c80-7503-11eb-9743-b8cb431f1152.PNG)

**Additional context**
 Both me and my friend co-own the server, we both have this issue.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**
I can reproduce it whenever on my lap top, and she can reproduce it whenever on his desktop. 

I hope that's enough info for a valid bug report, I also don't know if my friend and I are the only ones dealing with this issue.

**Comment by LukasmanMHdude** [comment]
🤡

**Comment by PrincessSmile** [comment]
> 🤡

very helpful -_- (sarcasm)

**Comment by LukasmanMHdude** [comment]
please don't make dupe issues, just reopen your old one

**Comment by PrincessSmile** [comment]
> please don't make dupe issues, just reopen your old one

I don't know how to

**Comment by DaRealMinecraftexpert** [comment]
> > please don't make dupe issues, just reopen your old one
> 
> I don't know how to

![image](https://user-images.githubusercontent.com/55472940/108746874-b9ea1c00-74f1-11eb-8ea8-5e066e850859.png)
This Button will change to a green "Reopen" Tag if your issue is closed. Click it, and it will Reopen your issue.

**Comment by PrincessSmile** [comment]
> > > please don't make dupe issues, just reopen your old one
> > 
> > 
> > I don't know how to
> 
> ![image](https://user-images.githubusercontent.com/55472940/108746874-b9ea1c00-74f1-11eb-8ea8-5e066e850859.png)
> This Button will change to a green "Reopen" Tag if your issue is closed. Click it, and it will Reopen your issue.

Ok this is actually helpful, thank you, I'll be closing this issue and reopening the original issue.
