### ISSUE TITLE
Server competition (Event Suggestion)

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#54]
### Feature request

**Platform**
 All?

**Describe the feature**

Host a server competition for the person who can make the best/most unique server in a one month period. (Kingdoms did one and the winner won $100 PayPal)

- If Kingdoms.gg could afford this, so could Minehut. Obviously don't make this a regular thing because that would cost too much, but one of these events would surely attract more players then all of the other events have.

- Maybe make 2nd/3rd place get rank upgrades or something since just first place for a reward isn't really fair.

- Probably more than a month to make your server. Maybe something closer to 2 months.

- You would have to enter your server in a form of some sort agreeing to be judged/entering the competition with your server name or something.

- Maybe disallow servers in the competition that do payouts

**How the feature is useful**

This is an interesting event because it encourages people to work hard on their servers.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
Hey, please DM the leader of the Events Team **CyberRyan#8381** on Discord for event suggestions, we don't handle those here at the moment. Thanks!
