### ISSUE TITLE
Drag and drop files

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#541]
### Feature request

**Checklist**
- I have read and agree to the README (found on https://github.com/Minehut/Meta)
- This is not a bug report, support request or plugin request
- I have searched the Issue Tracker to make sure this is not a duplicate issue
- This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
we should be able to drag and drop files to upload them to that current section of the file manager

**How the feature is useful**
it would be sick to drag and drop worlds, scripts, plugin configs, etc

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update.
