### ISSUE TITLE
Ability to remove GH embed 

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#546]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord
**Describe the feature**

Add a :x: reaction to the github issue links when the bot sends a hyperlink for mentioning an issue ie #7 where the author may react and the bot will delete the message
**How the feature is useful**

If the bot triggered and it shouldn’t have you can just remove the message 
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
This should probably go in meta feedback

**Comment by Blocksnmore** [comment]
Theres been feature requests here for stuff in the mh bot

**Comment by LukasmanMHdude** [comment]
ah ok

**Comment by MiginsMC** [comment]
I think this is cool, but it's not really used at all in the bot so it would seem a bit out of place here imo

**Comment by Sniped** [comment]
> I think this is cool, but it's not really used at all in the bot so it would seem a bit out of place here imo

Maybe we could add it to other embeds in the bot? What aspects of the bot do you think could use this?

**Comment by quick007YT** [comment]
> > I think this is cool, but it's not really used at all in the bot so it would seem a bit out of place here imo
> 
> Maybe we could add it to other embeds in the bot? What aspects of the bot do you think could use this?

could work with all the tags embeads as well

**Comment by MiginsMC** [comment]
> > I think this is cool, but it's not really used at all in the bot so it would seem a bit out of place here imo
> 
> 
> 
> Maybe we could add it to other embeds in the bot? What aspects of the bot do you think could use this?

I too think this would be cool with tags and other commands that use embeds like help and bp. Also, only the user who used the command (and maybe staff?) should be able to react.
