### ISSUE TITLE
Server names

### ISSUE THREAD

**Issue by tskopen** [Minehut/Meta#547]
Hi I asked on the forums and they told me to go here so yeah 

Why is the name limited for Minehut servers 10 and can it be bumped up to maybe 15

That's it Thanks :D

**Comment by Sniped** [comment]
I'm assuming that you're talking about the number of characters a Minehut server name can have. In that case, a feature request was put out for this and can be found on issue #522.

In the future, when suggesting new features, please use the format given to you for a feature request, thank you :)
