### ISSUE TITLE
Interactive Tutorials

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#549]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
A user could access a tutorials section, or maybe tips can come up on the screen somewhere? You press the button to start the tutorial and it actually shows you what to do in real time on your screen. This could be managing whitelist, server settings, ops, installing plugins, etc.

**How the feature is useful**
It's much simpler this way than to go through a YouTube video to do stuff.

**Comment by LukasmanMHdude** [comment]
TBH not really necessary. If I get what you saying, it would bassilly be an embedded video for things like whitelist, and defo not worth the effort to make all the steps and stuff that tell you what to click/what each button does.

**Comment by PundaChen** [comment]
#144 ?

**Comment by DaRealMinecraftexpert** [comment]
Could be, but this one is more Interactive, Like if someone was holding your hand as you did it for yourself rather than Reading it Word-for-word.

**Comment by Sniped** [comment]
Looking at both issues, I'd say that this issue is very similar to #144. The ideas mentioned in this issue should be added onto that issue.
