### ISSUE TITLE
ads

### ISSUE THREAD

**Issue by tskopen** [Minehut/Meta#550]
/ad in not only the lobby

Can /ad be cross server as in you can do /ad in your server and people get rewards for advertising your server sorta like /vote  but for minehut 
/friends already does this so cant /ad ?

Thanks sorry if this has been suggested i didn't see the forum if so

**Comment by MiginsMC** [comment]
Hey, thanks for making a suggestion, however you need to follow our format shown [here](https://github.com/Minehut/Meta/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=).

**Comment by LukasmanMHdude** [comment]
feel like as alr talked abt this and said it was a bad idea cause automation and making it to easy + more chat spam and stuff. Servers could say "Click here for a free 100 coins" that makes them execute the /ad message or whatever
