### ISSUE TITLE
/ad in minehut server

### ISSUE THREAD

**Issue by tskopen** [Minehut/Meta#551]
### Feature request

**Checklist**
- [ yes] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ yes] This is not a bug report, support request or plugin request
- [ yes] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ yes] This issue does not contain any sensitive information 

**Minecraft Java And Bedrock**

**make it for you can do /ad in your server and you can set up rewards systems sorta like /vote**

**It Helps servers advertise without leaving the server and people advertise the server more  and they get rewards for it :D**

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
gonna leave this link here https://github.com/Minehut/Meta/issues/550#issuecomment-798959423

**Comment by CoreyShupe** [comment]
> feel like as alr talked abt this and said it was a bad idea cause automation and making it to easy + more chat spam and stuff. Servers could say "Click here for a free 100 coins" that makes them execute the /ad message or whatever

Wanted to just point out this isn't necessarily true, I don't think there's currently a way to run proxy commands and if it were added it would need to be like that. It's more of an issue of "well, do we really want to take up more command space from servers", putting in this proxy command would reserve even more space in the "we can't override x command" like `/s` or `/staffchat`. I don't think /ad has enough merit to be in the necessary enough to take up that space.

**Comment by Prorickey** [comment]
This is a great idea and I would love to see it happen

**Comment by tskopen** [comment]
> gonna leave this link here [#550 (comment)](https://github.com/Minehut/Meta/issues/550#issuecomment-798959423)

you can make bots in minehut lobby to do /ad already there's always ways to cheat the system

**Comment by tskopen** [comment]
> > feel like as alr talked abt this and said it was a bad idea cause automation and making it to easy + more chat spam and stuff. Servers could say "Click here for a free 100 coins" that makes them execute the /ad message or whatever
> 
> Wanted to just point out this isn't necessarily true, I don't think there's currently a way to run proxy commands and if it were added it would need to be like that. It's more of an issue of "well, do we really want to take up more command space from servers", putting in this proxy command would reserve even more space in the "we can't override x command" like `/s` or `/staffchat`. I don't think /ad has enough merit to be in the necessary enough to take up that space.

could there be a way to turn it on and off? like in options or smth

**Comment by quick007YT** [comment]
> > gonna leave this link here [#550 (comment)](https://github.com/Minehut/Meta/issues/550#issuecomment-798959423)
> 
> you can make bots in minehut lobby to do /ad already there's always ways to cheat the system

not a good reason lol, saying "well you can already cheat the system so i give up"

**Comment by tskopen** [comment]
> > > gonna leave this link here [#550 (comment)](https://github.com/Minehut/Meta/issues/550#issuecomment-798959423)
> > 
> > 
> > you can make bots in minehut lobby to do /ad already there's always ways to cheat the system
> 
> not a good reason lol, saying "well you can already cheat the system so i give up"

Not what i meant but there is ways to cheat the system. i never said we shouldn't do things to stop people from doing that .
I'm just saying that we shouldn't not do things cause people can scam people with it people can say  DO /join "server" FOR FREE COINS or smth like that servers already advertise with Paypal rewards
my point is making a /ad available in the server and a option for the server owners to give auto rewards like that will help servers advertise

**Comment by iUntreated** [comment]
I think I'm going to have to disagree with this. Sure, it'd be a great thing for servers; however, I just see more of the popular servers being in chat with /ad because they get rewards on the server. If anything, it would flood out the smaller servers that are trying to gain players. The idea of rewards for advertising is cool, but it can cause problems.

**Comment by tskopen** [comment]
We could have a limit of one vote with rewards only every 24 hours like topg and stuff or limit the aomunt of server reward votes  

> I think I'm going to have to disagree with this. Sure, it'd be a great thing for servers; however, I just see more of the popular servers being in chat with /ad because they get rewards on the server. If anything, it would flood out the smaller servers that are trying to gain players. The idea of rewards for advertising is cool, but it can cause problems.

**Comment by Sniped** [comment]
> could there be a way to turn it on and off? like in options or smth

I believe it would still steal from the possible commands a server could have, regardless of whether or not the command could be turned on and off.

I personally think that bumping a server would be better than introducing /ad as a proxy command to "vote" for that server. Bumping servers as a way of advertisement was suggested in issue #352.

**Comment by lolBoi9696** [comment]
Maybe instead of this a actual vote plugin on minehut to add /vote and stuff and u can maybe make Ur server vote able like maybe they could be a page on minehuts website seeing all the top voted servers and stuff and maybe u need to put like a server API key u get from creating a vote page on minehut and in the plugins config and you can set rewards and stuff.  Why its bad to add /ad in to servers may cause more spam in lobbies so I don't agree with it being a feature idk u should get the point!
