### ISSUE TITLE
"Supporter" Role in Minehut Clubs

### ISSUE THREAD

**Issue by Centrect** [Minehut/Meta#552]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**

Website (Forums)

**Describe the feature**

Add a "Supporter" Role to the forum clubs, similar to the "Moderator" and "Leader" roles on the forum clubs.

**How the feature is useful**

This could be useful if server owners want to make a dedicated area for supporters, such as a private forum or maybe you have to be a supporter to apply for staff, etc.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
> be a supporter to apply for staff, etc.

pay money to be staff... gud idea ima use that for my next server

**Comment by farwl** [comment]
Ooh yes I like this idea.

**Comment by iUntreated** [comment]
Seems like a cool idea; could be introduced like the "Veteran" and "Rookie" forum titles there are now.

**Comment by Sniped** [comment]
I'm in support of this idea, however unsure of the possibility, @BennyDoesStuff do you think this would be possible?

**Comment by Sniped** [comment]
Appears to not be possible on our end, rather would need an Invision developer to implement it.
