### ISSUE TITLE
Stop Advertisement on Paid Servers

### ISSUE THREAD

**Issue by LiamiTheGod** [Minehut/Meta#559]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

in-game
**Describe the feature**

Stop broadcasting advertisements on paid servers
**How the feature is useful**

me and a lot of other server owners pay money for servers on mine hut, our players and staff shouldn't have to deal with advertisements from mine hut themselves, you guys don't even offer a lag-free experience so at least stop advertising on paid servers, attached below is just one of the regular advertisements my staff and players have to deal with
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**
![can you not](https://user-images.githubusercontent.com/80356634/111837080-3e606c80-88ef-11eb-99fa-11911c43322e.png)

**Comment by Sniped** [comment]
I'm unsure if this is intentional or not, I believe it's a bug, @CoreyShupe can you confirm?

**Comment by CoreyShupe** [comment]
> I'm unsure if this is intentional or not, I believe it's a bug, @CoreyShupe can you confirm?

This isn't an automated broadcast. It would be intentionally sent there unless he didn't intentionally send it to all servers. Then it would be a bug.

**Comment by drtshock** [comment]
Not a bug, just testing out different ways to promote things and see how effective they are. I hear you, we won't broadcast on paid servers next week.
