### ISSUE TITLE
Tab complete /world

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#561]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java

**Describe the feature**
tab complete the /world command to show a list of the worlds on the server

**How the feature is useful**
would speed up traveling between worlds

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iUntreated** [comment]
Agree with this, should be fairly easy and simple to do. Would love to see it added.

**Comment by farwl** [comment]
+1

**Comment by quick007YT** [comment]
would also be nice to see #269

**Comment by BennyDoesStuff** [comment]
This command doesn't exist anymore so this issue doesn't apply.
