### ISSUE TITLE
Marketplace showcases

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#562]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
YouTube videos should be made/linked showcasing minigames and maps in the marketplace

**How the feature is useful**
This could make users more confident in purchasing from the marketplace.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Yep we have a video portal on the roadmap.
