### ISSUE TITLE
Better Marketplace Listings

### ISSUE THREAD

**Issue by quick007YT** [Minehut/Meta#563]
### Feature request

**Platform**
Website

**Describe the feature**
Please make these better, why are these being listed lol?

![image](https://user-images.githubusercontent.com/69743171/111919471-65ca4d00-8a47-11eb-80ed-c8da2425205d.png)
We really don't need to encourage gen servers thank you

![image](https://user-images.githubusercontent.com/69743171/111919487-7c70a400-8a47-11eb-8371-59293637c04b.png)
Are you serious. I could probably recreate these in less then 10 minutes with more customizations.

Also, the other maps look decent, although if I could choose between a free spigotMC one or a mh one, you know which one I'd choose

**How the feature is useful**

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
I'm confused at what you mean by "make these better". What are **you** personally looking for in marketplace listings? I personally don't see the problem with wanting to cater to an audience with various tastes, such as the recently booming Dupe genre and GenPvP genre.

**Comment by drtshock** [comment]
Funny enough those were the 2 most popular ones over the weekend ;) 

We'll open up applications to become a creator soon enough!

**Comment by quick007YT** [comment]
> Funny enough those were the 2 most popular ones over the weekend ;)

wtf I want in. Would love to be a creator, not over 18 though.

**Comment by farwl** [comment]
Wish I could apply for creator :(

**Comment by farwl** [comment]
These resources do look pretty basic for an update that's been delayed for months though.
