### ISSUE TITLE
Allow /ad when chat is muted

### ISSUE THREAD

**Issue by Oiiink** [Minehut/Meta#564]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java
**Describe the feature**

I believe whenever chat is muted their should be a way for them to advertise their server
**How the feature is useful**

Minehut stands out from other server hosts for their community. If chat is muted it makes it hard to grow that community and it basically makes it so the thing that made MH stand out the most just gone. It's basically like a town known for hot springs without any hot springs. Sometimes chat is getting muted just because of "e" spam or whatever it is. There should be a way for them to disable or enable /ad when chat is muted. 

Bots: I know that bots end up using /ad on a server which is why there should be a disable ad feature when chat is muted due to bot spam. I don't think it should be muted whenever people end up spamming "e". A way to fix that would be by adding a setting.

Settings: Two new settings: Disable ads (disable all ads inside of your chat), Disable chat (disable chat but allows advertisements), I believe they both should also be toggleable at the same time which can fully disable chat or half and half disable chat.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
The main reason chat is muted is because of the swarms of bots advertising a server. If the ads were to be allowed while chat is muted there would be bots left and right in ads instead of normal chat.

**Comment by Oiiink** [comment]
That's why I said their should be a way for them to disable /ad's and allow it.

**Comment by Sniped** [comment]
You already made a similar issue on this (https://github.com/Minehut/Meta/issues/520), if you want, you can edit that issue to include everyone being able to use /ad when chat is muted rather than just donors.
