### ISSUE TITLE
Ability to delete GitHub issues

### ISSUE THREAD

**Issue by Oiiink** [Minehut/Meta#565]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

Delete your issue to prevent accidental duplicates.
**How the feature is useful**

I think that you should be able to delete your GitHub issue. Maybe you realized after posting it that someone ended up already posting it. It would also make Meta Staff's jobs a lot easier because they wouldn't have to close it because it's a duplicate of something else.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Oiiink** [comment]
I accidentally typed the name of the issue wrong. I was wondering if anyone could change it to Delete GitHub Issues or something.

**Comment by Sniped** [comment]
Only admins are able to delete issues, and we're not going to be giving everyone admin access to the Minehut Meta repository. You can just close your own issue and we'll mark it with appropriate labels.
