### ISSUE TITLE
Folders tree-view sidebar | Bookmarked folders/paths in File Manager

### ISSUE THREAD

**Issue by AyhamAl-Ali** [Minehut/Meta#567]
**Checklist**
- [√ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ √] This is not a bug report, support request or plugin request
- [ √] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ √] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

We often want to go to specific path in the File Manager such as `plugins/Skript/scripts/` without the ability of having paths in URL *(as I once suggested and got denied a year or more ago)* which makes the File Manager go to the root everytime you reload/close the tab or your browser crashes etc, it is at least a good idea to allow using a built-in Bookmarks sidebar so that we can go to specific folders/paths quicker.

OR maybe add a compact folders tree-view sidebar so that we can navigate folders faster

**How the feature is useful**

Navigating folders easier, go to specific oftenly used folder quicker.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007YT** [comment]
#16 dupe

**Comment by AyhamAl-Ali** [comment]
Oh, apologize I probably didn't notice that when searching
