### ISSUE TITLE
Addition of PlugMan features into PlayerServer.

### ISSUE THREAD

**Issue by CoolProgrammerX** [Minehut/Meta#572]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game, Java

**Describe the feature**

It would be very useful if PlayerServer had in-built option to enable, disable, load, unload or reload plugins just how PlugMan works.

**How the feature is useful**

At this moment, I'm only thinking from my point of view, and I honestly don't know if other's would agree with this since it's not quite "necessary" to be a feature, but could be useful. Since PlugMan can't be added (due to its power of being able to disable plugins like PlayerServer), I think this could be a good feature for PlayerServer as a plugin.
Thanks a lot.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by xenitrogen** [comment]
I don't see the point in having the ability to reload plugins since you can't add custom plugins to minehut.

**Comment by quick007YT** [comment]
loading/reloading plugins while the server is online can cause serious serverside issues, I don't think this is a good idea

**Comment by mygizli04** [comment]
The reason they disallowed reloading is because it breaks plugins, plugman is almost as bad as reload (except on a slightly less scale ) so i doubt that's going to happen

**Comment by honkling** [comment]
well reloading using /reload is much worse because it also refreshes the world and player profiles

**Comment by quick007YT** [comment]
iirc /reload is blocked

**Comment by CoolProgrammerX** [comment]
Might be useful in the future to instantly load/unload/reload/enable/disable custom plugins? Not sure.


> iirc /reload is blocked
It's blocked for players, still works via console.

> loading/reloading plugins while the server is online can cause serious serverside issues, I don't think this is a good idea
Shouldn't cause serious issues, but just for testing purposes?

**Comment by BennyDoesStuff** [comment]
The player servers plugin doesn't exist anymore so this issue doesn't apply. You can now install custom plugins anyways so you can now directly use PlugMan if you so desire.
