### ISSUE TITLE
New ideas for the Skript plugin

### ISSUE THREAD

**Issue by GearsEngine** [Minehut/Meta#579]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Minecraft Java Edition and the web panel.

**Describe the feature**
The Skript plugin is so cool, I use it so much for admin tools and new player commands!
It works REALLY well on Minehut, but I think it should have new features because Minehut has it limited _(Note: If I don't realize some removal of features is for security reasons, please tell me!)_

1. Add more 'on command "/whatever":' event functionalty like 'on command "/friend": cancel event', so you could have something like a custom friend system.
2. Maybe remove the /skript:command thing for when you create a command, BUT don't remove things like /skript:skript and /skript:sk.
3. Add more file functionality (I understand that this is a risk, but Minehut can just create their own fork of things, and make it more limited.) Probably should include adding SkUtilities and skript-yaml.
4. Add functionality in vanilla Skript for tablists and scoreboards, I don't want to have to use SkRayFall and SkQuery for these things.
5. Add support for datapacks, so you can just do something like 'command /loadpack: trigger: load datapack from file "https://minehut.com/url/datapack.zip"' I would like this so I don't have to copy and paste my datapacks or use a world upload. (This could be a security risk, because @drtshock has said that .zip files are what .jar files are, but this could be limited to only accept things like .mcfunction files in the .zip.)
6. Add functionality for an arguments list, so you can use 'command /command ["my", "cool", "command"]' to have arguments show up where the command suggestions show up. This is already a thing IN THE PLAYER AND OFFLINEPLAYER ARGUMENT, but you can't get custom text.

I really hope some of these get added in some way _(If I'm being stupid and some of these features exist already, please tell me!)_

**How the feature is useful**
It will have a lot of nice features and I think it will be a nice addition to Skript. It will really help everyone that develops scripts for Skript.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
Skript is not maintained by minehut, look here for skript feature requests: https://github.com/SkriptLang/Skript

**Comment by quick007YT** [comment]
read https://github.com/Minehut/Meta/issues/578#issuecomment-814570495
