### ISSUE TITLE
Disallow ad bots

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#58]
### Feature request

**Platform**
 In-game

**Describe the feature**

Disallow bots in the lobby that automatically advertise servers every x seconds/minutes. Even if they aren't spamming / flooding, it's still a bot.
![](https://cdn.discordapp.com/attachments/592130982451216402/715059211146362930/unknown.png)

**How the feature is useful**

It makes the chat clean.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment]
I thought there was a feature that prevented duplicate messages? Maybe they should increase the delay between?

**Comment by BennyDoesTheStuff** [comment]
I feel like this isn't specific enough. I'm going to go ahead and close this issue, please be more specific on a possible solution for suggestions like this. I do have a proposal for a potential way to handle this, so I'll probably make an issue for that.
