### ISSUE TITLE
Linking Dev Minehut account and the main Minehut account together for sharing credits

### ISSUE THREAD

**Issue by BndEgl** [Minehut/Meta#580]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
 Website

**Describe the feature**

I want to be able to link my Dev Minehut Account and the Main Minehut Account together. Not much other detail to add to it...

**How the feature is useful**

This feature would benefit all the players who use/will use the Dev Minehut because it will allow us to share the credits from the main account into the dev account so that we can increase the plugin limit by upgrading the servers. This would be a really nice feature to see (also, maybe a link to the dev minehut dashboard accessible from the menu on the left of the main minehut dashboard and vise versa for dev minehut so we can easily navigate between the 2)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by ahoulton** [comment]
> 
> ### Feature request
> 
> **Checklist**
> 
>     * [x]  I have read and agree to the README (found on https://github.com/Minehut/Meta)
> 
>     * [x]  This is not a bug report, support request or plugin request
> 
>     * [x]  I have searched the Issue Tracker to make sure this is not a duplicate issue
> 
>     * [x]  This issue does not contain any sensitive information
> 
> 
> **Platform**
> Website
> 
> **Describe the feature**
> 
> I want to be able to link my Dev Minehut Account and the Main Minehut Account together. Not much other detail to add to it...
> 
> **How the feature is useful**
> 
> This feature would benefit all the players who use/will use the Dev Minehut because it will allow us to share the credits from the main account into the dev account so that we can increase the plugin limit by upgrading the servers. This would be a really nice feature to see (also, maybe a link to the dev minehut dashboard accessible from the menu on the left of the main minehut dashboard and vise versa for dev minehut so we can easily navigate between the 2)
> 
> **Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

Minehut Dev is meant for testing new stuff which will be on the main network, I don't think this will happen.

**Comment by CoreyShupe** [comment]
As said above the dev network is unstable and not for people to really be using. We don't officially support it (as in our support team) and we don't guarantee it will be up, or work at any time. We also give free credits out for testing in certain situations which can't be transferred / used on live.

This won't happen.

**Comment by xenitrogen** [comment]
They give out credits on the dev network to be used on the dev network for testing..
