### ISSUE TITLE
the bug that make minehut so so lugy

### ISSUE THREAD

**Issue by trprokey** [Minehut/Meta#589]
do you remember that lagy days some pepole are making so so much lag
i found how day made
they made with  crazy enchantments plugin multi arrow ench
that plugin make that max trow 29000 arrows in 1 time and they use that you need to delete that ench from crazy enchantements plugin
the plugin: https://www.spigotmc.org/resources/crazy-enchantments.16470/

**Comment by killergotrekt** [comment]
please use the format

**Comment by MiginsMC** [comment]
As @killergotrekt said, please use the [format](https://github.com/Minehut/Meta/issues/new?assignees=&labels=bug&template=bug_report.md&title=) given to you when making a bug report. I'm giving you a day to edit it to conform to the format, otherwise I will be closing it.

**Comment by quick007** [comment]
@trprokey

**Comment by Sniped** [comment]
Closing due to failure to conform to format
