### ISSUE TITLE
Remove Marketplace Ads on Servers with Purchased Packs

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#593]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java & Bedrock
**Describe the feature**

Remove the Minehut MarketPlace ads if the user has purchased a pack from the market place.
**How the feature is useful**

Because some server owners don’t want minehut’s ads. They are quite annoying.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by lolBoi9696** [comment]
Just ignore the ads??

**Comment by Blocksnmore** [comment]
Semi dupe of #483

**Comment by Sniped** [comment]
> Semi dupe of #483

This issue relates to removing marketplace advertisements on servers that have previously purchased a pack, so I wouldn't really call it a dupe.

**Comment by BennyDoesStuff** [comment]
Marketplace advertisements should only be sent to free servers.

**Comment by Tringlle** [comment]
> Marketplace advertisements should only be sent to free servers.

That's not what this is...

If you have a purchased pack like "Moderation Tools" on your server, don't send the marketplace advertisments.

**Comment by Tringlle** [comment]
@BennyDoesStuff
