### ISSUE TITLE
Show rank in /find

### ISSUE THREAD

**Issue by drtshock** [Minehut/Meta#6]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In game

**Describe the feature**

When doing /find, we should show a user's rank if they have one.

**How the feature is useful**

Lets users flex their ranks more.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by liami101** [comment]
Good idea

**Comment by Sniped** [comment]
Closing as this has been implemented
