### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by Desfile** [Minehut/Meta#60]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Within the file manager of the server panel add syntax highlighting to corresponding file types (such as .sk)

**How the feature is useful**

Allows for easier file editing and is helpful to server developers.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
Skript highlighting with vuex seems very difficult, but I will investigate what it may take with our new syntax highlighting. It may be a configuration file or it may not be possible. I will return to this issue once I know more.

**Comment by BennyDoesStuff** [comment]
This is now implemented as of the recent file manager update.
