### ISSUE TITLE
Trampoline

### ISSUE THREAD

**Issue by calcium2k** [Minehut/Meta#600]
### Feature request

**Checklist**

- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
Both.

**Describe the feature**

We want trampolines back in the lobby.

**How the feature is useful**

It is fun and people liked it.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
This could fit under #599
