### ISSUE TITLE
FastAsyncWorldEdit Schematic Download

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#601]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Both
**Describe the bug**

When using /dl schematic with FAWE it will say “Schematic Doesn’t exist.”
**To reproduce**
Steps to reproduce the behaviour:
Download FAWE, restart server, make schematic, attempt to download
**Expected behaviour**

I expect it to download without issue.
**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 
Client: latest
Browser: Chrome
OS: Windows 10 Latest
MHSrv: SunniDev
**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
This also occurs with /ul when you upload schematics (last i checked)

**Comment by quick007** [comment]
Can reproduce

**Comment by pop4959** [comment]
For some extra context here, downloading schematics should work perfectly fine, however they're currently installed to the WorldEdit plugin folder, and not FastAsyncWorldEdit.

That being said, this should probably be viewed as more of a feature request (to allow downloading schematics for use with FastAsyncWorldEdit) instead of a bug.

**Comment by drtshock** [comment]
Any suggested implementations?

1. We add disclaimer that this only works for WE not FAWE
2. We search in the WE dir first and then FAWE
3. You use the panel to download them once we have custom plugins

**Comment by quick007** [comment]
#2 sounds nice

**Comment by pop4959** [comment]
#1 and #3 work

For #2 I think best would probably be to install to one or both directories (if both exist) so that users can use either plugin to copy it. This would of course result in potential duplication but schematic files are typically very small.

**Comment by Tringlle** [comment]
I think #2 would be better

**Comment by Tringlle** [comment]
So I did find (maybe) a solution. You can just change the schematic folder location in config-legacy.yml to a new folder called “WorldEdit” and a sub folder called “schematics”

**Comment by BennyDoesStuff** [comment]
The /download command doesn't exist anymore so this issue doesn't apply. You can now directly download files from the file manager anyways as an alternative.
