### ISSUE TITLE
Marketplace ideas 

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#603]
**Platform**
Market

**Describe the feature**
Add older minehut lobbies and event maps to market 

**How the feature is useful**
People may want to revisit memorable and nostalgic places. The maps are already made, and wouldn’t be much of a hassle just to put them on. They could even be sold for a few credits.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment]
This would go with https://github.com/Minehut/Meta/issues/403, in fact it was already proposed that it could be done on the market on that issue.

**Comment by Shlba** [comment]
> This would go with #403, in fact it was already proposed that it could be done on the market on that issue.

I sent that suggestion a while ago, and that one was focused on releasing them on discord. This one was focused on market...

**Comment by DaRealMinecraftexpert** [comment]
Look at Trent's Reply to 403.

It says that to the MH Market may happen
