### ISSUE TITLE
Allow Uploading Folders In The File Manager

### ISSUE THREAD

**Issue by BanditEagle** [Minehut/Meta#604]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
 Forums

**Describe the feature**
 Ability to upload folders into the File Manager

**How the feature is useful**
 This feature is very helpful for people who want to upload things such as already-set-up skripts which are in many folders which have a lot of skripts inside of each of them, or especially for people who want to upload datapacks as they will need to upload all of the files individually and create folders for each of them, which takes a lot of time. This would save a lot of time for people and would help out everyone!

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
This is coming with custom plugins.
