### ISSUE TITLE
Skript

### ISSUE THREAD

**Issue by OGContent** [Minehut/Meta#605]
### Bug report

**Checklist**
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] I am NOT reporting a security vulnerability
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information

**Platform**

Idk its a skript plugin issue so it both
**Describe the bug**

* inserting skript script *
on command:
  cancel event
  * end of the script *
  so if I do this the server will have a longer time stopping, and not saving, and it will eventually stop but kicks you out of the game and says "[Proxy] error"
**To reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by killergotrekt** [comment]
shouldn't plugin issues be on the forums?

**Comment by OGContent** [comment]
> shouldn't plugin issues be on the forums?

idk man a helper sent me to the meta

**Comment by BurningBrimstone** [comment]
> 
> 
> shouldn't plugin issues be on the forums?

No. Bug reports for Minehut Forks of plugins go here on the GitHub, as the Skript fork does not have an issues page. While plugin suggestions and updates go on the forums.

In regards to the bug report:

I personally can't replicate this behavior both on a Minehut server, nor on a localhost running PaperMC 1.16.5-603 and Skript version 2.5.3. Both being clean installations with no other plugins or scripts.

Once the script is created and reloaded, no commands function (as intended), and when I stopped the server, the server stopped as normal, the world saved, and nothing abnormal is present in the logs.

If there's anything wrong with my recreation let me know, but as of now, I cannot reproduce the bug. @OGContent

Script used:
`on command:
    cancel event`

**Comment by pop4959** [comment]
If you find an issue with our plugin forks you can post about that on the forum as well. I'm in charge of review as well as updating those forks. Before posting, I would also recommend checking if this is an issue in the official release of Skript (with the same version as Minehut is using). If it is, you should still report it to the official issue tracker.
