### ISSUE TITLE
Add more plugin slots for the free plan servers so people can  improve their servers 

### ISSUE THREAD

**Issue by herofireYT** [Minehut/Meta#606]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

**How the feature is useful**

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007** [comment]
won't happen, also how did you manage to screw the templete up this much

**Comment by BluBoy3ch0** [comment]
> won't happen, also how did you manage to screw the templete up this much

*template :)

**Comment by Sniped** [comment]
While this issue has the template, the author only put their suggestion in the title rather than going into detail on it using the template. Please fill out the template when making an issue, I'll give you one day to do this, otherwise your issue will be closed.

**Comment by herofireYT** [comment]
> While this issue has the template, the author only put their suggestion in the title rather than going into detail on it using the template. Please fill out the template when making an issue, I'll give you one day to do this, otherwise your issue will be closed.

uhh im new sooo ....

**Comment by MiginsMC** [comment]
> > While this issue has the template, the author only put their suggestion in the title rather than going into detail on it using the template. Please fill out the template when making an issue, I'll give you one day to do this, otherwise your issue will be closed.
> 
> uhh im new sooo ....

Feel free to dm one of our Meta Staff (see users in Meta Discord with the rank) for assistance.
