### ISSUE TITLE
Bottom area of page unresponsive due to ads

### ISSUE THREAD

**Issue by awaffle1** [Minehut/Meta#608]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website

**Describe the bug**

When an ad appears, closing it using the X- both of them if another pops up- yields 1 of 3 results:
1. The ad just straight up doesn't disappear and the entire row where the ad is- from your left end of the browser to the right- becomes unresponsive and no buttons are able to be used or pressed there. Happens about 30% of the time.
2. The ad disappears, but the unresponsive part is still there and it's even more infuriating because you can see the buttons but YOU JUST CAN'T PRESS THEM AAAAAAAAAA- this happens about 60% of the time
3. The ad disappears and the part that is usually unresponsive is responsive again. The good ending. Happens about 10% of the time. Feels more like never.

**To reproduce**
Steps to reproduce the behaviour:
Step 1: Turn off your adblocker
Step 2: Go to the dashboard
Step 3: Close the ad
Step 4: Scream in pain when either 1 or 2 happens to you

**Expected behaviour**

The ad should disappear and I should be able to interact with the buttons at the bottom of the screen.

**Device Information**

- Web browser (and version): Google Chrome 90.0.4430.93 (Official Build) (64-bit) (cohort: Stable) (from chrome://version)
- Operating system (and version): Windows 10 Home 10.0.19041 Build 19041

**Screenshots**

**Additional context**

I discovered this issue while trying to upload a file. I can't access the upload button when this error is happening. A good fix for this one could just be to raise the buttons up or let me scroll up more.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by quick007** [comment]
https://adguard.com/en/welcome.html

**Comment by awaffle1** [comment]
> https://adguard.com/en/welcome.html

yeah yeah yeah, I have an adblocker, I just don't like using it on sites I regularly visit

**Comment by drtshock** [comment]
Yes this is an issue with one of the sticky footer units we use unfortunately :\ I'll report it again to see if we can get it resolved.

**Comment by awaffle1** [comment]
Thanks!

**Comment by drtshock** [comment]
There's a pull request waiting for code review. This should be deployed this week.

**Comment by awaffle1** [comment]
> There's a pull request waiting for code review. This should be deployed this week.

Okay, thank you!

**Comment by drtshock** [comment]
The fix is in production.
