### ISSUE TITLE
Welcome message for new users

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#61]
### Feature request

**Platform**
 In-game

**Describe the feature**

Send a message to new users upon joining saying something along the lines of "Create your free server at minehut.com"

**How the feature is useful**

Helps new users.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
Implemented.
