### ISSUE TITLE
Update custom plugins via link

### ISSUE THREAD

**Issue by quick007** [Minehut/Meta#611]
### Feature request

**Platform**
Web (core)

**Describe the feature**
Being able to put a spigot plugin (and using https://spiget.org/ to download it) or a direct download link, it would auto-update. Minehut has the capability to do this, but they haven't done it because of security issues. 

The reason for the spiget API is you could add links for already existing plugins/plugins you add from spigot and they could auto-populate with information.

**How the feature is useful**
1: It goes with my goal of trying to allow people to push directly from their pc via GitHub to minehut directly
2: You don't have to wait for Pop to update plugins that are less used, and we'll always have the latest version - even a ce (cutting edge) version if you so wish.
3: People could buy plugins and have them auto-update as well.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
We review plugins before they're able to be installed so we won't be doing it for that side of things. Once we have custom plugins, server owners will be able to upload their own plugins.
