### ISSUE TITLE
Give Default ranks pink color when they /ad

### ISSUE THREAD

**Issue by XePup** [Minehut/Meta#614]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Game

**Describe the feature**

Give Default Ranks the pink ad color. Its like VIP rank but instead of white its pink.

**How the feature is useful**

It will encourage default ranks to use /ad because it will be a benefit reaching spotting out. While making lobbies less spammed.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
I don’t see how this would reduce spam in the slightest. Also this would likely not be good for ranked players as pink would stand out more compared to white

**Comment by XePup** [comment]
it would make Defaults be recognized more for there ads. Cause /ad or not there adds don't stand out.

**Comment by BluBoy3ch0** [comment]
Isn't the point to make it so that you have to pay to be more visible, giving defaults the ability to be recognized kind of defeats this purpose.

**Comment by drtshock** [comment]
I think if anything, this would take away from the perks that we give people that pay for ranks.

**Comment by XePup** [comment]
now that i think about it, MH just needs and auto mute for saying "/join" in the chat. 

if thats done we don't need to add a insentive
