### ISSUE TITLE
Minehut Forums Bug

### ISSUE THREAD

**Issue by M1nordragonMC** [Minehut/Meta#615]
![Screenshot (92)](https://user-images.githubusercontent.com/81280361/116828547-5ae9f880-ab6d-11eb-9cd0-336b3e7d5fb0.png)
It has been showing this screen for the past 20 mins.

**Comment by Blocksnmore** [comment]
Unable to reproduce, try clearing your cache ![https://blocksnmore.is-inside.me/M7CCbUi5.png]
Also follow the format smh.

**Comment by Sniped** [comment]
This issue completely ignores the format and has a vague title. Please use the included format when creating a bug report and I encourage you to make your title more specific to the bug you're reporting. I'm going to give you a day to do this, otherwise I'll be closing this issue.

**Comment by Blocksnmore** [comment]
@Sniped you should probably close this

**Comment by Sniped** [comment]
> @Sniped you should probably close this

Forgot about this, closing now due to failure to follow the format.
