### ISSUE TITLE
Access to view console output or get .prlog or any log/error files in the file manager.

### ISSUE THREAD

**Issue by Abraxwe** [Minehut/Meta#616]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

**How the feature is useful**

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BluBoy3ch0** [comment]
#39
