### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by OGContent** [Minehut/Meta#618]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

Both ig
**Describe the feature**

allow something like bungeecord to big servers who want minigames and stuff
**How the feature is useful**

Minigames servers, and big servers if they have a bunch of players and the server cant handle they could send half of the players to the other server
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007** [comment]
Dupe of #484 and #571

**Comment by OGContent** [comment]
> Dupe of #484 and #571

oh man
