### ISSUE TITLE
Add /ad to the API 

### ISSUE THREAD

**Issue by AyhamAl-Ali** [Minehut/Meta#619]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**

API? Discord

**Describe the feature**

Allowing us to get a notification when our servers/any server receives an **/ad** in the lobby

So that we can make a discord bot to detect when that event happens and integrate with Skript to give in-game rewards or I can directly add that to Skript's events by connecting to Minehut's API and making a PR so that this can be actually built-in Skript-MH plugin and easier to do for all server owners.

**How the feature is useful**

Allow server owners to get more creative about how they can keep their servers up with many players online by rewarding players who advertises their servers in the lobbies.

**Note**
It would be great to be able to get more info about the advertiser such as their Minehut Rank (this is probably most important one to allow make different rewards for higher MH Ranks as their ads look way better that normal players - I think this is already a thing in the current API?)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
Minehut’s API is not intended for public use, so they won’t add any features specifically for public use until API use is supported (which is more if, than when)

**Comment by OGContent** [comment]
Dont think they will ever add it to the API.

**Comment by drtshock** [comment]
I'm not a fan of this because it will just encourage more people to use /ad for more servers, which will result in more lobby spam. Lobby chat is already filled with /ad spam and impossible to have a conversation. I'd rather figure out a better way to help players find servers, still letting server owners promote their servers, while also making lobby chat spam free enough to hold a conversation.

**Comment by orvit-png** [comment]
> I'd rather figure out a better way to help players find servers
Random server should allow you to connect to a server you have never joined, not whitelisted, and select whether or not you want to join decently sized servers or small ones

**Comment by AyhamAl-Ali** [comment]
> I'm not a fan of this because it will just encourage more people to use /ad for more servers, which will result in more lobby spam. Lobby chat is already filled with /ad spam and impossible to have a conversation. I'd rather figure out a better way to help players find servers, still letting server owners promote their servers, while also making lobby chat spam free enough to hold a conversation.

You can provide a quick ans simple solution for this by adding a toggle for `/ad` messages so that people can toggle ad message and don't get annoyed by it.

**Comment by CerialPvP** [comment]
> > I'm not a fan of this because it will just encourage more people to use /ad for more servers, which will result in more lobby spam. Lobby chat is already filled with /ad spam and impossible to have a conversation. I'd rather figure out a better way to help players find servers, still letting server owners promote their servers, while also making lobby chat spam free enough to hold a conversation.
> 
> You can provide a quick ans simple solution for this by adding a toggle for `/ad` messages so that people can toggle ad message and don't get annoyed by it.

Yes but most of them will toggle it and server owners will not get any players

**Comment by Blocksnmore** [comment]
> > I'm not a fan of this because it will just encourage more people to use /ad for more servers, which will result in more lobby spam. Lobby chat is already filled with /ad spam and impossible to have a conversation. I'd rather figure out a better way to help players find servers, still letting server owners promote their servers, while also making lobby chat spam free enough to hold a conversation.
> 
> You can provide a quick ans simple solution for this by adding a toggle for `/ad` messages so that people can toggle ad message and don't get annoyed by it.

This has already been confirmed by trent as not happening

**Comment by CerialPvP** [comment]
> I don't see this ever being added as some sort of endpoint on the API (for the same reasons as jellz stated above), but a better thing to suggest would be the ability to set a webhook URL for /ad on a server's dashboard that would receive a payload with the player's UUID as well as the text of the ad.

also there could be an opportunity for like Ad2Win or smth like that so you ad and you get like Advertiser's key or whatever

**Comment by ReportCardsMC** [comment]
If this was implemented, I could see possibly showing the /ad message for each ad to about 50-75% of the lobbies instead of everyone in lobbies
