### ISSUE TITLE
Voting Message Color Scheme

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#62]
### Feature request

**Platform**
 In-game

**Describe the feature**

Change the color theme of the voting message in the lobbies to match Minehut's light blue theme.

**How the feature is useful**

Looks better.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Could you provide examples as to how it should change?

**Comment by farwl** [comment]
The current color scheme of the voting message is orange / yellow. Minehut messages are usually blue / aqua.

**Comment by Sniped** [comment]
Discussion for the general styling guide that would include voting messages is now on issue #342
