### ISSUE TITLE
Tuske Unregister Enchant Bug

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [Minehut/Meta#621]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 Both

**Describe the bug**

If you install Tuske with Skript and include the effect `unregister [the] [custom] enchantment %custom enchantment%` anywhere in your file, it will say cant understand this condition/effect.

**To reproduce**
Steps to reproduce the behaviour:
1. Install Skript and tuske
2. Restart the server
3. Navigate to File Manager > plugins > Skript > scripts > create a new file named "error.sk" (the name doesnt matter as long as you are consistent)
4. Open the file you have just created and paste this code in:
```
on script load:
	set {_telepathy} to "Telepathy" parsed as custom enchantment
	if {_telepathy} is not set:
		register a new custom enchantment with id name "Telepathy"
		set {_telepathy} to "Telepathy" parsed as custom enchantment
		set max level of {_telepathy} to 5
		set rarity of {_telepathy} to 1
		set accepted items for {_telepathy} to "Swords" and "Bow"
		set lore name of {_telepathy} to "Magic Power"
		broadcast "&a%{_telepathy}%&a has been created!"
	else:
		broadcast "&aUnregistering..."
		unregister enchantment Telepathy
		broadcast "&a%{_telepathy}%&a has been unregistered!"
``` 
5. Save the file, then go into minecraft and type "/sk reload (file name)"
6. Repeat the step above
7. This is what it looked like for me.
![image](https://user-images.githubusercontent.com/70504198/117579525-42279880-b0c1-11eb-8ecd-66bbbf829023.png)

**Expected behaviour**

No error on reload

**Device Information**

This bug is plugin related
- Minehut server name: GenPot

**Screenshots**

**Additional context**

It appears to me that the error only shows when the enchant is not yet registered, therefore it is not getting called.
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by tarna** [comment]
Are you sure this is not just a TuSKe issue. Cause I don't think Minehut uses any custom version of TuSKe. They usually put all their edited plugins on their GitHub and TuSKe is not one of them.

**Comment by MinecraftMan1013number2** [comment]
> Are you sure this is not just a TuSKe issue. Cause I don't think Minehut uses any custom version of TuSKe. They usually put all their edited plugins on their GitHub and TuSKe is not one of them.

Its possible

**Comment by tarna** [comment]
> > Are you sure this is not just a TuSKe issue. Cause I don't think Minehut uses any custom version of TuSKe. They usually put all their edited plugins on their GitHub and TuSKe is not one of them.
> 
> Its possible

Ok looks like it is just a TuSKe issue and not a Minehut one. Like I said, don't think Minehut even uses a custom TuSKe but I tested it on an external server and it does the same. Every other reload, it says it understand this effect. 

Can probably close this not since it's not a Minehut bug.

**Comment by MinecraftMan1013number2** [comment]
ok, thanks for looking into it.

**Comment by quick007** [comment]
TuSKe hasn't been updated in like 3 years, I don't think this will get fixed
