### ISSUE TITLE
Add sub-users to console

### ISSUE THREAD

**Issue by Sufixess** [Minehut/Meta#625]
Sub-users are simply other emails given restricted & editable access to certain features of said console. This will allow for sharing a server across multiple emails without having to entrust anybody with your email, and/or possible other servers. The creator of said server will have full-access, and I will be able to edit the specific access that other's have. 

Currently, developers who have console access are able to steal names, skripts, configs, and/or completely ruin a server in a few minutes which, in my opinion, is something that shouldn't be possible. Adding sub-users would allow for all of these issues to be removed to an extent, putting the server owner in-charge of everything server-related.

**Comment by quick007** [comment]
ayy someone actually checked past issues (although they didn't follow the format lol)
