### ISSUE TITLE
Boosters and mute

### ISSUE THREAD

**Issue by OGContent** [Minehut/Meta#634]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**

discord
**Describe the feature**

When you get muted and you're a booster you should have permissions to talk in the boosters channel but if the person was just cussing out everyone and cursing they should get booster mute
**How the feature is useful**

useful for people who booster and got muted
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
no :)
