### ISSUE TITLE
[Suggestion] The uploading of .tesf files (Terra plugin can not function without it!)

### ISSUE THREAD

**Issue by DereC4** [Minehut/Meta#636]
### Feature request

**Checklist**
- [Y] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [Y] This is not a bug report, support request or plugin request
- [Y] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [Y] This issue does not contain any sensitive information 

**Platform**
Java

**Describe the feature**
I am suggesting that .tesf extension files be allowed to be uploaded onto Minehut. While I was testing the recently added Terra's functionality with Minehut, I discovered that the structure files (.tesf) it uses to manually generate all its structures (even all the custom trees) are not able to be uploaded on Minehut thus breaking custom Terra packs.

**How the feature is useful**
Our custom packs will be extremely empty as Terra makes extensive use of a custom structure generation system to override vanilla generation and not having structures removes a core part of Terra. Making this change would allow for us custom pack makers to fully use our packs as intended. Until then, custom packs are virtually unuseable on Minehut leaving users with only the "Default" pack.  
 
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by DereC4** [comment]
Any luck?

**Comment by BennyDoesStuff** [comment]
The file extension limit has been removed as of the recent file manager update.
