### ISSUE TITLE
Skript bug with Amount expression

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [Minehut/Meta#637]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Describe the bug**

When you set a list variable to anything, then put something like `set {_size} to the size of {_size::*}`, that line will error.

**To reproduce**
Steps to reproduce the behaviour:
Use `set {_size} to the size of {_size::*}` in any part of a script
I have used it like this:
```
command /sizetest:
	trigger:
		set {_size::*} to "Line 1", "Line 2" and "Line 3"
		set {_size} to the size of {_size::*}
		send "%{_size}%"
```

**Expected behaviour**

It sends you "3", but instead, it sends "<none>"

**Device Information**

- Minehut server name: HighSkyFly

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
Minehut doesn't deal with skript errors, you should report it on the skriptlang/skript github repository

**Comment by MinecraftMan1013number2** [comment]
This doesnt happen with normal skript, so i reported it here

**Comment by tarna** [comment]
> Minehut doesn't deal with skript errors, you should report it on the skriptlang/skript github repository

If it's an issue with the Minehut fork version of skript then yes, it belongs here. 

Also I just tested this on external and on Minehut and it did not do this. It printed 3 for me.

**Comment by MinecraftMan1013number2** [comment]
it printed 3 for minehut or external? or both

**Comment by tarna** [comment]
> it printed 3 for minehut or external? or both

both

**Comment by MinecraftMan1013number2** [comment]
i just uninstalled and reinstalled skript, and its still happening

**Comment by tarna** [comment]
> i just uninstalled and reinstalled skript, and its still happening

Is it because you are using the wrong syntax? You used **set {_size} to the size of {_size::*}** and that gives me an error and prints <none>. I used **set {_size} to size of {_size::*}** and it worked fine for me. I thought it was just a mistake you made when writing it out but that may be the issue.

**Comment by CoolProgrammerX** [comment]
I’m pretty sure this was a bug found in Skript itself and was patched in the recent update.

**Comment by MinecraftMan1013number2** [comment]
> > i just uninstalled and reinstalled skript, and its still happening
> 
> Is it because you are using the wrong syntax? You used **set {_size} to the size of {_size::*}** and that gives me an error and prints none. I used **set {_size} to size of {_size::*}** and it worked fine for me. I thought it was just a mistake you made when writing it out but that may be the issue.

it worked when I removed "the"... thats strange lol
thanks for your help :)
