### ISSUE TITLE
Minehut Discord Bot False Warn

### ISSUE THREAD

**Issue by easonuwu** [Minehut/Meta#638]
### Bug report

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

**Platform**
 Discord

**Describe the bug**
False Warn

**To reproduce**
Steps to reproduce the behaviour:
1. 2 people types in chat
2. One of the players deletes all his messages
3. Bot warns you (the person that didn't delete his messages)

**Expected behaviour**
User should not be warned.

**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 

**Screenshots**
[image](https://user-images.githubusercontent.com/71189551/120229923-cb755980-c280-11eb-85ad-f0fdd9a5b05f.png)
https://i.gyazo.com/1e52e6663d0d5dc0dbf46db8a813acb1.mp4

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by tarna** [comment]
This is not a bug and warns are manual, not automatic. If you feel like a punishment is unfair, make an appeal [here](https://forums.minehut.com/application/form/3-player-appeals/). This is not the place for that.

**Comment by easonuwu** [comment]
I didnt get punished, i got autowarned for "Chat Flooding"

**Comment by tarna** [comment]
> I didnt get punished, i got autowarned for "Chat Flooding"

A warn is a punishment. And there are no autowarns. All punishments are manual. Like I said, if you feel like a punishment is unfair, make an appeal with the link I provided above. This is not the place for that.

**Comment by easonuwu** [comment]
Okay then.
