### ISSUE TITLE
Show moderator that issued a warn/mute

### ISSUE THREAD

**Issue by easonuwu** [Minehut/Meta#639]
### Feature request

**Checklist**
- [ X ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ X ] This is not a bug report, support request or plugin request
- [ X ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ X ] This issue does not contain any sensitive information 

**Platform**
 Discord

**Describe the feature**

Show the moderator that issued a warn/mute.

**How the feature is useful**

Clears out confusion for players that get warned/muted.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment]
The person who issued a punishment used to be shown but it was removed since people could harass the mod that punished them.

**Comment by easonuwu** [comment]
Ah, i see...
