### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by OGContent** [Minehut/Meta#640]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**

both
**Describe the feature**

If a server was full they should enter a queue and if they wanted to leave the queue they should do the command /leavequeue or /queue leave
and there wouldn't be a command spam trying to join a server
**How the feature is useful**

its useful for full servers that want people 
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
We will probably not be doing this (or if we did consider it, not for a long time) so I'm going to close the issue. If a server has a limited amount of player slots, the server should instead take action such as using our networks feature to send players to a lobby if the server is full.
