### ISSUE TITLE
Ability for zip files to be put inside the datapacks folder

### ISSUE THREAD

**Issue by PixelTheKermit** [Minehut/Meta#641]
### Feature request
_**Checklist**_
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

_**Platform**_
Website
_**Describe the feature**_
You should be able to put zip files inside the datapack folder for quicker datapack installation

_**How the feature is useful**_
This feature would benefit alot of people who want to use datapacks in their minehut server as it will massively decrease the ammount of time needed to install them

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by DereC4** [comment]
Agree. This would also help with many plugins that use compressed files such as Terra, the free and widely used world generation plugin that was recently added (because right now it does not work with minehut because you can't upload certain extensions).

**Comment by joaoP-santos** [comment]
Yeah, there are a lot of plugins that have a "datapack version". Furthermore, if we could upload zip files we would be able to upload other things besides datapacks.

**Comment by PixelTheKermit** [comment]
Going to close this due to Minehut Unleashed being announced.
