### ISSUE TITLE
Terra custom packs broken

### ISSUE THREAD

**Issue by HaTInAnd** [Minehut/Meta#643]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Website and Java!

**Describe the bug**
the world plugin Terra cant have custom packs because structures cant be uploaded 

**To reproduce**
1. Download terra
2. Try to upload your own pack using minehut
3. You can not upload the structures but you can upload everything else for a custom pack
4. Terra wont let you load the pack

**Expected behaviour**
The structure files should be uploadable so the plugin can work

**Device Information**

- Java 1.16.5
- Chrome
- Windows 10
dupe.minehut.gg

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by tarna** [comment]
This should probably be a feature request to add .tesf files to the extension whitelist and its already been suggested in #636

**Comment by BennyDoesStuff** [comment]
This is no longer an issue as of the recent file manager update.
