### ISSUE TITLE
change button on main website

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#644]
**Platform**
 website, main page

**Describe the feature**
 change the wording of this button 
![image](https://user-images.githubusercontent.com/42002575/120905761-938d5e00-c654-11eb-8115-f9ca7722a0a7.png)

**How the feature is useful**
the wording looks incredibly unproffesional imo

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BurningBrimstone** [comment]
A change to "Take My Credits!" might be better, but it ultimately seems inconsequential.

**Comment by not-3than** [comment]
I personally think "Take My Money!" is hilariously accurate.

**Comment by Reimagining** [comment]
Honestly, given the community this service is targeted for, I think its perfect; I think the image of a hosting company such as Minehut would to have a professional side but also friendly side given that they are community based. Plus, I don't think 4 words affect the image that much even if it were that impactful. Maybe promote how they listen to community and actually try to fulfill 🤔?

**Comment by BennyDoesStuff** [comment]
This issue no longer applies as the website design was updated and changed.
