### ISSUE TITLE
Server not joinable on Bedrock Edition version 1.16.220

### ISSUE THREAD

**Issue by ElectroGamesYT** [Minehut/Meta#645]
### Bug report

**Checklist**
- [YES] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [YES] I am NOT reporting a security vulnerability
- [YES] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [YES] This issue does not contain any sensitive information

**Platform**

Bedrock

**Describe the bug**

Join bedrock.minehut.com:19132 on Bedrock Edition version 1.16.220

**To reproduce**
Steps to reproduce the behaviour:
Umm.. I just said above...
1. Go to 'Minecraft Bedrock edition'
2. Click on 'Click the server'
3. Scroll down to 'Play Button'

**Expected behaviour**

For the server to be joinable and not just saying "Connecting to external server"...

**Device Information**

- Minecraft client (and version): 1.15.220
- Web browser (and version): Chrome. Btw if you didnt know, chrome has nothing to do with Bedrock Edition.
- Operating system (and version): Windows 10
- Minehut server name: MineHut

**Screenshots**

**Additional context**

The server is locatable, it shows it has 11k players on and im getting 44 ping but the server is not joinable.
Ive been trying to join for the past few weeks. I also tried sometime last year and I still couldnt join.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
Bedrock is known for being unreliable on minehut so I wouldn't use it

**Comment by ahoulton** [comment]
Trent (@drtshock) is aware that Bedrock is outdated, but cannot give an ETA on an update to 1.16.220.

**Comment by terretta** [comment]
> _aware Bedrock is outdated but cannot give an ETA on update_

But think of the children (on iPads) who can’t join their friends (on PC) while in lockdown!

Or, rather, think of the parents of those children… :-)

**Comment by CoreyShupe** [comment]
`- Temporarily dropping Bedrock support in favor of 1.17 clients. We'll bring this back soon.`

**Comment by CerialPvP** [comment]
Maybe make a system which when bedrock releases a new version, it will automatically update.

**Comment by DaRealMinecraftexpert** [comment]
I believe they tried that at one point

**Comment by BennyDoesStuff** [comment]
Bedrock edition support should be working so this isn't an issue anymore.
