### ISSUE TITLE
Model Engine .bbmodel Support

### ISSUE THREAD

**Issue by Saksham12SG** [Minehut/Meta#646]
HI MineHut Team!, please add support for .bbmodel files 
if we want to import a generic project on model engine blueprint files 
we cannot do that it says an issue "this should be a most add to minehut so that model engine generic project importing will work,
you also need to install the assets folder on the files to see the custom mob model you made, means we need to download that also  from the file manager which we can't, which makes model engine  a "not working" plugin

**Comment by DaRealMinecraftexpert** [comment]
Format, good sir. There's a Format you need to use

**Comment by not-3than** [comment]
Yea yea follow the format.

Please allow for more file types rather than just blocking all except for a few.
Make a file type blacklist instead of a whitelist!

**Comment by Saksham12SG** [comment]
> Yea yea follow the format.
> 
> Please allow for more file types rather than just blocking all except for a few.
> Make a file type blacklist instead of a whitelist!
indeed

**Comment by DereC4** [comment]
I agree with this; a lot of things use certain blocked extensions like the Terra plugin using .tesf for structure files instead of .schem or .nbt

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update (there is no longer a file extension limit).
