### ISSUE TITLE
Add a search bar to Minehut.com and Marketplace

### ISSUE THREAD

**Issue by not-3than** [Minehut/Meta#647]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

Add a search bar to search through the main website so users can find pages easier as well as adding a second search bar to the market page (so the market is kept separate), to make it easier for people to find what they want rather than trying to use ctrl+f or just looking through.
**How the feature is useful**

Benefits users because they can find stuff easier on the website. Benefits market creators because it makes their things easier to access, which means more sales.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007** [comment]
no idea why the mh market has pages or no search bar, but I don't think we need a search bar for users

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent Minehut market update.
