### ISSUE TITLE
Skript

### ISSUE THREAD

**Issue by ghost** [Minehut/Meta#651]
### Bug report

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] I am NOT reporting a security vulnerability
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information

**Platform**

both**Describe the bug**

Ok, so me and some people are/were having a problem with Skript regex in Minehut, and if we go outside Minehut it works fine.
**To reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

Regex doesn't give null error or any errors
**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by honkling** [comment]
issue could be more descriptive

**Comment by OGContent** [comment]
> issue could be more descriptive

regex overall is bad in minehut, but regex outside minehut is good

**Comment by terminated-star** [comment]
> > issue could be more descriptive
> 
> regex overall is bad in minehut, but regex outside minehut is good

That's probably due to the Skript version (I don't see how it would be anything else), do you have any examples of how it works differently on a Minehut server vs elsewhere?
