### ISSUE TITLE
Server displaying wrong amount of players.

### ISSUE THREAD

**Issue by lj-pixel** [Minehut/Meta#652]
### Bug report

**Checklist**
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] I am NOT reporting a security vulnerability
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information

**Platform**

Java

**Describe the bug**

The server I own displays the wrong amount of players on the server list. It is pretty much always 5 - 10 players behind. It also displays it incorrectly on the dashboard.

I had an issue yesterday where my server displayed as offline, but still having players on also. This caused a very large rollback. 

**To reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

Server to display correct player info.

**Device Information**

- Minecraft client (and version): 1.16.5
- Web browser (and version):  Safari
- Operating system (and version):  Mac Big Sur
- Minehut server name: ByteGens

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by CoreyShupe** [comment]
This should be fixed in a future version of the panel. Going to leave this open until it goes out though.

**Comment by lj-pixel** [comment]
> This should be fixed in a future version of the panel. Going to leave this open until it goes out though.

Was this apart of the issue with where the server was displaying offline even with players on? I think that was the reason nothing on my server saved.

**Comment by CoreyShupe** [comment]
> Was this apart of the issue with where the server was displaying offline even with players on? I think that was the reason nothing on my server saved.

The issue with nothing saving is unrelated. We've already made patches to what caused that, any server with the latest software will be able to save just fine. We're doing the best we can to ensure even older servers are saving properly even with the old versions.

**Comment by lj-pixel** [comment]
> > Was this apart of the issue with where the server was displaying offline even with players on? I think that was the reason nothing on my server saved.
> 
> The issue with nothing saving is unrelated. We've already made patches to what caused that, any server with the latest software will be able to save just fine. We're doing the best we can to ensure even older servers are saving properly even with the old versions.

Awesome, anyway to know if I'm on new software?

**Comment by ahoulton** [comment]
> 
> 
> > > Was this apart of the issue with where the server was displaying offline even with players on? I think that was the reason nothing on my server saved.
> > 
> > 
> > The issue with nothing saving is unrelated. We've already made patches to what caused that, any server with the latest software will be able to save just fine. We're doing the best we can to ensure even older servers are saving properly even with the old versions.
> 
> Awesome, anyway to know if I'm on new software?

You should be already on it, Minehut mass updates basically everything.
