### ISSUE TITLE
Add older versions support

### ISSUE THREAD

**Issue by f1shy-dev** [Minehut/Meta#653]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java

**Describe the feature**

Now that Minehut has implemented a version selector, I think we should add support for older server versions, such as `1.8`.

**How the feature is useful**

It would be useful for servers like PVP servers who want to use the `1.8` PVP Mechanics, as it may be buggy using ProtocolSupport/ViaVersion. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
We will in the future once we have a chance to make the plugin panel know which version the server is, and install the correct version of the plugin accordingly. We wanted to get this out so we didn't have to force everyone onto 1.17 like we have done in past updates.

This is already planned, along with forge and other versions :)

**Comment by f1shy-dev** [comment]
Ah ok, makes sense. Excited for when that drops 🤩!

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent custom versions update!
