### ISSUE TITLE
Developer integration for /ad

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Meta#655]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Allow users to specify a webhook endpoint for each of their servers to be triggered when an in-game player uses /ad to advertise a server. The payload should include the server name, the UUID of the player who executed the command, and the text that they used to advertise the server.
Example payload:
```json
{
    "uuid": "20737a76-497a-4bac-bb93-4693d6ff152a",
    "server": "MyCoolServer123",
    "text": "Join now!"
}
```
would result from a player with the UUID `20737a76-497a-4bac-bb93-4693d6ff152a` running the following command:
```
/ad MyCoolServer123 Join now!
```

**How the feature is useful**

This would allow developers to implement in-game rewards for their servers for people who use /ad.
There were previously services (that broke the Minehut TOS by sharing data) that would use an in-game bot in the lobby to detect when a player advertised a server.
This would be an officially supported service offered by Minehut that could even be locked behind paid server plans.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
More possible ways this could be implemented (though the above is most versatile):
- Send a command to the user's server with the payload
- A subscribable event in the PlayerServer plugin (if it's even going to be used still)

**Comment by drtshock** [comment]
Hey see my response here https://github.com/Minehut/Meta/issues/619#issuecomment-839958699

**Comment by iGalaxyYT** [comment]
Ah my bad, can't believe I made this issue when I even commented on that original one 🤦‍♂️
Closing this now
