### ISSUE TITLE
Incorrect Ban Formatting

### ISSUE THREAD

**Issue by Saturn5Vfive** [Minehut/Meta#659]
### Incorrect Ban Formatting

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

I have witnessed this bug on the java platform of minecraft,
I am unsure if this bug applies also to the bedrock version

**Describe the bug**
Once a player is kicked for being banned from minehut, a message similar to that in the image under screenshots is shown, inside said ban message, there are intended to be color codes to destinguish the different parts of the message. instead of formatting the color codes as intended, they are ignored and added to the message as characters.

**To reproduce**
Steps to reproduce the behaviour:
1. Log onto 'mc.minehut.com'
2. Become perminantly banned (this bug may only apply when getting banned perminantly for the "bot" reason and for the "forever" duration)
4. Note how the color codes are not applied when the ban message is sent

**Expected behaviour**
The expected behaviour is that the color codes would change the formatting of the ban message, giving it the intended colors 

**Device Information**

- Minecraft client: Fabric 1.17.0 (at the time of the initial encounter) however the bug applies to the vanilla 1.17.0 client as well
- Web browser (and version): Google Chrome Version 91.0.4472.106 (Official Build) (64-bit)
- Operating system : Windows 10 Home OS Build 19042.1052 (64-bit)
- Minehut server name: mc.minehut.com

**Screenshots**
![image](https://user-images.githubusercontent.com/58058856/122872224-c0e53780-d2f5-11eb-9007-e03e7083abf5.png)

**Additional context**
This is not a ban appeal!

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Centrect** [comment]
Well at least you are not a bot :)

I assume this has something to do with the punishment upgrades they rolled out a few months ago, either that or something on your client is buggy!

**Comment by Saturn5Vfive** [comment]
I dont think its my client, I tried it on fabric and vanilla 1.17 and 1.16.4 and it had the same malformatted message

**Comment by CoreyShupe** [comment]
This is an issue with velocity and our switch into the new text component library it uses natively. We'll probably fix these message cases soon.

**Comment by CoolProgrammerX** [comment]
Can technically/partially reproduce this.
Someone on Discord sarcastically sent me a DM including a screenshot of their ban screen saying "Minehut's ban screen is so nice".

**Comment by BennyDoesStuff** [comment]
This seems to have been fixed.
