### ISSUE TITLE
Don't count version support plugins toward plugin limit

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#66]
### Feature request

**Platform**
 In-game / website

**Describe the feature**

Don't count Protocol Support or ViaVersion towards the plugin slot. Minehut doesn't allow us to change our server version, making these two plugins the only way to allow older versions to join. Why count these towards the limit. It's unethical to make people pay monthly so they can have players on an older version join. You're charging monthly for what other server hosts do for free. Maybe start counting it towards the limit once you can change your server version ;)

**How the feature is useful**

Quality of life feature.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
The plugin limit no longer exists as of the recent custom plugins update.
