### ISSUE TITLE
require-resource-pack option from server.properties

### ISSUE THREAD

**Issue by tarna** [Minehut/Meta#663]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Add the new 1.17 `require-resource-pack` option from `server.properties` to the settings tab on the panel for 1.17 servers. Also add the new `resource-pack-prompt` option that only works if the require-resource-pack option is enabled.

**How the feature is useful**

This `require-resource-pack` option makes players need to use the resource pack in order to play on the server. This option can make it easier for 1.17 server owners to force someone to use a resource pack instead of using a plugin like Skript to kick them if they aren't using it.

The `resource-pack-prompt` option shows a custom message when a resource pack is prompted if the `require-resource-pack` option is also true.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
The `resource-pack-prompt` option is the message that shows when a user is prompted to install the pack (e.g. "Our resource pack is required for many features of our server, please install it!"), not the message that gets sent to the client when they are kicked for not accepting it.

**Comment by tarna** [comment]
> The `resource-pack-prompt` option is the message that shows when a user is prompted to install the pack (e.g. "Our resource pack is required for many features of our server, please install it!"), not the message that gets sent to the client when they are kicked for not accepting it.

Oh ya sorry. I read the thing wrong online. You are correct.

**Comment by CoreyShupe** [comment]
This is added.
