### ISSUE TITLE
Front page stats not showing

### ISSUE THREAD

**Issue by Prorickey** [Minehut/Meta#669]
### Bug report

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

**Platform**

Website

**Describe the bug**

On the website on the front page in the section that shows Hot servers and their player counts it does not show any players. It also doesn't show the network ram usage, server count or player count.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to https://minehut.com
2. Scroll down to the section below the quotes.
3. Observe

**Expected behaviour**

I would expect it to show the correct stats instead of nothing and NaN

**Device Information**

- Web browser (and version): Chrome

**Screenshots**

![image](https://user-images.githubusercontent.com/78997566/123995979-dcf37380-d99c-11eb-84b2-2ece36b4e112.png)

**Additional context**

The reason for this issue is that the two API endpoints https://api.minehut.com/network/top_servers and https://api.minehut.com/network/simple_stats return "{"ok":false,"msg":"An unknown error occured"}" instead of the correct stats

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by OGContent** [comment]
> ### Bug report
> **Checklist**
> 
> * [x]  I have read and agree to the README (found on https://github.com/Minehut/Meta)
> * [x]  I am NOT reporting a security vulnerability
> * [x]  I have searched the Issue Tracker to make sure this is not a duplicate issue
> * [x]  This issue does not contain any sensitive information
> 
> **Platform**
> 
> Website
> 
> **Describe the bug**
> 
> On the website on the front page in the section that shows Hot servers and their player counts it does not show any players. It also doesn't show the network ram usage, server count or player count.
> 
> **To reproduce**
> Steps to reproduce the behaviour:
> 
> 1. Go to https://minehut.com
> 2. Scroll down to the section below the quotes.
> 3. Observe
> 
> **Expected behaviour**
> 
> I would expect it to show the correct stats instead of nothing and NaN
> 
> **Device Information**
> 
> * Web browser (and version): Chrome
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/78997566/123995979-dcf37380-d99c-11eb-84b2-2ece36b4e112.png)
> 
> **Additional context**
> 
> The reason for this issue is that the two API endpoints https://api.minehut.com/network/top_servers and https://api.minehut.com/network/simple_stats return "{"ok":false,"msg":"An unknown error occured"}" instead of the correct stats
> 
> **Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

Minehut is having problems right now, maybe after they solve things it will go back to normal

**Comment by tarna** [comment]
Ya, this was probably cause of Minehut's issues that happened earlier but it seems to be fine now. The only thing that isn't working of that part is showing the current player count for the top servers, which I think has already been acknowledged. 

What FiXed said about that current player count now showing - https://discord.com/channels/546414872196415501/546422616609783818/855851252306935838

**Comment by Prorickey** [comment]
It was due to the minehut issues yesterday and is now fixed, closing the issue.
