### ISSUE TITLE
All server selector only for servers with certain categories. 

### ISSUE THREAD

**Issue by Prorickey** [Minehut/Meta#674]
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**

Both

**Describe the feature**

I think the random server selector should be moved down one slot(The highlighted slot in the photo) and to replace it there should be a nametag or enchanted book which you can search through servers with certain categories. It should first open up a GUI that lets you select a category which would then bring you to another menu that is exactly like the normal all servers menu but with only servers that have the selected category. It should display the servers in order by player count.

**How the feature is useful**

It helps people find the type of server that they are looking for because the all servers page could get a little cluttered with the same types of servers and it would be nice to have a sort of filter to find your type of server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**
![image](https://user-images.githubusercontent.com/78997566/124543705-c06b9700-ddf3-11eb-87cf-f4766b513434.png)

**Comment by OGContent** [comment]
This is already being worked on, if you have the Discord meta please see #server-discovery-feedback

**Comment by Prorickey** [comment]
My bad
