### ISSUE TITLE
Revert the new color scheme back to the old one (Dev Panel)

### ISSUE THREAD

**Issue by ReportCardsMC** [Minehut/Meta#677]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

(Idk if this is a mistake or not)
The new panel and the color scheme look weird to me, I'm unsure if this is just the fact I'm used to the old one, or it just genuinely looks weird. It doesn't give off the same aesthetic as the old one and almost doesn't feel like Minehut as it doesn't have that "Minehut blue" you see, anywhere.

The sidebar is not as intuitive as the old one. I'm unsure if this will be changed or not.

Unless it's put somewhere else, the loss of the header at the top feels like a downside on Minehut's end as it's a loss of a good place to put advertisements

![Panel Image](https://cdn.upload.systems/uploads/jRwMAmPZ.png)

**How the feature is useful**

In my opinion, reverting the color scheme will keep the panel at least somewhat similar to the old one and keep it familiar for most users.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
You shouldn't treat the dev server as live. Feel free to recreate this issue once this is present on live. The new panel design is being worked on and shouldn't be seen as the final product.
