### ISSUE TITLE
Add SkriptAddonPatcher

### ISSUE THREAD

**Issue by CerialPvP** [Minehut/Meta#678]
### Feature request

**Checklist**
- [ x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x ] This is not a bug report, support request or plugin request
- [ x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x ] This issue does not contain any sensitive information 

**Platform**

Both

**Describe the feature**

Make SkriptAddonPatcher auto install into servers
Link: https://github.com/TPGamesNL/SkriptAddonPatcher

**How the feature is useful**

In Skript 2.6, most of addons are broken. If minehut is using 2.6, then that would be very useful to keep addons running.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
Makes more sense to individually patch the addons. This probably isn't something we're going to put on any server but it could definitely be used for updates.

**Comment by pop4959** [comment]
We'll be updating to Skript 2.6 once it's released and we have support for 1.17 plugins in our panel. Most likely how this is going to work is out 1.16 servers will continue using Skript 2.5.3, and 1.17 servers will run Skript 2.6. We'll also need to wait for developers to release plugin updates that support the new release before we fully commit. It's definitely our goal to make sure your servers keep running smoothly during the update transition.
