### ISSUE TITLE
Funny feature

### ISSUE THREAD

**Issue by ElmoPog** [Minehut/Meta#679]
### Feature request

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] This is not a bug report, support request or plugin request
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**

Discord

**Describe the feature**
 Make it so the minehut bot sends the emoji :protectcp: every time someone either sends a poke emoji or sticker of Coolprogrammer

**How the feature is useful**
 It’s not that useful, but maybe a way to thank Coolprogrammer for being #1 chatter in the Minehut discord 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment]
no
