### ISSUE TITLE
Add support for .py files in the new file manager

### ISSUE THREAD

**Issue by Anonymous136** [Minehut/Meta#683]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

Platform: Website

Suggestion:
In the new file manager, you could add support for python files. With the minecraft-python plugin, you could use python to create plugins. This could help people (like me) who use python as the main programming language to create plugins.

**Comment by ahoulton** [comment]
There are plans to completely remove the file type whitelist in the near (ish) future, meaning that requests to add support for file types will no longer be needed.

If you want to see more information regarding this update, please see [here](https://go.minehut.com/unleashed).

**Comment by drtshock** [comment]
We won't have a file extension whitelist soon so any file type will be supported.
