### ISSUE TITLE
Add limited world edit to the Twitch Build Competition

### ISSUE THREAD

**Issue by MinecollYT** [Minehut/Meta#685]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
For the Minecraft server(the twitch build competition), both java and bedrock

**Describe the feature**
Add FAWE(worldedit) for player's to use on the twitch build competition. To prevent server lag, the actions should be limited e.g.: some blocks might be blacklisted(spawner, note blocks, pistons, redstone, carrot, potato, ...) and the max amount of blocks a player can do at once might be a few hundred.

**How the feature is useful**
Helps the player build faster and more impressive builds and prevents annoying work

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
The twitch build competition has now ended. We couldn't have given players world edit anyways as it makes it easier for users to lag out and crash the server. Sorry about that!
