### ISSUE TITLE
You can die in the twitch build event

### ISSUE THREAD

**Issue by MinecollYT** [Minehut/Meta#688]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x]  This issue does not contain any sensitive information

**Platform**
Not sure, but I tried it on java

**Describe the bug**
You can take damage in the lobby of the twitch build competition

**To reproduce**
Steps to reproduce the behaviour:
1. Join the Twitch Build Competition
2. Try to die (e.g. Drowning)

**Expected behaviour**
Cancel damage event

**Device Information**
- Minecraft client (and version): -
- Web browser (and version):  -
- Operating system (and version):  -
- Minehut server name: Twitch Build Competition

**Screenshots**

**Additional context**
![2021-07-25_00 20 38](https://user-images.githubusercontent.com/43142792/126882347-0802e939-7175-4fee-b71b-3b086eb247c1.png)

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by BennyDoesStuff** [comment]
The twitch build event is over now. Thanks for the report, however!
