### ISSUE TITLE
UI Customization

### ISSUE THREAD

**Issue by exwundee** [Minehut/Meta#690]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website [UI]

**Describe the feature**

Have the option for multiple themes, perhaps a custom UI editor? Generally just your typical light/dark themes, and include the options of different color palettes. 

**How the feature is useful**

Some players may be sensitive to other colors, or could potentially be color blind. Giving this option will help those who fit that description, as well will give customization to all players to have the most optimized Minehut experience.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Related to https://github.com/Minehut/Meta/issues/690
