### ISSUE TITLE
A new plugin for the nether

### ISSUE THREAD

**Issue by Marth0z** [Minehut/Meta#695]
A plugin called Very Dangerous Nether,
With this plugin the nether it is more dangerous and with the new structures you have a better experience in the nether.
-There are new mobs
-Custom structures
-New Sounds.
The plugin link is here ============> https://www.spigotmc.org/resources/very-dangerous-nether.76333/

**Comment by mpschorr** [comment]
Please don't suggest plugins here, there's a category on the [forums](https://forums.minehut.com/forum/20-plugins/) for that.
