### ISSUE TITLE
Email changes 

### ISSUE THREAD

**Issue by Giuca002** [Minehut/Meta#701]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

A button to change our email

**How the feature is useful**

For our privacy
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
dupe of #265

**Comment by Giuca002** [comment]
they are all closed 

> dupe of #265

**Comment by PundaChen** [comment]
265 is still open
