### ISSUE TITLE
Skript over 1k lines not loading properly & cannot download

### ISSUE THREAD

**Issue by yeetttt** [Minehut/Meta#709]
Bug occurs on Website and Ingame
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information
Minecraft client: Optifine, Java
Web browser: Chrome
Operating system: Windows 10
Minehut server name: Unsecured

I've recently tried to load a skript that is over 1k lines and it shows that it has been over 1k lines and you need to download the skript. When loading the skript it loads only the 1k shown. 

How to replicate: The loading skript does not happen over 1k normally and only recently did this. My guess is that one of the skript developers accidently clicked save while they within the skript causing it to save only the 1k lines. Please note that the download is still bugged no matter what.

**Comment by awaffle1** [comment]
Downloading works fine for me. I assume its an issue on your end.

**Comment by BennyDoesStuff** [comment]
This has been fixed recently so you can now view files > 1k lines in the file manager. Thanks for the report!
