### ISSUE TITLE
Server stuck on “Downloading”

### ISSUE THREAD

**Issue by CodingWRLD** [Minehut/Meta#717]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
Website

**Describe the bug**

When activating a minehut server, it goes into a downloading state. If you delete all server files inside the file manager, it will create some essential files but the server still fails to startup. 

The only files and folders that appears is...

Plugins/
server.jar
server.properties
spigot.yml 

so they must be a file or something that is not checked when downloading a server.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to File Manager
2. Delete every file
3. Start the server backup
4. See the infinite “Downloading” state

**Expected behaviour**
Even though this is a stupid mistake, and you should use the rest server button instead. Once deleting every file. By my experience they is no way to recover from this. Even using the reset server button or the fix server button.

**Device Information**

- Minecraft client (and version): not needed
- Web browser (and version): Safari (But should not matter as it’s not really a client side problem)
- Operating system (and version): IOS
- Minehut server name: 1TaZeBlock

**Screenshots**
![6F9D8505-E45C-4B4C-B1C9-42BCECC36D48](https://user-images.githubusercontent.com/53272749/128607064-44919b45-72af-4e42-a305-599dbce4a58b.png)

**Additional context**
I originally was helping someone in the discord with this problem. But after trying to reproduce this with a spare server I have, I can confirm seems to be a problem.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by PundaChen** [comment]
try force stopping in danger zone

**Comment by CodingWRLD** [comment]
> try force stopping in danger zone

Already tried the normal steps. Force hibernate, reset, repair. All seems to not work. They seems to be quite a few players reporting server startup issues so wondering if it’s something to do with that.

**Comment by PundaChen** [comment]
create a support ticket to get the issue fixed

**Comment by CodingWRLD** [comment]
> create a support ticket to get the issue fixed

yeah. I'm not bothered by this issue. It was reported in the discord and I tried to reproduce it so I decided to report the bug here. The server that's broken is only a spare server I have anyway.

**Comment by drtshock** [comment]
Please report through tickets. The support team works to identify trends within tickets and works with the dev team to fix things if needed.
