### ISSUE TITLE
Remove Sidenav Hover

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#72]
### Feature request

**Platform**
 Website

**Describe the feature**

Remove the hover behavior from the sidenav while it's collapsed. It's pointless and looks weird. Make it so while it's collapsed you just hover over the icons instead of it automatically expanding. And then to view the full content, you can already just click the nav toggle button.

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment]
Could you add a gif/video for what you're talking about?

**Comment by drtshock** [comment]
Does this cause problems? It actually works almost the same as gmail's navigation.

**Comment by farwl** [comment]
It does cause problems. It's quite buggy and causes visual errors most of the time. It isn't smooth either.

**Comment by ZeroParticle** [comment]
I'd love to see some of the bugs and visual errors. We did update it a little bit recently to get everything lined up better. I'm not sure I agree about the hover being useless, the icons alone aren't enough for everyone.

**Comment by WallyTube** [comment]
> I'd love to see some of the bugs and visual errors. We did update it a little bit recently to get everything lined up better. I'm not sure I agree about the hover being useless, the icons alone aren't enough for everyone.

move the sidenav to the top bar that the logo is in. we all want this.

**Comment by BennyDoesStuff** [comment]
Not sure if this is an issue anymore as a result of the recent design update.
