### ISSUE TITLE
Undefined Credits and overlapping credit box

### ISSUE THREAD

**Issue by Chasewhip8** [Minehut/Meta#724]
### Bug report

**Checklist**
- [ X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ X] I am NOT reporting a security vulnerability
- [ X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ X] This issue does not contain any sensitive information

**Platform**

Website Marketplace
https://shop.minehut.com/products/

**Describe the bug**

Credits are undefined and the box does not properly allow for the scrolling of categories at 100% page scale on a 1080p monitor. 

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://shop.minehut.com/products/'
2. look in the bottom left for undefined credits
3. Notice how scrolling the category bar at 100% page scale does not allow to scroll all the way down so the credit box is overlapping some categories.

**Expected behaviour**

The number of credits displayed and proper scrolling for categories.

**Device Information**

- Minecraft client (and version):  N/A
- Web browser (and version):  92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)
- Operating system (and version):  Windows 10 Latest
- Minehut server name:  N/A

**Screenshots**

https://i.imgur.com/SLaaolR.png
All the way scrolled down

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by BennyDoesStuff** [comment]
I don't seem to be experiencing this issue anymore. If you're still having this issue, please respond here and I can reopen it. Thank you for reporting!
