### ISSUE TITLE
Cracked Support

### ISSUE THREAD

**Issue by DuckySoLucky** [Minehut/Meta#725]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java

**Describe the feature**
Ability to Add Cracked Support in Settings Tab. It would add so many possibilities to new players, Minehut would become even more popular. Tons of Cracked Players would like that, Best way to do is to have Cracked Off Default and you can do change it, but there would be one catch. Minehut will need to disable /hub /lobby etc.. For cracked Users or Add AuthMe Plugin to Lobby.

**How the feature is useful**
Tons of Players will come to Minehut

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
I don't think this is a good idea, it'll make security way more annoying, also minehut shouldn't support piracy

**Comment by CoreyShupe** [comment]
Won't happen.

**Comment by tarna** [comment]
There is also no incentive for Minehut for adding this. What are the chances that a person not willing to pay for the game will be willing to purchase credits on Minehut.

**Comment by CoreyShupe** [comment]
> There is also no incentive for Minehut for adding this. What are the chances that a person not willing to pay for the game will be willing to purchase credits on Minehut. 

Less of that and more of:
1) we don't support piracy
2) authentication is an issue
3) it makes our setup nearly impossible to enforce
4) it breaks multi proxy setups pretty easily
5) it's a huge security concern for users

**Comment by PixelTheKermit** [comment]
can't you already do this with server.properties?

**Comment by honkling** [comment]
> can't you already do this with server.properties?

No, online-mode is already disabled in server.properties. Online mode is enforced proxy side.
