### ISSUE TITLE
Pay to win on Minehut

### ISSUE THREAD

**Issue by Giuca002** [Minehut/Meta#727]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Minecraft has a pay to win problem and that's bad now the reason why I'm typing this is a few days ago I joined a server and it was VERY pay to win so I asked the discord and they said to report it to Mojang and we both know Mojang does not do crap so this is why Minehut needs to start shutting down these server because Mojang could get lazy and block the Minehut domain 

**How the feature is useful**

to stop pay to win on Minehut
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
Iirc one of the staff have commented before that mh itself won't enforce the eula and it'll be down to the individual server owners

**Comment by Giuca002** [comment]
well this needs to change because the minehut domain could be blocked

**Comment by DaRealMinecraftexpert** [comment]
I would like to see this too, because imagine a large number of people making Pay to join altogether.

**Comment by Giuca002** [comment]
well then we should have a form that we can fill out to report these server and not like the Mojang one were they never read it

**Comment by CoreyShupe** [comment]
We will not be personally enforcing the eula. Mojang has shut down minehut servers before and we will accept their decision if they come to us with more. They won't block our domain, we have historically worked with mojang in the past but won't be enforcing it personally. We will leave it to mojang to enforce.

**Comment by Giuca002** [comment]
The problem we are having is they don't enforce it and I find it lazy if you guys don't shutdown these servers on your network Mojang has only blocked 3k server globally and Minehut alone has almost 6 million server I'm guessing 500k of them are pay to win

**Comment by XePup** [comment]
mojang have blocked some servers, but you can still join them. I'm pretty sure lunar client has a feature where you can't join P2W servers

**Comment by Giuca002** [comment]
yeah thats a client but the main game its a different story in my opinion Minehut is just being lazy so they dont have to enforce the eula when thats their job to do so if someone is breaking the law and using your service SHUT THEM DOWN

**Comment by XePup** [comment]
> yeah thats a client but the main game its a different story in my opinion Minehut is just being lazy so they dont have to enforce the eula when thats their job to do so if someone is breaking the law and using your service SHUT THEM DOWN

so your saying its the MC HOST's job, that would be way to hard. Firstly your saying every single host which has loads of servers and secondly its impossible to enforce it completely without someone breaking it.

**Comment by killergotrekt** [comment]
> yeah thats a client but the main game its a different story in my opinion Minehut is just being lazy so they dont have to enforce the eula when thats their job to do so if someone is breaking the law and using your service SHUT THEM DOWN

Administrators and Moderators has already denied these suggestions already in the past - no changing their minds as of now.

**Comment by tarna** [comment]
> yeah thats a client but the main game its a different story in my opinion Minehut is just being lazy so they dont have to enforce the eula when thats their job to do so if someone is breaking the law and using your service SHUT THEM DOWN

It is not Minehut's job or any server host's to enforce the EULA. And the Minecraft EULA isn't a law.
