### ISSUE TITLE
More places to vote for minehut

### ISSUE THREAD

**Issue by SunnyWolve** [Minehut/Meta#728]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java, Bedrock and Website.
**Describe the feature**

I am suggesting that Minehut adds a vote feature to more voting websites. Basically you can vote at more than one site, and get credits from each.
**How the feature is useful**

The feature is useful to Minehut, as they can get more publicity from being listed on more sites, and to players, who can vote more and get more credits from doing so.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by DaRealMinecraftexpert** [comment]
Plus, the more vote sites, the more vote credits you can gain, right?

**Comment by SunnyWolve** [comment]
That is correct

**Comment by tarna** [comment]
Not good. Would ruin the credit economy. 25 credits per day is already good. It is even enough to get the first server plan by just voting. imo, if more sites were to be added, either the number of credits per vote would need to be reduced or you just get credits from one of the voting sites and people can vote on any of the sites.

**Comment by BennyDoesStuff** [comment]
We need to make money to continue operating Minehut since servers are not free. Because we're already the second-largest server in Minecraft, we aren't going to gain any more players from advertisements by allowing players to vote on other server lists as well.
