### ISSUE TITLE
Ad Track

### ISSUE THREAD

**Issue by Name12MH** [Minehut/Meta#729]
I think ad track should be back allowed but you should make it so one server can only be advertised 4 times in a 40 second period

**Comment by PundaChen** [comment]
Follow the format
The issue with ad track is not only the extreme spam it causes but also the fact that someone is storing the lobby chat, which isn't allowed
Also, 4 ads every 40 seconds is still a ton of ads

**Comment by DebitCardz** [comment]
They're working on a new server discovery feature, also ad track is really bad for the lobby chat.
