### ISSUE TITLE
Server Slots

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#73]
### Feature request

**Platform**
 Website

**Describe the feature**

Either lower the price on buying server slots or remove the price all together.

![](https://cdn.discordapp.com/attachments/592130982451216402/717989879774052352/unknown.png)

**How the feature is useful**

It's really pointless and just tricks new users who don't know they can make more than one account.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment]
I think the price is pretty much justified considering they wouldn't want you to buy 4393483 server slots for free lol.

**Comment by jellz** [comment]
It's not a trick. It's convenient to have all of your servers in one account

**Comment by CoreyShupe** [comment]
We won't remove the cost for buying server slots. You buy server slots so you don't have to remember 20 accounts for your servers. It's much easier to host a single user with multiple slots.
