### ISSUE TITLE
Server Discovery

### ISSUE THREAD

**Issue by Name12MH** [Minehut/Meta#732]
Vote.minehut.com

A website where it takes you to a page, there is a search bar and you can type the server you want, than it’ll show the upvotes and downvotes of that server, you can chose to login to your forums account or minehut account and up or down vote that server, 
There is also 5 pages on that page you can toggle between, each page will show 10 of the top servers so for example: page 1: top 10 servers, page 2: top 11-20 servers, so on, this would be an AMAZING idea imo and maybe you get 5 credits for voting? And you can vote for 1 server every day but not the same one or maybe same one idk, this would be amazing thing to have within minehut.

**Comment by DebitCardz** [comment]
Issue does not follow the format provided by Minehut.

**Comment by BennyDoesStuff** [comment]
Please recreate the issue and make sure you follow our issue template. Thank you!
