### ISSUE TITLE
File Manager considering file extension starting from the character next to the left-most period, till the last character of the full file name, while renaming.

### ISSUE THREAD

**Issue by CoolProgrammerX** [Minehut/Meta#735]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Dashboard (https://minehut.com/dashboard/)

**Describe the bug**

The File Manager considers all characters after the left-most period, of the file name, to be the file's extension. This happens when you try to rename the file.
For example, the file name is "MyPlugin-v1.2.3.jar", the File Manager considers "2.3.jar" to be the extension. As a result, it only allows you to rename the "MyPlugin-v1" part of the file name.

**To reproduce**
1. Go to https://minehut.com/dashboard/
2. Click on Activate (or Edit if the server is already online).
3. Navigate to the File Manager tab.
4. Upload a demo file. For example:
![Screen Shot 2021-08-16 at 11 42 30 AM](https://user-images.githubusercontent.com/74978722/129518940-65fb746c-d891-496d-844a-9a7fa7e1c7fb.png)
5. Make sure it's has been uploaded.
![Screen Shot 2021-08-16 at 11 43 47 AM](https://user-images.githubusercontent.com/74978722/129520572-c143429a-214c-44ca-ae3f-e178a7df5d55.png)
6. Right-click on this file, and click Rename.
![Screen Shot 2021-08-16 at 11 59 23 AM](https://user-images.githubusercontent.com/74978722/129520560-873e1618-a4e3-43a8-b422-de280586ee8a.png)

**Expected behavior**

Should consider the file name to be from the starting character, till the character before the right-most period in the file name, unless it's a file with the extension "tar.gz".

**Device Information**

- Minecraft client (and version): Minecraft 1.16.5
- Web browser (and version): Mozilla Firefox 91.0
- Operating system (and version): OS X 10.12.6
- Minehut server name: N/A

**Screenshots**

Provided in "Steps to reproduce the behavior".

**Additional context**

N/A

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by CoreyShupe** [comment]
This is a visual (ish) bug so I marked it with low priority, but this does seem like a bug, we might just want to not hide any part of it and let you rename like the option with windows file management. It might be beneficial to make it a user setting.

**Comment by CoolProgrammerX** [comment]
> This is a visual (ish) bug so I marked it with low priority, but this does seem like a bug, we might just want to not hide any part of it and let you rename like the option with windows file management. It might be beneficial to make it a user setting.

Thought so, doesn't seem like a bug, more of a suggestion.

**Comment by CoolProgrammerX** [comment]
@BennyDoesStuff
Requesting to close issue as we can now modify the file name along with its extension.
