### ISSUE TITLE
Sending/Sharing Credits

### ISSUE THREAD

**Issue by SunnyWolve** [Minehut/Meta#736]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java
**Describe the feature**

Credit Tranfer. Make it so that there is a feature to send people credits.
**How the feature is useful**

This feature benifits players, who can send credits to their friends.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Tringlle** [comment]
We've already determined this. The answer is no (#274)
