### ISSUE TITLE
Domain Names for paid plans

### ISSUE THREAD

**Issue by muiky05** [Minehut/Meta#740]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Not 100% sure, more ingame than others though

**Describe the feature**

Custom Domain name allowed for servers while still keeping /ad permissions (potentially a paid only perk, for certain plans)

**How the feature is useful**

Will make servers more appealing as .minehut.gg looks less like an official server than (name).net or (name).com

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MrBaileyQ** [comment]
You can set custom server IP's. If you register a domain & edit the DNS you can get a custom IP!

**Comment by CoreyShupe** [comment]
Custom IPs are already a thing as said by MrBailey, there's a CFAQ section about them. Closing this since it's already possible with custom domain records.

**Comment by muiky05** [comment]
didnt know that, my fault
