### ISSUE TITLE
enforce caps rule on ads

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#741]
**Platform**
ingame both

**Describe the feature**
enforce the caps rule on ads

**How the feature is useful**
 less floody if ads arent in full ads, I dont know why this doesnt get enforced, all rules still count even in ads
![image](https://user-images.githubusercontent.com/42002575/130099955-8859c85a-46b6-4f6d-a9ba-1bb38933346c.png)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment]
This is already something our moderation team does.

**Comment by PundaChen** [comment]
Idk about you but they dont really seem to care all that much about ads in full caps

**Comment by CoreyShupe** [comment]
> Idk about you but they dont really seem to care all that much about ads in full caps

I forwarded the issue to our mod team and they'll work on being more vigilant about the issue.
