### ISSUE TITLE
Allow adrewards but increase time/advertisement

### ISSUE THREAD

**Issue by Thomas6098** [Minehut/Meta#743]
### Feature request

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

I own a server called Light Skies which is the 2-3rd biggest skymine server on minehut. Recently our player count has gone from 80 at peak to 30-40 players online due to adrewards. The removal of adrewards has hit hard on us and other not gen servers. Currently the most common way people join servers is through the in game server list which makes it hard for new and non gen servers to grow. The reasoning for removing adrewards is that it makes the lobbies full of just advertisement spam. My solution to this is to increase the time per advertisement to about 4x but allow adrewards. This would mean it is possible to grow a new server and would reduce the amount of spam in the lobbies. 

**How the feature is useful**

It helps new servers get exposure and not just stay at the bottom. The only way to grow currently is to be already big and be a gen server. New servers and non gen servers have no chance. 

**Please upvote this so minehut can see this.** 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
Adrewards is under the collecting data from minehut, the main concern is people using this data maliciously. Also increasing the time is more of a band-aid patch instead of a permanent one

**Comment by CoreyShupe** [comment]
On what @Blocksnmore was talking about, we want to lean more into a better server discovery architecture than lobby spam. It's not a great way of handling things. In the discord we have quite a few ideas and an entire channel dedicated to coming up with ideas.

**Comment by Thomas6098** [comment]
> Adrewards is under the collecting data from minehut, the main concern is people using this data maliciously. Also increasing the time is more of a band-aid patch instead of a permanent one

how is it being used maliciously?

**Comment by CoreyShupe** [comment]
> how is it being used maliciously?

Data from anywhere could be used maliciously, tracking a user and figuring out where they are, who they're advertising to, what they're talking about. Either way it's mining data which is not good in any sense. We don't allow mining data and selling it, and we also don't want bots sitting around our lobbies especially with that intention.

Even if this wasn't an issue my comment prior still stands, we'd rather lean into a better advertisement architecture.

**Comment by Thomas6098** [comment]
> > how is it being used maliciously?
> 
> Data from anywhere could be used maliciously, tracking a user and figuring out where they are, who they're advertising to, what they're talking about. Either way it's mining data which is not good in any sense. We don't allow mining data and selling it, and we also don't want bots sitting around our lobbies especially with that intention.
> 
> Even if this wasn't an issue my comment prior still stands, we'd rather lean into a better advertisement architecture.

They could implement their own ad reward system. I would even be willing to create one for them

**Comment by CoreyShupe** [comment]
> > > how is it being used maliciously?
> > 
> > 
> > Data from anywhere could be used maliciously, tracking a user and figuring out where they are, who they're advertising to, what they're talking about. Either way it's mining data which is not good in any sense. We don't allow mining data and selling it, and we also don't want bots sitting around our lobbies especially with that intention.
> > Even if this wasn't an issue my comment prior still stands, we'd rather lean into a better advertisement architecture.
> 
> They could implement their own ad reward system. I would even be willing to create one for them
> and the last bit yea but there would be the same amount of ad spam as now

We could create our own ad reward system sure, but that's not where we want to spend our time, and no we don't take public contributions to our internal codebase.

As for "it would be the same" is incorrect, we've seen a drop in usage since enforcing the rule, and either way it's not a great system in the first place, it's a step up over no system, but we'd rather implement a more complex system to handle this kind of thing.

The dedicated channel has a bunch more information on what we're trying to do and it's a massive step over ads in the lobby chat. Either way we really don't want to lean more into the /ad system or even do more work towards it until we have more of our server discovery system created. Dev work is prioritized and working on the /ad system is not a priority over the new server discovery system we have in the planning stages right now.

Ad rewards is a cool system and it's neat how people got it working, however, it does include mining our private data and causes more issues than it solves.

**Comment by BennyDoesStuff** [comment]
I'm going to go ahead and lock this issue based on the conversation that happened above. We are planning on adding a new system that will allow servers to more easily advertise and grow their player base without needing to flood our lobby chats. We currently have a Discord channel in our meta Discord server focused on discussing possible ways to rework this.

Once we come closer to changing this up, we'll make sure to gain additional feedback.
