### ISSUE TITLE
Multiple Users.

### ISSUE THREAD

**Issue by RORY112345** [Minehut/Meta#745]
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x ] This issue does not contain any sensitive information 

Add multiple Users for the Dashboard for the server. For staffs to have their own login credentials. So we can add the user's name in there or something like that. And we can give him perms like Only able to access the server's file manager.

**Comment by drtshock** [comment]
#13
