### ISSUE TITLE
Modpacks and Forge 1.16

### ISSUE THREAD

**Issue by RORY112345** [Minehut/Meta#748]
**Checklist**
- [ x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x ] This is not a bug report, support request or plugin request
- [ x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x ] This issue does not contain any sensitive information 

Add Normal Forge 1.16, Modpacks option.

**Comment by tarna** [comment]
You can suggest more server types in #722 and forge has already been suggested. And Modpacks aren't a server type. But if you mean adding different modpacks to the addon page, that is already planned. 

This issue also doesn't follow the full format.

**Comment by RORY112345** [comment]
What is the full format if i may ask? So next time when i ask question i can use that.

**Comment by tarna** [comment]
> What is the full format if i may ask? So next time when i ask question i can use that.

Just don't delete any of the text that comes up when creating the issue with the format and fill out the questions that it asks.

**Comment by CoreyShupe** [comment]
Forge 1.16 isn't possible on proxies anyhow.
