### ISSUE TITLE
“I know what I’m doing.”

### ISSUE THREAD

**Issue by Name12MH** [Minehut/Meta#751]
[x] Request - Add an “I know what I’m doing.” Button to the account settings, it will make all free add one instant click to download and delete, also will not warn you when opening certain file types, and a bunch of other fratires. Would make everything so much easier…

**Comment by Tringlle** [comment]
Use the template. Its there for a reason.

**Comment by BennyDoesStuff** [comment]
Please recreate your issue and make sure you follow the template provided. Thank you!!
