### ISSUE TITLE
Targeted at @BennyDoesStuff 

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#768]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

Github
**Describe the feature**

Please close with a comment... Don't send a message, then click close. Please
**How the feature is useful**

It benefits people who are watching GitHub. I get 2 emails every time you close an issue. You send a reason, and then a "Closed #number" 
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
This is a comment, I’m click the button “close with comment” which should close the issue with whatever reasoning I put in this box. I’m not sure if I’m doing something wrong, but correct me if I am.
