### ISSUE TITLE
An infinitely loading Minehut logo is shown when you're being redirected to the login screen as soon as the session expires.

### ISSUE THREAD

**Issue by CoolProgrammerX** [Minehut/Meta#775]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Dashboard

**Describe the bug**

The Minehut logo infinitely loads when your session expires, and you're being redirected to the login page. The issue can be resolved by using a VPN or switching between internet connections. Also checked the Minehut Discord and noticed other people experiencing the same.

**To reproduce**
Steps to reproduce the behaviour:
Sorry, I'm unsure about reproducing this.

**Expected behaviour**

Should show the SLG login page.

**Device Information**

- Minecraft client (and version): N/A
- Web browser (and version): Mozilla Firefox 91.0.2
- Operating system (and version): macOS Sierra 10.12.6
- Minehut server name: N/A

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by BennyDoesStuff** [comment]
This should be fixed now.
