### ISSUE TITLE
Allow custom server icons in the server list.

### ISSUE THREAD

**Issue by emopedia** [Minehut/Meta#777]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game

**Describe the feature**

A server icon, one that goes next to the name and motd on the server list.

**How the feature is useful**

It is an ideal way to make servers more recognizable in the server list. With thousands of servers and the vast majority of players having extensive server lists, a server icon is good to have in order to stand out and be recognizable.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Reimagining** [comment]
yes. no other comments necessary, this should be a priority function!

**Comment by BennyDoesStuff** [comment]
Do you mean in the server GUI in the lobby, or in the multiplayer list on your Minecraft launcher?

**Comment by Reimagining** [comment]
The multiplayer list. It is default to minehut logo and cannot be customized whatsoever.

**Comment by emopedia** [comment]
> Do you mean in the server GUI in the lobby, or in the multiplayer list on your Minecraft launcher?

The multiplayer list.

**Comment by BennyDoesStuff** [comment]
Duplicate of #419
