### ISSUE TITLE
Parkour server category

### ISSUE THREAD

**Issue by skaoir** [Minehut/Meta#780]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**
Minehut should add a "Parkour" server category. that's it

**How the feature is useful**
It would be much easier to find good parkour servers.

**Comment by tarna** [comment]
Use #627 to suggest new categories.

**Comment by BennyDoesStuff** [comment]
#627 should be the place where you suggest new categories. Thank you for the suggestion, however!
