### ISSUE TITLE
Custom forge versions

### ISSUE THREAD

**Issue by TwisterLT7** [Minehut/Meta#782]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

I had an idea for a system that allows any user to use any version of forge on their servers by making a drop down menu for minecraft version known as custom. You then get to control what version of Mc you can install e.g. Beta, alpha and older releases without it constantly installing and checking the current minecraft version is there. 
**How the feature is useful**

This would benefit people as they would have more control on what their server looks like as currently users are limit to servers that are 1.8 and above where competitors such as aternos give almost all minecraft versions free. It would also mean problems that occur on specific versions of forge have compatability with mods as things like sponge forge don't always work as intended with certain mods like vics. Overall this would also increase popularity with the server as you would be able to have for options for servers and thus better business for Minehut in general. 
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment]
Minehut uses Velocity and it only supports 1.7+ servers so lower versions won't work anyways. Also, they are already working on adding more server types and versions. You can just suggest them in #722 if they haven't been suggested already.

I also remember Trent saying they have to go into like a maintenance in order to add new server types but they can add new versions to a server type without a maintenance. So they can't add new server types easily.

**Comment by BennyDoesStuff** [comment]
Unfortunately like mentioned above, because Minehut uses a proxy system, not all versions will be compatible with Minehut. This also isn't the thread to suggest new versions. Thanks for the suggestion, however!
