### ISSUE TITLE
World (from mh-marketplace) resets after uninstalling worldedit

### ISSUE THREAD

**Issue by Deltaxbyte** [Minehut/Meta#783]
[link of steps to recreate](https://drive.google.com/file/d/1oLnqbt6JR8uI-jQkr9ayzMev8iR1ussg/view?usp=sharing)
(video has terrible quality bc my pc is broken and I had to use my laptop)

Pls fix this issue. This highly impacts servers with maps from the marketplace therefore affecting the creators who will earn less from their products. I can't confirm this bug applies on other plugins since it will take a lot more time to test them out, but for sure uninstalling worldedit definitely triggers this issue. I had a friend whom doesn't use a map from the addon panel which had no trouble uninstalling worldedit, so I believe the problem might be because now map products are considered as a addon as well which I believe is not right.

**Comment by BennyDoesStuff** [comment]
I'm not able to reproduce this. Could you please recreate this issue and make you sure:
- follow the issue format we have provided on the GitHub
- provide a bit more information on how to reproduce (such as the exact market item this happens to, etc).

Thank you so much for reporting bugs!

**Comment by Deltaxbyte** [comment]
Updated, I hope these information help. @BennyDoesStuff
