### ISSUE TITLE
API broken and misleading 

### ISSUE THREAD

**Issue by Giuca002** [Minehut/Meta#789]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

WEB

**Describe the bug**

Only the very basic api commands work and for more advanced stuff you get cannot post/ errors 
**To reproduce**
Use the api to turn on a server

**Expected behaviour**
turn on the server

**Device Information**

- Minecraft client (and version): 
- Web browser (and version): Brave and safari 
- Operating system (and version): IOS and windows 10
- Minehut server name: FishDev

**Screenshots**

**Additional context**

At this point you might as well get rid of the api or fix it :/ but it would be nice to be able to turn on my server from my phone with the api 
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Reimagining** [comment]
Yeah, doesn't work for me either :/

**Comment by CoreyShupe** [comment]
API isn't officially supported.
