### ISSUE TITLE
/m doesn't tab complete names

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#79]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

In-game, Java (1.16.2)
**Describe the bug**

when I write '/msg ' it tab completes the names of users in the lobby/server. However when I do '/m ' (alias of /msg) it does not.
**To reproduce**
Steps to reproduce the behaviour:
1. Type '/m ' in the lobby
2. See error

**Expected behaviour**

/m would tab complete the users in the lobby/server
**Device Information**

- Minecraft client (and version): 1.16.2
- Operating system (and version): MacOS Catelina version 10.15.4

**Screenshots**

![Screen Shot 2020-08-16 at 12 58 20 pm](https://user-images.githubusercontent.com/58871819/90325586-e95b2180-dfc0-11ea-8f6f-c8226c5ddbdd.png)
![Screen Shot 2020-08-16 at 12 58 29 pm](https://user-images.githubusercontent.com/58871819/90325588-f24bf300-dfc0-11ea-8d18-8ec20d84784e.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by MiginsMC** [comment]
Text colours and the things that go above the message like <message> also don't work with the /m alias.
![Screen Shot 2020-08-21 at 6 20 03 pm](https://user-images.githubusercontent.com/58871819/90868979-f02bcf00-e3da-11ea-94d0-62e641a8d863.png)
![Screen Shot 2020-08-21 at 6 20 30 pm](https://user-images.githubusercontent.com/58871819/90869022-0043ae80-e3db-11ea-863b-c1cf63a1b47c.png)

**Comment by PundaChen** [comment]
Can confirm, 1.12.2 5zig + optifine

**Comment by theminecoder** [comment]
This isn't a bug per say. The actual issue is that player have access to the built in msg command on the lobby server, were the tab completing is happening. /m is handled on the proxy where It has no knowledge who on your actual server (this would be an expensive call to keep up to date considering how many people are online at any point in time). We will be removing the built in msg command on the lobby server at some point in the future which will remove the confusion.
