### ISSUE TITLE
Tester Rank not shown in /friend list

### ISSUE THREAD

**Issue by pogchampjacob** [Minehut/Meta#793]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 Java (and probably bedrock)

**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. Add a "Tester" ranked player as a friend.
2. Run /friend list
3. Scroll down to their name.
4. They won't have the rank.

**Expected behaviour**

Should show the colour of their rank or something similar.

**Device Information**

- Minecraft client (and version):  1.16.5
- Web browser (and version):  Brave 
- Operating system (and version): Windows 10 Build 19043
- Minehut server name: Lobby

**Screenshots**

https://media.discordapp.net/attachments/546422616609783818/888781409920102510/unknown.png

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Joshplays05MC** [comment]
Yeh same I have [Tester] ranks on my friends list and their names are just gray. As well as [Events] rank also I believe.

**Comment by CoolProgrammerX** [comment]
FiXed said that this will be fixed when the proxies restart.
![C2A6D325-8F28-4FE8-9650-0DC8AA777FAD](https://user-images.githubusercontent.com/74978722/133915488-de3118c2-3c57-44cc-ac51-c0adc222fdfe.jpeg)
More information here: https://discord.com/channels/546414872196415501/546422616609783818/883746397759893555
