### ISSUE TITLE
Automatic Script Reloading

### ISSUE THREAD

**Issue by MrScopes** [Minehut/Meta#796]
### Feature request

**Checklist**
- [-] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [-] This is not a bug report, support request or plugin request
- [-] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [-] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Whenever saving a .sk file, it should ask "Do you want to reload this script?". There could also be a button "don't ask again" and when in a .sk file there could be a special button for managing that. When in a folder in your scripts folder ex: scripts/hello/hi.sk, there could be a button "Reload this folder?". It could sudo the owner ingame (not sure if this is possible, just for errors), or just run through the console. Just an idea to make developing a bit quicker.

**How the feature is useful**
Would make developing in Skript a bit faster.

**Comment by tarna** [comment]
SkQuery is an addon that has a feature where if you put this certain option in a skript, it will automatically reload it if it detects a change. You can just use that or some other plugin that has a similar feature. 

https://skripthub.net/docs/?id=3895

**Comment by drewtadlock** [comment]
> This is something you could implement yourself through a plugin (or even a script using Skript-mirror) so I don’t think it’s something that would be added to the file manager itself.

Live console was also something we could implement ourself
