### ISSUE TITLE
Sponsor links

### ISSUE THREAD

**Issue by Dinoboy50** [Minehut/Meta#797]
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

 discord

**Describe the feature**

I want you to post links of sponsorships in discord so people who want to watch them can easily do so
**How the feature is useful**

People who want to watch dont have to wait hours just to get a 30 second video and minehut (probably) gets free money

Vote yes or no

**Comment by BennyDoesStuff** [comment]
Unfortunately, it doesn't work like this. There is a limit on how many times you can watch the video over a certain period of time.

**Comment by Dinoboy50** [comment]
Yes but why does that stop having a permanent link? you can make this link redirect to the new link every time it changes
