### ISSUE TITLE
Feature Request: Allowing server owners to access the server panel when their server is in hibernation mode

### ISSUE THREAD

**Issue by bes-ptah** [Minehut/Meta#798]
### Feature request

***
###### -  ✓ This issue does not contain any sensitive information 
***

#### Platform
Both Java and Bedrock, although I don't use bedrock

***
**Describe the feature**
Server owners should have access to their panel (server files, addons, console etc), even if the servers are hibernated. Server owners can also edit files before starting the server, meaning also they save a restart. (I'm also a server owner and that is how I got this idea)
***
**How the feature is useful**
It could lower the amount of minehut computers hosting servers running just for accessing the panel, more available servers for other people, and allows server owners to do anything they need to before starting the server up.

---
**Use 👍 and 👎 reactions on what you think on my idea**

**Comment by CoolProgrammerX** [comment]
This comment might relate to it: https://github.com/Minehut/Meta/issues/737#issuecomment-899533204
