### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by Extrample** [Minehut/Meta#799]
Please add a category "PvE" and "1.8 PvE", Since I am making a player versus entity server, so please add PvE
**do it i dare you**

Thank you.

**Comment by CoolProgrammerX** [comment]
> Please add a category "PvE" and "1.8 PvE", Since I am making a player versus entity server, so please add PvE
> **do it i dare you**
> 
> Thank you.

Incorrect format while making a suggestion issue, use this template from here: https://github.com/Minehut/Meta/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=New+category+request

**Comment by tarna** [comment]
use issue #627 to suggest new categories

**Comment by CoolProgrammerX** [comment]
> Please add a category "PvE" and "1.8 PvE", Since I am making a player versus entity server, so please add PvE
> **do it i dare you**
> 
> Thank you.

Incorrect format to suggest something. Also, use this thread to suggest server categories:  https://github.com/Minehut/Meta/issues/627

**Comment by BennyDoesStuff** [comment]
#627
