### ISSUE TITLE
Allow editing of all server files directly

### ISSUE THREAD

**Issue by drtshock** [Minehut/Meta#8]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Allow users to edit all server files directly, except .jar files. Minehut will need to overwrite any options in server.properties, spigot.yml, and paper.yml that need to be overwritten such as player count, and any settings related to bungee.

**How the feature is useful**

Brings us closer to other normal hosts, gives users much more control over their server. I can stop getting dm's about 0 tick farms.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Does this mean file types like .js will become available?

**Comment by jellz** [comment]
What plugins does Minehut have that uses .js files?

**Comment by iGalaxyYT** [comment]
> What plugins does Minehut have that uses .js files?

WorldEdit and a few others
