### ISSUE TITLE
this is stupid

### ISSUE THREAD

**Issue by Extrample** [Minehut/Meta#802]
This is so stupid, Cursing is not allowed in messaging, Like last time it was so good, So please bring curse messaging back, Or maybe make it so when you are friends with someone you can curse, but you can't if you aren't friends with someone, OR MAYBE A SETTING SO YOU CAN enable cursing, Please, No one sees you cursing, It's literally private messaging!!! So there's no reason to block this in messaging.

**Comment by tarna** [comment]
You need to use the issue format when making suggestions. Also this could possibly fall under the discussion that happened in #359.

**Comment by BennyDoesStuff** [comment]
Please use the issue format when submitting suggestions.
