### ISSUE TITLE
Change Account Email

### ISSUE THREAD

**Issue by orvitpng** [Minehut/Meta#805]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

The ability to change your account email. I have run into scenarios where I am switching emails and I can't switch on Minehut.
**How the feature is useful**

It allows you to get a new email without losing access to everything.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment]
dupe of #265

**Comment by orvitpng** [comment]
> dupe of #265

Searched for the keyword email and didn't find it. My bad.
