### ISSUE TITLE
Rename the mc-functions channel

### ISSUE THREAD

**Issue by erenkarakal** [Minehut/Meta#811]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform** Discord

**Describe the feature** Renaming the mc-functions channel, here are some possible names: vanilla, vanilla-functions, vanilla-commands, vanilla-mechanics, vanilla-technical, datapacks-commands

**How the feature is useful** People are ALWAYS misusing the channel, hopefully this will reduce, maybe remove it

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
Good idea, but let's keep Discord-specific channel suggestions out of GitHub. I will write this down and refer back to it in the future.
