### ISSUE TITLE
Ability to actually appeal / report something which happened on Discord

### ISSUE THREAD

**Issue by LouisLit** [Minehut/Meta#813]
Right now you gotta enter every single field about client mods, what server it occurred on, the server version, and the server IP.

But none of these refer to discord. Just in game. And even at that, do not apply to in game appeals either. 

Astounds me that I need to point this out, but add a section for Discord Appeals, Minecraft Appeals, Discord Reports, Minecraft Reports. Lmao

**Comment by Sniped** [comment]
use [the format](https://github.com/Minehut/Meta/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=)

**Comment by Sniped** [comment]
then someone needs to close this issue

**Comment by LouisLit** [comment]
> then someone needs to close this issue

@BennyDoesStuff

**Comment by CoreyShupe** [comment]
Not using proper format.
