### ISSUE TITLE
Notify players when starting server with >12 plugins and Free plan.

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#82]
### Feature request

**Platform**
 In-game

**Describe the feature**

**How the feature is useful**

Send players a message in the lobby like That server couldn't start because it needs an upgraded plan. when they try to start a server that has >12 plugins but still uses the Free plan.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
I think panel already does this... Are you saying for people that want to only open the server from in game?

**Comment by farwl** [comment]
Yeah. People who don't own the server and try to start it via the in-game lobby. They could be confused as to why it isn't starting and blame Minehut for a 'bug'.

**Comment by WallyTube** [comment]
I highly doubt someone would submit  a bug report before checking their panel, but okay.

**Comment by BennyDoesStuff** [comment]
The plugin limit no longer exists as of the recent custom plugins update.
