### ISSUE TITLE
Don't make proxy require a server plan.

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#826]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

Remove the requirement of a server plan to use server networks. Its not necessary in the slightest.

If you're going to require a plan, at least only do it on the proxy server.
**How the feature is useful**

It benefits creators who are trying to create something unique, but don't have money to spend on credits.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment]
> Sure, but every additional "world" server will still require a plan, and so will the additional server slots. For owners or players starting out, they are unlikely to abuse that system without buying more credits themselves. Allowing a free tier to function as a proxy is more so for people that want to try it out or test it out. Small servers would still require someone to stay online, and as they grow they will inevitably purchase more plans or credits.
> 
> IMHO I just don't see how this change could drastically imbalance things, if anything balance it out as people are more willing to purchase for something they have tried. Paying users will be able to try networks on their server and decide if it's right for them or not; non-paying users will either need to purchase server plans/credits for every added server or just not use it. But it's still early to say nonetheless

With your way, say someone owns 4 servers. One proxy is free and 3 servers have a plan and are connected to the proxy. And then there is one player connected to one of the proxy servers and now all 3 servers are online until they log off. So they are paying for 3 servers but basically have all those servers online using just one player. But if they make the proxy server also require a plan, they are paying for 4 servers and that could make up the resources for being able to use one player to keep all the servers online. Sorry if this explanation isn't great.

But FiXed said that they are working on new plans for proxies anyways so the pricing for them will change.

**Comment by BennyDoesStuff** [comment]
I'm going to close this issue. One important fact when it comes to proxies is we can't track what sub servers a player is on, only the fact that they are online somewhere on that proxy. That means any server you add to the proxy will stay online 24/7, even if the server is on our cheapest paid plan (~$4/month).

Sometime in the future, we're planning on adding a specific "proxy plan" which you can purchase for your proxy. I don't have any details or specifics on this just yet, however.
