### ISSUE TITLE
TuSKe does not work

### ISSUE THREAD

**Issue by KingCreeperz** [Minehut/Meta#838]
On 1.17.1 and with the latest version of TuSKe. it doesn't work

Proof:
![image](https://user-images.githubusercontent.com/72216537/139484775-e6be6fd8-8b7a-4e22-ae41-916f5ad3a573.png)

I reloaded a command using a GUI and that it did not work. I AM MAKING A RPG I HAVE WORK TO DO

Here is the code `command /fun [<string>] [<player>]:
  permission: op
  permission message: "&cYou can't have fun non"
  trigger:
    if arg-1 is not set:
      send "&cFun" to player
      send "&c/fun give <player>" to player
    if arg-1 is "give":
      give arg-2 book named "&c&lFun Spell" with lore "&7Let's have fun"
      if arg-2 is not set:
        send "&cPlease state a player before giving" to player
on right click:
	if name of player's tool is "&c&lFun Spell":
		open virtual chest with size 3 named "&c&lFun Spell" to player
		format gui slot 9 of player with tnt named "&cSpawn TNT" to run:
			spawn tnt at player`
			
It seems that `format gui slot 9 of player with tnt named "&cSpawn TNT" to run` is probably the problem

Let me know

**Comment by tarna** [comment]
This doesn't follow the format. And that would be an issue with Skript and TuSke. Nothing that Minehut can fix. TuSKe is heavily outdated and hasn't been updated in over 4 years. Revert to Skript 2.5.3 if you still want to TuSKe. Or just remove TuSKe and use something else.

**Comment by Gloozzyy** [comment]
> This doesn't follow the format. And that would be an issue with Skript and TuSke. Nothing that Minehut can fix. TuSKe is heavily outdated and hasn't been updated in over 4 years. Revert to Skript 2.5.3 if you still want to TuSKe. Or just remove TuSKe and use something else.

reverting doesnt work for me it just makes it so i cant reload scripts with guis lol

**Comment by MrScopes** [comment]
> > This doesn't follow the format. And that would be an issue with Skript and TuSke. Nothing that Minehut can fix. TuSKe is heavily outdated and hasn't been updated in over 4 years. Revert to Skript 2.5.3 if you still want to TuSKe. Or just remove TuSKe and use something else.
> 
> reverting doesnt work for me it just makes it so i cant reload scripts with guis lol

skript-gui is the updated, maintained version of tuske
[Download](https://github.com/APickledWalrus/skript-gui/releases), [How-To](https://github.com/APickledWalrus/skript-gui/wiki); alternatively you can use [Vanilla GUIs](https://forums.skunity.com/threads/vanilla-guis.8939/)

**Comment by KingCreeperz** [comment]
Dude don’t necro post

**Comment by MrScopes** [comment]
@KingCreeperz this issue is unrelated to minehut and needs to be closed out, I answered the users question and informed a staff member
