### ISSUE TITLE
Whitelist status resetting on velocity proxy restart

### ISSUE THREAD

**Issue by bubbarob19** [Minehut/Meta#840]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
In-game, Java Edition

**Describe the bug**
 Whenever I restart my velocity server proxy, the whitelists of the sub-servers disable. The players on the whitelist do not change; just the status of the whitelist.

**To reproduce**
Steps to reproduce the behaviour:
1. Create a velocity server proxy with subservers
2. Turn on the whitelist on the subserver
3. Either wait for your proxy to shut down or manually shut it down
4. Restart the proxy
5. Join the server, and you will see that the whitelist is off

**Expected behaviour**
I expected for the whitelist to stay on, rather than disabling.

**Device Information**

- Minecraft client (and version): Optifine 1.17.1
- Web browser (and version): Chrome
- Operating system (and version): Windows 10
- Minehut server name: Abundant

**Screenshots**

**Additional context**
FiXed told me in the Velocity Discord to make an issue here.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by MinecraftMan1013number2** [comment]
ive heard of this happening to a couple of people, and it also happens to some servers im working on.

**Comment by ReportCardsMC** [comment]
This is due to your whitelist setting in the settings tab in your server manager, pretty sure it's intentional but it sucks

**Comment by drtshock** [comment]
This should be fixed now.
