### ISSUE TITLE
Server won't start after removing it from proxy

### ISSUE THREAD

**Issue by Georgak** [Minehut/Meta#848]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 Website

**Describe the bug**

My server won't start after removing it from proxy.

![image](https://user-images.githubusercontent.com/65731193/140575339-a42705bf-00ab-407b-b85a-194f9ea8e48d.png)

**To reproduce**
Steps to reproduce the behaviour:
1. Make a proxy
2. Add a server to it
3. Move server out of proxy
4. Server doesn't start

**Expected behaviour**

Start of server

**Device Information**

- Minecraft client (and version): -
- Web browser (and version):  -
- Operating system (and version):  -
- Minehut server name: EcoKB

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by drtshock** [comment]
Does it work if you hibernate the server or change the server type / version?

**Comment by Georgak** [comment]
> Does it work if you hibernate the server or change the server type / version?

It doesn't work when i hibernate the server, but i haven't changed the server version to anything. Both the server and the main proxy server is set to 1.17.1

**Comment by Georgak** [comment]
> Does it work if you hibernate the server or change the server type / version?

I just tried removing the server from the proxy after it was hibernated and changed its Minecraft version, but it won't start:
![image](https://user-images.githubusercontent.com/65731193/141145501-2eb0fcb3-ff3e-43fd-8465-b19780ac8b92.png)

**Comment by CoreyShupe** [comment]
Internal bug ticket made.
