### ISSUE TITLE
File Search improvements

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#85]
### Feature request

**Platform**
 Website (Panel File Manager)

**Describe the feature**

Make the Search Files bar bring up all instances of your search query from all of your server's files, not just the current directory. This would help people navigate easier, and it's kind of pointless to just keep it to one directory, because most folders don't have too many files so it's easy to find what you're looking for.

![](https://cdn.discordapp.com/attachments/592130982451216402/722920130627239936/unknown.png)

Also make the search not case sensitive.

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
Implemented in the recent file manager update.
