### ISSUE TITLE
Friend list bug

### ISSUE THREAD

**Issue by IWolfZZ** [Minehut/Meta#852]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 Both

**Describe the bug**
 What the bug is, is everyone on your friend list is blue so with the online icon.

**To reproduce**
Steps to reproduce the behaviour:
1. Type /friend list

**Expected behaviour**

**Device Information**

- Minecraft client (and version):  Vanilla
- Web browser (and version):  None
- Operating system (and version):  Windows
- Minehut server name:  None

**Screenshots**
 
![image](https://user-images.githubusercontent.com/87252860/141246421-42f44993-769c-4a80-bf49-25c9e248403d.png)

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Checkmate128** [comment]
Despite how stupid this “feature” is, I am pretty sure this is intentional.

**Comment by CoreyShupe** [comment]
I don't think this is intentional. Will add it to the backlog.

**Comment by CoreyShupe** [comment]
This should be fixed now
