### ISSUE TITLE
Text Editor

### ISSUE THREAD

**Issue by Georgak** [Minehut/Meta#854]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website

**Describe the bug**

Text Editor sometimes deletes characters instead of adding a space when pressing the space button in your keyboard.
To fix you need to reopen the file.

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by CoreyShupe** [comment]
This seems like overwrite mode.
https://www.webopedia.com/definitions/insert-mode/amp/

**Comment by tarna** [comment]
I know this is already closed but this was a dupe of #801, which is also invalid but isn't closed yet
