### ISSUE TITLE
Using Github for servers

### ISSUE THREAD

**Issue by ReportCardsMC** [Minehut/Meta#861]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Being able to give a github URL (and tokens for private repos) to allow for easy server updating through github repositories. Maybe even allowing specific files to pull from a repo as compared to the entire server folder. So for example I could have a plugin that I want to auto-update on restart from a github repo/release before the server starts up again.

**How the feature is useful**

This would be useful for servers that are commonly updating their plugins/scripts, especially if they have multiple hub/game servers with the same files, it'd make it easy to go through each, and click a button to pull from the repo (or even allow on start to pull).

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by mpschorr** [comment]
(Probably) a dupe of #711

**Comment by ReportCardsMC** [comment]
Ah my bad, my search didn't come up with anything

Yes, this is a dupe of that, thank you for pointing it out :)))
