### ISSUE TITLE
Servername seen as "Inappropriate"

### ISSUE THREAD

**Issue by DuEselGeburt** [Minehut/Meta#862]
### Bug report

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] I am NOT reporting a security vulnerability
- [x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x ] This issue does not contain any sensitive information

**Platform**
 Java idk about Bedrock

**Describe the bug**
 basicly my server name is "EselCrafts" and MH doesnt allow that i say "Donkey" in German(Esel) so it says its inappropriate and that doesnt allow me to advertise my server nor msg it to anyone without evading the Block

**To reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
 my Servername to work? idk why it is even seen as Inappropriate

**Device Information**

- Minecraft client (and version): Latest Version Normal Minecraft
- Web browser (and version): Google Chrome (Latest)
- Operating system (and version): Windows 10
- Minehut server name: EselCrafts

**Screenshots**
 /

**Additional context**
 /

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Checkmate128** [comment]
This might be more of a filter request rather than a bug.
