### ISSUE TITLE
File uploading on the file manager broken

### ISSUE THREAD

**Issue by SantioMC** [Minehut/Meta#864]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website

**Describe the bug**

Uploading a file on the file manager doesn't work. Uploaded files do appear in the correct uploaded directory but show up as 0 bytes as the file size [example image](https://i.imgur.com/dPQUkMC.png)

**To reproduce**
Steps to reproduce the behaviour:
1. Open file manager
2. Go to the directory you want to upload a file in and upload any sort of file
3. After uploading, it should appear as 0 bytes as the file size and the server should be unable to recognize the file.

**Expected behaviour**

Uploaded files should be able to upload correctly

**Device Information**

- Minecraft client (and version):  N/A
- Web browser (and version): Chrome (Version 96.0.4664.45 (Official Build) (64-bit))
- Operating system (and version): Windows 10 21H1
- Minehut server name: N/A

**Screenshots**
[Final upload result](https://i.imgur.com/dPQUkMC.png)

**Additional context**
None

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by drtshock** [comment]
Fixed, thanks for reporting.
