### ISSUE TITLE
Ad Captcha

### ISSUE THREAD

**Issue by IWolfZZ** [Minehut/Meta#879]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Java Ingame

**Describe the feature**

What feature I am suggesting is the captcha for the /ad so like if the player was constantly advertising for hours it would give them a captcha to solve. (No matter if they have a rank or not.)

Another idea is a IP limit per player for advertising a certain server. How will this help, is it will remove a lot of people that are just using accounts or NFA's for advertising there server. So basically if you have more than 3 accounts advertising in the last 2 mins it will block your ad & kick you.

In my opinion I think both of these ideas should be added. Give some feed back.

**How the feature is useful**
How's this is useful is it will remove ad botters and make some part of the lobby less spammy (a little bit)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Checkmate128** [comment]
As far as I am aware, you can use as many accounts as you want to advertise. However, Minehut has the ability to know how often someone advertises, how accurate their ads are (how much time after cooldown before ad), and other info. Minehut could utilize both random captchas and captchas targeted at players who are deemed suspicious by some sort of algorithm.

**Comment by IWolfZZ** [comment]
"know how often someone advertises, how accurate their ads are (how much time after cooldown before ad), "

 **Calculating how accurate there ads are would be useless since someone could just easily put a randomizer on**

**Comment by Checkmate128** [comment]
> "know how often someone advertises, how accurate their ads are (how much time after cooldown before ad), "
> 
> **Calculating how accurate there ads are would be useless since someone could just easily put a randomizer on**

Getting the fools who don’t use a randomizer (and many of the botters do not have a randomizer) would reduce the burden on staff to detect botters.

**Comment by IWolfZZ** [comment]
> > "know how often someone advertises, how accurate their ads are (how much time after cooldown before ad), "
> > **Calculating how accurate there ads are would be useless since someone could just easily put a randomizer on**
> 
> Getting the fools who don’t use a randomizer (and many of the botters do not have a randomizer) would reduce the burden on staff to detect botters.

As I already said it can easily be bypassed with any botting program

**Comment by ntrogen** [comment]
Definitely something I'd like to see and the IP limit would be perfect as it partly fixes spam ads.

**Comment by Checkmate128** [comment]
> > > "know how often someone advertises, how accurate their ads are (how much time after cooldown before ad), "
> > > **Calculating how accurate there ads are would be useless since someone could just easily put a randomizer on**
> > 
> > 
> > Getting the fools who don’t use a randomizer (and many of the botters do not have a randomizer) would reduce the burden on staff to detect botters.
> 
> As I already said it can easily be bypassed with any botting program

My point is that the majority of botters do not use a randomizer. These botters should be automatically flagged. Some botters will use a randomizer or other bypass tools and must be detected by staff or a captcha that appears like every 5 ads or something.

**Comment by IWolfZZ** [comment]
> > > > "know how often someone advertises, how accurate their ads are (how much time after cooldown before ad), "
> > > > **Calculating how accurate there ads are would be useless since someone could just easily put a randomizer on**
> > > 
> > > 
> > > Getting the fools who don’t use a randomizer (and many of the botters do not have a randomizer) would reduce the burden on staff to detect botters.
> > 
> > 
> > As I already said it can easily be bypassed with any botting program
> 
> My point is that the majority of botters do not use a randomizer. These botters should be automatically flagged. Some botters will use a randomizer or other bypass tools and must be detected by staff or a captcha that appears like every 5 ads or something.

Like I just stated in my past two comments I have said every botting program has a randomizer, Even if they dont have a randomizer Lag of minehut would mess with it, so the seconds would be off
