### ISSUE TITLE
In-game Control Panel

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#88]
### Feature request

**Platform**
 In-game

**Describe the feature**

Bring back the /mh command. (aka /controlpanel)

**How the feature is useful**

Commonly used by many. Not sure why it was removed.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment]
Redundant if they can access more through the online panel.

**Comment by drtshock** [comment]
Can you explain what you want this to do?

**Comment by farwl** [comment]
The same thing it did last time. Worlds / Schematics, Gamerules, DeOP all OPs, etc. I personally used this for the gamerules to quickly configure.

**Comment by CoreyShupe** [comment]
This is not going to work due to server versions now being able to be swapped. We're probably going to be discontinuing the PlayerServer plugin due to this as well. It doesn't make sense to maintain 10+ different versions of this plugin since it can be achieved better via the panel.
