### ISSUE TITLE
Still able to use colourcodes/formats in msgs

### ISSUE THREAD

**Issue by Zmottos** [Minehut/Meta#880]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

**Describe the bug**

Using Hex codes (ex: &#000000) allow people to send colours in messages (whereas &0, &1 etc) doesn't anymore
Using &&(throwawaycode)0 allows people to send colours in messages
**To reproduce**
Steps to reproduce the behaviour:
1. Go to any server/lobby
2. do /msg <user> &#000000hi

**Expected behaviour**

It wouldn't send any colour formatting as it was removed

**Device Information**

- Minecraft client (and version): Minecraft 1.17.1

**Screenshots**

<img width="281" alt="Screen Shot 2021-12-05 at 3 22 29 AM" src="https://user-images.githubusercontent.com/95563788/144739202-204ceb15-0e0d-4e86-b154-a537c2bceb09.png">

**Additional context**
Not really important, just thought it would be a good idea to report it
---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**
(Can be reproduced as of 5/12/2021
(Can be reproduced as of 13/12/2021
(Can be reproduced as of 21/12/2021
(Can be reproduced as of 27/12/2021

**Comment by Checkmate128** [comment]
I was able to reproduce it.

**Comment by CoreyShupe** [comment]
Is this something people don't want?

**Comment by Checkmate128** [comment]
> Is this something people don't want?

I like color codes in msg. I really don’t know why the normal ones were removed.

**Comment by CoreyShupe** [comment]
Fixed
