### ISSUE TITLE
Reduce Prices

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#888]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

Reduce the price of Daily to 25 where its sustainable by voting.
**How the feature is useful**

It benefits minehut, they get more ads because everyone is voting to keep their daily plan. Plus, the 25 is only enough to keep it for a day. So you'd have to be voting every day to keep your plan.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment]
You can already get the MH20 plan by just voting and a lot of people already vote every day for this. So I don't really see a need for this. And Minehut is already like top 10 on the voting website they use so it wouldn't really help them that much.

**Comment by ntrogen** [comment]
Minehut plans are not that expensive I don't see how this helps Minehut.

**Comment by Qeid** [comment]
pov: rich and famous

> Minehut plans are not that expensive I don't see how this helps Minehut.
