### ISSUE TITLE
Can see a wither?

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#896]
### Bug report

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] I am NOT reporting a security vulnerability
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information

**Platform**

Java (Only tested)
**Describe the bug**

Uhm, I can see the wither?
![image](https://user-images.githubusercontent.com/68918014/147835101-258cf0c7-49f3-483d-9db7-3ed86e3e7d35.png)

**To reproduce**
Steps to reproduce the behaviour:
1. Join a Lobby
2. Move your screen around
3. Wither outline will appear

**Expected behaviour**

Why is wither in lobby???
**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 
Uhm, 1.8.9, Lobby, Windows, idk
**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by Blocksnmore** [comment]
I believe this is caused by viarewind (Or a bossbar plugin, not sure which) to allow older versions to see the custom bossbars. There's nothing minehut can do about it.

**Comment by tarna** [comment]
Ya like Blocksnmore said, this is caused by the via plugins. Because bossbars work differently in older versions and that's how it's done.  Just ignore it.

**Comment by tarna** [comment]
Ya like Blocksnmore said, this is caused by the via plugins. Because bossbars work differently in older versions and that's how it's done.  Just ignore it.

**Comment by tarna** [comment]
Ya like Blocksnmore said, this is caused by the via plugins. Because bossbars work differently in older versions and that's how it's done.  Just ignore it.
