### ISSUE TITLE
MH Captcha Huge Flaw

### ISSUE THREAD

**Issue by IWolfZZ** [Minehut/Meta#909]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
 Java

**Describe the bug**
 Okay so there's a huge flaw in the Minehut captcha which Lower versions like 1.7 and 1.8 will automatically bypass the captcha which is a huge flaw. Id assume this would help prevent people from botting lobbies and there own servers / others. 

**To reproduce**
Steps to reproduce the behaviour:
1. Go to on 1.8 and try to trigger the captcha (Not possible)
2. Go on 1.16.5+ and try to trigger the captcha (Possible)

**Expected behaviour**
 1.7 & 1.8 players should be sent to the captcha. I don't know what you all did wrong pretty sure you all broke the Captcha and it was blank for 1.8 and 1.7 at some point and got lazy and just forgot about 1.8 players and allowed them into the lobby. This should really be fixed.

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by CoreyShupe** [comment]
The captcha can be triggered by 1.7/1.8 clients but cannot be completed by them. We believe it's an issue with ViaBackwards but are working on investigating

**Comment by IWolfZZ** [comment]
How is it not true at this current state legit people are botting there servers with 1.8 bots.

**Comment by CoreyShupe** [comment]
It could be, but it’s not how they’re getting past it.

**Comment by IWolfZZ** [comment]
Wdym thats not how there getting pass it. If the bots use 1.8 they will automatically get sent to the lobby. I'm talking about bots which server owners use to boost there server on the server list. Not ad botting since adbotters just buy patron accounts and use a program to advertise automatically with multiple accounts.

**Comment by CoreyShupe** [comment]
1.8 accounts don’t bypass the lobby, that’s not how it works

**Comment by cupiditys** [comment]
also, if you connect on 1.8 you can reconnect on 1.18.1 and wont get a captcha

**Comment by IWolfZZ** [comment]
> also, if you connect on 1.8 you can reconnect on 1.18.1 and wont get a captcha

Well no duh the captcha triggers on a Proxy/VPN Detection or other stuff.

**Comment by cupiditys** [comment]
> > also, if you connect on 1.8 you can reconnect on 1.18.1 and wont get a captcha
> 
> Well no duh the captcha triggers on a Proxy/VPN Detection or other stuff.

yea what i mean is if you use a proxy you can just connect on 1.8 and reconnect right after and bypass it

**Comment by IWolfZZ** [comment]
> > > also, if you connect on 1.8 you can reconnect on 1.18.1 and wont get a captcha
> > 
> > 
> > Well no duh the captcha triggers on a Proxy/VPN Detection or other stuff.
> 
> yea what i mean is if you use a proxy you can just connect on 1.8 and reconnect right after on 1.18.1 and bypass it

Ohh I get it now yeah I know that, wouldnt that get resolved with 1.8 captcha

**Comment by cupiditys** [comment]
> > > > also, if you connect on 1.8 you can reconnect on 1.18.1 and wont get a captcha
> > > 
> > > 
> > > Well no duh the captcha triggers on a Proxy/VPN Detection or other stuff.
> > 
> > 
> > yea what i mean is if you use a proxy you can just connect on 1.8 and reconnect right after on 1.18.1 and bypass it
> 
> Ohh I get it now yeah I know that, wouldnt that get resolved with 1.8 captcha if it was fixed

yea probably, also heres a video

https://user-images.githubusercontent.com/66990287/149643564-0d21ef08-b6a0-46e0-ad61-43ba1f957e8d.mp4

**Comment by IWolfZZ** [comment]
I also think they should add back the old Minehut Move captcha with the current captcha that should get fixed. The move captcha would prevent some ad botters from auto advertising with a simple script. (Yes Ik this would be very simple to bypass but its one step to remove some people with bad ad bot programs & would prevent some people autoading with 5 accounts kinda)

**Comment by cupiditys** [comment]
honestly need to add some sort of bot protection even past the captcha, since you can literally just solve the captcha manually anyways and still bot

this is what minehuts chat has turned into
![image](https://user-images.githubusercontent.com/66990287/149649332-ad4a5ccd-aec8-4059-abe6-000bfcd1f656.png)

**Comment by IWolfZZ** [comment]
I mean 

> honestly need to add some sort of bot protection even past the captcha, since you can literally just solve the captcha manually anyways and still bot
> 
> this is what minehuts chat has turned into ![image](https://user-images.githubusercontent.com/66990287/149649332-ad4a5ccd-aec8-4059-abe6-000bfcd1f656.png)

I mean they need to enforce a rule about advertising with alts, they did it with ad trackers so why not using alts for malicious ad use.

**Comment by CoreyShupe** [comment]
The issue with 1.8 clients has been resolved.

**Comment by cupiditys** [comment]
yea but you literally just cant see the captcha
![2022-01-17_11 10 36](https://user-images.githubusercontent.com/66990287/149804149-0d7b4130-76ac-4304-866c-9b628ef8edbd.png)
i suppose it does "resolve" the issue though

**Comment by CoreyShupe** [comment]
Yeah, it’s a via issue I believe, 1.8.9 is super legacy so it’s not necessarily top priority
