### ISSUE TITLE
Live Status Page

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#91]
### Feature request

**Platform**
 Website

**Describe the feature**

Make a live status page for Minehut that displays status for all platforms. (Ex. In-game servers, Website/Panel, Forums, etc.)

Ex. Panel - Operational

Something like this could be helpful to redirect players to when Minehut is having issues, hosting provider is down, etc.

**How the feature is useful**

Useful because you can see all minehut platform statuses there and its useful for people who don't have Discord.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Could be made using Atlassian's Statuspage.io (since Minehut already uses Bitbucket, another Atlassian product), and the URL could be something like status.minehut.com

**Comment by drtshock** [comment]
Yeah, statuspage.io is just incredibly expensive. But yes with our recent issues, I've actually been looking into this. LMK all the information you'd want to see on here.

**Comment by iGalaxyYT** [comment]
Separate tracking/incident lists for servers, website/API, and authentication would be nice.

**Comment by CoreyShupe** [comment]
https://track.minehut.com

This will show when things are down or not functioning properly.
