### ISSUE TITLE
Add a cooldown to the server when the server gets advertised with /ad

### ISSUE THREAD

**Issue by fastflop** [Minehut/Meta#913]
### Feature request

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**
 Ingame, Both

**Describe the feature**
 Add a cooldown to the server that is being advertised via /ad. To prevent trolls from using /ad on a server and typing nothing, you could have a whitelist feature where only certain players can advertise (whitelisted players can be added via the panel)

**How the feature is useful**
 Prevents multiple bots from advertising a server at the same time and reduces spam in chat.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by IWolfZZ** [comment]
I think they should limit the amount of ads the user can send with users IP from advertising, something like that

**Comment by CoreyShupe** [comment]
#924 is more detailed, let's move the conversation there
