### ISSUE TITLE
creating core/main folder inside plugins/Skript/scripts/ gets deleted on server hibernation

### ISSUE THREAD

**Issue by GStudiosX2** [Minehut/Meta#914]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

website

**Describe the bug**

creating core/main folder inside `plugins/Skript/scripts/` gets deleted on server hibernation

**To reproduce**
Steps to reproduce the behaviour:
1. Go to the panel
2. Go to file manager
3. Create folder named "core" or "main" in `plugins/Skript/scripts`
4. Force hibernate
5. Folder will be deleted/not saved

**Expected behaviour**

the folder should save and appear with all your files but it doesn't ?

**Device Information**

- Minecraft client (and version): 1.17.1
- Web browser (and version): chrome
- Operating system (and version): windows 10
- Minehut server name: 

**Screenshots**

i will show a video hopefully but i havent got a video rn but i have tried this like 2 times and its defiantly being deleted alright

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by CoreyShupe** [comment]
Can you reproduce this behavior by restarting a server outside of minehut, like on your personal computer with the same setup.

**Comment by GStudiosX2** [comment]
> Can you reproduce this behavior by restarting a server outside of minehut, like on your personal computer with the same setup.

i dont think so it only happens on minehut (btw you spelt behaviour wrong)

**Comment by Blocksnmore** [comment]
> > Can you reproduce this behavior by restarting a server outside of minehut, like on your personal computer with the same setup.
> 
> i dont think so it only happens on minehut (btw you spelt behaviour wrong)

FiXed didn’t spell it wrong, in American English behavior is spelled without a u

**Comment by GStudiosX2** [comment]
> > > Can you reproduce this behavior by restarting a server outside of minehut, like on your personal computer with the same setup.
> > 
> > 
> > i dont think so it only happens on minehut (btw you spelt behaviour wrong)
> 
> FiXed didn’t spell it wrong, in American English behavior is spelled without a u. This applies to other words as well like color

i forget that fixed doesnt live in the uk lmao

**Comment by MrScopes** [comment]
I had this issue several months ago, didn't try on my personal pc

**Comment by GStudiosX2** [comment]
> I had this issue several months ago, didn't try on my personal pc

same but yeah it doesnt delete on my pc just minehut it gets deleted

**Comment by MrScopes** [comment]
user skillsbo on the main discord said "i suspect its with something related to mh traversing directories and deleting them if they are named main or core, possibly related to market content is my best guess", I can't really think of any reasons why `main` and `core` folders get deleted but me and some users have lost code due to it

**Comment by GStudiosX2** [comment]
its still happening 😢i hope this gets fixed soon people have lost a lot of scripts due to this kinda there fault they didnt save their scripts onto their computer though

**Comment by CoreyShupe** [comment]
Should be fixed within a week or so. I'll close the issue when it is.
