### ISSUE TITLE
Delete command confirmation

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#92]
### Feature request

**Platform**
 In-game

**Describe the feature**

Add a confirmation to the /del command. 

**How the feature is useful**

Prevents accidents and mistakes.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment]
This command no longer issues in-game so I'm going to close this.
