### ISSUE TITLE
File Manager tab multiple lines

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#93]
### Feature request

**Platform**
 Website (File Manager text editor)

**Describe the feature**

Make it so when you highlight multiple lines and hit tab, it tabs all of them, not just one..

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment]
Possible duplicate of #95 - could've made both of these into one issue

**Comment by drtshock** [comment]
Doesn't seem like a duplicate, just separate super specific requests.

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update.
