### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by enffinity** [Minehut/Meta#944]
these are the steps to solve it
![bra
![Ocle64u58u](https://user-images.githubusercontent.com/59962964/157297310-e20acc7d-8bdf-484f-883a-2b43ba87eefa.png)
ve_rS
![brave_xDBUFWf0kb](https://user-images.githubusercontent.com/59962964/157297326-04ba4228-9a12-4b3f-9862-7867b59c5a82.png)

![brave_MLVJI1lYqz](https://user-images.githubusercontent.com/59962964/157297315-339f516a-acd4-4de8-9a39-b895f66a396b.png)
LQuNvFLG](https://user-images.githubusercontent.com/59962964/157297293-b40668b9-811c-46b3-9d14-3b0e2b4ad081.png)
![brave_wxDK6KhYEx](https://user-images.githubusercontent.com/59962964/157297305-102b66f9-e2ad-4771-8998-9bc2b071bc3c.png)

**Comment by CoreyShupe** [comment]
This is wrong. The bug is known and will be fixed. Closing this since it doesn't follow format, and is just an incorrect diagnoses of the issue.
