### ISSUE TITLE
Switching lobbies breaks player visibility

### ISSUE THREAD

**Issue by colton-boi** [Minehut/Meta#945]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**
In-game

**Describe the bug**
When connecting with player visibility off, players will be visible and you will have to enable and disable player visibility again.

**To reproduce**
Steps to reproduce the behaviour:
1. Disable player visibility
2. Disconnect and reconnect or swap lobbies
3. Players will be visible

**Expected behaviour**
Make players not be visible when reconnecting with visibility off

**Device Information**

- Minecraft client (and version): Fabric 1.17.1

---

**Comment by GStudiosX2** [comment]
I don't personally have this issue I think. You sure it ain't fabric?

**Comment by Star-MC** [comment]
I was able to replicate. Tracked down the bug and resolved with an update today.
