### ISSUE TITLE
Magma server version

### ISSUE THREAD

**Issue by JinXz135** [Minehut/Meta#948]
Hello sir ツ

I need help with installing a new server version onto my server, but I am not sure it is possible. If there is a way I would really appreciate it if you could contact me as I am desperate for installing the server version `magma`, which allows mods and plugins(a lot more plugins than `spongeforge or fabric`) which I will need  for my server.

Thank you for your time and have a good day 😉

**Comment by tarna** [comment]
This isn't a place to get support. You can do that on either the Minehut Discord, Forums, or creating a support ticket. And no, you can only get the server softwares Minehut provides in their list.

**Comment by CoreyShupe** [comment]
This looks more like a suggestion to bring `Magma` into minehut and allow it as a server version rather than anything else. Regardless this is being closed for not being in the proper format. Please review the issue formats for feature requests and submit one in the proper format.
