### ISSUE TITLE
Proper tabbing in file manager text editor

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#95]
### Feature request

**Platform**
 Website

**Describe the feature**

When you hit tab at the end of a line, it finds the last open space in the line and places the tab there...? Make it so it performs normally.. (Makes a tab at the end of the line)

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Can you show more of what you mean?

**Comment by farwl** [comment]
Here's me hitting tab at the end of a line.
![](https://gyazo.com/5042262a49f5d5cc88be7cfa91ff048e.gif)

**Comment by BennyDoesStuff** [comment]
Implemented as of the recent file manager update.
