### ISSUE TITLE
Coop

### ISSUE THREAD

**Issue by abra6325** [Minehut/Meta#953]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java ingame

**Describe the feature**

Can Minehut have Coop servers so 2 people can edit the files and add pluginsto the same server?
**How the feature is useful**

Server developers
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by erenkarakal** [comment]
sub-users are already suggested

**Comment by GStudiosX2** [comment]
Dupe of #13 ?

**Comment by Tringlle** [comment]
Yeah, it would be considered that. Someone close this as it is a duplicate.

**Comment by BennyDoesStuff** [comment]
Duplicate of #13
