### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by DianRBLX** [Minehut/Meta#957]
Make an option so we can turn off the captcha on our servers because it's annoying

**Comment by CoreyShupe** [comment]
The captcha is a barrier of entry to minehut. It won’t be removed.

**Comment by DianRBLX** [comment]
in our servers not minehut like when they join ur own server there won't be a captcha but when they try doing /hub then it will teleport then to do a captcha

**Comment by CoreyShupe** [comment]
> 

We have no such feature where we captcha people after they've entered the game.

**Comment by DianRBLX** [comment]
exactly that's why I am suggesting it

**Comment by CoreyShupe** [comment]
You're suggesting we add a feature where people get captchad while playing? If so, please re-open an issue under the proper formats provided in the issue creation screen.

**Comment by DianRBLX** [comment]
are u a robot or something??? I never said that I said minehut should add a feature where when people join with our own server IP they don't get captcha only when they go to the hub or join the minehut server

**Comment by CoreyShupe** [comment]
> are u a robot or something??? I never said that I said minehut should add a feature where when people join with our own server IP they don't get captcha only when they go to the hub or join the minehut server

We won't be removing the captcha which exists already. It is a barrier of entry to our network - we do not allow bots on our network in any fashion. Please read the rules. The feature exists to back this rule. It won't be changed.

**Comment by DianRBLX** [comment]
no I don't want that I want u guys to implement a feature where u can turn off the captcha FOR YOUR OWN SERVER

**Comment by DianRBLX** [comment]
exactly that's why I am suggesting to implement a feature where u can turn it off

**Comment by Blocksnmore** [comment]
> exactly that's why I am suggesting to implement a feature where u can turn it off

I'm pretty sure that minehut won't be adding a toggle to network wide protection. Why should it be disabled in the first place if it protects against bots?

**Comment by DianRBLX** [comment]
because it's our own server they can do a thing where if u toggle it u won't be shows in the most players leaderboards and stuff

**Comment by CoreyShupe** [comment]
This won't happen. End of discussion.
