### ISSUE TITLE
[BUG]: Player Count Issue

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#967]
### Checklist

- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

### What platform does this issue occur on?

Java, Bedrock, Website

### Current Behavior?

This is probably going to make a lot of people mad for reporting this. If anyone knows about it in the first place.

When you set your playercount higher than your plan limit, it will give an error, but if you click save, it successfully changes it to a higher number. It wont stick to your limit.

### What should happen?

It should error when changing it

### Reproduction Steps

Go to ur mh dashboard
Settings tab
Set your player count higher than it *can* be
Save settings
restart server
see playercount is as the number you set it to

### Client Information?

MultiMC 1.18.2
Opera

### Images?

I am at school rn, so cant take screenshot

**Comment by CoreyShupe** [comment]
Does is stick even after rebooting your server?

**Comment by tarna** [comment]
Cannot reproduce. Gets changed back when restarting the server. This used to work but think it has been fixed since then.

**Comment by CoreyShupe** [comment]
Closing this issue until evidence otherwise is provided.
