### ISSUE TITLE
[FEATURE]: Parole

### ISSUE THREAD

**Issue by iDerpyOfficial** [Minehut/Meta#969]
### Checklist

- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

### Affected Platform?

Java, Bedrock, Discord

### What is the feature you are requesting?

Early un-tempbans or un-mutes for doing good in the community
For example:
1. If a user is muted on minecraft, but staff sees they are nice on the discord, they might get unmuted
2. If a user gets punished, but staff sees they were helping with something like bug reports or user reports, they might get unmuted

### How is this feature useful for Minehut?

Obviously this idea is dumb on its own, but maybe someone can expand on this to make it more fair. Sometimes people get punished falsly or for absurd reasons, and I think there should be some system where they can earn back the trust of the staff and maybe even get un-punished.

Thank you for coming to my TED Talk.

**Comment by Daddy-Talpapa** [comment]
sounds like you got muted lmao

**Comment by iDerpyOfficial** [comment]
> sounds like you got muted lmao

I did, but that's not why I made this post.

**Comment by Daddy-Talpapa** [comment]
It 100% is.

**Comment by iDerpyOfficial** [comment]
> It 100% is.

If you say so.

**Comment by CoreyShupe** [comment]
This would be case by case via support. It does not belong in a feature request.

**Comment by tarna** [comment]
This kinda already exists. If you are banned for a long time, make an appeal saying it's been a while since you were banned and you have learned your lesson since then and want a second chance or something like that. And depending on your circumstances, they'll unban you.
