### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#97]
### Feature request

**Platform**
 Website

**Describe the feature**

Syntax highlighting for the editor.

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
Copy of #60 I believe

**Comment by xSpiderMC** [comment]
I feel like this should overall just be a new text editor that incoperates many different suggestions like line numbers, syntax highlighting ect.

**Comment by drtshock** [comment]
Duplicate as referenced above.
