### ISSUE TITLE
An option to Whitelist and Blacklist words

### ISSUE THREAD

**Issue by Lo1O** [Minehut/Meta#972]
### Checklist

- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

### Affected Platform?

Java, Bedrock

### What is the feature you are requesting?

An option to allow and disallow certain words via commands like /allow word  _insert word_      /disallow word _insert word_

### How is this feature useful for Minehut?

To allow people to see certain words and not see certain words.

**Comment by tarna** [comment]
dupe of #359

**Comment by Lo1O** [comment]
Huh, I searched all possibility of an duplation issue. I never found this one. Sorry for the dupe.
