### ISSUE TITLE
ayo?

### ISSUE THREAD

**Issue by iDerpyOfficial** [Minehut/Meta#973]
### Checklist

- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I have ensured the phrase is not properly filtered on the platform

### Which filter has the issue?

Minecraft

### Should the phrase be Filtered or Unfiltered?

Unfiltered

### Phrase

my fart smells like toast

### Why should the phrase be filtered/unfiltered?

i see nothing wrong with it
also it's blocked due to "custom"... what's that even mean

this request is half unserious, but like seriously that's weird that it blocks that

**Comment by CoreyShupe** [comment]
Request isn’t serious. Closing.
