### ISSUE TITLE
Last Server button in Main Menu compass

### ISSUE THREAD

**Issue by CerialPvP** [Minehut/Meta#979]
### Checklist

- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

### Affected Platform?

Java, Bedrock

### What is the feature you are requesting?

So I see a lot of people in the lobbies asking "how do I get the last server I played on?" because it seems it isn't clear for them the IP is in the scoreboard or tab or any other place.

So in the main menu compass, add an option to rejoin the latest server the player was on. What it will do, is it will make the player join the previous server they played. For example, a player has joined server A, and they went to server B. They want to rejoin server A because they enjoyed it. They simply go to the lobby and go to the main menu and click that button.

### How is this feature useful for Minehut?

It could benefit 2 people; the owner and the player. The owner can enjoy his new players coming back to the server, and the player could enjoy more fun on that server.

**Comment by erenkarakal** [comment]
Dupe of #337 and is already added in the dev server
