### ISSUE TITLE
Blur / gray out disabled and inaccessible files.

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#98]
### Feature request

**Platform**

**Describe the feature**

Blur/gray out disabled or inaccessible files. Ex. disabled skript files (still accessible)
![](https://cdn.discordapp.com/attachments/592130982451216402/725895867298742312/unknown.png)

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
This seems pretty specific to skript. Does this apply anywhere else? And why would we do this? QOL isn't really a justification. Does it clear up current confusion that users are having?

**Comment by farwl** [comment]
It applies for disabled directories like spigot.yml and such.

**Comment by BennyDoesStuff** [comment]
With the recent file manager update, all files are now accessible (including previously spigot.yml, server.properties, etc) so graying out inaccessible files is not going to be needed anymore.
