### ISSUE TITLE
more ram

### ISSUE THREAD

**Issue by MagnusAsked** [Minehut/Meta#982]
### Checklist

- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

### Affected Platform?

Java

### What is the feature you are requesting?

add more ram to free servers make it like 1.5gb or somethin bc atm its like 1gb 

### How is this feature useful for Minehut?

its usefull bc i believe more people will stay and keep using minehut and maybe even donate if they can actually see how good it is hard to see how good it is when your free server crashes every second so i think it will serve to gain more members and donations

**Comment by agentgamer100** [comment]
RAM costs money, and if Minehut were to give all free servers an extra 0.5 GB of RAM, that's gonna be a lotta money (or not idrk how much RAM costs) 

Also if your "free server crashes every second" then you might wanna optimize your server by getting rid of world or plugins.

**Comment by CoreyShupe** [comment]
The free server I operate for the devs to have fun on runs perfectly fine with no lag, tps drops, or any other issues.

If your server crashes every second you might want to look into paper optimization guides and work on tweaking the server to work better for your purposes.

My initial guess is you’ve loaded a bunch of plugins onto your server, are using the base paper config or just not even paper at all, and have probably quite a few people playing.

1) if you’re not on paper you should be if you need optimization
2) configuring anything to your requirements is usual in most systems you’ll encounter, there’s about a million guides out there on how to optimize paper
3) more people means more chunks means more mobs so keep that in mind
4) take timings reports, spark reports etc…

If your memory is over committing you probably have a plug-in in there taking up tons of memory. Or you’re not using paper as questioned above.
