### ISSUE TITLE
Uskyblock doesn’t work in 1.17.1

### ISSUE THREAD

**Issue by lankydog246** [Minehut/Meta#995]
### Checklist

- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

### What platform does this issue occur on?

Java

### Current Behavior?

Doesn’t work in 1.17.1 even though it claims to, it does however work in 1.16.5

### What should happen?

To be able to use it

### Reproduction Steps

Either fix it or stop showing that it works for 1.17.1

### Client Information?

Lunar client, chrome, windows 10, ld246sb

**Comment by BennyDoesStuff** [comment]
Fixed, I updated the plugin to a newer version (2.9.0) that is compatible with 1.17.
